/**
 * edl/problem-registry.ts
 * Engineering Data Layer — Problem Entity Registry
 *
 * 15 canonical Problem entities with governance metadata and relationship arrays.
 * Engineering content (definition, failureProgression, etc.) is Phase 4.
 */

import type { EDLProblemEntity, EDLProblemRegistry } from './types';

export const EDL_PROBLEMS: EDLProblemRegistry = {

  'PROB-ABRASIVE-WEAR': {
    id: 'PROB-ABRASIVE-WEAR',
    name: 'Abrasive Wear',
    slug: 'abrasive-wear',
    category: 'mechanical-wear',
    severity: 'critical',
    status: 'draft',
    version: '0.1',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    addressedByTechnologies: ['TECH-MACROCORE', 'TECH-SYNTRAX', 'TECH-NANOFORCE'],
    measuredByStandards: ['STD-ISO-16889', 'STD-ISO-4406'],
  },

  'PROB-ADHESIVE-WEAR': {
    id: 'PROB-ADHESIVE-WEAR',
    name: 'Adhesive Wear',
    slug: 'adhesive-wear',
    category: 'mechanical-wear',
    severity: 'high',
    status: 'draft',
    version: '0.1',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    addressedByTechnologies: ['TECH-SYNTRAX', 'TECH-NANOFORCE'],
    measuredByStandards: ['STD-ISO-16889', 'STD-ISO-4406'],
  },

  'PROB-BEARING-WEAR': {
    id: 'PROB-BEARING-WEAR',
    name: 'Bearing Wear',
    slug: 'bearing-wear',
    category: 'mechanical-wear',
    severity: 'critical',
    status: 'draft',
    version: '0.1',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    addressedByTechnologies: ['TECH-SYNTRAX', 'TECH-NANOFORCE'],
    measuredByStandards: ['STD-ISO-16889', 'STD-ISO-4406'],
  },

  'PROB-INJECTOR-WEAR': {
    id: 'PROB-INJECTOR-WEAR',
    name: 'Injector Wear',
    slug: 'injector-wear',
    category: 'mechanical-wear',
    severity: 'high',
    status: 'draft',
    version: '0.1',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    addressedByTechnologies: ['TECH-SYNTAPORE', 'TECH-HYDROCORE'],
    measuredByStandards: ['STD-ASTM-D6304', 'STD-ISO-12937', 'STD-ISO-16332'],
  },

  'PROB-SILICON-DUST-INGESTION': {
    id: 'PROB-SILICON-DUST-INGESTION',
    name: 'Silicon Dust Ingestion',
    slug: 'silicon-dust-ingestion',
    category: 'contamination',
    severity: 'critical',
    status: 'draft',
    version: '0.1',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    addressedByTechnologies: ['TECH-MACROCORE'],
    measuredByStandards: ['STD-ISO-5011', 'STD-SAE-J1539'],
  },

  'PROB-WATER-INGRESS': {
    id: 'PROB-WATER-INGRESS',
    name: 'Water Ingress',
    slug: 'water-ingress',
    category: 'contamination',
    severity: 'high',
    status: 'draft',
    version: '0.1',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    addressedByTechnologies: ['TECH-HYDROCORE', 'TECH-SYNTAPORE', 'TECH-HYDROCORE', 'TECH-MARINECLEAN', 'TECH-DRYCORE'],
    measuredByStandards: ['STD-ASTM-D6304', 'STD-ISO-12937', 'STD-ISO-8573-1'],
  },

  'PROB-FUEL-CONTAMINATION': {
    id: 'PROB-FUEL-CONTAMINATION',
    name: 'Fuel Contamination',
    slug: 'fuel-contamination',
    category: 'contamination',
    severity: 'high',
    status: 'draft',
    version: '0.1',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    addressedByTechnologies: ['TECH-SYNTAPORE', 'TECH-HYDROCORE', 'TECH-HYDROCORE', 'TECH-MARINECLEAN'],
    measuredByStandards: ['STD-ASTM-D6304', 'STD-ISO-16332', 'STD-ISO-12937'],
  },

  'PROB-AIR-RESTRICTION': {
    id: 'PROB-AIR-RESTRICTION',
    name: 'Air Restriction',
    slug: 'air-restriction',
    category: 'contamination',
    severity: 'high',
    status: 'draft',
    version: '0.1',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    addressedByTechnologies: ['TECH-MACROCORE'],
    measuredByStandards: ['STD-ISO-5011', 'STD-SAE-J1539', 'STD-ISO-29463'],
  },

  'PROB-CAVITATION': {
    id: 'PROB-CAVITATION',
    name: 'Cavitation',
    slug: 'cavitation',
    category: 'structural-failure',
    severity: 'critical',
    status: 'draft',
    version: '0.1',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    addressedByTechnologies: ['TECH-NANOFORCE', 'TECH-HYDROCORE'],
    measuredByStandards: ['STD-ISO-16889', 'STD-NFPA-T2-14'],
  },

  'PROB-PUMP-FAILURE': {
    id: 'PROB-PUMP-FAILURE',
    name: 'Pump Failure',
    slug: 'pump-failure',
    category: 'structural-failure',
    severity: 'critical',
    status: 'draft',
    version: '0.1',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    addressedByTechnologies: ['TECH-NANOFORCE', 'TECH-SYNTRAX'],
    measuredByStandards: ['STD-ISO-16889', 'STD-ISO-4406', 'STD-NFPA-T2-14'],
  },

  'PROB-FILTER-COLLAPSE': {
    id: 'PROB-FILTER-COLLAPSE',
    name: 'Filter Collapse',
    slug: 'filter-collapse',
    category: 'structural-failure',
    severity: 'high',
    status: 'draft',
    version: '0.1',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    addressedByTechnologies: ['TECH-MACROCORE', 'TECH-NANOFORCE'],
    measuredByStandards: ['STD-ISO-16889', 'STD-NFPA-T2-14'],
  },

  'PROB-MEDIA-FATIGUE': {
    id: 'PROB-MEDIA-FATIGUE',
    name: 'Filter Media Fatigue',
    slug: 'media-fatigue',
    category: 'structural-failure',
    severity: 'medium',
    status: 'draft',
    version: '0.1',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    addressedByTechnologies: ['TECH-MACROCORE', 'TECH-NANOFORCE'],
    measuredByStandards: ['STD-ISO-16889', 'STD-ISO-5011'],
  },

  'PROB-VARNISH-FORMATION': {
    id: 'PROB-VARNISH-FORMATION',
    name: 'Varnish Formation',
    slug: 'varnish-formation',
    category: 'chemical-degradation',
    severity: 'high',
    status: 'draft',
    version: '0.1',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    addressedByTechnologies: ['TECH-SYNTRAX', 'TECH-NANOFORCE'],
    measuredByStandards: ['STD-ISO-4406', 'STD-ISO-16889', 'STD-DIN-51524'],
  },

  'PROB-OXIDATION': {
    id: 'PROB-OXIDATION',
    name: 'Oxidative Degradation',
    slug: 'oxidation',
    category: 'chemical-degradation',
    severity: 'medium',
    status: 'draft',
    version: '0.1',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    addressedByTechnologies: ['TECH-SYNTRAX'],
    measuredByStandards: ['STD-ISO-4406', 'STD-DIN-51524'],
  },

  'PROB-MICROBIAL-GROWTH': {
    id: 'PROB-MICROBIAL-GROWTH',
    name: 'Microbial Growth',
    slug: 'microbial-growth',
    category: 'biological',
    severity: 'medium',
    status: 'draft',
    version: '0.1',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    addressedByTechnologies: ['TECH-HYDROCORE', 'TECH-MARINECLEAN', 'TECH-HYDROCORE'],
    measuredByStandards: ['STD-ASTM-D6304', 'STD-ISO-12937'],
  },

};
