import { OemPartEntry, OemPartId } from './master-data-types';

/**
 * OEM PART REGISTRY
 *
 * Master registry mapping OEM parts to their categories and linked cross-references.
 */
export const OEM_PART_REGISTRY: Record<OemPartId, OemPartEntry> = {
  'DONALDSON-DBF5810': {
    id: 'DONALDSON-DBF5810',
    oemId: 'DONALDSON',
    oemPartNumber: 'DBF5810',
    category: 'fuel',
    duty: 'HD',
    productType: 'Fuel Filter',
    crossReferences: ['EF95810'],
    specifications: [
      { label: 'Diámetro exterior', value: '5.35 Pulgadas (136 MM)' },
      { label: 'Tamaño de la rosca', value: '1 3/8-16 UN' },
      { label: 'Longitud', value: '12.13 Pulgadas (308 MM)' },
    ],
    oemCrossReferences: [
      { manufacturer: 'CATERPILLAR', partNumber: '4227587' },
      { manufacturer: 'HIFI-FILTER', partNumber: 'SN55446' },
      { manufacturer: 'FLEETGUARD', partNumber: 'FF5810NN' },
      { manufacturer: 'SAKURA', partNumber: 'FC55290' },
      { manufacturer: 'SF-FILTER', partNumber: 'SK33541' },
    ],
    equipmentApplications: [
      { equipment: 'CATERPILLAR 24', year: '-', equipmentType: 'Calificador', equipmentOptions: '-', engine: 'CATERPILLAR C27', engineOption: '-' },
      { equipment: 'CATERPILLAR 6020B', year: '-', equipmentType: 'Pala', equipmentOptions: '-', engine: 'CATERPILLAR C32', engineOption: '-' },
      { equipment: 'CATERPILLAR 777G', year: '-', equipmentType: 'Camión De Acarreo', equipmentOptions: '-', engine: 'CATERPILLAR C32', engineOption: '-' },
      { equipment: 'CATERPILLAR 797F', year: '-', equipmentType: 'Camión De Volteo', equipmentOptions: '700 SERIES', engine: 'CATERPILLAR C175-20', engineOption: '-' },
      { equipment: 'CATERPILLAR C175-16', year: '-', equipmentType: 'Motores', equipmentOptions: '-', engine: 'CATERPILLAR C175-16', engineOption: '-' },
    ],
    sourceUrl: 'https://shop.donaldson.com/store/es-us/product/DBF5810/prod1390138',
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-P169071': {
    id: 'DONALDSON-P169071',
    oemId: 'DONALDSON',
    oemPartNumber: 'P169071',
    category: 'oil',
    duty: 'HD',
    productType: 'Oil Filter',
    crossReferences: ['EL83487'],
    specifications: [
      { label: 'Diámetro exterior', value: '3.67 Pulgadas (93.2 MM)' },
      { label: 'Tamaño de la rosca', value: '3/4-16 UN' },
      { label: 'Longitud', value: '5.32 Pulgadas (135.1 MM)' },
    ],
    oemCrossReferences: [
      { manufacturer: 'ACE SCRAP METAL', partNumber: 'PH1' },
      { manufacturer: 'AGCO', partNumber: '72257916' },
      { manufacturer: 'ALCOA MARINE', partNumber: 'NO220' },
      { manufacturer: 'ALFA ROMEO', partNumber: '370640000' },
      { manufacturer: 'ALLCAR', partNumber: 'APH8' },
      { manufacturer: 'AC-DELCO', partNumber: 'AC015' },
      { manufacturer: 'BALDWIN', partNumber: 'B2' },
      { manufacturer: 'BOSCH', partNumber: '0451104063' },
      { manufacturer: 'CARQUEST', partNumber: '84515' },
      { manufacturer: 'COOPERS-FIAAM', partNumber: 'FT4403' },
      { manufacturer: 'FIL FILTER', partNumber: 'ZP502' },
      { manufacturer: 'FRAM', partNumber: 'HP1' },
      { manufacturer: 'HENGST', partNumber: 'H17W02' },
      { manufacturer: 'HIFI-FILTER', partNumber: 'SO10032' },
      { manufacturer: 'KNECHT', partNumber: 'OC67' },
      { manufacturer: 'LUBER-FINER', partNumber: 'HP1' },
      { manufacturer: 'MAHLE', partNumber: 'OC67' },
      { manufacturer: 'MANN', partNumber: 'W940/1' },
      { manufacturer: 'PURFLUX', partNumber: 'LS582' },
      { manufacturer: 'PUROLATOR', partNumber: 'L30007' },
      { manufacturer: 'RYCO', partNumber: 'Z131A' },
      { manufacturer: 'SAKURA', partNumber: 'C8011' },
      { manufacturer: 'SOFIMA', partNumber: 'S5600R' },
      { manufacturer: 'UFI', partNumber: '23.102.00' },
      { manufacturer: 'VALEO', partNumber: '586059' },
      { manufacturer: 'WIX', partNumber: '51775' },
    ],
    equipmentApplications: [
      { equipment: 'ALLIS-CHALMERS 714B', year: '-', equipmentType: 'Retroexcavadora', equipmentOptions: '-', engine: 'PERKINS 4.236', engineOption: '-' },
      { equipment: 'ALLIS-CHALMERS 715', year: '-', equipmentType: 'Retroexcavadora', equipmentOptions: '-', engine: 'PERKINS 4.236', engineOption: '-' },
      { equipment: 'ALLIS-CHALMERS 715B', year: '-', equipmentType: 'Retroexcavadora', equipmentOptions: '-', engine: 'PERKINS 4236', engineOption: '-' },
      { equipment: 'ALLIS-CHALMERS 715D', year: '-', equipmentType: 'Retroexcavadora', equipmentOptions: '-', engine: 'PERKINS 4.236', engineOption: '-' },
      { equipment: 'ALLIS-CHALMERS 816', year: '-', equipmentType: 'Retroexcavadora', equipmentOptions: '-', engine: 'PERKINS 4.248', engineOption: '-' },
    ],
    sourceUrl: 'https://shop.donaldson.com/store/es-us/product/P169071/16389',
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-DBA5016': {
    id: 'DONALDSON-DBA5016',
    oemId: 'DONALDSON',
    oemPartNumber: 'DBA5016',
    category: 'air',
    duty: 'HD',
    productType: 'Air Filter',
    crossReferences: ['EA15016'],
    specifications: [
      { label: 'Diámetro exterior', value: '10.40 Pulgadas (264.2 MM)' },
      { label: 'Diámetro interior', value: '6.04 Pulgadas (153.4 MM)' },
      { label: 'Longitud', value: '26.00 Pulgadas (660.4 MM)' },
    ],
    oemCrossReferences: [
      { manufacturer: 'FLEETGUARD', partNumber: 'AF1616NF' },
      { manufacturer: 'LUBER-FINER', partNumber: 'LAF8494MXM' },
    ],
    sourceUrl: 'https://shop.donaldson.com/store/es-us/product/DBA5016/11824',
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-P105958': {
    id: 'DONALDSON-P105958',
    oemId: 'DONALDSON',
    oemPartNumber: 'P105958',
    category: 'cabin',
    duty: 'HD',
    productType: 'Cabin Air Filter',
    crossReferences: ['EC15958'],
    specifications: [
      { label: 'Longitud', value: '10.00 Pulgadas (254 MM)' },
      { label: 'Ancho', value: '10.00 Pulgadas (254 MM)' },
      { label: 'Altura', value: '2.57 Pulgadas (65.4 MM)' },
    ],
    oemCrossReferences: [
      { manufacturer: 'CATERPILLAR', partNumber: '3I0044' },
      { manufacturer: 'GPC', partNumber: 'EP5261' },
      { manufacturer: 'AIR REFINER', partNumber: 'ARM105958' },
      { manufacturer: 'BALDWIN', partNumber: 'PA3473' },
      { manufacturer: 'BUCYRUS ERIE', partNumber: '46163220' },
      { manufacturer: 'CLARKE', partNumber: '82404141' },
      { manufacturer: 'FLEETGUARD', partNumber: 'AF1986' },
      { manufacturer: 'HEAVY-DUTY-AIR', partNumber: 'HDA5957' },
      { manufacturer: 'HEAVY-DUTY-AIR', partNumber: 'HDA5958' },
      { manufacturer: 'HIFI-FILTER', partNumber: 'SC90026' },
      { manufacturer: 'INTRUPA', partNumber: 'IF5024' },
      { manufacturer: 'INTRUPA', partNumber: 'IF5024Q' },
      { manufacturer: 'KRALINATOR', partNumber: 'LA510' },
      { manufacturer: 'LOESING', partNumber: '020185' },
      { manufacturer: 'NELSON', partNumber: '105958' },
      { manufacturer: 'NELSON', partNumber: '84208N' },
      { manufacturer: 'NILFISK-ADVANCE', partNumber: '82404141' },
      { manufacturer: 'RUSTON-BUCYRUS', partNumber: '46163220' },
      { manufacturer: 'UNIT-RIG', partNumber: '19865' },
      { manufacturer: 'VMC', partNumber: 'AF105958' },
      { manufacturer: 'WALGAHN-MOTORENTECHNIK', partNumber: '00810519' },
    ],
    sourceUrl: 'https://shop.donaldson.com/store/es-us/product/P105958/14716',
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-P105957': {
    id: 'DONALDSON-P105957',
    oemId: 'DONALDSON',
    oemPartNumber: 'P105957',
    category: 'cabin',
    duty: 'HD',
    productType: 'Cabin Air Filter',
    crossReferences: ['EC15957'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-P501108': {
    id: 'DONALDSON-P501108',
    oemId: 'DONALDSON',
    oemPartNumber: 'P501108',
    category: 'fuel-water-separator',
    duty: 'HD',
    productType: 'Fuel/Water Separator',
    crossReferences: ['ES91108'],
    oemCrossReferences: [
      { manufacturer: 'HIFI-FILTER', partNumber: 'SN40728' },
      { manufacturer: 'CATERPILLAR', partNumber: '3820664' },
      { manufacturer: 'CATERPILLAR', partNumber: '4385386' },
      { manufacturer: 'EKKA-FILTER', partNumber: 'EK1098' },
      { manufacturer: 'FLEETGUARD', partNumber: 'FS20131' },
      { manufacturer: 'SF-FILTER', partNumber: 'SK487021' },
    ],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-P502392': {
    id: 'DONALDSON-P502392',
    oemId: 'DONALDSON',
    oemPartNumber: 'P502392',
    category: 'fuel-water-separator',
    duty: 'HD',
    productType: 'Fuel/Water Separator',
    crossReferences: ['ES92392'],
    oemCrossReferences: [
      { manufacturer: 'BALDWIN', partNumber: 'BF7912' },
      { manufacturer: 'FLEETGUARD', partNumber: 'FS19605' },
      { manufacturer: 'HENGST', partNumber: 'E1030K' },
      { manufacturer: 'HIFI-FILTER', partNumber: 'SN40005' },
      { manufacturer: 'MAHLE', partNumber: 'KX332' },
      { manufacturer: 'MAN', partNumber: '81125010021' },
      { manufacturer: 'MANN', partNumber: 'PU911' },
      { manufacturer: 'RACOR', partNumber: 'PFF5601' },
      { manufacturer: 'SAKURA', partNumber: 'SF7922' },
      { manufacturer: 'UFI', partNumber: '2606200' },
      { manufacturer: 'WIX', partNumber: '95100E' },
    ],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-P502517': {
    id: 'DONALDSON-P502517',
    oemId: 'DONALDSON',
    oemPartNumber: 'P502517',
    category: 'fuel-water-separator',
    duty: 'HD',
    productType: 'Fuel/Water Separator',
    crossReferences: ['ES92517'],
    oemCrossReferences: [
      { manufacturer: 'BALDWIN', partNumber: 'BF1384SP' },
      { manufacturer: 'CATERPILLAR', partNumber: '3466695' },
      { manufacturer: 'FLEETGUARD', partNumber: 'FS19704' },
      { manufacturer: 'FRAM', partNumber: 'PS11026' },
      { manufacturer: 'HIFI-FILTER', partNumber: 'SN902530' },
      { manufacturer: 'MACK', partNumber: '20539578' },
      { manufacturer: 'MAHLE', partNumber: 'KC371D' },
      { manufacturer: 'MANN', partNumber: 'WK940/32' },
      { manufacturer: 'RACOR', partNumber: 'R25P' },
      { manufacturer: 'SAKURA', partNumber: 'SFC710730' },
      { manufacturer: 'UFI', partNumber: '2446100' },
      { manufacturer: 'WIX', partNumber: '33775' },
    ],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-P550020': {
    id: 'DONALDSON-P550020',
    oemId: 'DONALDSON',
    oemPartNumber: 'P550020',
    category: 'fuel-water-separator',
    duty: 'HD',
    productType: 'Fuel/Water Separator',
    crossReferences: ['ES90020'],
    oemCrossReferences: [
      { manufacturer: 'AC-DELCO', partNumber: 'PF1284' },
      { manufacturer: 'BALDWIN', partNumber: 'BT112' },
      { manufacturer: 'CATERPILLAR', partNumber: '9Y4450' },
      { manufacturer: 'CUMMINS', partNumber: '152499' },
      { manufacturer: 'FLEETGUARD', partNumber: 'FS19250' },
      { manufacturer: 'FRAM', partNumber: 'PH20' },
      { manufacturer: 'HASTINGS', partNumber: 'LF129' },
      { manufacturer: 'JOHN DEERE', partNumber: 'AR58956' },
      { manufacturer: 'MANN', partNumber: 'W936/2' },
      { manufacturer: 'PUROLATOR', partNumber: 'L20015' },
      { manufacturer: 'WIX', partNumber: '51243' },
    ],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-P552414': {
    id: 'DONALDSON-P552414',
    oemId: 'DONALDSON',
    oemPartNumber: 'P552414',
    category: 'fuel-water-separator',
    duty: 'HD',
    productType: 'Fuel/Water Separator',
    crossReferences: ['ES92414'],
    oemCrossReferences: [
      { manufacturer: 'BALDWIN', partNumber: 'V1874T' },
      { manufacturer: 'FLEETGUARD', partNumber: 'FS1874T' },
      { manufacturer: 'PUROLATOR', partNumber: 'L60146' },
      { manufacturer: 'WIX', partNumber: '51874' },
    ],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-P584764': {
    id: 'DONALDSON-P584764',
    oemId: 'DONALDSON',
    oemPartNumber: 'P584764',
    category: 'air-dryer',
    duty: 'HD',
    productType: 'Air Dryer',
    crossReferences: ['ED44764'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-P951413': {
    id: 'DONALDSON-P951413',
    oemId: 'DONALDSON',
    oemPartNumber: 'P951413',
    category: 'air-dryer',
    duty: 'HD',
    productType: 'Air Dryer',
    crossReferences: ['ED41413'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-P953571': {
    id: 'DONALDSON-P953571',
    oemId: 'DONALDSON',
    oemPartNumber: 'P953571',
    category: 'air-dryer',
    duty: 'HD',
    productType: 'Air Dryer',
    crossReferences: ['ED43571'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-DBC4081': {
    id: 'DONALDSON-DBC4081',
    oemId: 'DONALDSON',
    oemPartNumber: 'DBC4081',
    category: 'coolant',
    duty: 'HD',
    productType: 'Coolant Filter',
    crossReferences: ['EW74081'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-DBC4085': {
    id: 'DONALDSON-DBC4085',
    oemId: 'DONALDSON',
    oemPartNumber: 'DBC4085',
    category: 'coolant',
    duty: 'HD',
    productType: 'Coolant Filter',
    crossReferences: ['EW74085'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-DBC4086': {
    id: 'DONALDSON-DBC4086',
    oemId: 'DONALDSON',
    oemPartNumber: 'DBC4086',
    category: 'coolant',
    duty: 'HD',
    productType: 'Coolant Filter',
    crossReferences: ['EW74086'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-DBC4088': {
    id: 'DONALDSON-DBC4088',
    oemId: 'DONALDSON',
    oemPartNumber: 'DBC4088',
    category: 'coolant',
    duty: 'HD',
    productType: 'Coolant Filter',
    crossReferences: ['EW74088'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-DBC4089': {
    id: 'DONALDSON-DBC4089',
    oemId: 'DONALDSON',
    oemPartNumber: 'DBC4089',
    category: 'coolant',
    duty: 'HD',
    productType: 'Coolant Filter',
    crossReferences: ['EW74089'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-DBC4785': {
    id: 'DONALDSON-DBC4785',
    oemId: 'DONALDSON',
    oemPartNumber: 'DBC4785',
    category: 'coolant',
    duty: 'HD',
    productType: 'Coolant Filter',
    crossReferences: ['EW74785'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-P550866': {
    id: 'DONALDSON-P550866',
    oemId: 'DONALDSON',
    oemPartNumber: 'P550866',
    category: 'coolant',
    duty: 'HD',
    productType: 'Coolant Filter',
    crossReferences: ['EW70866'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-P550867': {
    id: 'DONALDSON-P550867',
    oemId: 'DONALDSON',
    oemPartNumber: 'P550867',
    category: 'coolant',
    duty: 'HD',
    productType: 'Coolant Filter',
    crossReferences: ['EW70867'],
    oemCrossReferences: [
      { manufacturer: 'CARQUEST', partNumber: '89113' },
      { manufacturer: 'ALLIANCE', partNumber: 'ABPN10GWF2127' },
      { manufacturer: 'BALDWIN', partNumber: 'B5087' },
      { manufacturer: 'CUMMINS', partNumber: '3680434' },
      { manufacturer: 'DONALDSON', partNumber: 'P550585' },
      { manufacturer: 'FLEETGUARD', partNumber: 'WF2127' },
      { manufacturer: 'FLEETRITE', partNumber: 'WFR82127' },
      { manufacturer: 'FRAM', partNumber: 'PR8694' },
      { manufacturer: 'HASTINGS', partNumber: 'WC23' },
      { manufacturer: 'HIFI-FILTER', partNumber: 'WE2127' },
      { manufacturer: 'MACK', partNumber: '5839WF2127' },
      { manufacturer: 'NAPA', partNumber: '4113' },
      { manufacturer: 'WIX', partNumber: '24113' },
    ],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-P551008': {
    id: 'DONALDSON-P551008',
    oemId: 'DONALDSON',
    oemPartNumber: 'P551008',
    category: 'coolant',
    duty: 'HD',
    productType: 'Coolant Filter',
    crossReferences: ['EW71008'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-P552055': {
    id: 'DONALDSON-P552055',
    oemId: 'DONALDSON',
    oemPartNumber: 'P552055',
    category: 'coolant',
    duty: 'HD',
    productType: 'Coolant Filter',
    crossReferences: ['EW72055'],
    oemCrossReferences: [
      { manufacturer: 'CARQUEST', partNumber: '89074' },
      { manufacturer: 'CATERPILLAR', partNumber: '1W5518' },
      { manufacturer: 'CUMMINS', partNumber: '258264' },
      { manufacturer: 'DONALDSON', partNumber: 'CFP552055' },
      { manufacturer: 'FLEETGUARD', partNumber: 'WF2055' },
      { manufacturer: 'FLEETRITE', partNumber: 'WFR82055' },
      { manufacturer: 'Fram', partNumber: 'PR3753' },
      { manufacturer: 'General Motors', partNumber: '23507189' },
      { manufacturer: 'HENGST', partNumber: 'H29WF' },
      { manufacturer: 'John Deere', partNumber: 'AR94652' },
      { manufacturer: 'Komatsu', partNumber: '6004111030' },
      { manufacturer: 'MACK', partNumber: '5839WF2054' },
      { manufacturer: 'Purolator', partNumber: 'PW4455' },
      { manufacturer: 'Sakura', partNumber: 'WC6901' },
      { manufacturer: 'Volvo', partNumber: '207015007' },
      { manufacturer: 'Wix', partNumber: '24157' },
    ],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-P552070': {
    id: 'DONALDSON-P552070',
    oemId: 'DONALDSON',
    oemPartNumber: 'P552070',
    category: 'coolant',
    duty: 'HD',
    productType: 'Coolant Filter',
    crossReferences: ['EW72070'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-P552071': {
    id: 'DONALDSON-P552071',
    oemId: 'DONALDSON',
    oemPartNumber: 'P552071',
    category: 'coolant',
    duty: 'HD',
    productType: 'Coolant Filter',
    crossReferences: ['EW72071'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-P552072': {
    id: 'DONALDSON-P552072',
    oemId: 'DONALDSON',
    oemPartNumber: 'P552072',
    category: 'coolant',
    duty: 'HD',
    productType: 'Coolant Filter',
    crossReferences: ['EW72072'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-P552073': {
    id: 'DONALDSON-P552073',
    oemId: 'DONALDSON',
    oemPartNumber: 'P552073',
    category: 'coolant',
    duty: 'HD',
    productType: 'Coolant Filter',
    crossReferences: ['EW72073'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-P552074': {
    id: 'DONALDSON-P552074',
    oemId: 'DONALDSON',
    oemPartNumber: 'P552074',
    category: 'coolant',
    duty: 'HD',
    productType: 'Coolant Filter',
    crossReferences: ['EW72074'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-P552075': {
    id: 'DONALDSON-P552075',
    oemId: 'DONALDSON',
    oemPartNumber: 'P552075',
    category: 'coolant',
    duty: 'HD',
    productType: 'Coolant Filter',
    crossReferences: ['EW72075'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-P552076': {
    id: 'DONALDSON-P552076',
    oemId: 'DONALDSON',
    oemPartNumber: 'P552076',
    category: 'coolant',
    duty: 'HD',
    productType: 'Coolant Filter',
    crossReferences: ['EW72076'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-P552096': {
    id: 'DONALDSON-P552096',
    oemId: 'DONALDSON',
    oemPartNumber: 'P552096',
    category: 'coolant',
    duty: 'HD',
    productType: 'Coolant Filter',
    crossReferences: ['EW72096'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-P552106': {
    id: 'DONALDSON-P552106',
    oemId: 'DONALDSON',
    oemPartNumber: 'P552106',
    category: 'coolant',
    duty: 'HD',
    productType: 'Coolant Filter',
    crossReferences: ['EW72106'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-P554019': {
    id: 'DONALDSON-P554019',
    oemId: 'DONALDSON',
    oemPartNumber: 'P554019',
    category: 'coolant',
    duty: 'HD',
    productType: 'Coolant Filter',
    crossReferences: ['EW74019'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-P554071': {
    id: 'DONALDSON-P554071',
    oemId: 'DONALDSON',
    oemPartNumber: 'P554071',
    category: 'coolant',
    duty: 'HD',
    productType: 'Coolant Filter',
    crossReferences: ['EW74071'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-P554072': {
    id: 'DONALDSON-P554072',
    oemId: 'DONALDSON',
    oemPartNumber: 'P554072',
    category: 'coolant',
    duty: 'HD',
    productType: 'Coolant Filter',
    crossReferences: ['EW74072'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-P554073': {
    id: 'DONALDSON-P554073',
    oemId: 'DONALDSON',
    oemPartNumber: 'P554073',
    category: 'coolant',
    duty: 'HD',
    productType: 'Coolant Filter',
    crossReferences: ['EW74073'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-P554074': {
    id: 'DONALDSON-P554074',
    oemId: 'DONALDSON',
    oemPartNumber: 'P554074',
    category: 'coolant',
    duty: 'HD',
    productType: 'Coolant Filter',
    crossReferences: ['EW74074'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-P554075': {
    id: 'DONALDSON-P554075',
    oemId: 'DONALDSON',
    oemPartNumber: 'P554075',
    category: 'coolant',
    duty: 'HD',
    productType: 'Coolant Filter',
    crossReferences: ['EW74075'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-P554685': {
    id: 'DONALDSON-P554685',
    oemId: 'DONALDSON',
    oemPartNumber: 'P554685',
    category: 'coolant',
    duty: 'HD',
    productType: 'Coolant Filter',
    crossReferences: ['EW74685'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-P554860': {
    id: 'DONALDSON-P554860',
    oemId: 'DONALDSON',
    oemPartNumber: 'P554860',
    category: 'coolant',
    duty: 'HD',
    productType: 'Coolant Filter',
    crossReferences: ['EW74860'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-P765594': {
    id: 'DONALDSON-P765594',
    oemId: 'DONALDSON',
    oemPartNumber: 'P765594',
    category: 'coolant',
    duty: 'HD',
    productType: 'Coolant Filter',
    crossReferences: ['EW75594'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-P957032': {
    id: 'DONALDSON-P957032',
    oemId: 'DONALDSON',
    oemPartNumber: 'P957032',
    category: 'air-dryer',
    duty: 'HD',
    productType: 'Air Dryer',
    crossReferences: ['ED47032'],
    specifications: [
      { label: 'Diámetro exterior', value: '5.51 Pulgadas (140 MM)' },
      { label: 'Tamaño de la rosca', value: 'M42 X 1.5' },
      { label: 'Longitud', value: '6.5 Pulgadas (165 MM)' },
      { label: 'Ráfaga de colapso', value: '435 PSI (30 Bar)' },
      { label: 'Estilo', value: 'Spin-On' },
    ],
    oemCrossReferences: [
      { manufacturer: 'ALCO', partNumber: 'SP8003' },
      { manufacturer: 'BOSCH-REXROTH', partNumber: '1487434011' },
      { manufacturer: 'KNECHT', partNumber: 'AL23' },
      { manufacturer: 'KNORR-BREMSE', partNumber: 'II38789F' },
      { manufacturer: 'MAN', partNumber: '81521020016' },
      { manufacturer: 'MERCEDES-BENZ', partNumber: '4294895' },
      { manufacturer: 'RENAULT VI', partNumber: '5000295422' },
      { manufacturer: 'WABCO', partNumber: '4324102202' },
      { manufacturer: 'HIFI-FILTER', partNumber: 'TB1387' },
      { manufacturer: 'MANN', partNumber: 'TB1374/4X' },
      { manufacturer: 'UFI', partNumber: '27F2400' },
    ],
    equipmentApplications: [
      { equipment: 'MERCEDES-BENZ U216', year: '2013', equipmentType: 'Camión', equipmentOptions: 'U-SERIE', engine: 'MERCEDES-BENZ OM 934', engineOption: '-' },
      { equipment: 'MERCEDES-BENZ U219', year: '2013', equipmentType: 'Camión', equipmentOptions: 'U-SERIE', engine: 'MERCEDES-BENZ OM 934', engineOption: '-' },
      { equipment: 'MERCEDES-BENZ U318', year: '2013', equipmentType: 'Camión', equipmentOptions: 'U-SERIE', engine: 'MERCEDES-BENZ OM 934', engineOption: '-' },
      { equipment: 'MERCEDES-BENZ U319', year: '2013', equipmentType: 'Camión', equipmentOptions: 'U-SERIE', engine: 'MERCEDES-BENZ OM 934', engineOption: '-' },
      { equipment: 'MERCEDES-BENZ U323', year: '2013', equipmentType: 'Camión', equipmentOptions: 'U-SERIE', engine: 'MERCEDES-BENZ OM 934', engineOption: '-' },
      { equipment: 'MERCEDES-BENZ U423', year: '2013', equipmentType: 'Camión', equipmentOptions: 'U-SERIE', engine: 'MERCEDES-BENZ OM 934', engineOption: '-' },
      { equipment: 'MERCEDES-BENZ U427', year: '2013', equipmentType: 'Camión', equipmentOptions: 'U-SERIE', engine: 'MERCEDES-BENZ OM 936', engineOption: '-' },
      { equipment: 'MERCEDES-BENZ U429', year: '2013', equipmentType: 'Camión', equipmentOptions: 'U-SERIE', engine: 'MERCEDES-BENZ OM 936', engineOption: '-' },
      { equipment: 'MERCEDES-BENZ U430', year: '2013', equipmentType: 'Camión', equipmentOptions: 'U-SERIE', engine: 'MERCEDES-BENZ OM 936', engineOption: '-' },
      { equipment: 'MERCEDES-BENZ U527', year: '2013', equipmentType: 'Camión', equipmentOptions: 'U-SERIE', engine: 'MERCEDES-BENZ OM 936', engineOption: '-' },
      { equipment: 'MERCEDES-BENZ U529', year: '2013', equipmentType: 'Camión', equipmentOptions: 'U-SERIE', engine: 'MERCEDES-BENZ OM 936', engineOption: '-' },
      { equipment: 'MERCEDES-BENZ U530', year: '2013', equipmentType: 'Camión', equipmentOptions: 'U-SERIE', engine: 'MERCEDES-BENZ OM 936', engineOption: '-' },
      { equipment: 'RENAULT VI MIDLINER S120', year: '1990', equipmentType: 'Camión', equipmentOptions: 'MIDLINER S', engine: 'PERKINS PHASER 130110T', engineOption: '-' },
      { equipment: 'RENAULT VI MIDLINER S135', year: '1994', equipmentType: 'Camión', equipmentOptions: 'MIDLINER S', engine: 'PERKINS PHASER 130110TI', engineOption: '-' },
      { equipment: 'RENAULT VI MIDLINER S135-08', year: '1996', equipmentType: 'Camión', equipmentOptions: 'MIDLINER S', engine: 'RENAULT VI MIDR 04.02.26', engineOption: '-' },
      { equipment: 'RENAULT VI MIDLINER S140', year: '1990', equipmentType: 'Camión', equipmentOptions: 'MIDLINER S', engine: 'RENAULT VI MIDS 13006.02.12C', engineOption: '-' },
      { equipment: 'RENAULT VI MIDLINER S150', year: '1994', equipmentType: 'Camión', equipmentOptions: 'MIDLINER S', engine: 'RENAULT VI MIDR 13006.02.12/26', engineOption: '-' },
      { equipment: 'RENAULT VI MIDLINER S150-08', year: '1996', equipmentType: 'Camión', equipmentOptions: 'MIDLINER S', engine: 'RENAULT VI MIDR 04.02.26', engineOption: '-' },
      { equipment: 'RENAULT VI MIDLINER S150-09', year: '1996', equipmentType: 'Camión', equipmentOptions: 'MIDLINER S', engine: 'RENAULT VI MIDR 04.02.26', engineOption: '-' },
      { equipment: 'RENAULT VI MIDLINER S180', year: '1992', equipmentType: 'Camión', equipmentOptions: 'MIDLINER S', engine: 'RENAULT VI MIDR 13006.02.26V', engineOption: '-' },
      { equipment: 'RENAULT VI MIDLINER S180-08', year: '1991', equipmentType: 'Camión', equipmentOptions: 'MIDLINER S', engine: 'RENAULT VI MIDR 06.02.26L1', engineOption: '-' },
    ],
    sourceUrl: 'https://shop.donaldson.com/store/es-us/product/P957032/68127',
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'FLEETGUARD-AD27746': {
    id: 'FLEETGUARD-AD27746',
    oemId: 'FLEETGUARD',
    oemPartNumber: 'AD27746',
    category: 'air-dryer',
    duty: 'HD',
    productType: 'Air Dryer',
    crossReferences: ['ED47746'],
    specifications: [
      { label: 'Forma de hilo', value: 'Métrico' },
      { label: 'Altura', value: '6.46 pulgadas/164.00 mm' },
      { label: 'Diámetro exterior de la junta', value: '4.37 pulgadas/111.00 mm' },
      { label: 'Diametro de hilo', value: '1.61 pulgadas/41.00 mm' },
      { label: 'Diámetro exterior más grande', value: '7.87 pulgadas/200.00 mm' },
      { label: 'Clase de Rosca', value: '6H' },
      { label: 'Comentarios', value: 'Con coalescedor de aceite' },
    ],
    oemCrossReferences: [
      { manufacturer: 'HIFI-FILTER', partNumber: 'TB1393' },
      { manufacturer: 'MANN', partNumber: 'TB1394/6X' },
      { manufacturer: 'UFI', partNumber: '27F1400' },
    ],
    // NOTE: representative sample only -- the official Fleetguard page lists 600+ equipment fitments (mostly European DAF/Van Hool/Bova/VDL trucks & buses); not exhaustively captured.
    equipmentApplications: [
      { equipment: 'Blue Bird - Vision School Bus', year: '2019', equipmentType: '-', equipmentOptions: '-', engine: 'V10-6.8L-415-S', engineOption: '-' },
      { equipment: 'Autocar Llc. - Xpeditor', year: '2017', equipmentType: '-', equipmentOptions: '-', engine: 'L9', engineOption: '-' },
      { equipment: 'Van Hool - ASTRONEF TX16', year: '2020', equipmentType: '-', equipmentOptions: '-', engine: 'MX-13', engineOption: '-' },
      { equipment: 'Van Hool - ALTANO TDX21', year: '2020', equipmentType: '-', equipmentOptions: '-', engine: 'D2676 LOH27', engineOption: '-' },
      { equipment: 'DAF - XF106 460', year: '2020', equipmentType: '-', equipmentOptions: '-', engine: 'MX13 (EURO 6)', engineOption: '-' },
      { equipment: 'DAF - LF46/LF56 FA180', year: '2020', equipmentType: '-', equipmentOptions: '-', engine: 'PX-5', engineOption: '-' },
      { equipment: 'Irizar - i4300 Hybrid', year: '2017', equipmentType: '-', equipmentOptions: '-', engine: 'ISB5.7', engineOption: '-' },
      { equipment: 'Vdl Bus & Coach - CITEA SLFA-187-310', year: '2014', equipmentType: '-', equipmentOptions: '-', engine: 'CURSOR 9', engineOption: '-' },
      { equipment: 'Tatra - PHOENIX 460', year: '2014', equipmentType: '-', equipmentOptions: '-', engine: 'MX265', engineOption: '-' },
      { equipment: 'Ginaf - X5364T', year: '2008', equipmentType: '-', equipmentOptions: '-', engine: 'MX340S', engineOption: '-' },
      { equipment: 'Bova - FUTURA FLD127-310', year: '2007', equipmentType: '-', equipmentOptions: '-', engine: 'PR265S', engineOption: '-' },
      { equipment: 'DAF - CF85 460', year: '2006', equipmentType: '-', equipmentOptions: '-', engine: 'MX340S', engineOption: '-' },
      { equipment: 'DAF - XF95 530', year: '2002', equipmentType: '-', equipmentOptions: '-', engine: 'XE TYPE', engineOption: '-' },
      { equipment: 'Ginaf - X4343LS', year: '1999', equipmentType: '-', equipmentOptions: '-', engine: 'XE280C', engineOption: '-' },
      { equipment: 'DAF - 75CF 250', year: '1998', equipmentType: '-', equipmentOptions: '-', engine: 'PF100M SERIES', engineOption: '-' },
    ],
    sourceUrl: 'https://www.fleetguard.com/es/product/AD27746',
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'FLEETGUARD-AD27748': {
    id: 'FLEETGUARD-AD27748',
    oemId: 'FLEETGUARD',
    oemPartNumber: 'AD27748',
    category: 'air-dryer',
    duty: 'HD',
    productType: 'Air Dryer',
    crossReferences: ['ED47748'],
    specifications: [
      { label: 'Forma de hilo', value: 'Métrico' },
      { label: 'Diametro de hilo', value: '1.54 pulgadas/39.00 mm' },
      { label: 'Diámetro exterior de la junta', value: '4.37 pulgadas/111.00 mm' },
      { label: 'Altura', value: '6.46 pulgadas/164.00 mm' },
      { label: 'Diámetro exterior más grande', value: '5.51 pulgadas/140.00 mm' },
      { label: 'Clase de Rosca', value: '6H' },
      { label: 'Comentarios', value: 'Con coalescedor de aceite' },
    ],
    oemCrossReferences: [
      { manufacturer: 'HIFI-FILTER', partNumber: 'TB1394' },
      { manufacturer: 'MANN', partNumber: 'TB1394/17X' },
      { manufacturer: 'MANN', partNumber: 'TB1396/5X' },
    ],
    // NOTE: representative sample only -- official page lists 152 equipment fitments (mostly European Volvo trucks).
    equipmentApplications: [
      { equipment: 'Volvo - FM II 330', year: '2016', equipmentType: '-', equipmentOptions: '-', engine: 'D11K330', engineOption: '-' },
      { equipment: 'Volvo - FM II 460', year: '2016', equipmentType: '-', equipmentOptions: '-', engine: 'D13K460', engineOption: '-' },
      { equipment: 'Volvo - FMX II 500', year: '2016', equipmentType: '-', equipmentOptions: '-', engine: 'D13K500', engineOption: '-' },
      { equipment: 'Volvo - FE II 320-18 CNG', year: '2016', equipmentType: '-', equipmentOptions: '-', engine: 'G9K320', engineOption: '-' },
      { equipment: 'Volvo - FL 280-16', year: '2016', equipmentType: '-', equipmentOptions: '-', engine: 'D8K280', engineOption: '-' },
      { equipment: 'Volvo - FL240', year: '2013', equipmentType: '-', equipmentOptions: '-', engine: 'D5K', engineOption: '-' },
      { equipment: 'Volvo - FE320', year: '2013', equipmentType: '-', equipmentOptions: '-', engine: 'D8K', engineOption: '-' },
      { equipment: 'Volvo - FMX420', year: '2013', equipmentType: '-', equipmentOptions: '-', engine: 'D13K EURO', engineOption: '-' },
    ],
    sourceUrl: 'https://www.fleetguard.com/es/product/AD27748',
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'FLEETGUARD-AD27749': {
    id: 'FLEETGUARD-AD27749',
    oemId: 'FLEETGUARD',
    oemPartNumber: 'AD27749',
    category: 'air-dryer',
    duty: 'HD',
    productType: 'Air Dryer',
    crossReferences: ['ED47749'],
    specifications: [
      { label: 'Forma de hilo', value: 'Británico' },
      { label: 'Altura', value: '7.05 pulgadas/179.00 mm' },
      { label: 'Diámetro exterior de la junta', value: '4.37 pulgadas/111.00 mm' },
      { label: 'Diametro de hilo', value: '1.25 pulgadas/31.75 mm' },
      { label: 'Diámetro exterior más grande', value: '5.51 pulgadas/140.00 mm' },
      { label: 'Clase de Rosca', value: 'Otro' },
      { label: 'Comentarios', value: 'Con coalescedor de aceite' },
    ],
    oemCrossReferences: [
      { manufacturer: 'HIFI-FILTER', partNumber: 'TB1402' },
      { manufacturer: 'MANN', partNumber: 'TB1394/3X' },
      { manufacturer: 'MANN', partNumber: 'TB1396/3X' },
      { manufacturer: 'UFI', partNumber: '27F3000' },
    ],
    // NOTE: representative sample only -- official page lists 141 equipment fitments (mostly European Scania trucks).
    equipmentApplications: [
      { equipment: 'Scania - P410 CNG', year: '2018', equipmentType: '-', equipmentOptions: '-', engine: 'OC13 101', engineOption: '-' },
      { equipment: 'Scania - P250', year: '2018', equipmentType: '-', equipmentOptions: '-', engine: 'DC07 113', engineOption: '-' },
      { equipment: 'Scania - P340 CNG', year: '2018', equipmentType: '-', equipmentOptions: '-', engine: 'OC09 104', engineOption: '-' },
      { equipment: 'Scania - P280 CNG', year: '2018', equipmentType: '-', equipmentOptions: '-', engine: 'OC09 105', engineOption: '-' },
      { equipment: 'Scania - P220', year: '2018', equipmentType: '-', equipmentOptions: '-', engine: 'DC07 112', engineOption: '-' },
      { equipment: 'Scania - G340 CNG', year: '2018', equipmentType: '-', equipmentOptions: '-', engine: 'OC09 105', engineOption: '-' },
    ],
    sourceUrl: 'https://www.fleetguard.com/es/product/AD27749',
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'FLEETGUARD-AD27751': {
    id: 'FLEETGUARD-AD27751',
    oemId: 'FLEETGUARD',
    oemPartNumber: 'AD27751',
    category: 'air-dryer',
    duty: 'HD',
    productType: 'Air Dryer',
    crossReferences: ['ED47751'],
    specifications: [
      { label: 'Forma de hilo', value: 'Métrico' },
      { label: 'Diámetro exterior más grande', value: '5.51 pulgadas/140.00 mm' },
      { label: 'Diámetro exterior de la junta', value: '4.37 pulgadas/111.00 mm' },
      { label: 'Diametro de hilo', value: '1.61 pulgadas/41.00 mm' },
      { label: 'Altura', value: '120.00 pulgadas/3048.00 mm' },
      { label: 'Clase de Rosca', value: '6H' },
    ],
    oemCrossReferences: [
      { manufacturer: 'HIFI-FILTER', partNumber: 'TB1388' },
      { manufacturer: 'KOLBENSCHMIDT', partNumber: '634-AD' },
      { manufacturer: 'MANN', partNumber: 'TB1364X' },
      { manufacturer: 'UFI', partNumber: '2739300' },
    ],
    // NOTE: representative sample only -- official page lists 368 equipment fitments (Peterbilt, DAF, and other North American/European trucks). Replaces obsolete Fleetguard AF27853.
    equipmentApplications: [
      { equipment: 'Peterbilt - 210', year: '-', equipmentType: '-', equipmentOptions: '-', engine: 'PX-6', engineOption: '-' },
      { equipment: 'DAF - LF170', year: '2021', equipmentType: '-', equipmentOptions: '-', engine: 'PX-4', engineOption: '-' },
      { equipment: 'DAF - LF46/LF56 FA280', year: '2020', equipmentType: '-', equipmentOptions: '-', engine: 'PX-7', engineOption: '-' },
      { equipment: 'DAF - LF46/LF56 FA210', year: '2020', equipmentType: '-', equipmentOptions: '-', engine: 'PX-5', engineOption: '-' },
    ],
    sourceUrl: 'https://www.fleetguard.com/es/product/AD27751',
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'FLEETGUARD-AD27754': {
    id: 'FLEETGUARD-AD27754',
    oemId: 'FLEETGUARD',
    oemPartNumber: 'AD27754',
    category: 'air-dryer',
    duty: 'HD',
    productType: 'Air Dryer',
    crossReferences: ['ED47754'],
    specifications: [
      { label: 'Forma de hilo', value: 'Nacional Unificado' },
      { label: 'Diámetro exterior más grande', value: '3.07 pulgadas/78.00 mm' },
      { label: 'Diámetro exterior de la junta', value: '2.82 pulgadas/71.50 mm' },
      { label: 'Tipo de medio', value: 'Microvidrio' },
      { label: 'Diametro de hilo', value: '0.75 pulgadas/19.05 mm' },
      { label: 'Altura', value: '5.00 pulgadas/127.00 mm' },
      { label: 'Clase de Rosca', value: '1B' },
    ],
    oemCrossReferences: [
      { manufacturer: 'HIFI-FILTER', partNumber: 'TB1391' },
      { manufacturer: 'MANN', partNumber: 'TB719' },
    ],
    // NOTE: representative sample only -- official page lists 435 equipment fitments (mixed North American/European fleets).
    equipmentApplications: [
      { equipment: 'International - PRO LF627 PREM', year: '2010', equipmentType: '-', equipmentOptions: '-', engine: 'ISX15', engineOption: '-' },
      { equipment: 'Blue Bird - All American FE', year: '2009', equipmentType: '-', equipmentOptions: '-', engine: 'C7', engineOption: '-' },
      { equipment: 'Autocar Llc. - Xpeditor WX', year: '2009', equipmentType: '-', equipmentOptions: '-', engine: 'ISL G (8.9)', engineOption: '-' },
      { equipment: 'Mercedes-Benz - VARIO 812D (670)', year: '2020', equipmentType: '-', equipmentOptions: '-', engine: 'OM602.985LA', engineOption: '-' },
    ],
    sourceUrl: 'https://www.fleetguard.com/es/product/AD27754',
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'FLEETGUARD-AD27755': {
    id: 'FLEETGUARD-AD27755',
    oemId: 'FLEETGUARD',
    oemPartNumber: 'AD27755',
    category: 'air-dryer',
    duty: 'HD',
    productType: 'Air Dryer',
    crossReferences: ['ED47755'],
    specifications: [
      { label: 'Forma de hilo', value: 'Métrico' },
      { label: 'Diámetro exterior más grande', value: '5.51 pulgadas/140.00 mm' },
      { label: 'Diámetro exterior de la junta', value: '4.37 pulgadas/111.00 mm' },
      { label: 'Altura', value: '6.54 pulgadas/166.00 mm' },
      { label: 'Diametro de hilo', value: '1.61 pulgadas/41.00 mm' },
      { label: 'Clase de Rosca', value: '6H' },
      { label: 'Comentarios', value: 'Para aplicaciones de camiones Mercedes' },
    ],
    oemCrossReferences: [
      { manufacturer: 'HIFI-FILTER', partNumber: 'TB1404' },
      { manufacturer: 'MANN', partNumber: 'TB1394/8X' },
      { manufacturer: 'UFI', partNumber: '27K0100' },
    ],
    equipmentApplications: [
      { equipment: 'Kassbohrer - S 431 DT EURO 6', year: '2016', equipmentType: '-', equipmentOptions: '-', engine: 'OM471', engineOption: '-' },
      { equipment: 'Evobus - CITARO 2012 12M NGT', year: '2015', equipmentType: '-', equipmentOptions: '-', engine: 'M936G', engineOption: '-' },
      { equipment: 'Sisu - 530', year: '2015', equipmentType: '-', equipmentOptions: '-', engine: 'OM 471 LA', engineOption: '-' },
      { equipment: 'Sisu - 520', year: '2014', equipmentType: '-', equipmentOptions: '-', engine: 'OM 473 LA', engineOption: '-' },
      { equipment: 'Sisu - 420', year: '2014', equipmentType: '-', equipmentOptions: '-', engine: 'OM 471 LA', engineOption: '-' },
    ],
    sourceUrl: 'https://www.fleetguard.com/es/product/AD27755',
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'FLEETGUARD-AD27756': {
    id: 'FLEETGUARD-AD27756',
    oemId: 'FLEETGUARD',
    oemPartNumber: 'AD27756',
    category: 'air-dryer',
    duty: 'HD',
    productType: 'Air Dryer',
    crossReferences: ['ED47756'],
    specifications: [
      { label: 'Forma de hilo', value: 'Métrico' },
      { label: 'Altura', value: '6.46 pulgadas/164.00 mm' },
      { label: 'Diámetro exterior de la junta', value: '4.37 pulgadas/111.00 mm' },
      { label: 'Diámetro exterior más grande', value: '5.51 pulgadas/140.00 mm' },
      { label: 'Diametro de hilo', value: '1.54 pulgadas/39.00 mm' },
      { label: 'Clase de Rosca', value: '6H' },
    ],
    oemCrossReferences: [
      { manufacturer: 'HIFI-FILTER', partNumber: 'TB1395' },
      { manufacturer: 'MANN', partNumber: 'TB1396X' },
    ],
    // NOTE: representative sample only -- official page lists 527 equipment fitments (mostly European Van Hool coaches).
    equipmentApplications: [
      { equipment: 'Autocar Llc. - Xpeditor', year: '2017', equipmentType: '-', equipmentOptions: '-', engine: 'L9', engineOption: '-' },
      { equipment: 'Van Hool - ALTANO TDX21', year: '2020', equipmentType: '-', equipmentOptions: '-', engine: 'MX-13', engineOption: '-' },
      { equipment: 'Van Hool - ASTROMEGA TDX27', year: '2020', equipmentType: '-', equipmentOptions: '-', engine: 'MX-13', engineOption: '-' },
    ],
    sourceUrl: 'https://www.fleetguard.com/es/product/AD27756',
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'FLEETGUARD-AD27757': {
    id: 'FLEETGUARD-AD27757',
    oemId: 'FLEETGUARD',
    oemPartNumber: 'AD27757',
    category: 'air-dryer',
    duty: 'HD',
    productType: 'Air Dryer',
    crossReferences: ['ED47757'],
    specifications: [
      { label: 'Región correspondiente', value: 'América del Norte, Europa, América del Sur' },
    ],
    oemCrossReferences: [
      { manufacturer: 'MANN', partNumber: 'TB1394/13X' },
      { manufacturer: 'UFI', partNumber: '27H0900' },
    ],
    // NOTE: representative sample only -- official page lists 75 equipment fitments (mixed North American/European fleets).
    equipmentApplications: [
      { equipment: 'Blue Bird - Vision School Bus', year: '2019', equipmentType: '-', equipmentOptions: '-', engine: 'V10-6.8L-415-S', engineOption: '-' },
      { equipment: 'DAF - XF450', year: '2021', equipmentType: '-', equipmentOptions: '-', engine: 'MX-11', engineOption: '-' },
      { equipment: 'DAF - XF106 440', year: '2020', equipmentType: '-', equipmentOptions: '-', engine: 'MX-11', engineOption: '-' },
    ],
    sourceUrl: 'https://www.fleetguard.com/es/product/AD27757',
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-P167410': {
    id: 'DONALDSON-P167410',
    oemId: 'DONALDSON',
    oemPartNumber: 'P167410',
    category: 'hydraulic',
    duty: 'HD',
    productType: 'Hydraulic Filter, Cartridge',
    crossReferences: ['EH67410'],
    specifications: [
      { label: 'Diámetro exterior', value: '3.84 Pulgadas (97.5 MM) (approx., per third-party listing -- Donaldson\'s own Atributos tab did not render specification values during capture)' },
    ],
    oemCrossReferences: [
      { manufacturer: 'A P PARTS', partNumber: '2442CEL' },
      { manufacturer: 'ALTEC INDUSTRIES', partNumber: '35330001' },
      { manufacturer: 'AMERICAN PARTS', partNumber: '92407' },
      { manufacturer: 'CAN-FLO', partNumber: 'F2510NM' },
      { manufacturer: 'CATERPILLAR', partNumber: '3I0578' },
      { manufacturer: 'FLO-LINE NO.', partNumber: 'QK10' },
      { manufacturer: 'FLOW EZY', partNumber: '658306' },
      { manufacturer: 'GRAINGER', partNumber: '52YT64' },
      { manufacturer: 'GUARDIAN', partNumber: 'G051407' },
      { manufacturer: 'INGERSOLL RAND', partNumber: '50422195' },
      { manufacturer: 'KRALINATOR', partNumber: 'L808' },
      { manufacturer: 'PEERLESS PUMP', partNumber: '300579901' },
      { manufacturer: 'PTI', partNumber: 'HF4050CCB' },
      { manufacturer: 'SWIFT', partNumber: 'SF9700912UM' },
      { manufacturer: 'FLEETGUARD', partNumber: 'HF6110' },
      { manufacturer: 'PARKER', partNumber: 'PI-357-10M' },
      { manufacturer: 'HYDAC', partNumber: 'HK010BN' },
      { manufacturer: 'MP-FILTRI', partNumber: '35330001' },
      { manufacturer: 'WIX', partNumber: '51407' },
      { manufacturer: 'SAKURA', partNumber: 'H5517' },
      { manufacturer: 'MASSEY-FERGUSON', partNumber: '1495479M1' },
    ],
    // NOTE: FLEETGUARD/HF6110 is NOT literally printed on Donaldson's own page (Donaldson doesn't cross-reference to name-brand competitors);
    // confirmed as the correct physical equivalent via 8+ matching third-party brand codes shared between this page and HF6110's independent
    // crossreference.com listing (CAN-FLO, FLO-LINE, GUARDIAN, INGERSOLL RAND, KRALINATOR, PEERLESS, SWIFT all match exactly).
    // Chosen as the "most commercial" Donaldson code among 5 candidates found for HF6110 (P163910, P167410, P168107, P564056, P779578) per user instruction; the other 4 are recorded as alternates below.
    equipmentApplications: [
      { equipment: 'CATERPILLAR R40', year: '-', equipmentType: 'Carretilla Elevadora', equipmentOptions: '-', engine: 'PERKINS 4.236', engineOption: '-' },
      { equipment: 'CATERPILLAR R60', year: '-', equipmentType: 'Carretilla Elevadora', equipmentOptions: '-', engine: 'PERKINS 4.236', engineOption: '-' },
      { equipment: 'CATERPILLAR R80', year: '-', equipmentType: 'Carretilla Elevadora', equipmentOptions: '1KK', engine: 'PERKINS 4.236', engineOption: '-' },
      { equipment: 'CATERPILLAR RC60', year: '-', equipmentType: 'Carretilla Elevadora', equipmentOptions: '-', engine: 'PERKINS 4.236', engineOption: '-' },
    ],
    sourceUrl: 'https://shop.donaldson.com/store/es-us/product/P167410/16304',
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-P163910-ALT': {
    id: 'DONALDSON-P163910-ALT',
    oemId: 'DONALDSON',
    oemPartNumber: 'P163910',
    category: 'hydraulic',
    duty: 'HD',
    productType: 'Hydraulic Filter, Cartridge',
    crossReferences: ['EH67410'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-P168107-ALT': {
    id: 'DONALDSON-P168107-ALT',
    oemId: 'DONALDSON',
    oemPartNumber: 'P168107',
    category: 'hydraulic',
    duty: 'HD',
    productType: 'Hydraulic Filter, Cartridge',
    crossReferences: ['EH67410'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-P564056-ALT': {
    id: 'DONALDSON-P564056-ALT',
    oemId: 'DONALDSON',
    oemPartNumber: 'P564056',
    category: 'hydraulic',
    duty: 'HD',
    productType: 'Hydraulic Filter, Cartridge',
    crossReferences: ['EH67410'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'DONALDSON-P779578-ALT': {
    id: 'DONALDSON-P779578-ALT',
    oemId: 'DONALDSON',
    oemPartNumber: 'P779578',
    category: 'hydraulic',
    duty: 'HD',
    productType: 'Hydraulic Filter, Cartridge',
    crossReferences: ['EH67410'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'FLEETGUARD-FH143': {
    id: 'FLEETGUARD-FH143',
    oemId: 'FLEETGUARD',
    oemPartNumber: 'FH143',
    category: 'fuel-housing',
    duty: 'HD',
    productType: 'Fuel Filter Housing (Turbine/FH Architecture)',
    crossReferences: ['ET90143'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'FLEETGUARD-FH21462': {
    id: 'FLEETGUARD-FH21462',
    oemId: 'FLEETGUARD',
    oemPartNumber: 'FH21462',
    category: 'fuel-housing',
    duty: 'HD',
    productType: 'Fuel Filter Housing (Turbine/FH Architecture)',
    crossReferences: ['ET91462'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'FLEETGUARD-FH21732': {
    id: 'FLEETGUARD-FH21732',
    oemId: 'FLEETGUARD',
    oemPartNumber: 'FH21732',
    category: 'fuel-housing',
    duty: 'HD',
    productType: 'Fuel Filter Housing (Turbine/FH Architecture)',
    crossReferences: ['ET91732'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'FLEETGUARD-FH22168': {
    id: 'FLEETGUARD-FH22168',
    oemId: 'FLEETGUARD',
    oemPartNumber: 'FH22168',
    category: 'fuel-housing',
    duty: 'HD',
    productType: 'Fuel Filter Housing (Turbine/FH Architecture)',
    crossReferences: ['ET92168'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'FLEETGUARD-FH23088': {
    id: 'FLEETGUARD-FH23088',
    oemId: 'FLEETGUARD',
    oemPartNumber: 'FH23088',
    category: 'fuel-housing',
    duty: 'HD',
    productType: 'Fuel Filter Housing (Turbine/FH Architecture)',
    crossReferences: ['ET93088'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'FLEETGUARD-FH23089': {
    id: 'FLEETGUARD-FH23089',
    oemId: 'FLEETGUARD',
    oemPartNumber: 'FH23089',
    category: 'fuel-housing',
    duty: 'HD',
    productType: 'Fuel Filter Housing (Turbine/FH Architecture)',
    crossReferences: ['ET93089'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'FLEETGUARD-FH23090': {
    id: 'FLEETGUARD-FH23090',
    oemId: 'FLEETGUARD',
    oemPartNumber: 'FH23090',
    category: 'fuel-housing',
    duty: 'HD',
    productType: 'Fuel Filter Housing (Turbine/FH Architecture)',
    crossReferences: ['ET93090'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'FLEETGUARD-FH23091': {
    id: 'FLEETGUARD-FH23091',
    oemId: 'FLEETGUARD',
    oemPartNumber: 'FH23091',
    category: 'fuel-housing',
    duty: 'HD',
    productType: 'Fuel Filter Housing (Turbine/FH Architecture)',
    crossReferences: ['ET93091'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'FLEETGUARD-FH23092': {
    id: 'FLEETGUARD-FH23092',
    oemId: 'FLEETGUARD',
    oemPartNumber: 'FH23092',
    category: 'fuel-housing',
    duty: 'HD',
    productType: 'Fuel Filter Housing (Turbine/FH Architecture)',
    crossReferences: ['ET93092'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'FLEETGUARD-FH23093': {
    id: 'FLEETGUARD-FH23093',
    oemId: 'FLEETGUARD',
    oemPartNumber: 'FH23093',
    category: 'fuel-housing',
    duty: 'HD',
    productType: 'Fuel Filter Housing (Turbine/FH Architecture)',
    crossReferences: ['ET93093'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'FLEETGUARD-FH23094': {
    id: 'FLEETGUARD-FH23094',
    oemId: 'FLEETGUARD',
    oemPartNumber: 'FH23094',
    category: 'fuel-housing',
    duty: 'HD',
    productType: 'Fuel Filter Housing (Turbine/FH Architecture)',
    crossReferences: ['ET93094'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
  'FLEETGUARD-FH23095': {
    id: 'FLEETGUARD-FH23095',
    oemId: 'FLEETGUARD',
    oemPartNumber: 'FH23095',
    category: 'fuel-housing',
    duty: 'HD',
    productType: 'Fuel Filter Housing (Turbine/FH Architecture)',
    crossReferences: ['ET93095'],
    applications: [],
    equipment: [],
    engines: [],
    status: 'ACTIVE',
  },
};
