# Limpieza ELIMFILTERS
$root = "E:\Elimfilters\world-catalogue"
Set-Location $root
git rm -r --cached node_modules/ 2>$null
git rm -r --cached motor-de-busqueda/node_modules/ 2>$null
$files = @("audit-catalog.js","audit-crossref.js","audit.js","audit_alternatives.js","audit_contaminacion.js","audit_oem_codes.js","audit_specs.js","audit_specs_by_type.js","analyze.js","assign_industry_standards.js","auto-import.js","balanced_descriptions.js","check-baldwin.js","check-html.js","check-html2.js","check-oem.js","check_damage.js","check_final.js","check_heights.js","check_prefixes.js","check_skus_by_prefix.js","check_spinon.js","check_structure.js","clean-crossref.js","clean_competitor_codes.js","clean_contamination.js","clean_descriptions.js","clean_oil_columns.py","clean_p552100.js","cleanup_all.js","create-payload.js","final_check.js","find-api.js","find-api2.js","find-data.js","find_alternatives.js","find_logos.js","find_p552100.js","identify_alternatives.js","insert-air-filters.js","insert-air-housing.js","label_server.js","normalize-catalog.js","orchestrator_render_pipeline.js","query-catalog.js","recreate_el82100.js","regenerate_skus.js","review_tech.js","run-crossref-all.js","sample_by_type.js","scraper-bookmark.js","scraper-crossref-fuel.js","search552.js","spin_on_engine.js","spin_on_server.js","tech_by_type.js","test-catalog.js","test-donaldson.js","test-groq.js","test-regex.js","test-sku-direct.js","test-sku-system.js","text_mask.py","verify_cleanup.js","verify_principal.js","view_oem_structure.js","write_label.js","write_label2.js","qc_server.js","fleetguard_scraper.js","DEBUG-MATRIX-FINAL.md","DEBUG-MATRIX.md","FLEETGUARD-EXTRACTION-SOLUTIONS.md","FLEETGUARD-SCRAPER-INSTRUCTIONS.md","FLEETGUARD_DEPLOYMENT_GUIDE.md","FLEETGUARD_IMPLEMENTATION.md","FLEETGUARD_SCRAPER.md","FLEETGUARD_SCRAPER_README.md","MULTI_MODEL_ROUTING.md","PDF-ANALYSIS-MATRIX.md","CHATBOT.md","BACKUP_KLEO2026.md","DESIGN.md","CLAUDE_METADATA.md","fleetguard-productos.html","part-search-card.html","view-fleetguard-products.html","diagnostic.json","import-report.json","datos_originales.json","fleetguard_webscraper_sitemap.json","CATALOGO_VISUAL_ELIM.json","force-redeploy.txt","vercel.json")
foreach ($f in $files) { $p = Join-Path $root $f; if (Test-Path $p) { Remove-Item $p -Force; Write-Host "Eliminado: $f" } }
if (Test-Path "$root\public\antigravity.html") { Remove-Item "$root\public\antigravity.html" -Force }
git add -A
git commit -m "chore: limpieza repo"
Write-Host "Listo"
