'use strict';
const fs=require('fs'),{Client}=require('pg');
const RP='C:/Users/ELIMSERVER/world-catalogue/elimfilters-vault/91-private-evidence/fram-ld-gap-analysis/fram-ld-gap-2026-09-13T07-31-22-822Z.json';
const R=JSON.parse(fs.readFileSync(RP,'utf8'));const rows=R.results.filter(r=>r.status==='INSUFFICIENT_EXISTING');
const norm=v=>String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'');const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
(async()=>{const c=new Client({connectionString:process.env.CATALOG_DATABASE_URL,ssl:{rejectUnauthorized:false}});await c.connect();const skus=[...new Set(rows.flatMap(r=>r.candidates.map(x=>x.sku)))];
const sr=(await c.query(`SELECT elimfilters_sku,spec_key,spec_value FROM ld_catalog.ld_product_specifications WHERE elimfilters_sku=ANY($1::text[])`,[skus])).rows;const sm=new Map();for(const x of sr){if(!sm.has(x.elimfilters_sku))sm.set(x.elimfilters_sku,new Map());sm.get(x.elimfilters_sku).set(x.spec_key,x.spec_value)}
const core=['height_mm','outer_diameter_mm','gasket_od_mm','gasket_id_mm','thread_size','media_type','style'];const out=[];for(const r of rows){const j=JSON.parse(fs.readFileSync(r.file,'utf8'));const hs=j.public_catalog_proposal?.technical_specifications||{};const cs=r.candidates.map(ca=>{const ts=sm.get(ca.sku)||new Map();let comp=0,match=0,conf=0;const detail={};for(const k of core){const a=hs[k],b=ts.get(k);if(a==null||a===''||b==null||b==='')continue;comp++;let ok;if(k.endsWith('_mm')){const x=num(a),y=num(b);ok=x!=null&&y!=null&&Math.abs(x-y)<=0.6}else ok=norm(a)===norm(b);if(ok)match++;else conf++;detail[k]={a,b,ok};}return {...ca,spec_comparable:comp,spec_matches:match,spec_conflicts:conf,detail};});out.push({authority:r.authority,family:r.family,candidates:cs});}
const strong=[];for(const r of out){const s=r.candidates.filter(x=>x.spec_comparable>=3&&x.spec_conflicts===0&&x.spec_matches===x.spec_comparable);if(s.length===1)strong.push({...r,resolvedSku:s[0].sku,evidence:s[0]});}
console.log(JSON.stringify({total:out.length,strong:strong.length,strong_items:strong},null,2));fs.writeFileSync('C:/Users/ELIMSERVER/world-catalogue/tmp_fram_insufficient_ldspec.json',JSON.stringify({all:out,strong},null,2));await c.end()})().catch(e=>{console.error(e);process.exit(1)});
