'use strict';
const fs=require('fs'),{Client}=require('pg');
const RP='C:/Users/ELIMSERVER/world-catalogue/elimfilters-vault/91-private-evidence/fram-ld-gap-analysis/fram-ld-gap-2026-09-13T06-38-00-337Z.json';
const R=JSON.parse(fs.readFileSync(RP,'utf8')); const rows=R.results.filter(r=>r.status==='INSUFFICIENT_EXISTING');
const norm=v=>String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,''); const appKey=(m,mo,y,e)=>[norm(m),norm(mo),String(y||'').trim(),norm(e)].join('|'); const looseKey=(m,mo)=>[norm(m),norm(mo)].join('|');
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null}; const core=['height_mm','outer_diameter_mm','gasket_od_mm','gasket_id_mm'];
(async()=>{const c=new Client({connectionString:process.env.CATALOG_DATABASE_URL,ssl:{rejectUnauthorized:false}});await c.connect();const skus=[...new Set(rows.flatMap(r=>r.candidates.map(x=>x.sku)))];
const apps=(await c.query(`SELECT elimfilters_sku,make,model_family,model_type,year,engine_code FROM ld_catalog.ld_vehicle_applications WHERE elimfilters_sku=ANY($1::text[])`,[skus])).rows;const pubs=(await c.query(`SELECT sku,specs,thread_size,height_mm,outer_diameter_mm,gasket_od_mm,gasket_id_mm FROM public.elimfilters_catalog WHERE sku=ANY($1::text[])`,[skus])).rows;
const am=new Map(),pm=new Map(pubs.map(x=>[x.sku,x]));for(const a of apps){if(!am.has(a.elimfilters_sku))am.set(a.elimfilters_sku,[]);am.get(a.elimfilters_sku).push(a)}
const out=[];for(const r of rows){const j=JSON.parse(fs.readFileSync(r.file,'utf8')),p=j.public_catalog_proposal||{},ha=p.vehicle_application_candidates||[],hs=new Set(ha.map(x=>appKey(x.make,x.model,x.year,x.engine))),hl=new Set(ha.map(x=>looseKey(x.make,x.model))),hsp=p.technical_specifications||{};const scored=r.candidates.map(ca=>{const ta=am.get(ca.sku)||[],ts=new Set(ta.map(x=>appKey(x.make,x.model_family,x.year,x.engine_code||x.model_type))),tl=new Set(ta.map(x=>looseKey(x.make,x.model_family)));let inter=0,loose=0;for(const k of hs)if(ts.has(k))inter++;for(const k of hl)if(tl.has(k))loose++;const tp=pm.get(ca.sku)||{},tsp=tp.specs||{};let comparable=0,matches=0,conflicts=0;for(const k of core){const a=num(hsp[k]),b=num(tsp[k]??tp[k]);if(a==null||b==null)continue;comparable++;if(Math.abs(a-b)<=0.6)matches++;else conflicts++;}if(hsp.thread_size&&tp.thread_size){comparable++;if(norm(hsp.thread_size)===norm(tp.thread_size))matches++;else conflicts++;}return {...ca,source_apps:hs.size,target_apps:ts.size,exact_intersection:inter,source_ratio:hs.size?inter/hs.size:0,loose_intersection:loose,loose_ratio:hl.size?loose/hl.size:0,spec_comparable:comparable,spec_matches:matches,spec_conflicts:conflicts};});out.push({authority:r.authority,family:r.family,proposedSku:r.proposedSku,candidates:scored});}
const strong=x=>(x.exact_intersection>=2&&(x.source_ratio>=.5||x.exact_intersection>=20)&&x.spec_conflicts===0)||(x.loose_intersection>=3&&x.loose_ratio>=.6&&x.spec_conflicts===0)||(x.spec_comparable>=2&&x.spec_matches===x.spec_comparable&&x.spec_matches>=2);const resolved=[];for(const r of out){const s=r.candidates.filter(strong).sort((a,b)=>b.exact_intersection-a.exact_intersection||b.spec_matches-a.spec_matches||b.evidenceCount-a.evidenceCount);if(s.length===1)resolved.push({...r,resolvedSku:s[0].sku,evidence:s[0]});}
console.log(JSON.stringify({total:out.length,unique_resolved:resolved.length,unresolved:out.length-resolved.length,resolved:resolved.slice(0,40)},null,2));fs.writeFileSync('C:/Users/ELIMSERVER/world-catalogue/tmp_fram_insufficient_evidence.json',JSON.stringify({all:out,resolved},null,2));await c.end()})().catch(e=>{console.error(e);process.exit(1)});
