'use strict';
const fs=require('fs'),{Client}=require('pg');
const RP='C:/Users/ELIMSERVER/world-catalogue/elimfilters-vault/91-private-evidence/fram-ld-gap-analysis/fram-ld-gap-2026-09-13T06-38-00-337Z.json';
const R=JSON.parse(fs.readFileSync(RP,'utf8')); const rows=R.results.filter(r=>r.status==='SKU_COLLISION_EXISTING');
const norm=v=>String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'');
const appKey=(m,mo,y,e)=>[norm(m),norm(mo),String(y||'').trim(),norm(e)].join('|');
const looseKey=(m,mo)=>[norm(m),norm(mo)].join('|');
(async()=>{const c=new Client({connectionString:process.env.CATALOG_DATABASE_URL,ssl:{rejectUnauthorized:false}});await c.connect();
const skus=[...new Set(rows.map(r=>r.proposedSku))];
const parents=(await c.query(`SELECT elimfilters_sku,source_sku FROM ld_catalog.ld_product_catalog WHERE elimfilters_sku=ANY($1::text[])`,[skus])).rows;
const apps=(await c.query(`SELECT elimfilters_sku,make,model_family,model_type,year,engine_code FROM ld_catalog.ld_vehicle_applications WHERE elimfilters_sku=ANY($1::text[])`,[skus])).rows;
const pm=new Map(parents.map(x=>[x.elimfilters_sku,x.source_sku])); const am=new Map(); for(const a of apps){if(!am.has(a.elimfilters_sku))am.set(a.elimfilters_sku,[]);am.get(a.elimfilters_sku).push(a)}
const out=[];for(const r of rows){const j=JSON.parse(fs.readFileSync(r.file,'utf8')),p=j.public_catalog_proposal||{},refs=[...(p.competitor_cross_reference_candidates||[]),...(p.oem_cross_reference_candidates||[])];const src=pm.get(r.proposedSku)||null;const sourceLink=src?refs.filter(x=>norm(x.part_number)===norm(src)).map(x=>({manufacturer:x.manufacturer,part_number:x.part_number})):[];const ha=p.vehicle_application_candidates||[],ta=am.get(r.proposedSku)||[];const hs=new Set(ha.map(x=>appKey(x.make,x.model,x.year,x.engine))),ts=new Set(ta.map(x=>appKey(x.make,x.model_family,x.year,x.engine_code||x.model_type)));let inter=0;for(const k of hs)if(ts.has(k))inter++;const hl=new Set(ha.map(x=>looseKey(x.make,x.model))),tl=new Set(ta.map(x=>looseKey(x.make,x.model_family)));let loose=0;for(const k of hl)if(tl.has(k))loose++;out.push({authority:r.authority,sku:r.proposedSku,parent_source:src,source_link:sourceLink,source_apps:hs.size,target_apps:ts.size,exact_intersection:inter,source_ratio:hs.size?inter/hs.size:0,loose_intersection:loose,loose_ratio:hl.size?loose/hl.size:0});}
const grouped=new Map();for(const x of out){if(!grouped.has(x.sku))grouped.set(x.sku,[]);grouped.get(x.sku).push(x)}const singles=[...grouped.values()].filter(v=>v.length===1).flat();const strong=x=>x.source_link.length>0||(x.exact_intersection>=2&&(x.source_ratio>=.5||x.exact_intersection>=20))||(x.loose_intersection>=3&&x.loose_ratio>=.6);const safe=singles.filter(strong);console.log(JSON.stringify({rows:out.length,unique_targets:grouped.size,single_rows:singles.length,single_strong:safe.length,strong_by_source_link:safe.filter(x=>x.source_link.length>0).length,strong_by_apps:safe.filter(x=>!x.source_link.length).length,sample:safe.slice(0,30)},null,2));
fs.writeFileSync('C:/Users/ELIMSERVER/world-catalogue/tmp_fram_collision_evidence.json',JSON.stringify(out,null,2));await c.end()})().catch(e=>{console.error(e);process.exit(1)});
