const fs = require('fs');

const code = [];
code.push("require('dotenv').config();");
code.push("const express = require('express');");
code.push("const { fal } = require('@fal-ai/client');");
code.push("const path = require('path');");
code.push("const fs2 = require('fs');");
code.push("const https = require('https');");
code.push("const app = express();");
code.push("app.use(express.json());");
code.push("const RENDERS_DIR = path.join(__dirname, 'renders');");
code.push("if (!fs2.existsSync(RENDERS_DIR)) fs2.mkdirSync(RENDERS_DIR);");
code.push("app.use('/renders', express.static(RENDERS_DIR));");
code.push("fal.config({ credentials: process.env.FAL_KEY });");
code.push("function buildPrompt(data) {");
code.push("    const height = data.geometry_master && data.geometry_master.height_mm || 150;");
code.push("    const diameter = data.geometry_master && data.geometry_master.diameter_mm || 90;");
code.push("    const thread = data.thread_geometry && data.thread_geometry.designation || '';");
code.push("    const sku = data.sku || '';");
code.push("    return 'Professional studio product photography of a heavy duty spin-on oil filter, ' +");
code.push("        'dark gunmetal gray metallic matte finish body, very dark gray with subtle warm metallic sheen, ' +");
code.push("        height.toFixed(0) + 'mm tall, ' + diameter.toFixed(0) + 'mm diameter, ' +");
code.push("        'light gray text on body showing Elimfilters brand name and ' + sku + ' part number, ' +");
code.push("        'polished chrome metallic base plate with ' + thread + ' central thread and drain holes, ' +");
code.push("        'TWO VIEWS on pure white background: ' +");
code.push("        'LEFT VIEW filter laying horizontally tilted toward viewer showing full metallic base plate with central threaded hole and drain holes, ' +");
code.push("        'RIGHT VIEW filter standing vertically upright showing full cylindrical gunmetal body with text, ' +");
code.push("        'soft diffused studio lighting, subtle shadow underneath, ' +");
code.push("        'industrial heavy duty catalog photography, photorealistic, 4K quality';");
code.push("}");
code.push("function downloadImage(url, dest) {");
code.push("    return new Promise((resolve, reject) => {");
code.push("        const file = fs2.createWriteStream(dest);");
code.push("        https.get(url, (response) => {");
code.push("            response.pipe(file);");
code.push("            file.on('finish', () => { file.close(); resolve(); });");
code.push("        }).on('error', (err) => { fs2.unlink(dest, () => {}); reject(err); });");
code.push("    });");
code.push("}");
code.push("app.post('/label', async (req, res) => {");
code.push("    const data = req.body;");
code.push("    if (data.status !== 'OK') return res.json({ agent: 'label_engine', status: 'ERROR' });");
code.push("    const sku = data.sku;");
code.push("    const outputPath = path.join(RENDERS_DIR, sku + '.png');");
code.push("    try {");
code.push("        const prompt = buildPrompt(data);");
code.push("        console.log('Generando imagen con Flux...');");
code.push("        console.log('Prompt:', prompt);");
code.push("        const result = await fal.subscribe('fal-ai/flux/schnell', {");
code.push("            input: { prompt: prompt, image_size: 'landscape_4_3', num_inference_steps: 4, num_images: 1 }");
code.push("        });");
code.push("        const imageUrl = result.data.images[0].url;");
code.push("        console.log('Imagen generada:', imageUrl);");
code.push("        await downloadImage(imageUrl, outputPath);");
code.push("        console.log('PNG guardado:', outputPath);");
code.push("        return res.json({ agent: 'label_engine', status: 'OK', image_url: 'http://localhost:3002/renders/' + sku + '.png', image_path: outputPath, sku: data.sku, geometry_master: data.geometry_master, thread_geometry: data.thread_geometry });");
code.push("    } catch (err) {");
code.push("        console.error('Error:', err.message);");
code.push("        return res.json({ agent: 'label_engine', status: 'ERROR', error: err.message });");
code.push("    }");
code.push("});");
code.push("app.listen(3002, () => console.log('Label Engine running on port 3002'));");

fs.writeFileSync('label_server.js', code.join('\n'));
console.log('label_server.js actualizado con prompt gunmetal');