const fs = require('fs');

const code = [
"require('dotenv').config();",
"const express = require('express');",
"const { fal } = require('@fal-ai/client');",
"const path = require('path');",
"const fs2 = require('fs');",
"const https = require('https');",
"const app = express();",
"app.use(express.json());",
"const RENDERS_DIR = path.join(__dirname, 'renders');",
"if (!fs2.existsSync(RENDERS_DIR)) fs2.mkdirSync(RENDERS_DIR);",
"app.use('/renders', express.static(RENDERS_DIR));",
"fal.config({ credentials: process.env.FAL_KEY });",
"function buildPrompt(data) {",
"    const height = data.geometry_master && data.geometry_master.height_mm || 150;",
"    const diameter = data.geometry_master && data.geometry_master.diameter_mm || 90;",
"    const thread = data.thread_geometry && data.thread_geometry.designation || '';",
"    return 'Professional studio product photography of a white spin-on oil filter, ' +",
"        height.toFixed(0) + 'mm tall, ' + diameter.toFixed(0) + 'mm diameter, ' +",
"        'metallic base plate with ' + thread + ' thread, black top cap, ' +",
"        'orange label stripe in the middle, clean white background, ' +",
"        'soft studio lighting, two views: upright and tilted showing the base, ' +",
"        'photorealistic, industrial catalog photography';",
"}",
"function downloadImage(url, dest) {",
"    return new Promise((resolve, reject) => {",
"        const file = fs2.createWriteStream(dest);",
"        https.get(url, (response) => {",
"            response.pipe(file);",
"            file.on('finish', () => { file.close(); resolve(); });",
"        }).on('error', (err) => { fs2.unlink(dest, () => {}); reject(err); });",
"    });",
"}",
"app.post('/label', async (req, res) => {",
"    const data = req.body;",
"    if (data.status !== 'OK') return res.json({ agent: 'label_engine', status: 'ERROR' });",
"    const sku = data.sku;",
"    const outputPath = path.join(RENDERS_DIR, sku + '.png');",
"    try {",
"        const prompt = buildPrompt(data);",
"        console.log('Generando imagen con Flux...');",
"        console.log('Prompt:', prompt);",
"        const result = await fal.subscribe('fal-ai/flux/schnell', {",
"            input: { prompt: prompt, image_size: 'landscape_4_3', num_inference_steps: 4, num_images: 1 }",
"        });",
"        const imageUrl = result.images[0].url;",
"        console.log('Imagen generada:', imageUrl);",
"        await downloadImage(imageUrl, outputPath);",
"        console.log('PNG guardado:', outputPath);",
"        return res.json({ agent: 'label_engine', status: 'OK', image_url: 'http://localhost:3002/renders/' + sku + '.png', image_path: outputPath, sku: data.sku, geometry_master: data.geometry_master, thread_geometry: data.thread_geometry });",
"    } catch (err) {",
"        console.error('Error:', err.message);",
"        return res.json({ agent: 'label_engine', status: 'ERROR', error: err.message });",
"    }",
"});",
"app.listen(3002, () => console.log('Label Engine running on port 3002'));"
].join('\n');

fs.writeFileSync('label_server.js', code);
console.log('label_server.js escrito correctamente');