import Link from 'next/link';
import styles from './MacrocoreTechnologyPage.module.css';
import { TECHNICAL_REVIEWER } from '@/lib/technical-reviewer';

const faqs=[
 ['What is DRYCORE™?','DRYCORE™ is the ELIMFILTERS air-dryer filtration architecture for moisture control in compressed-air and pneumatic brake systems.'],
 ['Why is moisture control important in pneumatic brake systems?','Condensed moisture can affect valves, actuators and other pneumatic components, reducing system reliability and increasing service risk.'],
 ['What determines DRYCORE™ selection?','Compressor duty, airflow, purge behavior, ambient moisture exposure, capacity and the approved replacement interval must be considered together.'],
 ['Is DRYCORE™ an engine-air filter technology?','No. DRYCORE™ protects a compressed-air pathway and must not be treated as an engine-air or cabin-air filtration substitute.'],
 ['Can one service interval apply to every air dryer?','No. Service interval depends on the approved application, compressor duty, moisture exposure and validated product data.']
] as const;
const list=(items:string[])=><ul className={styles.list}>{items.map(x=><li key={x}>{x}</li>)}</ul>;

export function DrycoreStablePage(){
 const article={'@context':'https://schema.org','@type':'TechArticle','@id':'https://elimfilters.com/technologies/drycore/#article',headline:'DRYCORE™ Air Dryer Filtration Technology',name:'DRYCORE™',url:'https://elimfilters.com/technologies/drycore/',description:'DRYCORE™ is the ELIMFILTERS air-dryer filtration architecture for moisture control in compressed-air and pneumatic brake systems.',image:'https://elimfilters.com/images/airdryer-hero.avif',datePublished:'2026-08-31',dateModified:'2026-09-01',author:{'@type':'Organization','@id':'https://elimfilters.com/#organization',name:'ELIMFILTERS'},reviewedBy:TECHNICAL_REVIEWER,publisher:{'@type':'Organization','@id':'https://elimfilters.com/#organization',name:'ELIMFILTERS'},about:['air dryer filtration','compressed air moisture control','pneumatic brake system','air dryer purge cycle','compressed air condensation'].map(name=>({'@type':'Thing',name})),mentions:['air compressor duty','pneumatic valves','brake actuators','air reservoirs','ambient moisture exposure'].map(name=>({'@type':'Thing',name})),isPartOf:{'@type':'WebSite','@id':'https://elimfilters.com/#website',name:'ELIMFILTERS',url:'https://elimfilters.com/'}};
 const faq={'@context':'https://schema.org','@type':'FAQPage',mainEntity:faqs.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))};
 const breadcrumb={'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:'https://elimfilters.com/'},{'@type':'ListItem',position:2,name:'Technologies',item:'https://elimfilters.com/technologies/'},{'@type':'ListItem',position:3,name:'DRYCORE™',item:'https://elimfilters.com/technologies/drycore/'}]};
 return <main id="main-content" className={styles.page}>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(article)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faq)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumb)}}/>
  <section className={styles.hero} aria-labelledby="drycore-title"><img className={styles.heroBackground} src="/images/airdryer-hero.avif" alt="Compressed-air dryer service environment"/><div className={styles.heroShade} aria-hidden="true"/><h1 id="drycore-title" className={styles.srOnly}>DRYCORE™ Air Dryer Filtration Technology</h1><img className={styles.heroMark} src="/assets/DRYCORE_final.avif" alt="DRYCORE™"/></section>
  <nav aria-label="Breadcrumb" className={styles.breadcrumb}><div className={styles.inner}><Link href="/">HOME</Link><span>→</span><Link href="/technologies/">TECHNOLOGIES</Link><span>→</span><span>DRYCORE™</span></div></nav>
  <section className={styles.introSection}><div className={styles.inner}><p className={styles.eyebrow}>FILTRATION TECHNOLOGY</p><h2 className={styles.displayTitle} style={{fontSize:'clamp(2.25rem,5.25vw,4.65rem)'}}>DRYCORE™</h2><p className={styles.applicationLine}><strong>Compressed-Air Moisture Control</strong></p><p className={styles.lead}>An air-dryer filtration architecture for controlling moisture before condensation can affect pneumatic brake-system components.</p><div className={styles.metaStack}><p><span>Technical review:</span> <Link href="/about/leadership/">Víctor Abreu — Founder &amp; CEO</Link></p></div><div className={styles.twoColumnNotes}><article className={styles.noteBlock}><p className={styles.eyebrow}>DESCRIPTION</p><h3 className={styles.featureTitle}>Moisture Control for Pneumatic Reliability</h3><p className={styles.bodyWide}>DRYCORE™ is ELIMFILTERS’ air-dryer filtration architecture for compressed-air and pneumatic brake systems. Its engineering role is to remove moisture before condensation can affect valves, actuators and other pneumatic components.</p></article><article className={styles.noteBlock}><p className={styles.eyebrow}>SELECTION LOGIC</p><p className={styles.bodyWide}>Capacity, purge behavior, airflow, compressor duty, ambient moisture exposure and replacement interval must be matched to the approved application. The technology name does not imply one universal capacity, service interval or certification.</p></article></div></div></section>
  <section className={styles.band}><div className={styles.inner}><p className={styles.eyebrow}>OPERATING REALITY</p><h2 className={styles.h2}>Compressed air carries moisture load that changes with duty and environment.</h2><p className={styles.lead}>Frequent compressor cycling, high ambient humidity, temperature change and heavy pneumatic demand can increase the moisture burden reaching the air dryer.</p></div></section>
  <section className={styles.bandAlt}><div className={styles.inner}><p className={styles.eyebrow}>APPLICATION ENVIRONMENT</p><h2 className={styles.h2}>Where DRYCORE™ belongs</h2><div className={styles.editorialColumns}><div><h3 className={styles.h3}>Systems</h3>{list(['Heavy-duty pneumatic brake systems','Compressed-air vehicle circuits','Air dryer cartridge applications'])}</div><div><h3 className={styles.h3}>Exposure</h3>{list(['High humidity','Frequent compressor cycling','Cold-weather condensation risk','Severe-duty operation'])}</div><div><h3 className={styles.h3}>Protected components</h3>{list(['Valves','Actuators','Air reservoirs','Pneumatic controls'])}</div></div></div></section>
  <section className={styles.band}><div className={styles.inner}><p className={styles.eyebrow}>SPECIFICATION &amp; SELECTION</p><h2 className={styles.h2}>Questions before selecting an air-dryer element</h2><div className={styles.editorialColumns}><div><h3 className={styles.h3}>Key parameters</h3>{list(['Approved dryer geometry','Compressor duty cycle','Required airflow','Purge behavior','Moisture exposure','Service interval'])}</div><div><h3 className={styles.h3}>Common errors</h3>{list(['Selecting by thread or dimensions alone','Ignoring purge-system condition','Extending interval despite moisture symptoms','Treating DRYCORE™ as engine-air filtration'])}</div><div><h3 className={styles.h3}>Validation inputs</h3>{list(['Vehicle or equipment','Current dryer reference','Compressor type','Duty cycle','Climate and humidity','Service history'])}</div></div><div className={styles.inlineCta}><p><strong>Known application?</strong> Use Part Search. <strong>Moisture or purge problem?</strong> Use technical review.</p><div className={styles.buttonRow}><a className={styles.primaryButton} href="https://part-search.elimfilters.com" target="_blank" rel="noopener noreferrer" data-conversion-action="product-intelligence">FIND MY PART</a><a className={styles.secondaryButton} href="mailto:applications@elimfilters.com?subject=DRYCORE%20Air%20Dryer%20Application%20Assessment" data-conversion-action="application-support">TECHNICAL REVIEW</a></div></div></div></section>
  <section className={styles.bandAlt}><div className={styles.inner}><p className={styles.eyebrow}>HOW THE SYSTEM BEHAVES</p><h2 className={styles.h2}>Drying capacity, airflow and purge behavior operate as one system.</h2><p className={styles.lead}>A dryer element cannot be evaluated in isolation from compressor output, purge operation, reservoir condition and ambient moisture exposure.</p></div></section>
  <section className={styles.band}><div className={styles.inner}><p className={styles.eyebrow}>SERVICE &amp; DIAGNOSIS</p><h2 className={styles.h2}>What recurring moisture may be telling you</h2>{list(['Dryer element at service limit','Abnormal compressor duty','Purge-system fault','Reservoir drainage issue','Excessive ambient moisture load','Incorrect replacement interval'])}</div></section>
  <section className={styles.bandAlt}><div className={styles.inner}><p className={styles.eyebrow}>QUESTIONS FROM THE FIELD</p><h2 className={styles.h2}>Direct answers to common air-dryer questions.</h2><div className={styles.faqList}>{faqs.map(([q,a])=><details className={styles.faqItem} key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></div></section>
  <section className={styles.band}><div className={styles.inner}><p className={styles.eyebrow}>TECHNICAL BASIS</p><h2 className={styles.h2}>Technical reference</h2><div className={styles.twoColumnNotes}><article className={styles.noteBlock}><h3 className={styles.h3}>Product-level evidence</h3><p className={styles.body}>Capacity, pressure-drop behavior, airflow limits and service intervals belong to validated individual product data and the approved application.</p></article><article className={styles.noteBlock}><h3 className={styles.h3}>Claim governance</h3><p className={styles.body}>DRYCORE™ is not assigned one universal capacity, purge interval, airflow limit or certification across every application.</p></article></div></div></section>
  <section className={styles.bandAlt}><div className={styles.inner}><p className={styles.eyebrow}>WHEN A TECHNICAL REVIEW MAKES SENSE</p><h2 className={styles.h2}>When moisture control becomes a pneumatic-system problem</h2><p className={styles.lead}>Repeated water in reservoirs, freezing risk, abnormal purge behavior or short element life justify reviewing compressor duty, dryer operation and the complete pneumatic circuit.</p></div></section>
  <section className={styles.band}><div className={styles.inner}><p className={styles.eyebrow}>SYSTEM INTEGRATION</p><h2 className={styles.h2}>Air Intake &amp; Airflow Protection</h2><div className={styles.systemGrid}><div><p className={styles.lead}>DRYCORE™ provides the moisture-control layer for compressed-air and pneumatic brake-system protection.</p><Link className={styles.systemButton} href="/systems/air-intake/">EXPLORE PROTECTION SYSTEM</Link></div><p className={styles.bodyWide}>MACROCORE™ and MICROKAPPA™ protect different airflow paths. DRYCORE™ remains specific to compressed-air moisture control.</p></div></div></section>
  <section className={styles.ctaSection}><div className={styles.inner}><p className={styles.eyebrow}>APPLICATION SUPPORT</p><h2 className={styles.h2}>Bring us the dryer reference, compressor duty and moisture history — not just the part number.</h2><div className={styles.buttonRow}><a className={styles.primaryButton} href="https://part-search.elimfilters.com" target="_blank" rel="noopener noreferrer" data-conversion-action="product-intelligence">FIND MY PART</a><a className={styles.secondaryButton} href="mailto:applications@elimfilters.com?subject=DRYCORE%20Air%20Dryer%20Application%20Assessment" data-conversion-action="application-support">TECHNICAL REVIEW PATH</a></div></div></section>
 </main>;
}
