import Link from 'next/link';
import styles from './MacrocoreTechnologyPage.module.css';
import { TECHNICAL_REVIEWER } from '@/lib/technical-reviewer';

const faqs=[
 ['What is INTEKCORE™?','INTEKCORE™ is the ELIMFILTERS air-cleaner housing and sealing architecture for controlled airflow, element retention and bypass prevention.'],
 ['Why does housing integrity matter?','A damaged housing, poor element fit or inadequate seal loading can create an unfiltered-air ingress path around the intended filtration boundary.'],
 ['How is INTEKCORE™ different from MACROCORE™?','INTEKCORE™ governs the housing, retention and sealing boundary. MACROCORE™ governs the engine-air filtration layer.'],
 ['What must be validated in an air-cleaner housing application?','Housing geometry, inlet routing, restriction, element fit, seal loading, structural integrity and duty cycle should be validated for the intended application.'],
 ['Does INTEKCORE™ imply one universal ISO 5011 performance value?','No. ISO 5011 provides relevant air-cleaner test methods, but the technology name alone does not imply one universal result or certification.']
] as const;
const list=(items:string[])=><ul className={styles.list}>{items.map(x=><li key={x}>{x}</li>)}</ul>;

export function IntekcoreStablePage(){
 const article={'@context':'https://schema.org','@type':'TechArticle','@id':'https://elimfilters.com/technologies/intekcore/#article',headline:'INTEKCORE™ Air Cleaner Housing and Sealing Technology',name:'INTEKCORE™',url:'https://elimfilters.com/technologies/intekcore/',description:'INTEKCORE™ is the ELIMFILTERS air-cleaner housing and sealing architecture for controlled airflow, element retention and bypass prevention.',image:'https://elimfilters.com/images/intekcor-hero.avif',datePublished:'2026-08-31',dateModified:'2026-09-01',author:{'@type':'Organization','@id':'https://elimfilters.com/#organization',name:'ELIMFILTERS'},reviewedBy:TECHNICAL_REVIEWER,publisher:{'@type':'Organization','@id':'https://elimfilters.com/#organization',name:'ELIMFILTERS'},about:['air cleaner housing','air intake sealing','unfiltered air bypass prevention','engine intake airflow','element retention'].map(name=>({'@type':'Thing',name})),mentions:['housing geometry','seal loading','inlet routing','air cleaner restriction','ISO 5011','engine air filtration'].map(name=>({'@type':'Thing',name})),isPartOf:{'@type':'WebSite','@id':'https://elimfilters.com/#website',name:'ELIMFILTERS',url:'https://elimfilters.com/'}};
 const faq={'@context':'https://schema.org','@type':'FAQPage',mainEntity:faqs.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))};
 const breadcrumb={'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:'https://elimfilters.com/'},{'@type':'ListItem',position:2,name:'Technologies',item:'https://elimfilters.com/technologies/'},{'@type':'ListItem',position:3,name:'INTEKCORE™',item:'https://elimfilters.com/technologies/intekcore/'}]};
 return <main id="main-content" className={styles.page}>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(article)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faq)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumb)}}/>
  <section className={styles.hero} aria-labelledby="intekcore-title"><img className={styles.heroBackground} src="/images/intekcor-hero.avif" alt="Engine air-cleaner housing and intake environment"/><div className={styles.heroShade} aria-hidden="true"/><h1 id="intekcore-title" className={styles.srOnly}>INTEKCORE™ Air Cleaner Housing and Sealing Technology</h1><img className={styles.heroMark} src="/assets/INTEKCORE_final.avif" alt="INTEKCORE™"/></section>
  <nav aria-label="Breadcrumb" className={styles.breadcrumb}><div className={styles.inner}><Link href="/">HOME</Link><span>→</span><Link href="/technologies/">TECHNOLOGIES</Link><span>→</span><span>INTEKCORE™</span></div></nav>
  <section className={styles.introSection}><div className={styles.inner}><p className={styles.eyebrow}>FILTRATION TECHNOLOGY</p><h2 className={styles.displayTitle} style={{fontSize:'clamp(2.25rem,5.25vw,4.65rem)'}}>INTEKCORE™</h2><p className={styles.applicationLine}><strong>Air Cleaner Housing &amp; Sealing Architecture</strong></p><p className={styles.lead}>An intake-system architecture for preserving the protected airflow boundary through housing geometry, structural integrity, element retention and seal loading.</p><div className={styles.metaStack}><p><span>Technical review:</span> <Link href="/about/leadership/">Víctor Abreu — Founder &amp; CEO</Link></p></div><div className={styles.twoColumnNotes}><article className={styles.noteBlock}><p className={styles.eyebrow}>DESCRIPTION</p><h3 className={styles.featureTitle}>Controlled Airflow and Bypass Prevention</h3><p className={styles.bodyWide}>INTEKCORE™ is ELIMFILTERS’ air-cleaner housing and sealing architecture for controlled airflow and bypass prevention within engine intake systems.</p></article><article className={styles.noteBlock}><p className={styles.eyebrow}>ENGINEERING ROLE</p><p className={styles.bodyWide}>Housing sizing, inlet routing, restriction, element fit, retention and sealing must be validated for the intended duty cycle. Reliable sealing reduces the risk of unfiltered-air ingress around the filtration element.</p></article></div></div></section>
  <section className={styles.band}><div className={styles.inner}><p className={styles.eyebrow}>OPERATING REALITY</p><h2 className={styles.h2}>A high-efficiency element cannot protect an engine if air bypasses the element.</h2><p className={styles.lead}>Housing distortion, damaged sealing surfaces, incorrect element fit or retention problems can open an unintended contamination path even when the filtration media itself is suitable.</p></div></section>
  <section className={styles.bandAlt}><div className={styles.inner}><p className={styles.eyebrow}>APPLICATION ENVIRONMENT</p><h2 className={styles.h2}>Where INTEKCORE™ belongs</h2><div className={styles.editorialColumns}><div><h3 className={styles.h3}>Applications</h3>{list(['Engine air-cleaner housings','Primary and secondary intake assemblies','Heavy-duty intake systems'])}</div><div><h3 className={styles.h3}>Operating exposure</h3>{list(['High dust loading','Vibration and structural stress','Severe-duty off-road operation','High airflow demand'])}</div><div><h3 className={styles.h3}>Protected boundary</h3>{list(['Housing body','Element retention','Radial or axial seals','Inlet and outlet airflow path'])}</div></div></div></section>
  <section className={styles.band}><div className={styles.inner}><p className={styles.eyebrow}>SPECIFICATION &amp; SELECTION</p><h2 className={styles.h2}>Questions before selecting an air-cleaner housing</h2><div className={styles.editorialColumns}><div><h3 className={styles.h3}>Key parameters</h3>{list(['Required airflow','Allowable restriction','Housing geometry','Element fit','Seal loading','Inlet routing'])}</div><div><h3 className={styles.h3}>Common errors</h3>{list(['Selecting by diameter alone','Ignoring seal interface condition','Mismatching housing and element geometry','Overlooking vibration and mounting'])}</div><div><h3 className={styles.h3}>Validation inputs</h3>{list(['Engine or equipment','Current housing reference','Filter element reference','Airflow requirement','Mounting constraints','Duty environment'])}</div></div><div className={styles.inlineCta}><p><strong>Known housing or element?</strong> Use Part Search. <strong>Bypass, sealing or restriction problem?</strong> Use technical review.</p><div className={styles.buttonRow}><a className={styles.primaryButton} href="https://part-search.elimfilters.com" target="_blank" rel="noopener noreferrer" data-conversion-action="product-intelligence">FIND MY PART</a><a className={styles.secondaryButton} href="mailto:applications@elimfilters.com?subject=INTEKCORE%20Air%20Cleaner%20Housing%20Assessment" data-conversion-action="application-support">TECHNICAL REVIEW</a></div></div></div></section>
  <section className={styles.bandAlt}><div className={styles.inner}><p className={styles.eyebrow}>HOW THE SYSTEM BEHAVES</p><h2 className={styles.h2}>Housing, seal, element and airflow operate as one intake boundary.</h2><p className={styles.lead}>The housing must retain the element correctly, maintain seal compression and route the required airflow without creating an unintended bypass path or excessive restriction.</p></div></section>
  <section className={styles.band}><div className={styles.inner}><p className={styles.eyebrow}>SERVICE &amp; DIAGNOSIS</p><h2 className={styles.h2}>What dust downstream of the air cleaner may be telling you</h2>{list(['Damaged housing or cover','Incorrect element fit','Seal damage or inadequate compression','Loose retention hardware','Cracked intake ducting','Improper installation'])}</div></section>
  <section className={styles.bandAlt}><div className={styles.inner}><p className={styles.eyebrow}>QUESTIONS FROM THE FIELD</p><h2 className={styles.h2}>Direct answers to common housing and sealing questions.</h2><div className={styles.faqList}>{faqs.map(([q,a])=><details className={styles.faqItem} key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></div></section>
  <section className={styles.band}><div className={styles.inner}><p className={styles.eyebrow}>TECHNICAL BASIS</p><h2 className={styles.h2}>Technical reference</h2><div className={styles.twoColumnNotes}><article className={styles.noteBlock}><h3 className={styles.h3}>Relevant test framework</h3><p className={styles.body}>ISO 5011 provides relevant performance test methods for approved air-cleaner applications. Product-level results must remain tied to validated system data.</p></article><article className={styles.noteBlock}><h3 className={styles.h3}>Claim governance</h3><p className={styles.body}>INTEKCORE™ does not imply one universal efficiency, restriction limit, dust capacity or ISO 5011 result across every housing application.</p></article></div></div></section>
  <section className={styles.bandAlt}><div className={styles.inner}><p className={styles.eyebrow}>WHEN A TECHNICAL REVIEW MAKES SENSE</p><h2 className={styles.h2}>When filter replacement does not solve intake contamination</h2><p className={styles.lead}>Recurring downstream dust, seal witness marks, housing damage or abnormal restriction justify reviewing the complete air-cleaner assembly rather than replacing the element alone.</p></div></section>
  <section className={styles.band}><div className={styles.inner}><p className={styles.eyebrow}>SYSTEM INTEGRATION</p><h2 className={styles.h2}>Air Intake &amp; Airflow Protection</h2><div className={styles.systemGrid}><div><p className={styles.lead}>INTEKCORE™ provides the housing, retention and sealing layer of ELIMFILTERS Air Intake &amp; Airflow Protection.</p><Link className={styles.systemButton} href="/systems/air-intake/">EXPLORE PROTECTION SYSTEM</Link></div><p className={styles.bodyWide}>MACROCORE™ governs the engine-air filtration layer. INTEKCORE™ governs the structural and sealing boundary that ensures airflow passes through that element.</p></div></div></section>
  <section className={styles.ctaSection}><div className={styles.inner}><p className={styles.eyebrow}>APPLICATION SUPPORT</p><h2 className={styles.h2}>Bring us the housing, element, airflow requirement and failure pattern — not just the part number.</h2><div className={styles.buttonRow}><a className={styles.primaryButton} href="https://part-search.elimfilters.com" target="_blank" rel="noopener noreferrer" data-conversion-action="product-intelligence">FIND MY PART</a><a className={styles.secondaryButton} href="mailto:applications@elimfilters.com?subject=INTEKCORE%20Air%20Cleaner%20Housing%20Assessment" data-conversion-action="application-support">TECHNICAL REVIEW PATH</a></div></div></section>
 </main>;
}
