import Link from 'next/link';
import styles from './MacrocoreTechnologyPage.module.css';

const faqs = [
 ['What is MICROKAPPA™?','MICROKAPPA™ is ELIMFILTERS’ cabin air filtration architecture for controlling airborne dust, pollen and fine particulate matter before they enter the ventilation system and passenger compartment.'],
 ['What does a cabin air filter protect?','Cabin filtration helps reduce airborne particulate entering the occupied compartment and can also limit contaminant accumulation on ventilation ducts, evaporator surfaces and other HVAC components.'],
 ['Can a more restrictive cabin filter reduce HVAC airflow?','Yes. Particle retention and airflow resistance must be balanced. Excessive restriction can reduce ventilation performance, so the filter must be matched to the approved HVAC application.'],
 ['Why does a cabin filter plug early?','High dust exposure, pollen, construction environments, agricultural duty, extended service intervals and heavy recirculation can accelerate loading.'],
 ['Where can MICROKAPPA™ be applied?','Approved configurations can support passenger vehicles, commercial fleets and heavy-duty equipment across different cabin-filter geometries and operating environments.'],
 ['What information helps with cabin-filter application validation?','Vehicle or equipment identification, current filter, dimensions and geometry, HVAC configuration, operating environment, service interval and airflow or odor complaints are useful inputs.']
] as const;
const list=(items:string[])=><ul className={styles.list}>{items.map(x=><li key={x}>{x}</li>)}</ul>;

export function MicrokappaStablePage(){
 const article={'@context':'https://schema.org','@type':'TechArticle','@id':'https://elimfilters.com/technologies/microkappa/#article',headline:'MICROKAPPA™ Cabin Air Filtration Technology',name:'MICROKAPPA™',url:'https://elimfilters.com/technologies/microkappa/',description:'MICROKAPPA™ is the ELIMFILTERS cabin air filtration architecture developed to help capture airborne dust, pollen and fine particulate matter before they enter the vehicle ventilation system and passenger compartment.',author:{'@type':'Organization','@id':'https://elimfilters.com/#organization',name:'ELIMFILTERS'},publisher:{'@type':'Organization','@id':'https://elimfilters.com/#organization',name:'ELIMFILTERS'},about:['cabin air filtration','HVAC filtration','pollen filtration','fine particulate matter','cabin filter airflow resistance'].map(name=>({'@type':'Thing',name})),mentions:['ventilation ducts','evaporator surfaces','passenger compartment','commercial fleets','heavy-duty equipment'].map(name=>({'@type':'Thing',name})),isPartOf:{'@type':'WebSite','@id':'https://elimfilters.com/#website',name:'ELIMFILTERS',url:'https://elimfilters.com/'}};
 const faq={'@context':'https://schema.org','@type':'FAQPage',mainEntity:faqs.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))};
 const breadcrumb={'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:'https://elimfilters.com/'},{'@type':'ListItem',position:2,name:'Technologies',item:'https://elimfilters.com/technologies/'},{'@type':'ListItem',position:3,name:'MICROKAPPA™',item:'https://elimfilters.com/technologies/microkappa/'}]};
 return <main id="main-content" className={styles.page}>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(article)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faq)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumb)}}/>
  <section className={`${styles.hero} ${styles.microkappaHero}`} aria-labelledby="microkappa-title"><img className={styles.heroBackground} src="/images/cabin-hero.avif" alt="Vehicle cabin HVAC filtration environment"/><div className={styles.heroShade} aria-hidden="true"/><h1 id="microkappa-title" className={styles.srOnly}>MICROKAPPA™ Cabin Air Filtration Technology</h1><img className={styles.heroMark} src="/assets/MICROKAPPA_final.avif" alt="MICROKAPPA™"/></section>
  <nav aria-label="Breadcrumb" className={styles.breadcrumb}><div className={styles.inner}><Link href="/">HOME</Link><span>→</span><Link href="/technologies/">TECHNOLOGIES</Link><span>→</span><span>MICROKAPPA™</span></div></nav>
  <section className={styles.introSection}><div className={styles.inner}><p className={styles.eyebrow}>FILTRATION TECHNOLOGY</p><h2 className={styles.displayTitle} style={{fontSize:'clamp(2.25rem,5.25vw,4.65rem)'}}>MICROKAPPA™</h2><p className={styles.applicationLine}><strong>Cabin air filtration</strong></p><p className={styles.lead}>An HVAC filtration architecture for controlling airborne particulate before it enters the ventilation system and occupied cabin.</p><div className={styles.mediaGrid}><div className={styles.mediaCopy}><div className={styles.metaStack}><p><span>Technology:</span> MICROKAPPA™</p><p><span>Application:</span> Cabin and HVAC air filtration</p></div><p className={styles.eyebrow}>DESCRIPTION</p><h3 className={styles.featureTitle}>Cabin Air Contamination Control</h3><p className={styles.lead}>MICROKAPPA™ is ELIMFILTERS’ cabin air filtration architecture, developed to help capture airborne dust, pollen and fine particulate matter before they enter the vehicle’s ventilation system and passenger compartment.</p><p className={styles.bodyWide}>Its media structure is designed to balance particle retention with controlled airflow resistance, supporting consistent HVAC performance throughout the filter’s service interval. The architecture also helps limit contaminant accumulation within ventilation ducts, evaporator surfaces and other HVAC components.</p><p className={styles.bodyWide}>MICROKAPPA™ can be configured for different cabin-filter geometries and operating environments, providing a dependable filtration solution for passenger vehicles, commercial fleets and heavy-duty equipment.</p></div><figure className={styles.mediaFigure}><img className={styles.mediaImage} src="/images/MICROKAPPA-Media.jpeg" alt="MICROKAPPA filtration media microscopic visualization"/><figcaption>Microscopic visualization of filtration media structure used for technical illustration.</figcaption></figure></div></div></section>
  <section className={styles.band}><div className={styles.inner}><p className={styles.eyebrow}>OPERATING REALITY</p><h2 className={styles.h2}>Cabin filtration has to protect air quality without starving the HVAC system.</h2><p className={styles.lead}>Dust, pollen and fine airborne particulate enter through fresh-air intake and recirculation paths. As loading develops, filtration efficiency, contaminant capacity and airflow resistance must remain balanced for the approved HVAC application.</p></div></section>
  <section className={styles.bandAlt}><div className={styles.inner}><p className={styles.eyebrow}>APPLICATION ENVIRONMENT</p><h2 className={styles.h2}>Where MICROKAPPA™ belongs</h2><div className={styles.editorialColumns}><div><h3 className={styles.h3}>Applications</h3>{list(['Passenger vehicles','Commercial fleets','Heavy-duty equipment','Agricultural and construction cabs'])}</div><div><h3 className={styles.h3}>Operating exposure</h3>{list(['Road dust and urban particulate','Pollen and seasonal loading','Construction and agricultural dust','High recirculation duty'])}</div><div><h3 className={styles.h3}>Protected HVAC areas</h3>{list(['Passenger compartment','Ventilation ducts','Evaporator surfaces','HVAC airflow path'])}</div></div></div></section>
  <section className={styles.band}><div className={styles.inner}><p className={styles.eyebrow}>SPECIFICATION &amp; SELECTION</p><h2 className={styles.h2}>Questions before selecting a cabin filter</h2><div className={styles.editorialColumns}><div><h3 className={styles.h3}>Key parameters</h3>{list(['Approved geometry and fit','Particle-retention requirement','Airflow resistance','Media configuration','Seal integrity','Operating environment'])}</div><div><h3 className={styles.h3}>Common errors</h3>{list(['Selecting by dimensions alone','Ignoring airflow restriction','Extending intervals despite reduced airflow','Poor sealing at the filter frame'])}</div><div><h3 className={styles.h3}>Validation inputs</h3>{list(['Vehicle or equipment','Current filter reference','Dimensions and geometry','HVAC configuration','Duty environment','Service history'])}</div></div><div className={styles.inlineCta}><p><strong>Known application?</strong> Use Part Search. <strong>Airflow, fit or premature-loading problem?</strong> Use technical review.</p><div className={styles.buttonRow}><a className={styles.primaryButton} href="https://part-search.elimfilters.com" target="_blank" rel="noopener noreferrer" data-conversion-action="product-intelligence">FIND MY PART</a><a className={styles.secondaryButton} href="mailto:applications@elimfilters.com?subject=MICROKAPPA%20Cabin%20Air%20Application%20Assessment" data-conversion-action="application-support">TECHNICAL REVIEW</a></div></div></div></section>
  <section className={styles.bandAlt}><div className={styles.inner}><p className={styles.eyebrow}>HOW THE SYSTEM BEHAVES</p><h2 className={styles.h2}>Particle retention and airflow resistance develop together.</h2><p className={styles.lead}>A cabin filter is not defined by capture alone. Media structure, filtration area, loading behavior, frame sealing and HVAC airflow demand determine whether the system can maintain useful ventilation through the service interval.</p></div></section>
  <section className={styles.band}><div className={styles.inner}><p className={styles.eyebrow}>SERVICE &amp; DIAGNOSIS</p><h2 className={styles.h2}>What reduced cabin airflow may be telling you</h2>{list(['Loaded cabin filter','High dust or pollen exposure','Extended service interval','Incorrect filter geometry','Seal or installation problem','Contamination on downstream HVAC surfaces'])}<div className={styles.inlineCta}><p>Recurring airflow loss or unusually short service intervals justify an HVAC filtration review.</p><a href="mailto:applications@elimfilters.com?subject=MICROKAPPA%20HVAC%20Filtration%20Review" data-conversion-action="application-support">REQUEST CABIN FILTRATION REVIEW</a></div></div></section>
  <section className={styles.bandAlt}><div className={styles.inner}><p className={styles.eyebrow}>QUESTIONS FROM THE FIELD</p><h2 className={styles.h2}>Direct answers to common cabin-filtration questions.</h2><div className={styles.faqList}>{faqs.map(([q,a])=><details className={styles.faqItem} key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></div></section>
  <section className={styles.band}><div className={styles.inner}><p className={styles.eyebrow}>TECHNICAL BASIS</p><h2 className={styles.h2}>Technical reference</h2><div className={styles.twoColumnNotes}><article className={styles.noteBlock}><h3 className={styles.h3}>Product-level evidence</h3><p className={styles.body}>Efficiency, pressure-drop and capacity values belong to validated individual filter data and the applicable test method.</p></article><article className={styles.noteBlock}><h3 className={styles.h3}>Claim governance</h3><p className={styles.body}>MICROKAPPA™ is not assigned one universal efficiency, particulate rating, pressure-drop value or service interval across every cabin application.</p></article></div></div></section>
  <section className={styles.bandAlt}><div className={styles.inner}><p className={styles.eyebrow}>WHEN A TECHNICAL REVIEW MAKES SENSE</p><h2 className={styles.h2}>When cabin filtration becomes an HVAC performance problem</h2><p className={styles.lead}>Repeated airflow complaints, premature loading, fit problems or severe operating environments justify reviewing the complete cabin-air path rather than replacing elements by appearance alone.</p></div></section>
  <section className={styles.band}><div className={styles.inner}><p className={styles.eyebrow}>SYSTEM INTEGRATION</p><h2 className={styles.h2}>Air Intake &amp; Airflow Protection</h2><div className={styles.systemGrid}><div><p className={styles.lead}>MICROKAPPA™ controls particulate entering operator and passenger HVAC systems while preserving the airflow required by the ventilation architecture.</p><Link className={styles.systemButton} href="/systems/air-intake-airflow/">EXPLORE PROTECTION SYSTEM</Link></div><p className={styles.bodyWide}>Final selection resolves filter geometry, media configuration, particle-control requirement, airflow resistance, seal integrity and the real contamination environment.</p></div></div></section>
  <section className={styles.ctaSection}><div className={styles.inner}><p className={styles.eyebrow}>APPLICATION SUPPORT</p><h2 className={styles.h2}>Bring us the vehicle, HVAC configuration and operating environment — not just the part number.</h2><p className={styles.lead}>Use Part Search when the application is known. For recurring airflow loss, premature loading or uncertain cabin-filter architecture, use technical review.</p><div className={styles.buttonRow}><a className={styles.primaryButton} href="https://part-search.elimfilters.com" target="_blank" rel="noopener noreferrer" data-conversion-action="product-intelligence">FIND MY PART</a><a className={styles.secondaryButton} href="mailto:applications@elimfilters.com?subject=MICROKAPPA%20Cabin%20Air%20Application%20Assessment" data-conversion-action="application-support">TECHNICAL REVIEW PATH</a></div></div></section>
  <section className={styles.bandAlt}><div className={styles.inner}><p className={styles.eyebrow}>EXPLORE RELATED TECHNOLOGIES</p><h2 className={styles.h2}>Explore related protection technologies and principles.</h2><div className={styles.textLinks}><Link href="/systems/">Protection Systems →</Link><Link href="/industries/">Industries →</Link><Link href="/knowledge-center/">Knowledge System →</Link><a href="https://part-search.elimfilters.com">Part Search →</a></div></div></section>
 </main>;
}
