import Link from 'next/link';
import styles from './MacrocoreTechnologyPage.module.css';
import { TECHNICAL_REVIEWER } from '@/lib/technical-reviewer';

const faqs = [
  ['What is NANOFORCE™?', 'NANOFORCE™ is the ELIMFILTERS hydraulic-filtration architecture developed to maintain fluid cleanliness around the tolerance requirements of pumps, valves, actuators and precision hydraulic components.'],
  ['How is a hydraulic filter selected?', 'Selection should resolve the cleanliness target, critical particle size, system flow, pressure, fluid viscosity, duty cycle, filter position and validated element performance together.'],
  ['What does Beta performance mean in hydraulic filtration?', 'Beta performance expresses the relationship between upstream and downstream particle counts at a specified particle size under the applicable test method. Product-level Beta values must be supported by validated data.'],
  ['Is a lower micron rating always better for a hydraulic system?', 'No. Particle-control performance must be balanced with flow, pressure drop, viscosity, structural integrity and the cleanliness requirement of the most sensitive component.'],
  ['Where can NANOFORCE™ be applied?', 'Approved applications can include pressure-line, return-line and offline filtration positions where the element and housing are validated for the required flow, pressure and contamination-control duty.'],
  ['Why does hydraulic filter pressure drop increase?', 'Pressure drop can rise as contamination accumulates, fluid viscosity increases, flow rises or the selected element is not matched to the operating condition.'],
  ['What information helps with a hydraulic application review?', 'Useful inputs include equipment identification, hydraulic circuit, filter position, current element and housing, fluid type and viscosity, operating pressure and flow, cleanliness target, duty cycle and failure history.'],
] as const;

const list = (items:string[]) => <ul className={styles.list}>{items.map(x=><li key={x}>{x}</li>)}</ul>;

export function NanoforceStablePage() {
  const articleSchema = {
    '@context':'https://schema.org','@type':'TechArticle','@id':'https://elimfilters.com/technologies/nanoforce/#article',
    headline:'NANOFORCE™ Hydraulic Filtration Technology',name:'NANOFORCE™',url:'https://elimfilters.com/technologies/nanoforce/',
    description:'NANOFORCE™ is the ELIMFILTERS hydraulic-filtration architecture developed to maintain fluid cleanliness around the tolerance requirements of pumps, valves, actuators and precision hydraulic components.',
    author:{'@type':'Organization','@id':'https://elimfilters.com/#organization',name:'ELIMFILTERS'},reviewedBy:TECHNICAL_REVIEWER,publisher:{'@type':'Organization','@id':'https://elimfilters.com/#organization',name:'ELIMFILTERS'},
    about:['hydraulic filtration','hydraulic fluid cleanliness','pressure-line filtration','return-line filtration','offline filtration','Beta ratio','critical particle size','hydraulic filter pressure drop'].map(name=>({'@type':'Thing',name})),
    mentions:['pumps','hydraulic valves','actuators','precision hydraulic components','fluid viscosity','system flow','operating pressure'].map(name=>({'@type':'Thing',name})),
    isPartOf:{'@type':'WebSite','@id':'https://elimfilters.com/#website',name:'ELIMFILTERS',url:'https://elimfilters.com/'}
  };
  const faqSchema = {'@context':'https://schema.org','@type':'FAQPage',mainEntity:faqs.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))};
  const breadcrumbSchema = {'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[
    {'@type':'ListItem',position:1,name:'Home',item:'https://elimfilters.com/'},
    {'@type':'ListItem',position:2,name:'Technologies',item:'https://elimfilters.com/technologies/'},
    {'@type':'ListItem',position:3,name:'NANOFORCE™',item:'https://elimfilters.com/technologies/nanoforce/'}
  ]};

  return <main id="main-content" className={styles.page}>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(articleSchema)}} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumbSchema)}} />

    <section className={`${styles.hero} ${styles.nanoforceHero}`} aria-labelledby="nanoforce-title">
      <img className={styles.heroBackground} src="/images/nanoforce-mecanico.avif" alt="Hydraulic filtration service environment" />
      <div className={styles.heroShade} aria-hidden="true" />
      <h1 id="nanoforce-title" className={styles.srOnly}>NANOFORCE™ Hydraulic Filtration Technology</h1>
      <img className={styles.heroMark} src="/assets/NANOFORCE_final.avif" alt="NANOFORCE™" />
    </section>

    <nav aria-label="Breadcrumb" style={{padding:'1rem clamp(1.15rem,6vw,6rem)',borderBottom:'1px solid rgba(255,255,255,.12)',background:'#020202'}}><div className={styles.inner} style={{display:'flex',gap:'.65rem',fontSize:'.72rem',letterSpacing:'.08em'}}><Link href="/" style={{color:'rgba(255,255,255,.55)',textDecoration:'none'}}>HOME</Link><span>→</span><Link href="/technologies/" style={{color:'rgba(255,255,255,.55)',textDecoration:'none'}}>TECHNOLOGIES</Link><span>→</span><span style={{color:'#fff12d'}}>NANOFORCE™</span></div></nav>

    <section className={styles.introSection}><div className={styles.inner}>
      <p className={styles.eyebrow}>FILTRATION TECHNOLOGY</p>
      <h2 className={styles.displayTitle} style={{fontSize:'clamp(2.25rem,5.25vw,4.65rem)'}}>NANOFORCE™</h2>
      <p className={styles.applicationLine}><strong>Hydraulic fluid filtration</strong></p>
      <p className={styles.lead}>A hydraulic-filtration architecture for maintaining fluid cleanliness around the tolerance requirements of pumps, valves, actuators and precision components.</p>
      <div className={styles.mediaGrid}><div className={styles.mediaCopy}><div className={styles.metaStack}><p><span>Technology:</span> NANOFORCE™</p><p><span>Application:</span> Pressure-line, return-line and approved offline hydraulic filtration</p><p><span>Technical review:</span> <Link href="/about/leadership/">Víctor Abreu — Founder &amp; CEO</Link></p></div><p className={styles.eyebrow}>DESCRIPTION</p><h3 className={styles.featureTitle}>Hydraulic Fluid Cleanliness Control</h3><p className={styles.lead}>NANOFORCE™ is the ELIMFILTERS hydraulic-filtration architecture developed to maintain fluid cleanliness around the tolerance requirements of pumps, valves, actuators and precision hydraulic components.</p><p className={styles.bodyWide}>Media and element construction are selected according to the required cleanliness target, critical particle size, system flow, pressure, fluid viscosity and operating duty. This engineering flexibility allows filtration to be configured for pressure-line, return-line and approved offline applications.</p><p className={styles.bodyWide}>Product-level efficiency, Beta performance, contaminant capacity and pressure ratings must be supported by validated data under the applicable test standards.</p></div><figure className={styles.mediaFigure}><img className={styles.mediaImage} src="/images/NANOFORCE.png" alt="Conceptual hydraulic filtration media structure illustrating NANOFORCE fluid-cleanliness architecture" /><figcaption>Microscopic visualization of filtration media structure used for technical illustration.</figcaption></figure></div>
    </div></section>

    <section className={styles.band}><div className={styles.inner}><p className={styles.eyebrow}>OPERATING REALITY</p><h2 className={styles.h2}>Hydraulic component life depends on fluid cleanliness at precision clearances.</h2><p className={styles.lead}>Pumps, valves and actuators operate with internal interfaces that can be sensitive to particulate contamination. The filtration strategy should be built around the most contamination-sensitive component and the real operating duty of the circuit.</p></div></section>

    <section className={styles.bandAlt}><div className={styles.inner}><p className={styles.eyebrow}>APPLICATION ENVIRONMENT</p><h2 className={styles.h2}>Where NANOFORCE™ belongs</h2><div className={styles.editorialColumns}><div><h3 className={styles.h3}>Application positions</h3>{list(['Pressure-line hydraulic filtration','Return-line hydraulic filtration','Approved offline / kidney-loop filtration','Selected circulation and conditioning circuits'])}</div><div><h3 className={styles.h3}>Conditions that change filter duty</h3>{list(['High operating pressure','Variable system flow','Cold-fluid viscosity','High particulate ingress','Internally generated wear debris','Severe or continuous duty'])}</div><div><h3 className={styles.h3}>Protected components</h3>{list(['Hydraulic pumps','Directional and proportional valves','Actuators and cylinders','Servo and precision-control components'])}</div></div></div></section>

    <section className={styles.band}><div className={styles.inner}><p className={styles.eyebrow}>SPECIFICATION &amp; SELECTION</p><h2 className={styles.h2}>Questions before selecting a hydraulic filter</h2><div className={styles.editorialColumns}><div><h3 className={styles.h3}>Key engineering parameters</h3>{list(['Required cleanliness target','Critical particle size','Validated Beta performance','System flow','Operating pressure','Fluid viscosity','Contaminant capacity','Housing and seal interface'])}</div><div><h3 className={styles.h3}>Common selection errors</h3>{list(['Selecting by dimensions alone','Applying one micron rating to every circuit','Ignoring the most sensitive component','Ignoring cold-start viscosity','Using a return-line element in a pressure-line duty','Extending service beyond validated limits'])}</div><div><h3 className={styles.h3}>Application validation</h3>{list(['Equipment and hydraulic circuit','Filter position','Current housing and element','Fluid specification','Flow and pressure','Cleanliness target','Failure and service history'])}</div></div><div className={styles.inlineCta}><p><strong>Known part number?</strong> Use Part Search. <strong>Cleanliness problem or uncertain hydraulic duty?</strong> Use technical review.</p><div className={styles.buttonRow}><a className={styles.primaryButton} href="https://part-search.elimfilters.com" target="_blank" rel="noopener noreferrer" data-conversion-action="product-intelligence">FIND MY PART</a><a className={styles.secondaryButton} href="mailto:applications@elimfilters.com?subject=NANOFORCE%20Hydraulic%20Application%20Assessment" data-conversion-action="application-support">TECHNICAL REVIEW</a></div></div></div></section>

    <section className={styles.bandAlt}><div className={styles.inner}><p className={styles.eyebrow}>HOW THE SYSTEM BEHAVES</p><h2 className={styles.h2}>Efficiency, flow, pressure drop and contaminant capacity interact.</h2><p className={styles.lead}>A hydraulic filter cannot be judged by one rating alone. The useful configuration must control the critical particle population while preserving the required fluid flow and remaining structurally appropriate for the pressure and duty of its filtration position.</p></div></section>

    <section className={styles.band}><div className={styles.inner}><p className={styles.eyebrow}>SERVICE &amp; DIAGNOSIS</p><h2 className={styles.h2}>What rising differential pressure or recurring contamination may be telling you</h2>{list(['Unexpected cleanliness-code deterioration','Rapid differential-pressure increase','Repeated short filter intervals','Abnormal pump or valve wear','Element collapse or deformation','Recurring contamination after service'])}<div className={styles.inlineCta}><p>Repeated cleanliness failures or premature filter loading justify a hydraulic-system review.</p><a href="mailto:applications@elimfilters.com?subject=NANOFORCE%20Hydraulic%20System%20Review" data-conversion-action="application-support">REQUEST HYDRAULIC SYSTEM REVIEW</a></div></div></section>

    <section className={styles.bandAlt}><div className={styles.inner}><p className={styles.eyebrow}>QUESTIONS FROM THE FIELD</p><h2 className={styles.h2}>Direct answers to common hydraulic-filtration questions.</h2><div className={styles.faqList}>{faqs.map(([q,a])=><details className={styles.faqItem} key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></div></section>

    <section className={styles.band}><div className={styles.inner}><p className={styles.eyebrow}>TECHNICAL BASIS</p><h2 className={styles.h2}>Technical reference</h2><div className={styles.twoColumnNotes}><article className={styles.noteBlock}><h3 className={styles.h3}>Product-level evidence</h3><p className={styles.body}>Efficiency, Beta performance, contaminant capacity, collapse strength and pressure ratings must remain tied to validated data for the individual element and its applicable test method.</p></article><article className={styles.noteBlock}><h3 className={styles.h3}>Claim governance</h3><p className={styles.body}>NANOFORCE™ is not assigned one universal micron rating, Beta ratio, pressure rating, cleanliness code or service-life value across all hydraulic applications.</p></article></div></div></section>

    <section className={styles.bandAlt}><div className={styles.inner}><p className={styles.eyebrow}>WHEN A TECHNICAL REVIEW MAKES SENSE</p><h2 className={styles.h2}>When hydraulic filtration becomes a reliability problem</h2><p className={styles.lead}>Recurring valve problems, pump wear, unstable cleanliness results, premature differential pressure or repeated element changes justify reviewing the complete contamination path, circuit duty and cleanliness target.</p></div></section>

    <section className={styles.band}><div className={styles.inner}><p className={styles.eyebrow}>SYSTEM INTEGRATION</p><h2 className={styles.h2}>Hydraulic Protection</h2><div className={styles.systemGrid}><div><p className={styles.lead}>Hydraulic Protection manages particulate contamination around the sensitivity of pumps, valves, actuators and precision fluid-power components.</p><Link className={styles.systemButton} href="/systems/hydraulic/">EXPLORE PROTECTION SYSTEM</Link></div><p className={styles.bodyWide}>NANOFORCE™ provides the filtration architecture within this system. Final selection resolves the cleanliness target, critical component, filtration position, fluid viscosity, system flow, pressure and validated product evidence.</p></div></div></section>

    <section className={styles.ctaSection}><div className={styles.inner}><p className={styles.eyebrow}>APPLICATION SUPPORT</p><h2 className={styles.h2}>Bring us the circuit, cleanliness target and failure pattern — not just the part number.</h2><p className={styles.lead}>Use Part Search when the application is known. For recurring contamination, pressure-drop problems, premature wear or uncertain filtration position, use technical review.</p><div className={styles.buttonRow}><a className={styles.primaryButton} href="https://part-search.elimfilters.com" target="_blank" rel="noopener noreferrer" data-conversion-action="product-intelligence">FIND MY PART</a><a className={styles.secondaryButton} href="mailto:applications@elimfilters.com?subject=NANOFORCE%20Hydraulic%20Application%20Assessment" data-conversion-action="application-support">TECHNICAL REVIEW PATH</a></div></div></section>

    <section className={styles.bandAlt}><div className={styles.inner}><p className={styles.eyebrow}>EXPLORE RELATED TECHNOLOGIES</p><h2 className={styles.h2}>Explore related protection technologies and principles.</h2><div className={styles.textLinks}><Link href="/systems/">Protection Systems →</Link><Link href="/industries/">Industries →</Link><Link href="/knowledge-center/">Knowledge System →</Link><a href="https://part-search.elimfilters.com">Part Search →</a></div></div></section>
  </main>;
}
