import Link from 'next/link';
import styles from './MacrocoreTechnologyPage.module.css';
import { TECHNICAL_REVIEWER } from '@/lib/technical-reviewer';

const faqs = [
 ['What is THERMACORE™?','THERMACORE™ is the ELIMFILTERS cooling-system protection architecture for coolant cleanliness and component protection in approved engine and equipment cooling applications.'],
 ['What does a coolant filter protect?','A correctly specified coolant-filtration stage supports cleanliness of coolant passages, heat-transfer surfaces, seals and other protected cooling-system components. The complete protection strategy also depends on coolant chemistry and maintenance practice.'],
 ['Does every coolant filter contain supplemental coolant additives?','No. Additive-containing and blank coolant filters are different product configurations. Additive content or release rate must be confirmed from validated product and application data.'],
 ['Can coolant contamination reduce heat-transfer performance?','Deposits, corrosion products and suspended contamination can affect heat-transfer surfaces or restrict passages. Temperature problems still require diagnosis of the complete cooling system rather than assuming the filter is the sole cause.'],
 ['Can the wrong coolant chemistry damage a cooling system?','Yes. Coolant formulation, inhibitor condition and compatibility matter. Mixing incompatible chemistries or using fluid outside the engine requirements can contribute to deposits, corrosion and material compatibility problems.'],
 ['Can a coolant filter correct incorrect coolant chemistry?','No. Filtration can support cleanliness and, where specifically designed, additive management, but it cannot make an incorrect or incompatible coolant formulation acceptable.'],
 ['What information helps validate a THERMACORE™ application?','Engine or equipment identification, coolant specification, current filter and housing, filter configuration, service interval, operating duty and any history of corrosion, deposits, overheating or water-pump events are useful inputs.']
] as const;
const list=(items:string[])=><ul className={styles.list}>{items.map(x=><li key={x}>{x}</li>)}</ul>;

export function ThermacoreStablePage(){
 const article={'@context':'https://schema.org','@type':'TechArticle','@id':'https://elimfilters.com/technologies/thermacore/#article',headline:'THERMACORE™ Coolant Filtration Technology',name:'THERMACORE™',url:'https://elimfilters.com/technologies/thermacore/',description:'THERMACORE™ is the ELIMFILTERS cooling-system protection architecture for coolant cleanliness and component protection in approved engine and equipment cooling applications.',image:'https://elimfilters.com/images/THERMACORE-CAMION.avif',datePublished:'2026-08-31',dateModified:'2026-09-01',author:{'@type':'Organization','@id':'https://elimfilters.com/#organization',name:'ELIMFILTERS'},reviewedBy:TECHNICAL_REVIEWER,publisher:{'@type':'Organization','@id':'https://elimfilters.com/#organization',name:'ELIMFILTERS'},about:['coolant filtration','engine cooling system protection','coolant contamination control','coolant chemistry management','heat-transfer surface protection','cooling-system maintenance'].map(name=>({'@type':'Thing',name})),mentions:['water pump','radiator','heat exchanger','coolant passages','corrosion products','scale deposits','supplemental coolant additives','coolant compatibility'].map(name=>({'@type':'Thing',name})),isPartOf:{'@type':'WebSite','@id':'https://elimfilters.com/#website',name:'ELIMFILTERS',url:'https://elimfilters.com/'}};
 const faq={'@context':'https://schema.org','@type':'FAQPage',mainEntity:faqs.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))};
 const breadcrumb={'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:'https://elimfilters.com/'},{'@type':'ListItem',position:2,name:'Technologies',item:'https://elimfilters.com/technologies/'},{'@type':'ListItem',position:3,name:'THERMACORE™',item:'https://elimfilters.com/technologies/thermacore/'}]};
 return <main id="main-content" className={styles.page}>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(article)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faq)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumb)}}/>
  <section className={styles.hero} aria-labelledby="thermacore-title"><img className={styles.heroBackground} src="/images/THERMACORE-CAMION.avif" alt="Heavy-duty engine cooling-system service environment"/><div className={styles.heroShade} aria-hidden="true"/><h1 id="thermacore-title" className={styles.srOnly}>THERMACORE™ Coolant Filtration Technology</h1><img className={styles.heroMark} src="/assets/THERMACORE_final.avif" alt="THERMACORE™"/></section>
  <nav aria-label="Breadcrumb" style={{padding:'1rem clamp(1.15rem,6vw,6rem)',borderBottom:'1px solid rgba(255,255,255,.12)',background:'#020202'}}><div className={styles.inner} style={{display:'flex',gap:'.65rem',fontSize:'.72rem',letterSpacing:'.08em'}}><Link href="/" style={{color:'rgba(255,255,255,.55)',textDecoration:'none'}}>HOME</Link><span>→</span><Link href="/technologies/" style={{color:'rgba(255,255,255,.55)',textDecoration:'none'}}>TECHNOLOGIES</Link><span>→</span><span style={{color:'#fff12d'}}>THERMACORE™</span></div></nav>

  <section className={styles.introSection}><div className={styles.inner}><p className={styles.eyebrow}>FILTRATION TECHNOLOGY</p><h2 className={styles.displayTitle} style={{fontSize:'clamp(2.25rem,5.25vw,4.65rem)'}}>THERMACORE™</h2><p className={styles.applicationLine}><strong>Coolant &amp; Cooling-System Filtration</strong></p><p className={styles.lead}>A cooling-system protection architecture for coolant cleanliness and component protection in approved engine and equipment applications.</p>
   <div className={styles.mediaGrid}><div className={styles.mediaCopy}><div className={styles.metaStack}><p><span>Technology:</span> THERMACORE™</p><p><span>Application:</span> Approved engine and equipment coolant-filtration applications</p><p><span>Technical review:</span> <Link href="/about/leadership/">Víctor Abreu — Founder &amp; CEO</Link></p></div><p className={styles.eyebrow}>DESCRIPTION</p><h3 className={styles.featureTitle}>Coolant Cleanliness and Chemistry Control</h3><p className={styles.lead}>THERMACORE™ is the ELIMFILTERS cooling-system protection architecture for coolant cleanliness and component protection within Cooling System Protection.</p><p className={styles.bodyWide}>Its engineering role is to support cleanliness of coolant passages, seals and heat-transfer surfaces within the approved cooling-system maintenance strategy. Filter chemistry, capacity, flow and service interval must be matched to the engine and coolant requirements.</p><p className={styles.bodyWide}>Coolant filtration is one part of the system. Correct coolant formulation, chemistry compatibility, maintenance practice and the condition of the complete cooling circuit remain essential to thermal-system reliability.</p></div>
   <figure className={styles.mediaFigure}><img className={styles.mediaImage} src="/images/thermocore-imagen-productoFB.png" alt="ELIMFILTERS coolant filtration product application"/><figcaption>Representative coolant-filtration application visual for technical reference.</figcaption></figure></div>
  </div></section>

  <section className={styles.band}><div className={styles.inner}><p className={styles.eyebrow}>OPERATING REALITY</p><h2 className={styles.h2}>Cooling-system contamination is a heat-transfer and component-protection problem.</h2><p className={styles.lead}>Corrosion products, scale-related debris and suspended contamination can affect passages, seals and heat-transfer surfaces. Coolant chemistry and system condition must be managed together because filtration alone cannot correct an incompatible or degraded coolant formulation.</p><div className={styles.twoColumnNotes}><article className={styles.noteBlock}><h3 className={styles.h3}>Heat-transfer exposure</h3><p className={styles.body}>Deposits on heat-transfer surfaces or restriction inside cooling passages can reduce the system margin available to reject heat under sustained duty.</p></article><article className={styles.noteBlock}><h3 className={styles.h3}>Component exposure</h3><p className={styles.body}>Contaminated or chemically incorrect coolant can contribute to corrosion, seal distress and wear at water-pump and other cooling-system interfaces.</p></article></div></div></section>

  <section className={styles.bandAlt}><div className={styles.inner}><p className={styles.eyebrow}>APPLICATION ENVIRONMENT</p><h2 className={styles.h2}>Where THERMACORE™ belongs</h2><div className={styles.editorialColumns}><div><h3 className={styles.h3}>Approved applications</h3>{list(['Heavy-duty engine cooling systems','Truck and fleet cooling circuits','Construction and agricultural equipment','Power-generation cooling systems','Bus, coach and municipal equipment where approved'])}</div><div><h3 className={styles.h3}>Conditions that change filter duty</h3>{list(['High thermal load and long operating hours','Corrosion or sediment history','Coolant top-off and maintenance practices','Mixed or uncertain coolant chemistry','Extended service environments'])}</div><div><h3 className={styles.h3}>Protected system areas</h3>{list(['Radiators and heat exchangers','Water-pump interfaces','Coolant passages','Seals and thermostatic components','Heat-transfer surfaces'])}</div></div></div></section>

  <section className={styles.band}><div className={styles.inner}><p className={styles.eyebrow}>SPECIFICATION &amp; SELECTION</p><h2 className={styles.h2}>Questions before selecting a coolant filter</h2><div className={styles.editorialColumns}><div><h3 className={styles.h3}>Key engineering parameters</h3>{list(['Engine coolant requirement','Coolant chemistry compatibility','Filter position and housing','System flow and pressure drop','Validated contaminant capacity','Additive configuration where applicable','Service interval'])}</div><div><h3 className={styles.h3}>Common selection errors</h3>{list(['Selecting by thread or dimensions alone','Assuming every coolant filter contains additives','Mixing incompatible coolant chemistries','Ignoring system contamination during filter replacement','Extending service without validated application data'])}</div><div><h3 className={styles.h3}>Application validation</h3>{list(['Engine or equipment identification','Current coolant specification','Current filter and housing','Blank or additive-containing configuration','Operating duty','Corrosion, deposit or thermal history'])}</div></div><div className={styles.inlineCta}><p><strong>Known part number?</strong> Use Part Search. <strong>Coolant chemistry, contamination or repeated thermal problem?</strong> Use technical review.</p><div className={styles.buttonRow}><a className={styles.primaryButton} href="https://part-search.elimfilters.com" target="_blank" rel="noopener noreferrer" data-conversion-action="product-intelligence">FIND MY PART</a><a className={styles.secondaryButton} href="mailto:applications@elimfilters.com?subject=THERMACORE%20Coolant%20Application%20Assessment" data-conversion-action="application-support">TECHNICAL REVIEW</a></div></div></div></section>

  <section className={styles.bandAlt}><div className={styles.inner}><p className={styles.eyebrow}>HOW THE SYSTEM BEHAVES</p><h2 className={styles.h2}>Coolant chemistry, contamination loading and heat transfer must remain in balance.</h2><p className={styles.lead}>A useful cooling-system filtration strategy must preserve the required coolant flow while supporting cleanliness and the approved chemistry strategy. A filter cannot compensate for wrong coolant, incompatible additives, damaged heat exchangers or another system-level fault.</p><div className={styles.twoColumnNotes}><article className={styles.noteBlock}><h3 className={styles.h3}>Blank filter configurations</h3><p className={styles.body}>Where the approved product is a blank coolant filter, its role is filtration without assuming an additive charge.</p></article><article className={styles.noteBlock}><h3 className={styles.h3}>Additive-containing configurations</h3><p className={styles.body}>Where an approved product contains supplemental chemistry, type, quantity and service strategy must be supported by validated product data and engine requirements.</p></article></div></div></section>

  <section className={styles.band}><div className={styles.inner}><p className={styles.eyebrow}>SERVICE &amp; DIAGNOSIS</p><h2 className={styles.h2}>What recurring deposits or unstable cooling performance may be telling you</h2>{list(['Rust or corrosion products in coolant','Scale or sediment evidence','Coolant discoloration or contamination','Repeatedly short coolant-filter intervals','Temperature instability or overheating symptoms','Water-pump or seal events','Unknown or mixed coolant chemistry'])}<div className={styles.inlineCta}><p>Repeated contamination, deposits or thermal instability justify reviewing the complete cooling circuit and coolant-maintenance strategy.</p><a href="mailto:applications@elimfilters.com?subject=THERMACORE%20Cooling%20System%20Review" data-conversion-action="application-support">REQUEST COOLING SYSTEM REVIEW</a></div></div></section>

  <section className={styles.bandAlt}><div className={styles.inner}><p className={styles.eyebrow}>QUESTIONS FROM THE FIELD</p><h2 className={styles.h2}>Direct answers to common coolant-filtration questions.</h2><div className={styles.faqList}>{faqs.map(([q,a])=><details className={styles.faqItem} key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></div></section>

  <section className={styles.band}><div className={styles.inner}><p className={styles.eyebrow}>TECHNICAL BASIS</p><h2 className={styles.h2}>Technical reference</h2><div className={styles.twoColumnNotes}><article className={styles.noteBlock}><h3 className={styles.h3}>Product-level evidence</h3><p className={styles.body}>Filter chemistry, additive content, capacity, flow capability, pressure drop, service interval and compatibility must remain tied to validated product data and the requirements of the approved engine and coolant system.</p></article><article className={styles.noteBlock}><h3 className={styles.h3}>Claim governance</h3><p className={styles.body}>THERMACORE™ is not assigned one universal micron rating, coolant chemistry specification, additive dose, pressure rating, capacity or service interval across every application.</p></article></div></div></section>

  <section className={styles.bandAlt}><div className={styles.inner}><p className={styles.eyebrow}>WHEN A TECHNICAL REVIEW MAKES SENSE</p><h2 className={styles.h2}>When coolant filtration becomes a cooling-system reliability problem</h2><p className={styles.lead}>Recurring corrosion, deposits, shortened filter intervals, unknown coolant chemistry, water-pump events or temperature instability justify reviewing coolant condition, filtration duty, heat-transfer hardware and maintenance history as one system.</p></div></section>

  <section className={styles.band}><div className={styles.inner}><p className={styles.eyebrow}>SYSTEM INTEGRATION</p><h2 className={styles.h2}>Cooling System Protection</h2><div className={styles.systemGrid}><div><p className={styles.lead}>THERMACORE™ provides the coolant-cleanliness and component-protection layer of ELIMFILTERS Cooling System Protection.</p><Link className={styles.systemButton} href="/systems/cooling-system/">EXPLORE PROTECTION SYSTEM</Link></div><p className={styles.bodyWide}>Final selection resolves engine requirements, coolant chemistry, filter capacity, system flow, service interval and validated product evidence. THERMACORE™ remains separate from lubrication, hydraulic and fuel-system technologies.</p></div></div></section>

  <section className={styles.ctaSection}><div className={styles.inner}><p className={styles.eyebrow}>APPLICATION SUPPORT</p><h2 className={styles.h2}>Bring us the engine, coolant specification, duty cycle and failure pattern — not just the part number.</h2><p className={styles.lead}>Use Part Search when the application is known. For recurring contamination, chemistry uncertainty, deposits, thermal instability or an unclear coolant-filter configuration, use technical review.</p><div className={styles.buttonRow}><a className={styles.primaryButton} href="https://part-search.elimfilters.com" target="_blank" rel="noopener noreferrer" data-conversion-action="product-intelligence">FIND MY PART</a><a className={styles.secondaryButton} href="mailto:applications@elimfilters.com?subject=THERMACORE%20Coolant%20Application%20Assessment" data-conversion-action="application-support">TECHNICAL REVIEW PATH</a></div></div></section>

  <section className={styles.bandAlt}><div className={styles.inner}><p className={styles.eyebrow}>EXPLORE RELATED TECHNOLOGIES</p><h2 className={styles.h2}>Explore related protection technologies and principles.</h2><div className={styles.textLinks}><Link href="/systems/cooling-system/">Cooling System Protection →</Link><Link href="/industries/">Industries →</Link><Link href="/knowledge-center/">Knowledge System →</Link><a href="https://part-search.elimfilters.com">Part Search →</a></div></div></section>
 </main>;
}
