/**
 * edl/standard-registry.ts
 * Engineering Data Layer — Standard Entity Registry
 *
 * Governed entities for all KC-tracked industrial filtration standards.
 * Uses permanent STD-xxx identifiers. Relationship arrays use permanent IDs.
 */

import type { EDLStandardEntity, EDLStandardRegistry } from './types';

export const EDL_STANDARDS: EDLStandardRegistry = {

  'STD-ISO-16889': {
    id: 'STD-ISO-16889',
    code: 'ISO 16889',
    slug: 'iso-16889',
    title: 'Hydraulic fluid power — Filters — Multi-pass method for evaluating filtration performance of a filter element',
    issuingBody: 'ISO',
    domain: ['hydraulic', 'lubrication'],
    status: 'published',
    version: '1.0',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    scope: 'Defines the multi-pass test method for determining Beta ratio and filtration efficiency of hydraulic filter elements.',
    year: 2010,
    implementedByTechnologies: ['TECH-NANOFORCE', 'TECH-SYNTRAX'],
    addressesProblems: [
      'PROB-ABRASIVE-WEAR',
      'PROB-ADHESIVE-WEAR',
      'PROB-BEARING-WEAR',
      'PROB-CAVITATION',
      'PROB-PUMP-FAILURE',
      'PROB-FILTER-COLLAPSE',
      'PROB-MEDIA-FATIGUE',
      'PROB-VARNISH-FORMATION',
    ],
  },

  'STD-ISO-5011': {
    id: 'STD-ISO-5011',
    code: 'ISO 5011',
    slug: 'iso-5011',
    title: 'Inlet air cleaning equipment for internal combustion engines and compressors — Performance testing',
    issuingBody: 'ISO',
    domain: ['air-intake'],
    status: 'published',
    version: '1.0',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    scope: 'Specifies performance testing methods for air intake filters including efficiency, restriction, and dust holding capacity.',
    year: 2014,
    implementedByTechnologies: ['TECH-MACROCORE'],
    addressesProblems: [
      'PROB-SILICON-DUST-INGESTION',
      'PROB-AIR-RESTRICTION',
      'PROB-MEDIA-FATIGUE',
    ],
  },

  'STD-ISO-4406': {
    id: 'STD-ISO-4406',
    code: 'ISO 4406',
    slug: 'iso-4406',
    title: 'Hydraulic fluid power — Fluids — Method for coding the level of contamination by solid particles',
    issuingBody: 'ISO',
    domain: ['hydraulic', 'lubrication'],
    status: 'published',
    version: '1.0',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    scope: 'Defines the three-number cleanliness code (≥4µm / ≥6µm / ≥14µm) for hydraulic and lubrication fluids.',
    year: 2021,
    implementedByTechnologies: ['TECH-NANOFORCE', 'TECH-SYNTRAX'],
    addressesProblems: [
      'PROB-ABRASIVE-WEAR',
      'PROB-ADHESIVE-WEAR',
      'PROB-BEARING-WEAR',
      'PROB-PUMP-FAILURE',
      'PROB-VARNISH-FORMATION',
      'PROB-OXIDATION',
    ],
  },

  'STD-NAS-1638': {
    id: 'STD-NAS-1638',
    code: 'NAS 1638',
    slug: 'nas-1638',
    title: 'Cleanliness Requirements of Parts Used in Hydraulic Systems',
    issuingBody: 'NAS',
    domain: ['hydraulic'],
    status: 'draft',
    version: '0.1',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    implementedByTechnologies: ['TECH-NANOFORCE'],
    addressesProblems: ['PROB-ABRASIVE-WEAR', 'PROB-PUMP-FAILURE'],
  },

  'STD-ISO-29463': {
    id: 'STD-ISO-29463',
    code: 'ISO 29463',
    slug: 'iso-29463',
    title: 'High-efficiency filters and filter media for removing particles from air — Classification, performance testing and marking',
    issuingBody: 'ISO',
    domain: ['compressed-air', 'cabin-air'],
    status: 'draft',
    version: '0.1',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    implementedByTechnologies: ['TECH-DRYCORE', 'TECH-MICROKAPPA'],
    addressesProblems: ['PROB-AIR-RESTRICTION'],
  },

  'STD-ISO-8573-1': {
    id: 'STD-ISO-8573-1',
    code: 'ISO 8573-1',
    slug: 'iso-8573-1',
    title: 'Compressed air — Part 1: Contaminants and purity classes',
    issuingBody: 'ISO',
    domain: ['compressed-air'],
    status: 'draft',
    version: '0.1',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    implementedByTechnologies: ['TECH-DRYCORE'],
    addressesProblems: ['PROB-WATER-INGRESS'],
  },

  'STD-SAE-J1539': {
    id: 'STD-SAE-J1539',
    code: 'SAE J1539',
    slug: 'sae-j1539',
    title: 'Air Cleaner Test Code — Truck and Bus',
    issuingBody: 'SAE',
    domain: ['air-intake'],
    status: 'draft',
    version: '0.1',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    implementedByTechnologies: ['TECH-MACROCORE'],
    addressesProblems: ['PROB-SILICON-DUST-INGESTION', 'PROB-AIR-RESTRICTION'],
  },

  'STD-ISO-12937': {
    id: 'STD-ISO-12937',
    code: 'ISO 12937',
    slug: 'iso-12937',
    title: 'Petroleum products — Determination of water — Coulometric Karl Fischer titration method',
    issuingBody: 'ISO',
    domain: ['fuel'],
    status: 'draft',
    version: '0.1',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    implementedByTechnologies: ['TECH-TURBOCORE', 'TECH-SYNTAPORE', 'TECH-TURBOCORE'],
    addressesProblems: ['PROB-WATER-INGRESS', 'PROB-FUEL-CONTAMINATION', 'PROB-MICROBIAL-GROWTH'],
  },

  'STD-ASTM-D6304': {
    id: 'STD-ASTM-D6304',
    code: 'ASTM D6304',
    slug: 'astm-d6304',
    title: 'Standard Test Method for Determination of Water in Petroleum Products, Lubricating Oils, and Additives by Coulometric Karl Fischer Titration',
    issuingBody: 'ASTM',
    domain: ['fuel', 'lubrication'],
    status: 'draft',
    version: '0.1',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    implementedByTechnologies: ['TECH-TURBOCORE', 'TECH-SYNTAPORE', 'TECH-TURBOCORE'],
    addressesProblems: [
      'PROB-WATER-INGRESS',
      'PROB-FUEL-CONTAMINATION',
      'PROB-INJECTOR-WEAR',
      'PROB-MICROBIAL-GROWTH',
    ],
  },

  'STD-NFPA-T2-14': {
    id: 'STD-NFPA-T2-14',
    code: 'NFPA T2.14',
    slug: 'nfpa-t2-14',
    title: 'Hydraulic Fluid Power — Dimensions and Requirements for Filter Elements',
    issuingBody: 'NFPA',
    domain: ['hydraulic'],
    status: 'draft',
    version: '0.1',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    implementedByTechnologies: ['TECH-NANOFORCE'],
    addressesProblems: ['PROB-CAVITATION', 'PROB-PUMP-FAILURE', 'PROB-FILTER-COLLAPSE'],
  },

  'STD-ISO-11155-1': {
    id: 'STD-ISO-11155-1',
    code: 'ISO 11155-1',
    slug: 'iso-11155-1',
    title: 'Road vehicles — Air filters for passenger compartments — Part 1: Test for particulate filtration',
    issuingBody: 'ISO',
    domain: ['cabin-air'],
    status: 'draft',
    version: '0.1',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    implementedByTechnologies: ['TECH-MICROKAPPA'],
    addressesProblems: [],
  },

  'STD-DIN-71220': {
    id: 'STD-DIN-71220',
    code: 'DIN 71220',
    slug: 'din-71220',
    title: 'Air filters for passenger cars — Test methods',
    issuingBody: 'DIN',
    domain: ['cabin-air'],
    status: 'draft',
    version: '0.1',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    implementedByTechnologies: ['TECH-MICROKAPPA'],
    addressesProblems: [],
  },

  'STD-ISO-16332': {
    id: 'STD-ISO-16332',
    code: 'ISO 16332',
    slug: 'iso-16332',
    title: 'Diesel engines — Fuel filters — Test methods',
    issuingBody: 'ISO',
    domain: ['fuel'],
    status: 'draft',
    version: '0.1',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    implementedByTechnologies: ['TECH-TURBOCORE', 'TECH-SYNTAPORE'],
    addressesProblems: ['PROB-FUEL-CONTAMINATION', 'PROB-INJECTOR-WEAR'],
  },

  'STD-DIN-51524': {
    id: 'STD-DIN-51524',
    code: 'DIN 51524',
    slug: 'din-51524',
    title: 'Pressure fluids — Hydraulic oils — Minimum requirements',
    issuingBody: 'DIN',
    domain: ['hydraulic'],
    status: 'draft',
    version: '0.1',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    implementedByTechnologies: ['TECH-NANOFORCE'],
    addressesProblems: ['PROB-VARNISH-FORMATION', 'PROB-OXIDATION'],
  },

};
