/**
 * edl/system-registry.ts
 * Engineering Data Layer — Protection System Entity Registry
 *
 * 7 canonical Protection System entities with permanent SYS-xxx identifiers.
 * Systems are the Level 4 nodes in the KC Engineering Authority Hierarchy.
 */

import type { EDLSystemEntity, EDLSystemRegistry } from './types';

export const EDL_SYSTEMS: EDLSystemRegistry = {

  'SYS-AIR-INTAKE': {
    id: 'SYS-AIR-INTAKE',
    name: 'Air Intake Protection',
    slug: 'air-intake',
    description: 'Contamination interception before the combustion chamber. Protects engine cylinder liners, piston rings, and turbocharger components from particulate ingestion.',
    status: 'published',
    version: '1.0',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    primaryTechnologies: ['TECH-MACROCORE'],
    supportingTechnologies: ['TECH-INTEKCORE'],
    standards: ['STD-ISO-5011', 'STD-SAE-J1539', 'STD-ISO-16889'],
    productFamilies: [
      'FAM-PRIMARY-AIR',
      'FAM-SECONDARY-AIR',
      'FAM-SAFETY-ELEMENTS',
      'FAM-AIR-CLEANER-HOUSINGS',
    ],
    industries: [
      'IND-MINING',
      'IND-AGRICULTURE',
      'IND-CONSTRUCTION',
      'IND-TRUCK-FLEETS',
      'IND-POWER-GENERATION',
      'IND-MARINE',
      'IND-OIL-GAS',
    ],
    hdPrefix: 'EA1',
    ldPrefix: 'EA3',
  },

  'SYS-FUEL-CLEANLINESS': {
    id: 'SYS-FUEL-CLEANLINESS',
    name: 'Fuel Cleanliness Protection',
    slug: 'fuel-cleanliness',
    description: 'Water and particle elimination before the high-pressure injection circuit. Protects HPCR injectors operating at 1–3 µm internal tolerances.',
    status: 'published',
    version: '1.0',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    primaryTechnologies: ['TECH-SYNTAPORE', 'TECH-TURBOCORE', 'TECH-TURBOCORE'],
    supportingTechnologies: [],
    standards: ['STD-ASTM-D6304', 'STD-ISO-12937', 'STD-ISO-16332'],
    productFamilies: [
      'FAM-PRIMARY-FUEL',
      'FAM-SECONDARY-FUEL',
      'FAM-FUEL-WATER-SEPARATORS',
    ],
    industries: [
      'IND-MINING',
      'IND-AGRICULTURE',
      'IND-CONSTRUCTION',
      'IND-TRUCK-FLEETS',
      'IND-POWER-GENERATION',
      'IND-MARINE',
      'IND-OIL-GAS',
    ],
    hdPrefix: 'EF9',
    ldPrefix: 'EF3',
  },

  'SYS-LUBRICATION': {
    id: 'SYS-LUBRICATION',
    name: 'Lubrication Protection',
    slug: 'lubrication',
    description: 'Oil cleanliness maintained across extended service intervals. Controls soot accumulation, wear debris, and oxidation byproducts to ISO 4406 cleanliness targets.',
    status: 'published',
    version: '1.0',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    primaryTechnologies: ['TECH-SYNTRAX'],
    supportingTechnologies: [],
    standards: ['STD-ISO-4406', 'STD-ISO-16889', 'STD-DIN-51524'],
    productFamilies: ['FAM-OIL-FILTERS'],
    industries: [
      'IND-TRUCK-FLEETS',
      'IND-MINING',
      'IND-AGRICULTURE',
      'IND-CONSTRUCTION',
      'IND-POWER-GENERATION',
      'IND-MARINE',
      'IND-RAILWAY',
    ],
    hdPrefix: 'EL8',
    ldPrefix: 'EL3',
  },

  'SYS-HYDRAULIC': {
    id: 'SYS-HYDRAULIC',
    name: 'Hydraulic Protection',
    slug: 'hydraulic',
    description: 'Sub-micron contamination control in high-pressure hydraulic circuits operating at 200–450 bar. Protects servo valves, proportional valves, and pumps to ISO 16/14/11 or tighter cleanliness codes.',
    status: 'published',
    version: '1.0',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    primaryTechnologies: ['TECH-NANOFORCE'],
    supportingTechnologies: [],
    standards: ['STD-ISO-16889', 'STD-ISO-4406', 'STD-NFPA-T2-14', 'STD-NAS-1638', 'STD-DIN-51524'],
    productFamilies: ['FAM-HYDRAULIC-FILTERS'],
    industries: [
      'IND-CONSTRUCTION',
      'IND-MINING',
      'IND-MANUFACTURING',
      'IND-MARINE',
      'IND-AGRICULTURE',
      'IND-OIL-GAS',
    ],
    hdPrefix: 'EH6',
    ldPrefix: null,
  },

  'SYS-COOLING': {
    id: 'SYS-COOLING',
    name: 'Cooling System Protection',
    slug: 'cooling-system',
    description: 'SCA restoration and scale prevention in diesel engine cooling circuits. Maintains liner protection against cavitation erosion and heat transfer performance.',
    status: 'draft',
    version: '0.1',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    primaryTechnologies: ['TECH-THERMACORE'],
    supportingTechnologies: [],
    standards: [],
    productFamilies: ['FAM-COOLANT-FILTERS'],
    industries: [
      'IND-TRUCK-FLEETS',
      'IND-POWER-GENERATION',
      'IND-MINING',
      'IND-CONSTRUCTION',
    ],
    hdPrefix: 'EW7',
    ldPrefix: null,
  },

  'SYS-CABIN-AIR': {
    id: 'SYS-CABIN-AIR',
    name: 'Cabin Air Protection',
    slug: 'cabin-air',
    description: 'PM2.5 and chemical contaminant interception at the operator cabin. Defends heavy-duty equipment operators from silica dust, diesel exhaust particulate, and fuel vapour intrusion.',
    status: 'published',
    version: '1.0',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    primaryTechnologies: ['TECH-MICROKAPPA'],
    supportingTechnologies: [],
    standards: ['STD-ISO-11155-1', 'STD-DIN-71220'],
    productFamilies: ['FAM-CABIN-FILTERS'],
    industries: [
      'IND-MINING',
      'IND-CONSTRUCTION',
      'IND-TRUCK-FLEETS',
      'IND-AGRICULTURE',
      'IND-WASTE-MUNICIPAL',
    ],
    hdPrefix: 'EC1',
    ldPrefix: 'EC3',
  },

  'SYS-COMPRESSED-AIR': {
    id: 'SYS-COMPRESSED-AIR',
    name: 'Compressed Air Protection',
    slug: 'compressed-air',
    description: 'Moisture elimination from pneumatic braking and instrument air systems. Achieves ISO 8573-1 Class 1–2 dew point performance for safety-critical pneumatic circuits.',
    status: 'draft',
    version: '0.1',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    primaryTechnologies: ['TECH-DRYCORE'],
    supportingTechnologies: [],
    standards: ['STD-ISO-8573-1', 'STD-ISO-29463'],
    productFamilies: ['FAM-AIR-DRYER-FILTERS'],
    industries: [
      'IND-RAILWAY',
      'IND-MANUFACTURING',
      'IND-OIL-GAS',
      'IND-POWER-GENERATION',
    ],
    hdPrefix: 'ED4',
    ldPrefix: null,
  },

};
