/**
 * edl/system-registry.ts
 * Engineering Data Layer — Protection System Entity Registry
 *
 * Governed Protection System entities with permanent SYS-xxx identifiers.
 * Systems are Level 4 nodes in the KC Engineering Authority Hierarchy.
 */

import type { EDLSystemEntity, EDLSystemRegistry } from './types';

export const EDL_SYSTEMS: EDLSystemRegistry = {

  'SYS-AIR-INTAKE': {
    id: 'SYS-AIR-INTAKE',
    name: 'Air Intake Protection',
    slug: 'air-intake',
    description: 'Contamination interception before the combustion chamber. Protects engine components from particulate ingestion while preserving the approved airflow requirement.',
    status: 'published',
    version: '1.0',
    created: '2026-07-04',
    lastModified: '2026-09-01',
    contentPhase: 3,
    primaryTechnologies: ['TECH-MACROCORE'],
    supportingTechnologies: ['TECH-INTEKCORE'],
    standards: ['STD-ISO-5011', 'STD-SAE-J1539'],
    productFamilies: [
      'FAM-PRIMARY-AIR',
      'FAM-SECONDARY-AIR',
      'FAM-SAFETY-ELEMENTS',
      'FAM-AIR-CLEANER-HOUSINGS',
    ],
    industries: [
      'IND-MINING',
      'IND-AGRICULTURE',
      'IND-CONSTRUCTION',
      'IND-TRUCK-FLEETS',
      'IND-POWER-GENERATION',
      'IND-MARINE',
      'IND-OIL-GAS',
    ],
    hdPrefix: 'EA1',
    ldPrefix: 'EA3',
  },

  'SYS-FUEL-CLEANLINESS': {
    id: 'SYS-FUEL-CLEANLINESS',
    name: 'Fuel Cleanliness Protection',
    slug: 'fuel-cleanliness',
    description: 'Particulate filtration and water-management architectures selected according to the approved diesel fuel-system configuration and duty cycle.',
    status: 'published',
    version: '1.1',
    created: '2026-07-04',
    lastModified: '2026-09-01',
    contentPhase: 3,
    primaryTechnologies: ['TECH-SYNTAPORE', 'TECH-HYDROCORE', 'TECH-TURBOCORE'],
    supportingTechnologies: [],
    standards: ['STD-ASTM-D6304', 'STD-ISO-12937', 'STD-ISO-16332'],
    productFamilies: [
      'FAM-PRIMARY-FUEL',
      'FAM-SECONDARY-FUEL',
      'FAM-FUEL-WATER-SEPARATORS',
      'FAM-FUEL-TURBINE',
    ],
    industries: [
      'IND-MINING',
      'IND-AGRICULTURE',
      'IND-CONSTRUCTION',
      'IND-TRUCK-FLEETS',
      'IND-POWER-GENERATION',
      'IND-MARINE',
      'IND-OIL-GAS',
    ],
    hdPrefix: 'EF9',
    ldPrefix: 'EF3',
  },

  'SYS-LUBRICATION': {
    id: 'SYS-LUBRICATION',
    name: 'Lubrication Protection',
    slug: 'lubrication',
    description: 'Lubricant contamination control matched to the engine, lubricant condition and approved service strategy.',
    status: 'published',
    version: '1.0',
    created: '2026-07-04',
    lastModified: '2026-09-01',
    contentPhase: 3,
    primaryTechnologies: ['TECH-SYNTRAX'],
    supportingTechnologies: [],
    standards: ['STD-ISO-4406', 'STD-ISO-16889', 'STD-DIN-51524'],
    productFamilies: ['FAM-OIL-FILTERS'],
    industries: [
      'IND-TRUCK-FLEETS',
      'IND-MINING',
      'IND-AGRICULTURE',
      'IND-CONSTRUCTION',
      'IND-POWER-GENERATION',
      'IND-MARINE',
      'IND-RAILWAY',
    ],
    hdPrefix: 'EL8',
    ldPrefix: 'EL3',
  },

  'SYS-HYDRAULIC': {
    id: 'SYS-HYDRAULIC',
    name: 'Hydraulic Protection',
    slug: 'hydraulic',
    description: 'Hydraulic-fluid contamination control selected around the cleanliness requirement and the sensitivity of pumps, valves, actuators and controls.',
    status: 'published',
    version: '1.0',
    created: '2026-07-04',
    lastModified: '2026-09-01',
    contentPhase: 3,
    primaryTechnologies: ['TECH-NANOFORCE'],
    supportingTechnologies: [],
    standards: ['STD-ISO-16889', 'STD-ISO-4406', 'STD-NFPA-T2-14', 'STD-NAS-1638', 'STD-DIN-51524'],
    productFamilies: ['FAM-HYDRAULIC-FILTERS'],
    industries: [
      'IND-CONSTRUCTION',
      'IND-MINING',
      'IND-MANUFACTURING',
      'IND-MARINE',
      'IND-AGRICULTURE',
      'IND-OIL-GAS',
    ],
    hdPrefix: 'EH6',
    ldPrefix: null,
  },

  'SYS-COOLING': {
    id: 'SYS-COOLING',
    name: 'Cooling System Protection',
    slug: 'cooling-system',
    description: 'Coolant cleanliness and condition management within the approved engine cooling-system maintenance strategy.',
    status: 'draft',
    version: '0.1',
    created: '2026-07-04',
    lastModified: '2026-09-01',
    contentPhase: 3,
    primaryTechnologies: ['TECH-THERMACORE'],
    supportingTechnologies: [],
    standards: [],
    productFamilies: ['FAM-COOLANT-FILTERS'],
    industries: [
      'IND-TRUCK-FLEETS',
      'IND-POWER-GENERATION',
      'IND-MINING',
      'IND-CONSTRUCTION',
    ],
    hdPrefix: 'EW7',
    ldPrefix: null,
  },

  'SYS-CABIN-AIR': {
    id: 'SYS-CABIN-AIR',
    name: 'Cabin Air Protection',
    slug: 'cabin-air',
    description: 'Cabin-air contamination control selected around the approved HVAC configuration, operating environment and occupant exposure requirements.',
    status: 'published',
    version: '1.0',
    created: '2026-07-04',
    lastModified: '2026-09-01',
    contentPhase: 3,
    primaryTechnologies: ['TECH-MICROKAPPA'],
    supportingTechnologies: [],
    standards: ['STD-ISO-11155-1', 'STD-DIN-71220'],
    productFamilies: ['FAM-CABIN-FILTERS'],
    industries: [
      'IND-MINING',
      'IND-CONSTRUCTION',
      'IND-TRUCK-FLEETS',
      'IND-AGRICULTURE',
      'IND-WASTE-MUNICIPAL',
    ],
    hdPrefix: 'EC1',
    ldPrefix: 'EC3',
  },

  'SYS-COMPRESSED-AIR': {
    id: 'SYS-COMPRESSED-AIR',
    name: 'Compressed Air Protection',
    slug: 'compressed-air',
    description: 'Moisture control for approved pneumatic braking and instrument-air configurations.',
    status: 'draft',
    version: '0.1',
    created: '2026-07-04',
    lastModified: '2026-09-01',
    contentPhase: 3,
    primaryTechnologies: ['TECH-DRYCORE'],
    supportingTechnologies: [],
    standards: ['STD-ISO-8573-1'],
    productFamilies: ['FAM-AIR-DRYER-FILTERS'],
    industries: [
      'IND-RAILWAY',
      'IND-MANUFACTURING',
      'IND-OIL-GAS',
      'IND-POWER-GENERATION',
    ],
    hdPrefix: 'ED4',
    ldPrefix: null,
  },

};
