/**
 * edl/technology-registry.ts
 * Engineering Data Layer — Technology Entity Registry
 *
 * Governed entities for ELIMFILTERS filtration technologies.
 * Uses permanent TECH-xxx identifiers. Relationship arrays use permanent IDs.
 */

import type { EDLTechnologyEntity, EDLTechnologyRegistry } from './types';

export const EDL_TECHNOLOGIES: EDLTechnologyRegistry = {

  'TECH-MACROCORE': {
    id: 'TECH-MACROCORE',
    name: 'MACROCORE',
    slug: 'macrocore',
    domain: 'Air Intake Filtration',
    contaminationTarget: ['particulate', 'dust', 'silicon-dust'],
    status: 'published',
    version: '1.0',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    tagline: 'Progressive density gradient air intake filtration',
    engineeringPrinciple: 'Three-zone progressive density media achieving ISO 5011 absolute performance',
    implementsStandards: ['STD-ISO-5011', 'STD-SAE-J1539'],
    addressesProblems: ['PROB-SILICON-DUST-INGESTION', 'PROB-AIR-RESTRICTION', 'PROB-FILTER-COLLAPSE', 'PROB-MEDIA-FATIGUE'],
    usedInSystems: ['SYS-AIR-INTAKE'],
  },

  'TECH-SYNTRAX': {
    id: 'TECH-SYNTRAX',
    name: 'SYNTRAX',
    slug: 'syntrax',
    domain: 'Engine Lube Oil Filtration',
    contaminationTarget: ['particulate', 'wear-particles', 'oxidation-byproducts'],
    status: 'published',
    version: '1.0',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    tagline: 'Synthetic lube oil filtration for ISO 4406 cleanliness targets',
    engineeringPrinciple: 'Synthetic media multi-pass filtration per ISO 16889',
    implementsStandards: ['STD-ISO-16889', 'STD-ISO-4406'],
    addressesProblems: [
      'PROB-ABRASIVE-WEAR',
      'PROB-ADHESIVE-WEAR',
      'PROB-BEARING-WEAR',
      'PROB-PUMP-FAILURE',
      'PROB-VARNISH-FORMATION',
      'PROB-OXIDATION',
    ],
    usedInSystems: ['SYS-LUBRICATION'],
  },

  'TECH-NANOFORCE': {
    id: 'TECH-NANOFORCE',
    name: 'NANOFORCE',
    slug: 'nanoforce',
    domain: 'Hydraulic System Filtration',
    contaminationTarget: ['particulate', 'sub-micron-particles', 'varnish-precursors'],
    status: 'published',
    version: '1.0',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    tagline: 'High-precision hydraulic filtration for servo valve protection',
    engineeringPrinciple: 'Nanofiber-enhanced media for ISO 16/14/11 and tighter cleanliness codes',
    implementsStandards: ['STD-ISO-16889', 'STD-ISO-4406', 'STD-NFPA-T2-14', 'STD-NAS-1638', 'STD-DIN-51524'],
    addressesProblems: [
      'PROB-ABRASIVE-WEAR',
      'PROB-ADHESIVE-WEAR',
      'PROB-BEARING-WEAR',
      'PROB-CAVITATION',
      'PROB-PUMP-FAILURE',
      'PROB-FILTER-COLLAPSE',
      'PROB-MEDIA-FATIGUE',
      'PROB-VARNISH-FORMATION',
    ],
    usedInSystems: ['SYS-HYDRAULIC'],
  },

  'TECH-SYNTAPORE': {
    id: 'TECH-SYNTAPORE',
    name: 'SYNTAPORE',
    slug: 'SYNTAPORE',
    domain: 'Fuel HPCR Filtration',
    contaminationTarget: ['particulate', 'fuel-borne-particles'],
    status: 'published',
    version: '1.0',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    tagline: 'High-pressure common-rail injector protection filtration',
    engineeringPrinciple: 'Absolute rated synthetic fuel filtration for HPCR injector clearances',
    implementsStandards: ['STD-ASTM-D6304', 'STD-ISO-12937', 'STD-ISO-16332'],
    addressesProblems: ['PROB-INJECTOR-WEAR', 'PROB-FUEL-CONTAMINATION', 'PROB-WATER-INGRESS'],
    usedInSystems: ['SYS-FUEL-CLEANLINESS'],
  },

  'TECH-HYDROCORE': {
    id: 'TECH-HYDROCORE',
    name: 'HYDROCORE',
    slug: 'hydrocore',
    domain: 'Fuel Water Separation',
    contaminationTarget: ['particulate', 'free-water', 'biological'],
    status: 'published',
    version: '1.0',
    created: '2026-08-18',
    lastModified: '2026-08-18',
    contentPhase: 3,
    tagline: 'Fuel/water separation across approved separator architectures',
    engineeringPrinciple: 'Application-specific fuel/water separation for approved spin-on, cartridge, FH and FG systems',
    implementsStandards: ['STD-ISO-16332', 'STD-ASTM-D6304', 'STD-ISO-12937'],
    addressesProblems: ['PROB-WATER-INGRESS', 'PROB-FUEL-CONTAMINATION', 'PROB-MICROBIAL-GROWTH'],
    usedInSystems: ['SYS-FUEL-CLEANLINESS'],
  },

  'TECH-THERMACORE': {
    id: 'TECH-THERMACORE',
    name: 'THERMACORE',
    slug: 'thermacore',
    domain: 'Cooling System Protection',
    contaminationTarget: ['scale', 'corrosion-products', 'SCA-depletion'],
    status: 'draft',
    version: '0.1',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    tagline: 'Coolant supplemental additive filtration',
    implementsStandards: [],
    addressesProblems: [],
    usedInSystems: ['SYS-COOLING'],
  },

  'TECH-DRYCORE': {
    id: 'TECH-DRYCORE',
    name: 'DRYCORE',
    slug: 'drycore',
    domain: 'Compressed Air and Pneumatic Filtration',
    contaminationTarget: ['particulate', 'moisture', 'oil-aerosol'],
    status: 'draft',
    version: '0.1',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    tagline: 'ISO 8573-1 classified compressed air purification',
    implementsStandards: ['STD-ISO-8573-1', 'STD-ISO-29463'],
    addressesProblems: ['PROB-WATER-INGRESS'],
    usedInSystems: ['SYS-COMPRESSED-AIR'],
  },

  'TECH-INTEKCORE': {
    id: 'TECH-INTEKCORE',
    name: 'INTEKCORE',
    slug: 'intekcore',
    domain: 'Filter Housing Systems',
    contaminationTarget: ['particulate'],
    status: 'draft',
    version: '0.1',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    tagline: 'Integrated filter housing and mounting systems',
    implementsStandards: [],
    addressesProblems: [],
    usedInSystems: ['SYS-AIR-INTAKE'],
  },

  'TECH-DURATECH': {
    id: 'TECH-DURATECH',
    name: 'DURATECH',
    slug: 'duratech',
    domain: 'Fleet Maintenance Systems',
    contaminationTarget: ['particulate', 'water', 'biological'],
    status: 'draft',
    version: '0.1',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    tagline: 'Fleet-wide filtration maintenance kit system',
    implementsStandards: [],
    addressesProblems: [],
    usedInSystems: [],
  },

  'TECH-MARINECLEAN': {
    id: 'TECH-MARINECLEAN',
    name: 'MARINECLEAN',
    slug: 'marineclean',
    domain: 'Marine Diesel and Hydraulic Filtration',
    contaminationTarget: ['particulate', 'free-water', 'biological', 'salt'],
    status: 'draft',
    version: '0.1',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    tagline: 'IMO-certified marine filtration for diesel and hydraulic systems',
    implementsStandards: ['STD-ASTM-D6304', 'STD-ISO-12937'],
    addressesProblems: ['PROB-MICROBIAL-GROWTH', 'PROB-WATER-INGRESS', 'PROB-FUEL-CONTAMINATION'],
    usedInSystems: ['SYS-FUEL-CLEANLINESS', 'SYS-HYDRAULIC'],
  },

  'TECH-MICROKAPPA': {
    id: 'TECH-MICROKAPPA',
    name: 'MICROKAPPA',
    slug: 'microkappa',
    domain: 'Cabin Air Filtration',
    contaminationTarget: ['PM10', 'PM2.5', 'pollen', 'bacteria', 'VOCs'],
    status: 'published',
    version: '1.0',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    tagline: 'Occupant health protection per ISO 11155 and DIN 71220',
    engineeringPrinciple: 'Multi-layer cabin air filtration targeting PM2.5 and biological contaminants',
    implementsStandards: ['STD-ISO-11155-1', 'STD-DIN-71220', 'STD-ISO-29463'],
    addressesProblems: [],
    usedInSystems: ['SYS-CABIN-AIR'],
  },

};
