/**
 * edl/technology-registry.ts
 * Engineering Data Layer — Technology Entity Registry
 *
 * Governed entities for ELIMFILTERS filtration technologies.
 * Uses permanent TECH-xxx identifiers. Relationship arrays use permanent IDs.
 */

import type { EDLTechnologyEntity, EDLTechnologyRegistry } from './types';

export const EDL_TECHNOLOGIES: EDLTechnologyRegistry = {

  'TECH-MACROCORE': {
    id: 'TECH-MACROCORE',
    name: 'MACROCORE',
    slug: 'macrocore',
    domain: 'Air Intake Filtration',
    contaminationTarget: ['particulate', 'dust', 'silicon-dust'],
    status: 'published',
    version: '1.0',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    tagline: 'Progressive-density engine air intake filtration',
    engineeringPrinciple: 'Media configuration, sealing integrity and airflow management are matched to the approved intake application.',
    implementsStandards: ['STD-ISO-5011', 'STD-SAE-J1539'],
    addressesProblems: ['PROB-SILICON-DUST-INGESTION', 'PROB-AIR-RESTRICTION', 'PROB-FILTER-COLLAPSE', 'PROB-MEDIA-FATIGUE'],
    usedInSystems: ['SYS-AIR-INTAKE'],
  },

  'TECH-SYNTRAX': {
    id: 'TECH-SYNTRAX',
    name: 'SYNTRAX',
    slug: 'syntrax',
    domain: 'Engine Lube Oil Filtration',
    contaminationTarget: ['particulate', 'wear-particles', 'oxidation-byproducts'],
    status: 'published',
    version: '1.0',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    tagline: 'Lubrication filtration for engine asset protection',
    engineeringPrinciple: 'Media performance, contaminant capacity, pressure drop and valve integrity are matched to the approved lubrication application.',
    implementsStandards: ['STD-ISO-16889', 'STD-ISO-4406'],
    addressesProblems: [
      'PROB-ABRASIVE-WEAR',
      'PROB-ADHESIVE-WEAR',
      'PROB-BEARING-WEAR',
      'PROB-PUMP-FAILURE',
      'PROB-VARNISH-FORMATION',
      'PROB-OXIDATION',
    ],
    usedInSystems: ['SYS-LUBRICATION'],
  },

  'TECH-NANOFORCE': {
    id: 'TECH-NANOFORCE',
    name: 'NANOFORCE',
    slug: 'nanoforce',
    domain: 'Hydraulic System Filtration',
    contaminationTarget: ['particulate', 'wear-particles'],
    status: 'published',
    version: '1.0',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    tagline: 'Hydraulic contamination control for fluid-power systems',
    engineeringPrinciple: 'Media and element construction are selected around flow, pressure, cleanliness target and component sensitivity for the approved application.',
    implementsStandards: ['STD-ISO-16889', 'STD-ISO-4406', 'STD-NFPA-T2-14', 'STD-NAS-1638', 'STD-DIN-51524'],
    addressesProblems: [
      'PROB-ABRASIVE-WEAR',
      'PROB-ADHESIVE-WEAR',
      'PROB-BEARING-WEAR',
      'PROB-CAVITATION',
      'PROB-PUMP-FAILURE',
      'PROB-FILTER-COLLAPSE',
      'PROB-MEDIA-FATIGUE',
      'PROB-VARNISH-FORMATION',
    ],
    usedInSystems: ['SYS-HYDRAULIC'],
  },

  'TECH-SYNTAPORE': {
    id: 'TECH-SYNTAPORE',
    name: 'SYNTAPORE',
    slug: 'syntapore',
    domain: 'Diesel Fuel Particulate Filtration',
    contaminationTarget: ['particulate', 'fuel-borne-particles'],
    status: 'published',
    version: '1.1',
    created: '2026-07-04',
    lastModified: '2026-09-01',
    contentPhase: 3,
    tagline: 'Diesel fuel particulate filtration for approved primary, secondary and cartridge applications',
    engineeringPrinciple: 'Fuel particulate filtration performance is matched to the approved application, stage, flow requirement and service condition.',
    implementsStandards: ['STD-ISO-16332'],
    addressesProblems: ['PROB-INJECTOR-WEAR', 'PROB-FUEL-CONTAMINATION'],
    usedInSystems: ['SYS-FUEL-CLEANLINESS'],
  },

  'TECH-HYDROCORE': {
    id: 'TECH-HYDROCORE',
    name: 'HYDROCORE',
    slug: 'hydrocore',
    domain: 'Standard Fuel/Water Separation',
    contaminationTarget: ['free-water', 'emulsified-water', 'particulate'],
    status: 'published',
    version: '1.1',
    created: '2026-08-18',
    lastModified: '2026-09-01',
    contentPhase: 3,
    tagline: 'Fuel/water separation for approved standard non-turbine separator configurations',
    engineeringPrinciple: 'Application-specific separation for approved non-turbine separator filters, including drain and transparent-bowl configurations. FH and FG turbine systems are outside HYDROCORE scope.',
    implementsStandards: ['STD-ISO-16332', 'STD-ASTM-D6304', 'STD-ISO-12937'],
    addressesProblems: ['PROB-WATER-INGRESS', 'PROB-FUEL-CONTAMINATION', 'PROB-MICROBIAL-GROWTH'],
    usedInSystems: ['SYS-FUEL-CLEANLINESS'],
  },

  'TECH-TURBOCORE': {
    id: 'TECH-TURBOCORE',
    name: 'TURBOCORE',
    slug: 'turbocore',
    domain: 'Turbine-Style Fuel/Water Separation',
    contaminationTarget: ['free-water', 'emulsified-water', 'particulate'],
    status: 'published',
    version: '1.0',
    created: '2026-08-18',
    lastModified: '2026-09-01',
    contentPhase: 3,
    tagline: 'Turbine-style fuel/water separation reserved for approved FH and FG systems',
    engineeringPrinciple: 'Turbine-specific housing geometry, staged separation, element retention, sealing and flow routing are governed as one FH/FG architecture with dedicated approved replacement elements.',
    implementsStandards: ['STD-ASTM-D6304', 'STD-ISO-12937'],
    addressesProblems: ['PROB-WATER-INGRESS', 'PROB-FUEL-CONTAMINATION'],
    usedInSystems: ['SYS-FUEL-CLEANLINESS'],
  },

  'TECH-THERMACORE': {
    id: 'TECH-THERMACORE',
    name: 'THERMACORE',
    slug: 'thermacore',
    domain: 'Cooling System Protection',
    contaminationTarget: ['scale', 'corrosion-products', 'coolant-contamination'],
    status: 'draft',
    version: '0.1',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    tagline: 'Cooling-system filtration and coolant-condition support',
    implementsStandards: [],
    addressesProblems: [],
    usedInSystems: ['SYS-COOLING'],
  },

  'TECH-DRYCORE': {
    id: 'TECH-DRYCORE',
    name: 'DRYCORE',
    slug: 'drycore',
    domain: 'Compressed Air and Pneumatic Filtration',
    contaminationTarget: ['particulate', 'moisture', 'oil-aerosol'],
    status: 'draft',
    version: '0.1',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    tagline: 'Moisture control for approved pneumatic air-dryer applications',
    implementsStandards: ['STD-ISO-8573-1'],
    addressesProblems: ['PROB-WATER-INGRESS'],
    usedInSystems: ['SYS-COMPRESSED-AIR'],
  },

  'TECH-INTEKCORE': {
    id: 'TECH-INTEKCORE',
    name: 'INTEKCORE',
    slug: 'intekcore',
    domain: 'Filter Housing Systems',
    contaminationTarget: ['particulate'],
    status: 'draft',
    version: '0.1',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    tagline: 'Integrated air-cleaner housing and sealing architecture',
    implementsStandards: [],
    addressesProblems: [],
    usedInSystems: ['SYS-AIR-INTAKE'],
  },

  // Legacy commercial-solution records retained for compatibility only.
  // DURATECH and MARINECLEAN are not canonical core technology entities.
  'TECH-DURATECH': {
    id: 'TECH-DURATECH',
    name: 'DURATECH',
    slug: 'duratech',
    domain: 'Specialized Commercial Solution',
    contaminationTarget: [],
    status: 'draft',
    version: '0.1',
    created: '2026-07-04',
    lastModified: '2026-09-01',
    contentPhase: 3,
    tagline: 'Commercial maintenance-kit solution; not a core technology',
    implementsStandards: [],
    addressesProblems: [],
    usedInSystems: [],
  },

  'TECH-MARINECLEAN': {
    id: 'TECH-MARINECLEAN',
    name: 'MARINECLEAN',
    slug: 'marineclean',
    domain: 'Specialized Commercial Solution',
    contaminationTarget: [],
    status: 'draft',
    version: '0.1',
    created: '2026-07-04',
    lastModified: '2026-09-01',
    contentPhase: 3,
    tagline: 'Marine commercial solution; not a core technology',
    implementsStandards: [],
    addressesProblems: [],
    usedInSystems: [],
  },

  'TECH-MICROKAPPA': {
    id: 'TECH-MICROKAPPA',
    name: 'MICROKAPPA',
    slug: 'microkappa',
    domain: 'Cabin Air Filtration',
    contaminationTarget: ['PM10', 'PM2.5', 'pollen', 'selected-gaseous-contaminants'],
    status: 'published',
    version: '1.0',
    created: '2026-07-04',
    lastModified: '2026-07-04',
    contentPhase: 3,
    tagline: 'Cabin-air protection matched to approved HVAC applications',
    engineeringPrinciple: 'Cabin media configuration is selected around particulate exposure, airflow demand and HVAC pressure-drop limits.',
    implementsStandards: ['STD-ISO-11155-1', 'STD-DIN-71220'],
    addressesProblems: [],
    usedInSystems: ['SYS-CABIN-AIR'],
  },

};
