'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const {qualifyNaturalRemap}=require('../lib/catalog-natural-remap');
function fixture(){return {sku:'EA121575',codigo_base:'P821575',duty:'HEAVY_DUTY',canonical_source_brand:'DONALDSON',canonical_source_code:'P821575',canonical_source_status:'VERIFIED',oem_codes:[],competitor_codes:[],equipment_applications:[],vehicle_applications:[],enrichment_data:{codigo_base_governance:{primary_manufacturer_verified:true,approved_manufacturer:'DONALDSON',approved_codigo_base:'P821575'}}};}
function evidence(){return {sku:'EA121575',manufacturer:'DONALDSON',reference_code:'P821575',evidence_kind:'OFFICIAL_EXACT_SEARCH_RESULT',source_url:'https://shop.donaldson.com/store/en-us/search?Ntt=P821575',evidence_hash:'a'.repeat(64),verified_at:'2026-10-07T12:00:00Z'};}
test('verified free natural target is eligible without changing identity',()=>{const r=fixture();const before=JSON.stringify(r);assert.equal(qualifyNaturalRemap(r,'EA11575',[evidence()]).ready,true);assert.equal(JSON.stringify(r),before);});
test('unverified legacy identity cannot be renamed merely because target is free',()=>{const r=fixture();r.enrichment_data.codigo_base_governance.primary_manufacturer_verified=false;assert.equal(qualifyNaturalRemap(r,'EA11575',[evidence()]).ready,false);});
test('inactive occupied target is still protected',()=>{assert.equal(qualifyNaturalRemap(fixture(),'EA11575',[evidence()],[{sku:'EA11575',catalog_active:false}]).ready,false);});
test('complete evidence for a different code cannot authorize this base',()=>{const e=evidence();e.reference_code='P822858';assert.equal(qualifyNaturalRemap(fixture(),'EA11575',[e]).ready,false);});
test('URL alone and a lookalike official host are rejected',()=>{for(const change of [{evidence_hash:null},{source_url:'https://donaldson.com.attacker.example/product/P821575'},{verified_at:'invalid'}])assert.equal(qualifyNaturalRemap(fixture(),'EA11575',[{...evidence(),...change}]).ready,false);});
test('five digit target is rejected even when its final four digits match',()=>{assert.equal(qualifyNaturalRemap(fixture(),'EA121575',[evidence()]).ready,false);});
test('canonical mismatch is blocked without removing alternate references',()=>{const r=fixture();r.canonical_source_code='P822858';assert.equal(qualifyNaturalRemap(r,'EA11575',[evidence()]).ready,false);});
