const test=require('node:test');const assert=require('node:assert/strict');const {exactCodeToken,exactProductUrl,verifiesDonaldsonCrossReference,verifiedFleetguardIdentityForSource}=require('../lib/fleetguard-official-evidence');
const payload={text:'AF25551 Cross References Donaldson P821575',images:[{alt:'AF25551',src:'https://www.fleetguard.com/AF25551.jpg'}]};
const row={codigo_base:'P821575',canonical_source_code:'P821575'};
function evidence(){return {manufacturer:'FLEETGUARD',reference_code:'AF25551',evidence_kind:'OFFICIAL_FLEETGUARD_RENDERED_PRODUCT_PAGE',source_url:'https://www.fleetguard.com/product/AF25551',evidence_hash:'a'.repeat(64),verified_at:'2026-10-07T12:00:00Z',metadata:{cross_reference_confirmed:true,source_codigo_base:'P821575',source_canonical_code:'P821575'}};}
test('product code is exact, including at numeric boundaries',()=>{assert.equal(exactCodeToken('AF255510','AF25551'),false);assert.equal(exactCodeToken('AF25551 filter','AF25551'),true);});
test('official URL checks exact host and complete product path',()=>{assert.equal(exactProductUrl('https://evilfleetguard.com/product/AF25551','AF25551'),false);assert.equal(exactProductUrl('https://www.fleetguard.com/product/AF255510','AF25551'),false);assert.equal(exactProductUrl('https://www.fleetguard.com/product/AF25551','AF25551'),true);});
test('product existence cannot establish a different Donaldson identity',()=>{assert.equal(verifiesDonaldsonCrossReference(payload,'AF25551','P822858'),false);assert.equal(verifiesDonaldsonCrossReference(payload,'AF25551','P821575'),true);});
test('unbound image and missing cross-reference context are rejected',()=>{assert.equal(verifiesDonaldsonCrossReference({...payload,text:'AF25551 P821575'},'AF25551','P821575'),false);assert.equal(verifiesDonaldsonCrossReference({...payload,images:[{alt:'generic filter',src:'filter.jpg',parent:payload.text}]},'AF25551','P821575'),false);});
test('ledger must bind complete official proof to the current source base',()=>{assert.equal(verifiedFleetguardIdentityForSource(evidence(),row),true);assert.equal(verifiedFleetguardIdentityForSource(evidence(),{...row,codigo_base:'P822858'}),false);assert.equal(verifiedFleetguardIdentityForSource({...evidence(),metadata:{}},row),false);assert.equal(verifiedFleetguardIdentityForSource({...evidence(),evidence_hash:null},row),false);});
