const test=require('node:test');const assert=require('node:assert/strict');const {resolveZ900ModelRequest:resolve}=require('../lib/catalog-z900-model-request');
const models=['Z915B','Z915E','Z920M','Z925M EFI','Z925M Flex Fuel','Z930M EFI','Z930M','Z945M EFI','Z950M','Z955M EFI','Z960M'];
test('all eleven requested questions resolve a model rather than the full sentence',()=>{for(const model of models){const r=resolve('What filters does '+model+' take?');assert.equal(r.model.toUpperCase(),model.toUpperCase());assert.deepEqual(r.tokens.map(x=>x.toUpperCase()),['JOHN DEERE',model.toUpperCase()]);assert.equal(r.authority_scope,'MODEL_IDENTITY_ONLY');}});
test('EFI and Flex Fuel variants remain distinct',()=>{assert.equal(resolve('What filters does Z925M EFI take?').model,'Z925M EFI');assert.equal(resolve('What filters does Z925M Flex Fuel take?').model,'Z925M FLEX FUEL');assert.equal(resolve('What filters does Z930M take?').model,'Z930M');});
test('Spanish filter questions and an explicit brand preserve the same model identity',()=>{assert.equal(resolve('¿Qué filtros lleva Z915B?').model,'Z915B');assert.equal(resolve('Qué filtros lleva John Deere Z915B?').model,'Z915B');});
test('unknown variants and multiple models cannot silently become one known model',()=>{for(const q of ['What filters does Z925M take?','What filters does Z915 take?','What filters does Z930M and Z930M EFI take?'])assert.equal(resolve(q),null);});
test('model extraction supplies no engine, filter equivalence or completed application authority',()=>{const r=resolve('What filters does Z915B take?');assert.equal(r.engine,null);assert.equal(r.year,null);assert.equal(r.sku,undefined);assert.equal(r.evidence,undefined);});
test('bare part codes and unrelated diagnostics stay with the existing resolver',()=>{for(const q of ['Z915B','AF25551','Z915B low hydraulic pressure'])assert.equal(resolve(q),null);});

test('known model questions bypass part-reference preflight; bare codes retain it',()=>{const {shouldPreflight}=require('../lib/bot-protocol-reference-preflight');assert.equal(shouldPreflight('What filters does Z915B take?',{},['Z915B']),false);assert.equal(shouldPreflight('Z915B',{},['Z915B']),true);});
test('existing classifier routes all eleven questions to application lookup and clears another machine engine',()=>{const {deterministicClassify,mergeEntitiesIntoState}=require('../lib/bot-conversation-orchestrator');const {normalizeState}=require('../lib/bot-protocol-memory');for(const model of models){const state=normalizeState({equipment:{brand:'CUMMINS',model:'ISX',engine:'ISX15',year:2020}});const message='What filters does '+model+' take?';const c=deterministicClassify(message,state);assert.equal(c.intent,'application_lookup');assert.equal(c.entities.engine,null);assert.equal(c.entities.year,null);assert.equal(c.entities.model.toUpperCase(),model.toUpperCase());const next=mergeEntitiesIntoState(state,c,message);assert.equal(next.equipment.brand,'JOHN DEERE');assert.equal(next.equipment.engine,null);assert.equal(next.equipment.year,null);}});

test('an explicitly supplied engine for the same model survives equivalent brand formatting',()=>{const {deterministicClassify,mergeEntitiesIntoState}=require('../lib/bot-conversation-orchestrator');const {normalizeState}=require('../lib/bot-protocol-memory');const state=normalizeState({equipment:{brand:'John-Deere',model:'Z915B',engine:'CONFIRMED_TEST_ENGINE',year:2020}});const message='What filters does Z915B take?';const next=mergeEntitiesIntoState(state,deterministicClassify(message,state),message);assert.equal(next.equipment.engine,'CONFIRMED_TEST_ENGINE');assert.equal(next.equipment.year,2020);});
