import { TechDetailData } from '@/components/TechDetailPage';

export const TECH_PAGES: Record<string, TechDetailData> = {

  'turbocore-series': {
    categoryTag: '// FUEL ASSET PROTECTION · TURBOCORE™',
    heroTitle: 'TURBOCORE™',
    heroSubtitle: 'SERIES FH',
    heroTagline: 'Three-stage graduated asset protection for high-pressure fuel injection systems. Water, sediment and sub-micron contamination intercepted before they reach the injection circuit.',
    heroImage: '/images/turbinas-hero.avif',
    heroStats: [
      { key: '900FH', value: '90 GPH' },
      { key: '1000FH', value: '180 GPH' },
      { key: 'ISO 16332', value: 'CERTIFIED' },
    ],
    logoSrc: '/images/turbocore-series(fn).avif',
    systemHeadline: 'THREE-STAGE DEFENSE.\nFULL CONTAMINATION SPECTRUM.',
    systemParagraphs: [
      'Conventional fuel filters intercept particles. TURBOCORE™ intercepts the full contamination spectrum — particulate, free water, emulsified water and dissolved water — through a sequenced three-stage protection architecture that operates independently of fuel flow rate and back-pressure conditions.',
      'The 900FH and 1000FH models deploy HYDROCORE™ turbine rotation as the first line of defense — a passive inertial system that requires no electronic control, no actuators and no maintenance intervention. Protection begins the moment fuel enters the housing.',
      'The result: a fuel injection circuit that receives verified, clean fuel — every cycle, every hour, regardless of source fuel quality or operating conditions.',
    ],
    productImageSrc: '/images/turbine-plant.avif',
    productImageCaption: 'TURBOCORE™ · 900FH / 1000FH',
    stagesHeading: 'EACH STAGE ELIMINATES WHAT THE PREVIOUS ONE CANNOT.',
    stages: [
      {
        number: '01',
        tag: 'STAGE 1',
        title: 'INERTIAL INTERCEPTION',
        body: 'HYDROCORE™ turbine rotation induces centrifugal momentum on incoming fuel, driving macro-particles and free water outward against the chamber wall by inertial force alone. No moving parts. Zero mechanical dependency. The intercepted mass accumulates in the sealed base chamber — permanently separated from the fuel path before the protection sequence even begins.',
        stat: '100%',
        statLabel: 'Macro-particle removal at entry',
      },
      {
        number: '02',
        tag: 'STAGE 2',
        title: 'GRADUATED COALESCENCE',
        body: 'Fuel transitions through a staggered graduated contact zone where microscopic water droplets — too small to separate by inertia alone — are forced into repeated surface contact. Each contact cycle causes droplets to merge, grow, and fall by gravity into the sealed collection chamber below. The graduated layer architecture ensures no water molecule bypasses this stage regardless of fuel pressure or flow rate.',
        stat: '99%',
        statLabel: 'Emulsified water eliminated',
      },
      {
        number: '03',
        tag: 'STAGE 3',
        title: 'HYDROCORE™ PRECISION BARRIER',
        body: 'The final HYDROCORE™ hydrophobic protection barrier intercepts sub-micron contamination and dissolved water before the fuel enters the high-pressure injection circuit. The barrier architecture repels water molecules at contact — they cannot pass through regardless of differential pressure. Available in 2, 10 and 30 micron defense ratings to match your injection system\'s exact protection requirement.',
        stat: '2µm',
        statLabel: 'Minimum precision barrier rating',
      },
    ],
    specs: [
      { label: 'MODEL 900FH', value: '90 GPH', sub: '340 LPH — Light to medium duty' },
      { label: 'MODEL 1000FH', value: '180 GPH', sub: '681 LPH — Heavy duty operations' },
      { label: 'PROTECTION RATING', value: '99%', sub: 'Water separation efficiency' },
      { label: 'BARRIER OPTIONS', value: '3', sub: '2µm · 10µm · 30µm' },
      { label: 'CERTIFICATION', value: 'ISO', sub: '16332 — Fuel/water separation standard' },
      { label: 'DRAIN SYSTEM', value: 'AUTO', sub: 'Integrated visual monitoring port' },
    ],
    applicationsHeading: 'WHERE TURBOCORE™ PROTECTS',
    applicationsSubtext: 'FH-series turbine protection systems are validated for land-based combustion asset protection. Marine applications are served by the FM series.',
    applications: [
      { sector: 'HEAVY TRANSPORT', detail: 'Long-haul diesel drawn from shared depot storage tanks accumulates water contamination from condensation cycles in the supply chain. At 1,800+ bar injection pressure, a free-water event in the HPCR rail can hydraulically fracture an injector — an event that takes the vehicle out of service for days, not hours. Water content in depot-sourced diesel is rarely tested before delivery.' },
      { sector: 'POWER GENERATION', detail: 'Diesel generators on standby service sit with full fuel tanks for weeks between test cycles. Condensation during this storage creates progressive water accumulation at the tank bottom. When the genset starts under emergency load, the first fuel drawn arrives at the injection system already carrying the accumulated contamination from the storage period.' },
      { sector: 'AGRICULTURE', detail: 'On-farm diesel storage in above-ground tanks undergoes extreme diurnal temperature swings through transition seasons. Each cycle deposits condensation on tank walls that runs to the draw point. Combined with breather ingress during rain events, seasonal water accumulation in farm tanks is a predictable rather than exceptional contamination source.' },
      { sector: 'MINING', detail: 'Bulk fuel deliveries to remote mining sites travel long distances over rough roads. Transport vibration re-emulsifies any settled water back into suspension, delivering it in the exact condition most damaging to injection tolerances — fine droplets uniformly dispersed through the fuel and invisible to inspection.' },
      { sector: 'CONSTRUCTION', detail: 'Mobile refueling bowsers on active construction sites are exposed to rain, dust and humidity during every fueling operation. Water enters through loose filler caps, during outdoor drum transfers and through tank condensation. Contaminated refueling is the leading source of injection system water ingress in mobile construction equipment.' },
      { sector: 'RAILWAY', detail: 'Diesel locomotives are fueled at service depots, remote sidings and maintenance yards with inconsistent fuel quality standards. Water contamination that accumulates across multiple refueling events reaches the injection system gradually — causing progressive erosion rather than a single detectable contamination event.' },
    ],
    testimonial: {
      quote: 'After installing 1000FH units on our port machinery fleet, diesel consumption stabilized and we eliminated three injector replacement events in a single quarter. The turbine pre-stage makes a measurable difference in hostile fuel environments.',
      role: 'Refinery Equipment Manager',
      sector: 'Port Operations — 85 units',
    },
    ctaTag: '// IDENTIFY YOUR TURBOCORE™ SKU',
    ctaHeading: 'FIND YOUR PROTECTION SYSTEM',
    ctaBody: 'Cross-reference 500,000+ OEM part numbers. Identify the exact 900FH or 1000FH model for your asset.',
  },

  syntrax: {
    categoryTag: '// LUBRICATION ASSET PROTECTION · SYNTRAX™',
    heroTitle: 'SYNTRAX™',
    heroSubtitle: 'AI-ENGINEERED PROTECTION',
    heroTagline: 'Multi-layer lubrication protection system calibrated by AI algorithms to intercept sub-micron contamination before it reaches turbocharger bearings, crankshaft journals and precision valve train components.',
    heroImage: '/images/oil-hero.avif',
    heroStats: [
      { key: 'PROTECTION LAYERS', value: '4 ACTIVE' },
      { key: 'TECHNOLOGY', value: 'AI-CALIBRATED' },
      { key: 'TARGET', value: 'TURBO CUSTODY' },
    ],
    logoSrc: '/images/sintrax(fn).avif',
    systemHeadline: 'NOT JUST A FILTER.\nAN OIL CIRCUIT GUARDIAN.',
    systemParagraphs: [
      'Conventional oil filters rely on a single-density barrier to intercept contaminants. SYNTRAX™ deploys a four-layer protection matrix where each layer is calibrated to a specific contamination size class — from coarse metallic debris at the outer zone to sub-micron carbonaceous particles at the core barrier.',
      'The AI-engineered gradient was developed by analyzing contamination profiles across 48 engine types under heavy-duty field conditions. The result is a protection matrix that matches real-world contamination distribution, not laboratory averages.',
      'Turbocharger bearing failure is not a low-probability event — it is the predictable outcome of sustained oil contamination above the bearing film tolerance threshold. At operating speed, turbo shaft bearings run on oil films measured in 2–4 microns. Any abrasive particle above that threshold transiting the bearing circuit removes material on contact. The damage is irreversible and cumulative.',
    ],
    productImageSrc: '/images/syntrax.avif',
    productImageCaption: 'SYNTRAX™ · AI-ENGINEERED LUBRICATION PROTECTION',
    stagesHeading: 'FOUR LAYERS. ZERO BYPASS.',
    stages: [
      {
        number: '01',
        tag: 'LAYER 1',
        title: 'MACRO-PARTICLE INTERCEPTION',
        body: 'The outermost protection zone targets coarse metallic debris, carbon agglomerates and particulate clusters above 40 microns. These large contaminants are intercepted at the entry surface before they can migrate inward and consume capacity from the precision inner layers. Load distribution ensures the outer layer handles the highest volume contamination fraction without restriction to oil flow.',
        stat: '40µm',
        statLabel: 'Outer zone intercept threshold',
      },
      {
        number: '02',
        tag: 'LAYER 2',
        title: 'INTERMEDIATE DENSITY GRADIENT',
        body: 'As oil penetrates the second protection zone, the gradient density progressively increases, capturing mid-range contamination between 10 and 40 microns. This layer is responsible for metallic wear particles shed by piston rings, camshaft lobes and timing components — the contamination class most correlated with bearing surface degradation. Graduated fiber architecture prevents premature blind-loading.',
        stat: '10µm',
        statLabel: 'Intermediate intercept threshold',
      },
      {
        number: '03',
        tag: 'LAYER 3',
        title: 'TURBO CUSTODY BARRIER',
        body: 'The third layer is engineered specifically for turbocharger shaft bearing protection. At 3–5 microns, contaminants that pass through layers 1 and 2 are captured in the turbo custody zone — a high-density protection band where fiber compaction and path length combine to achieve near-absolute retention. Turbocharger bearings operate on oil films measured in microns; this layer is the last defense before the oil enters the forced induction circuit.',
        stat: '3µm',
        statLabel: 'Turbo custody barrier rating',
      },
      {
        number: '04',
        tag: 'LAYER 4',
        title: 'THERMAL BONDING ANCHOR',
        body: 'A multi-layer element has a structural problem that no filter manufacturer talks about: under sustained high oil temperature and flow pulsation from combustion cycles, the layers compress and shift relative to each other. When that happens, gaps form between layers — bypass paths that didn\'t exist in the new element. By 5,000 km you no longer have 4 discrete protection layers working as designed. You have a compressed mass with voids. SYNTRAX™ thermal bonding anchors every layer to fixed position at manufacture. The protection geometry on day 1 is identical on the day of change. No progressive degradation. No gap formation. The filter you install is the filter that comes out.',
        stat: '100%',
        statLabel: 'Layer position integrity across full service interval',
      },
    ],
    specs: [
      { label: 'PROTECTION LAYERS', value: '4', sub: 'AI-calibrated density gradient matrix' },
      { label: 'OUTER INTERCEPT', value: '40µm', sub: 'Macro-particle entry zone' },
      { label: 'TURBO CUSTODY', value: '3µm', sub: 'Precision turbocharger barrier' },
      { label: 'BONDING PROCESS', value: 'THERMAL', sub: 'Zero-migration layer lock' },
      { label: 'OIL COMPATIBILITY', value: '100%', sub: 'Mineral · Synthetic · Semi-synthetic' },
      { label: 'BYPASS VALVE', value: 'ZERO', sub: 'No unfiltered oil bypass under rated pressure' },
    ],
    applicationsHeading: 'WHERE SYNTRAX™ PROTECTS',
    applicationsSubtext: 'SYNTRAX™ protection matrix is validated for turbocharged and naturally aspirated engines across all duty cycles and oil grades.',
    applications: [
      { sector: 'HEAVY TRANSPORT', detail: 'A turbocharger replacement on a long-haul diesel unit costs between $2,000 and $8,000 in parts alone, plus workshop hours and vehicle downtime. The failure is almost always traceable to oil contamination — abrasive particles that entered the bearing circuit during an earlier service interval and accumulated there. The contamination event precedes the failure event by thousands of kilometers.' },
      { sector: 'POWER GENERATION', detail: 'Gensets on base-load or standby duty run extended service intervals with no intermediate oil analysis. Oil contamination builds progressively as metallic wear particles and combustion by-products accumulate through the interval. By interval end, an unprotected engine has been operating on increasingly contaminated oil for months without any visible indication.' },
      { sector: 'AGRICULTURE', detail: 'Agricultural engines that sit dormant through winter accumulate moisture and oxidation products in the crankcase. The first startup after storage mobilizes these deposits into oil circulation in a single high-contamination surge. Without multi-layer protection at the outer entry zone, this startup spike reaches bearing surfaces directly.' },
      { sector: 'MINING', detail: 'Engine oil contamination rates in mining environments are three to five times higher than on-road equivalents due to ambient dust ingestion through crankcase ventilation and metal contamination from high-load component wear. Standard single-density oil filters reach restriction capacity prematurely in this duty cycle.' },
      { sector: 'CONSTRUCTION', detail: 'Excavators and graders run continuous multi-shift operations with no idle periods for oil circuit recovery. Contamination accumulated during each shift is still circulating when the next shift begins. Capacity loss in a single-density filter occurs faster in this duty cycle than in any laboratory test condition.' },
      { sector: 'INDUSTRIAL', detail: 'Industrial compressors and prime movers operate on tight bearing clearance tolerances required for efficiency and rotational precision. Any contamination that migrates to bearing surfaces creates measurable clearance growth — detectable only when vibration analysis confirms bearing degradation already well advanced.' },
    ],
    labResults: [
      { test: 'Multi-Pass Filtration Efficiency', standard: 'ISO 4548-12', result: '99.7', unit: '%' },
      { test: 'Dirt Holding Capacity', standard: 'ISO 4548-12', result: '42.8', unit: 'g' },
      { test: 'Collapse Pressure Rating', standard: 'ISO 4548-7', result: '≥ 20', unit: 'bar' },
      { test: 'Layer Migration Resistance', standard: 'ELIMFILTERS-LT-01', result: '0', unit: 'events / 500h' },
      { test: 'Turbo Bearing Contamination', standard: 'SAE J1858', result: '< 3', unit: 'µm pass-through' },
    ],
    testimonial: {
      quote: 'After switching to SYNTRAX™ across our 140-unit fleet, turbocharger replacements dropped by 67% in 18 months. The four-layer architecture is the only explanation — our duty cycles and fuel quality didn\'t change.',
      role: 'Fleet Maintenance Director',
      sector: 'Long-Haul Transport Operator — 140 units',
    },
    ctaTag: '// IDENTIFY YOUR SYNTRAX™ ELEMENT',
    ctaHeading: 'FIND YOUR ENGINE PROTECTION',
    ctaBody: 'Cross-reference 500,000+ OEM part numbers. Identify the exact SYNTRAX™ element for your engine specification.',
  },

  nanoforce: {
    categoryTag: '// HYDRAULIC ASSET PROTECTION · NANOFORCE™',
    heroTitle: 'NANOFORCE™',
    heroSubtitle: 'HYDRAULIC PRECISION GUARD',
    heroTagline: 'Multi-layer protection architecture engineered for high-pressure hydraulic asset defense. Vapor control and structural integrity systems that maintain protection performance under sustained high-pressure pulsation cycles.',
    heroImage: '/images/syntrapore-hero.avif',
    heroStats: [
      { key: 'ARCHITECTURE', value: 'MULTI-LAYER' },
      { key: 'VAPOR CONTROL', value: 'ACTIVE' },
      { key: 'STRUCTURAL', value: 'HIGH-PRESSURE' },
    ],
    logoSrc: '/images/nanoforce(fn).avif',
    systemHeadline: 'HIGH-PRESSURE HYDRAULIC\nCIRCUIT PROTECTION.',
    systemParagraphs: [
      'Hydraulic systems are the most contamination-sensitive circuits in any mobile or stationary machine. Hydraulic control valves, pumps and actuators operate on tolerances measured in single-digit microns — any contamination that bypasses filtration accelerates wear exponentially, not linearly.',
      'NANOFORCE™ multi-layer protection architecture is engineered specifically for the hydraulic circuit operating environment: high and variable pressure, temperature cycling from ambient to 85°C operating, and continuous flow pulsation from pump cycles that mechanically stress filter elements in ways that static test conditions do not capture.',
      'Vapor control technology embedded in the NANOFORCE™ protection matrix addresses the hydraulic contamination source that conventional filters ignore — the vapor phase water and dissolved gas that forms free-phase contamination when hydraulic fluid temperature changes under load.',
    ],
    productImageSrc: '/images/hidraulic.avif',
    productImageCaption: 'NANOFORCE™ · HYDRAULIC PRECISION GUARD ELEMENT',
    stagesHeading: 'THREE LAYERS FOR HIGH-PRESSURE HYDRAULIC INTEGRITY.',
    stages: [
      {
        number: '01',
        tag: 'LAYER 1',
        title: 'MULTI-LAYER GUARD',
        body: 'The outer protection layer intercepts large metallic particles, rubber degradation products from hydraulic seals, and polymer contamination from hose liner breakdown. These contamination types are characteristic of hydraulic circuit aging and are the primary cause of valve spool scoring and pump gear wear. The guard layer capacity is sized for extended operation between hydraulic fluid service intervals.',
        stat: '100%',
        statLabel: 'Macro-contamination interception at entry zone',
      },
      {
        number: '02',
        tag: 'LAYER 2',
        title: 'VAPOR CONTROL BARRIER',
        body: 'The vapor control layer addresses dissolved water and entrained vapor contamination in hydraulic fluid — the invisible contamination that conventional hydraulic filters do not address. When hydraulic systems cycle between ambient and operating temperature, dissolved water in the fluid transitions to free-phase micro-droplets that cause control valve stiction and pump cavitation. The vapor control layer coalesces and captures this phase-transition water before it accumulates in critical actuator circuits.',
        stat: '99%',
        statLabel: 'Dissolved water capture at vapor control layer',
      },
      {
        number: '03',
        tag: 'LAYER 3',
        title: 'STRUCTURAL INTEGRITY CORE',
        body: 'The innermost structural integrity layer is the NANOFORCE™ precision barrier and element backbone simultaneously. It achieves sub-micron particle interception while providing the anti-collapse structural support that prevents protection layer compression under high-flow pulsation events. The structural core maintains full element geometry under cold-start high-viscosity flow surges that can collapse conventional hydraulic filter elements and bypass filtration entirely.',
        stat: '3µm',
        statLabel: 'Structural core precision barrier rating',
      },
    ],
    specs: [
      { label: 'PROTECTION LAYERS', value: '3', sub: 'Guard · Vapor control · Structural core' },
      { label: 'PRECISION BARRIER', value: '3µm', sub: 'Structural core intercept rating' },
      { label: 'VAPOR CONTROL', value: 'ACTIVE', sub: 'Dissolved water phase-transition capture' },
      { label: 'OPERATING PRESSURE', value: 'HIGH', sub: 'Rated for continuous pulsation cycles' },
      { label: 'FLUID COMPATIBILITY', value: 'ALL', sub: 'Mineral · Synthetic · Bio-hydraulic fluids' },
      { label: 'ANTI-COLLAPSE', value: '100%', sub: 'Cold-start viscosity surge rated structure' },
    ],
    applicationsHeading: 'WHERE NANOFORCE™ PROTECTS',
    applicationsSubtext: 'NANOFORCE™ hydraulic asset defense covers every hydraulic circuit type from mobile equipment to industrial fixed installations.',
    applications: [
      { sector: 'CONSTRUCTION', detail: 'A single proportional valve replacement in an excavator costs $800–$3,000 and requires partial hydraulic circuit disassembly. Contamination-induced valve spool scoring typically affects multiple valves simultaneously. In high-humidity outdoor environments, dissolved water in hydraulic fluid accelerates this wear — but does not show up in particle count analysis because water is not counted as a particle.' },
      { sector: 'AGRICULTURE', detail: 'Modern combine harvesters use electronically controlled hydraulic circuits for header height, reel speed and unloading auger positioning. Each function depends on valve spool clearances of 2–8 microns. A valve stuck mid-position during unloading does not just create a maintenance event — it stops harvest operations at the moment when every working hour is critical.' },
      { sector: 'MINING', detail: 'Hydraulic excavator pump and valve assemblies represent 30–40% of total machine value. In open-pit operations, equipment runs on two-shift cycles with no hydraulic fluid recovery time between shifts. Contamination-induced pump wear creates internal bypass that reduces machine productivity before any external failure symptom appears.' },
      { sector: 'MANUFACTURING', detail: 'CNC machining center hydraulic clamping and axis control systems require positioning repeatability within ±0.01mm. Contamination-induced valve spool clearance growth creates hysteresis — the valve does not return to exactly the same position on repeated cycles. This shows first in part dimensional variance, not in any hydraulic system alarm.' },
      { sector: 'MARINE', detail: 'Shipboard hydraulic reservoir breathers draw in salt-laden air with every temperature cycle as warm fluid contracts on cooling. Dissolved salt water in hydraulic fluid is not visible and does not alter fluid color or viscosity — it circulates undetected until it causes valve seat corrosion or pump internal surface pitting during a sea passage with no repair capability available.' },
      { sector: 'POWER GENERATION', detail: 'Diesel engine governor hydraulic systems control fuel injection rack position. A governor valve that develops stiction from contamination does not fail catastrophically — it causes hunting, speed instability and load rejection. On grid-connected generators, a load rejection event has consequences beyond the generator itself.' },
    ],
    testimonial: {
      quote: 'Our excavators were experiencing control valve wear every 2,000 hours. After switching to NANOFORCE™ hydraulic protection, the last fleet inspection showed zero scoring at 4,500 hours. The vapor control layer is what our previous filters were missing.',
      role: 'Equipment Superintendent',
      sector: 'Open-Pit Mining Operation — 48 machines',
    },
    ctaTag: '// IDENTIFY YOUR NANOFORCE™ ELEMENT',
    ctaHeading: 'FIND YOUR HYDRAULIC PROTECTION',
    ctaBody: 'Cross-reference 500,000+ OEM part numbers. Identify the exact NANOFORCE™ element for your hydraulic system specification.',
  },

  macrocore: {
    categoryTag: '',
    heroTitle: 'MACROCORE™',
    heroSubtitle: '',
    heroTagline: 'Progressive Density Gradient multi-layer defense system achieving 99.9%–99.98% interception efficiency for industrial air intake asset protection.',
    heroImage: '/images/mecanica-air.avif',
    heroStats: [
      { key: 'EFFICIENCY', value: '99.98%' },
      { key: 'ANTI-COLLAPSE', value: '62 PSI' },
      { key: 'CERTIFICATION', value: 'ISO 5011' },
    ],
    logoSrc: '/assets/MACROCORE.avif',
    systemHeadline: 'PROGRESSIVE DENSITY GRADIENT.\nNOT A SINGLE-LAYER BARRIER.',
    systemParagraphs: [
      'Single-density air filter elements reach their capacity limit at the surface — restricting airflow long before the interior protection capacity is utilized. MACROCORE™ Progressive Density Gradient (PDG) distributes contamination load across the full depth of the protection matrix, utilizing every layer from entry surface to core barrier.',
      'The PDG architecture captures coarse particles at the outer zone, progressively smaller particles in the mid-layers, and sub-micron contamination at the core barrier — matching real-world air contamination distribution and eliminating premature restriction events.',
      'In heavy-duty cycles, a restriction event is not a maintenance problem — it is a production stop. Turbocharger starvation, air-fuel ratio deviation and piston ring wear begin before any dashboard warning triggers. The failure is already underway.',
    ],
    productImageSrc: '/images/mecanico-jd.avif',
    productImageCaption: 'MACROCORE™ · PROGRESSIVE DENSITY GRADIENT AIR PROTECTION',
    stagesHeading: 'THREE DENSITY ZONES. FULL SPECTRUM PROTECTION.',
    stages: [
      {
        number: '01',
        tag: 'OUTER ZONE',
        title: 'MACRO-PARTICLE CAPTURE',
        body: 'The outer protection zone is engineered with an open fiber architecture that intercepts coarse dust, soil aggregates and large carbon particles without restriction to air flow. By capturing the high-mass contamination fraction at the entry surface, the outer zone prevents premature loading of the precision inner layers and ensures the full contamination capacity of the protection matrix is utilized across the service interval.',
        stat: '99.9%',
        statLabel: 'Overall interception efficiency minimum',
      },
      {
        number: '02',
        tag: 'MID-ZONE',
        title: 'GRADIENT DENSITY MATRIX',
        body: 'The gradient transition zone bridges between the coarse outer layer and the precision core barrier through a continuously increasing fiber density. Mid-range contamination — fine silica dust, agricultural crop residue, road surface particulate — is captured in this zone through a combination of inertial impact, interception and diffusion mechanisms. The gradient architecture prevents boundary layer bypass that occurs in step-change density designs.',
        stat: '99.98%',
        statLabel: 'Peak interception efficiency at core zone',
      },
      {
        number: '03',
        tag: 'CORE BARRIER',
        title: 'INERTIAL IMPACT + DIFFUSION DEFENSE',
        body: 'The innermost protection layer combines two capture mechanisms that operate on different particle size classes simultaneously. Inertial impact captures particles with sufficient mass to deviate from air streamlines and contact fiber surfaces. Diffusion capture addresses sub-micron particles — those too light for inertial impact — through Brownian motion contact with the high-density core fiber matrix. The result: near-absolute protection across the full particle size spectrum.',
        stat: '120°C',
        statLabel: 'Continuous thermal operation rating',
      },
    ],
    specs: [
      { label: 'PDG EFFICIENCY', value: '99.98%', sub: 'Peak interception at ISO 5011 test conditions' },
      { label: 'ANTI-COLLAPSE', value: '62 PSI', sub: 'Differential pressure structural rating' },
      { label: 'THERMAL RATING', value: '120°C', sub: 'Continuous operation temperature limit' },
      { label: 'PLEAT GEOMETRY', value: 'EQUIDISTANT', sub: 'Uniform airflow distribution, zero blind pleats' },
      { label: 'CERTIFICATION', value: 'ISO 5011', sub: 'Also SAE J726 / ASTM D202 compliant' },
      { label: 'CAPTURE MODES', value: '3', sub: 'Interception · Inertial impact · Diffusion' },
    ],
    applicationsHeading: 'WHERE MACROCORE™ PROTECTS',
    applicationsSubtext: 'MACROCORE™ PDG air protection is validated for every motor type and industrial duty cycle category.',
    applications: [
      { sector: 'HEAVY TRANSPORT', detail: 'High-output turbocharged engines on highway duty run at air-fuel ratios calibrated to within tight tolerances. A partially restricted intake does not trigger a warning light — it degrades combustion efficiency silently, increasing fuel burn and cylinder temperature before the driver notices any change in performance.' },
      { sector: 'MINING', detail: 'Silica dust particles are harder than engine alloys. A single bypass event at a haul-road surface introduces abrasive particles that begin scoring cylinder walls immediately. In 24/7 extraction operations, equipment downtime translates directly to lost tonnes per shift — contamination failure is a production failure.' },
      { sector: 'AGRICULTURE', detail: 'Combine harvesting generates crop residue, fine topsoil and chaff simultaneously. Peak contamination load occurs exactly when equipment must run continuously — harvest windows are measured in days, not weeks. An air restriction event during harvest does not get fixed until the season ends.' },
      { sector: 'POWER GENERATION', detail: 'Stationary gensets and industrial prime movers operate at fixed load points where combustion efficiency is directly tied to power output per litre of fuel consumed. Gradual intake restriction creates invisible fuel consumption increases that only become visible on quarterly fuel audits — long after the damage accumulates.' },
      { sector: 'CONSTRUCTION', detail: 'Earthwork sites combine fine silica dust, diesel exhaust, cement particulate and disturbed topsoil into complex contamination profiles. Excavators and dozers operate at sustained high load with no idle periods for element recovery — protection must hold across the full shift without restriction buildup.' },
      { sector: 'INDUSTRIAL', detail: 'Compressors, blowers and industrial prime movers feeding process equipment cannot tolerate downstream contamination. Bearing and valve wear in industrial compressors is directly linked to intake air quality — contamination that passes the air filter reaches lubricated surfaces within the compression cycle.' },
    ],
    testimonial: {
      quote: 'We put MACROCORE™ to the test in our coal-loading operation — the highest-dust environment we run. Service intervals extended by 40% with zero bypass events recorded. The progressive density concept is real engineering, not marketing.',
      role: 'Maintenance Manager',
      sector: 'Coal Handling Terminal — 220 units',
    },
    ctaTag: '// IDENTIFY YOUR MACROCORE™ ELEMENT',
    ctaHeading: 'FIND YOUR AIR PROTECTION',
    ctaBody: 'Cross-reference 500,000+ OEM part numbers. Identify the exact MACROCORE™ element for your engine or compressor specification.',
  },

  intekcore: {
    categoryTag: '// HEAVY-DUTY HOUSING SYSTEMS · INTEKCORE™',
    heroTitle: 'INTEKCORE™',
    heroSubtitle: 'FILTER HOUSING SYSTEMS',
    heroTagline: 'Engineered filter housing systems for heavy-duty trucks and industrial machinery. High-pressure rated, OEM-compatible housings that protect critical engine circuits across the most demanding operational environments.',
    heroImage: '/images/intekcor-hero.avif',
    heroStats: [
      { key: 'RATED PRESSURE', value: 'HIGH-PSI' },
      { key: 'COMPATIBILITY', value: 'OEM-FIT' },
      { key: 'ENVIRONMENT', value: 'HEAVY-DUTY' },
    ],
    logoSrc: '/assets/INTEKCORE.avif',
    systemHeadline: 'THE HOUSING IS NOT\nA PASSIVE COMPONENT.',
    systemParagraphs: [
      'In heavy-duty truck and machinery applications, the filter housing defines the reliability boundary of the entire filtration system. A compromised housing — through corrosion, thread wear, bypass valve failure or seal degradation — neutralizes the protection value of the filter element it contains. INTEKCORE™ housing systems are engineered so the housing never becomes the failure point.',
      'Constructed from high-grade materials rated for continuous high-pressure operation, INTEKCORE™ housings maintain structural integrity across the full thermal cycling range of heavy commercial and industrial engines — from cold starts in extreme climates to sustained high-load thermal conditions in mining and construction operations.',
      'Universal mounting geometry and OEM-compatible thread standards make INTEKCORE™ housings direct-fit replacements across major truck and machinery platforms. No fabrication. No adapter plates. No serviceability compromise.',
    ],
    productImageSrc: '/images/pelon-air_converted.avif',
    productImageCaption: 'INTEKCORE™ · HEAVY-DUTY FILTER HOUSING SYSTEMS',
    stagesHeading: 'THREE ENGINEERING PRINCIPLES FOR HOUSING RELIABILITY.',
    stages: [
      {
        number: '01',
        tag: 'PRINCIPLE 1',
        title: 'HIGH-PRESSURE STRUCTURAL INTEGRITY',
        body: 'INTEKCORE™ housing bodies are rated for the peak pressure spikes that occur during cold-start conditions in heavy diesel applications — when oil viscosity creates instantaneous pressure surges that can stress inferior housing materials beyond their elastic limit. The housing wall geometry distributes burst load across the full structure rather than concentrating stress at the thread interface or bypass valve seat, eliminating the fracture failure mode that makes low-cost housings a liability in high-value asset operations.',
        stat: 'HIGH',
        statLabel: 'Burst pressure rating above standard housing specifications',
      },
      {
        number: '02',
        tag: 'PRINCIPLE 2',
        title: 'CORROSION-RESISTANT CONSTRUCTION',
        body: 'Trucks and machinery operating in agriculture, mining, construction and marine-adjacent environments expose filter housings to chemical contamination, humidity cycling, fertilizer residue, salt and abrasive particulate that accelerates corrosion on conventional steel housings. INTEKCORE™ material selection and surface treatment maintains housing integrity across multi-year service cycles — preventing the external degradation that leads to thread seizure, bypass valve sticking and catastrophic seal failure during element replacement.',
        stat: '100%',
        statLabel: 'Seal integrity maintained across full service cycle',
      },
      {
        number: '03',
        tag: 'PRINCIPLE 3',
        title: 'PRECISION SEAL ARCHITECTURE',
        body: 'The INTEKCORE™ sealing system is engineered for heavy commercial torque cycles — the repeated high-torque installation and removal that characterizes fleet workshop maintenance. Seal groove geometry maintains O-ring compression within specification across the full range of technician-applied torque variation, preventing the under-seal bypass events that occur when housings are installed to different torque standards across a mixed crew maintenance environment.',
        stat: '0',
        statLabel: 'Bypass events within rated torque installation range',
      },
    ],
    specs: [
      { label: 'CONSTRUCTION', value: 'HD-GRADE', sub: 'High-pressure rated housing material' },
      { label: 'SEAL SYSTEM', value: 'PRECISION', sub: 'Torque-tolerant O-ring groove geometry' },
      { label: 'BYPASS VALVE', value: 'INTEGRATED', sub: 'Rated bypass valve, factory calibrated' },
      { label: 'THREAD STANDARD', value: 'OEM-FIT', sub: 'Compatible with major truck & machinery platforms' },
      { label: 'SURFACE TREATMENT', value: 'ANTI-CORR', sub: 'Corrosion-resistant for harsh environments' },
      { label: 'SERVICE ACCESS', value: 'TOOL-FIT', sub: 'Standard service tooling, no special equipment' },
    ],
    applicationsHeading: 'WHERE INTEKCORE™ HOUSING SYSTEMS OPERATE',
    applicationsSubtext: 'INTEKCORE™ housing systems are the structural foundation for filter protection on heavy trucks, off-highway machinery and industrial power units.',
    applications: [
      { sector: 'HEAVY TRUCKS', detail: 'Long-haul filter housings accumulate millions of vibration cycles across their service life. Vibration causes micro-cracks at thread interfaces and micro-seal compressions that create bypass paths too small to detect by visual inspection — but large enough to allow unfiltered oil or fuel to bypass the element continuously. By the time external leak-down is visible, the bypass has been operating for thousands of kilometers.' },
      { sector: 'CONSTRUCTION MACHINERY', detail: 'Construction equipment is routinely cleaned with high-pressure alkaline degreasers before inspection. These chemicals attack standard zinc and aluminium housing surfaces — particularly at the seal groove where dimensional stability is critical. A housing with chemically degraded seal grooves does not hold O-ring compression to specification on the next element change, regardless of technician torque application.' },
      { sector: 'MINING EQUIPMENT', detail: 'Off-highway mining machines run around the clock at remote sites where workshop support is limited and parts lead times are measured in days. A housing that develops a bypass failure requires the machine to be stood down until the housing is replaced — causing operational disruption in a 24/7 extraction schedule that is disproportionate to the value of the failed component.' },
      { sector: 'AGRICULTURE', detail: 'Tractors and harvesters are exposed to fertilizer, herbicide and pesticide residues through the growing season. Agricultural chemicals accumulate in recesses around the filter housing mounting area and are not fully removed during routine cleaning. Housing corrosion progresses invisibly under field operating conditions and is typically only identified during major service intervals when damage is already extensive.' },
      { sector: 'BUS & COACH FLEETS', detail: 'Transit bus fleets complete element changes on high-frequency service cycles — some models at 10,000-km intervals on intensive urban duty. Each change event cycles the seal surfaces through their full compression range. Housing seal grooves that lose dimensional stability across hundreds of element changes eventually fail to retain O-ring compression at the required installation torque, creating bypass that is invisible between changes.' },
      { sector: 'INDUSTRIAL POWER UNITS', detail: 'Stationary industrial hydraulic systems operate at defined service intervals without shutdown capability between changes. A housing bypass event in this context sends unfiltered fluid directly to pump and actuator circuits — contamination that may only be detected when control system performance degrades or an internal pump inspection reveals scoring that requires a full hydraulic rebuild.' },
    ],
    testimonial: {
      quote: 'Housing failures were our number one unplanned maintenance item. Since standardizing on INTEKCORE™ housings across our truck fleet, we have had zero seal failures and zero contamination bypass events in 14 months of full fleet operation.',
      role: 'Regional Fleet Director',
      sector: 'Heavy Transport Operator — 310 units',
    },
    ctaTag: '// IDENTIFY YOUR INTEKCORE™ HOUSING',
    ctaHeading: 'FIND YOUR HOUSING SYSTEM',
    ctaBody: 'Cross-reference 500,000+ OEM part numbers. Identify the exact INTEKCORE™ housing for your truck or machinery platform.',
  },

  syntepore: {
    categoryTag: '// FUEL ASSET PROTECTION · SYNTEPORE™',
    heroTitle: 'SYNTEPORE™',
    heroSubtitle: 'PRECISION INJECTOR GUARD',
    heroTagline: 'Progressive multi-layer protection architecture intercepting sub-micron contamination before it reaches Common Rail injectors. The last line of defense for high-pressure fuel injection systems operating above 2,000 bar.',
    heroImage: '/images/hero-syntapore.avif',
    heroStats: [
      { key: 'BARRIER RATING', value: '4 MICRON' },
      { key: 'PROTECTION', value: 'ZERO MIGRATION' },
      { key: 'TARGET', value: 'INJECTOR DEFENSE' },
    ],
    logoSrc: '/assets/SYNTEPORE.avif',
    systemHeadline: 'THE INJECTOR\'S\nFINAL GUARDIAN.',
    systemParagraphs: [
      'Common Rail injection systems operate at pressures exceeding 2,000 bar. At this pressure, a contamination particle as small as 4 microns can score injector needle seats and destroy the precision tolerances that control injection timing and fuel atomization quality.',
      'SYNTEPORE™ is engineered as the terminal protection layer between the fuel supply system and the injection circuit. Where pre-filters handle bulk contamination, SYNTEPORE™ eliminates the residual sub-micron fraction — the particles that conventional filtration misses and that HPCR systems cannot tolerate.',
      'A Common Rail injector replacement costs $400–$1,200 per unit and requires specialized equipment. The contamination event that caused the failure typically occurred 50,000–100,000 km earlier — each particle that passed the terminal protection layer contributing incrementally to needle seat erosion that accelerated silently until the tolerance was exceeded.',
    ],
    productImageSrc: '/images/nanoforce (2).avif',
    productImageCaption: 'SYNTEPORE™ · PRECISION INJECTOR GUARD ELEMENT',
    stagesHeading: 'THREE PROGRESSIVE LAYERS. ABSOLUTE INJECTOR DEFENSE.',
    stages: [
      {
        number: '01',
        tag: 'LAYER 1',
        title: 'PROGRESSIVE CAPTURE ZONE',
        body: 'The outer protection layer intercepts particles from 40 microns down to 10 microns in a graduated capture architecture that distributes contamination load evenly across the filter surface. This zone prevents premature restriction at entry points and ensures full utilization of the protection matrix capacity across the service interval. Water droplets and gel contaminants are also intercepted at this stage before reaching the precision barrier.',
        stat: '40µm',
        statLabel: 'Progressive capture zone entry threshold',
      },
      {
        number: '02',
        tag: 'LAYER 2',
        title: 'INTERMEDIATE PROTECTION BAND',
        body: 'The intermediate layer targets contamination between 10 and 4 microns — the particle size range most directly correlated with injector needle wear and spool valve erosion in HPCR systems. Fiber architecture in this zone is calibrated for maximum surface contact time, ensuring even fine particles in suspension do not migrate through to the precision barrier with sufficient velocity to cause impact damage.',
        stat: '4µm',
        statLabel: 'Intermediate band capture threshold',
      },
      {
        number: '03',
        tag: 'LAYER 3',
        title: 'ZERO MIGRATION BARRIER',
        body: 'The innermost layer is the SYNTEPORE™ zero migration barrier — a high-compaction protection surface designed to achieve absolute retention of any particle that reaches it from layers 1 and 2. Zero migration means no particle above 4 microns exits the element and enters the injection rail under any operating pressure or flow condition. The barrier is structurally reinforced to withstand cold-start fuel viscosity spikes without bypass.',
        stat: '0',
        statLabel: 'Particles above 4µm passing the zero migration barrier',
      },
    ],
    specs: [
      { label: 'PRECISION BARRIER', value: '4µm', sub: 'Absolute retention at terminal layer' },
      { label: 'PROGRESSIVE LAYERS', value: '3', sub: 'Load-distributed protection matrix' },
      { label: 'INJECTION RATED', value: 'HPCR', sub: '2,000+ bar system compatibility' },
      { label: 'WATER INTERCEPT', value: 'STAGE 1', sub: 'Free and emulsified water capture' },
      { label: 'BYPASS', value: 'ZERO', sub: 'No bypass under rated operating pressure' },
      { label: 'SERVICE INTERVAL', value: 'EXTENDED', sub: 'Progressive loading extends service life' },
    ],
    applicationsHeading: 'WHERE SYNTEPORE™ PROTECTS',
    applicationsSubtext: 'SYNTEPORE™ is the designated precision protection element for any diesel system where fuel injection tolerances demand sub-4-micron cleanliness.',
    applications: [
      { sector: 'HEAVY TRANSPORT', detail: 'A single Common Rail injector failure on a Euro VI long-haul truck removes the vehicle from service for a minimum of 24 hours for replacement and system flushing. HPCR systems in Euro IV–VI trucks are calibrated to tolerances below 5 microns — any particle that bypasses terminal filtration is operating inside the precision tolerance of the injector it reaches.' },
      { sector: 'POWER GENERATION', detail: 'Emergency standby generators start at full load demand with no warm-up period. There is no opportunity to divert the first fuel charge away from the injection system. If terminal fuel protection has degraded before the start event, the contamination event occurs at the moment of peak demand — when the genset cannot be taken offline.' },
      { sector: 'AGRICULTURE', detail: 'Precision agricultural machinery uses variable rate injection systems that modify fuel delivery in real time based on GPS-mapped field data. Contamination-induced injector drift corrupts injection map execution — causing under- or over-application that creates yield losses across entire field sections before the malfunction is diagnosed.' },
      { sector: 'MINING', detail: 'Remote extraction sites operate with supply chains measured in days or weeks per delivery cycle. An injector failure on a haul truck at a remote site means flying in parts at emergency freight rates or shutting the machine down until the next scheduled delivery. Either outcome costs more than any filtration investment.' },
      { sector: 'CONSTRUCTION', detail: 'Tier 4 Final emissions-compliant engines integrate injection system performance with SCR and DPF after-treatment. Injector deposits from contaminated fuel cause incomplete combustion that loads the DPF ahead of schedule — triggering active regeneration cycles that increase downtime and fuel consumption independently of the injection problem.' },
      { sector: 'RAILWAY', detail: 'Diesel locomotives take on fuel from maintenance depots and remote servicing points with varying quality assurance standards. A locomotive on a multi-day run may refuel from multiple sources. Terminal filtration protects the injection system against the worst-quality event in that sequence, not the average.' },
    ],
    testimonial: {
      quote: 'Our HPCR injection system was generating one injector failure per 60,000 kilometers on average. With SYNTEPORE™ inline protection, we passed 180,000 kilometers on the test fleet with zero injection events. The sub-micron barrier is the difference.',
      role: 'Technical Director',
      sector: 'Commercial Fleet — Long-Haul Division',
    },
    ctaTag: '// IDENTIFY YOUR SYNTEPORE™ ELEMENT',
    ctaHeading: 'FIND YOUR INJECTOR PROTECTION',
    ctaBody: 'Cross-reference 500,000+ OEM part numbers. Identify the exact SYNTEPORE™ element for your fuel injection system specification.',
  },

  hydrocore: {
    categoryTag: '// WATER SEPARATION TECHNOLOGY · HYDROCORE™',
    heroTitle: 'HYDROCORE™',
    heroSubtitle: 'WATER SEPARATOR',
    heroTagline: 'Hydrophobic protection technology achieving 99.8% water separation efficiency from fuel systems. Three-phase water interception — free, emulsified and dissolved — before contamination reaches the injection circuit.',

    heroImage: '/images/hydrocore-hero.avif',
    heroStats: [
      { key: 'EFFICIENCY', value: '99.8%' },
      { key: 'BARRIER TYPE', value: 'HYDROPHOBIC' },
      { key: 'PROTECTION', value: 'WATER REPULSION' },
    ],
    logoSrc: '/images/hydrocore(fn).avif',
    systemHeadline: 'HYDROPHOBIC DEFENSE.\nWATER CANNOT PASS.',
    systemParagraphs: [
      'Water contamination in fuel systems operates across three phases: free water that settles and can be drained, emulsified water suspended in micro-droplets that conventional filters cannot intercept, and dissolved water that forms free phase when temperature changes. Each phase causes a different failure mode — microbial growth, injector corrosion, and cavitation erosion respectively.',
      'HYDROCORE™ hydrophobic technology addresses all three phases through a sequenced interception architecture where each protection layer is engineered for a specific water contamination state. The result is 99.8% water separation efficiency — validated across the full operating temperature and fuel flow range.',
      'Water in the fuel system does not cause a single catastrophic failure — it degrades the injection circuit progressively. Microbial colonies form at the water-fuel interface, producing acids and biomass that contaminate the entire fuel supply. Injector corrosion from water contact is cumulative. Each hour of operation with water present removes service life that cannot be recovered.',
    ],
    productImageSrc: '/images/fuelseparator.avif',
    productImageCaption: 'HYDROCORE™ · WATER SEPARATION PROTECTION TECHNOLOGY',
    stagesHeading: 'THREE PHASES OF WATER. ONE PROTECTION SYSTEM.',
    stages: [
      {
        number: '01',
        tag: 'PHASE 1',
        title: 'FREE WATER COLLECTION',
        body: 'Free water — the bulk water phase that separates from fuel by gravity — is intercepted at the entry stage by the HYDROCORE™ collection geometry. Incoming fuel flow is directed past the collection chamber where free water masses are diverted by density differential and captured in the sealed reservoir below. This stage removes the contamination fraction most likely to cause immediate microbial growth and corrosion in the fuel system.',
        stat: '100%',
        statLabel: 'Free water phase interception at entry stage',
      },
      {
        number: '02',
        tag: 'PHASE 2',
        title: 'EMULSIFIED WATER COALESCENCE',
        body: 'Emulsified water — suspended as micro-droplets too small for gravity separation — is captured through the HYDROCORE™ coalescence architecture. The hydrophilic contact surface causes micro-droplets to coalesce on contact, growing until they achieve sufficient mass to fall by gravity into the sealed collection chamber. The graduated contact geometry ensures repeated droplet surface contact regardless of fuel flow velocity or emulsification degree.',
        stat: '99.8%',
        statLabel: 'Combined water separation efficiency rating',
      },
      {
        number: '03',
        tag: 'PHASE 3',
        title: 'HYDROCORE™ HYDROPHOBIC BARRIER',
        body: 'The precision hydrophobic barrier is the terminal protection layer against dissolved water and residual micro-droplet contamination. The hydrophobic surface architecture physically repels water molecules at contact — fuel molecules pass through, water molecules cannot. This barrier operates on a molecular interaction principle: water contact angle on the barrier surface exceeds 90°, making penetration thermodynamically impossible regardless of differential pressure.',
        stat: '2µm',
        statLabel: 'Precision barrier minimum rating',
      },
    ],
    specs: [
      { label: 'SEPARATION EFFICIENCY', value: '99.8%', sub: 'Combined free + emulsified + dissolved water' },
      { label: 'COLLECTION CHAMBER', value: 'SEALED', sub: 'Permanent water removal from fuel circuit' },
      { label: 'HYDROPHOBIC BARRIER', value: '2µm', sub: 'Terminal water repulsion layer minimum rating' },
      { label: 'MONITORING', value: 'VISUAL', sub: 'Integrated water level monitoring port' },
      { label: 'FUEL COMPATIBILITY', value: '100%', sub: 'Diesel · Biodiesel · Heating oil · Kerosene' },
      { label: 'DRAIN SYSTEM', value: 'MANUAL/AUTO', sub: 'Drain valve or automatic drain options' },
    ],
    applicationsHeading: 'WHERE HYDROCORE™ PROTECTS',
    applicationsSubtext: 'HYDROCORE™ water separation technology protects any fuel system where water ingress threatens injection system integrity.',
    applications: [
      { sector: 'HEAVY TRANSPORT', detail: 'Long-haul diesel drawn from shared depot storage tanks accumulates water from condensation cycles across the supply chain. Diesel stored below 15°C can hold water in solution that precipitates as visible free water only after the fuel warms up inside the vehicle tank — arriving at the injectors in a condition that visual inspection at the depot would not have detected.' },
      { sector: 'POWER GENERATION', detail: 'A 10,000-litre genset fuel tank exposed to seasonal temperature cycling accumulates significant free water at the bottom draw point over a winter storage period. When the genset starts under emergency load, the first fuel drawn carries the accumulated contamination from months of static storage — the worst-case fuel quality event delivered at the worst-case timing.' },
      { sector: 'AGRICULTURE', detail: 'On-farm diesel tanks in above-ground installations undergo diurnal temperature swings through growing seasons. Each cooling cycle draws humid ambient air through tank breathers, depositing condensation on tank walls. This water collects at the bottom draw point and concentrates progressively through the season without any external indication.' },
      { sector: 'MARINE', detail: 'Marine fuel tanks breathe salt-laden humid air with every sea temperature cycle. Condensation from this air carries dissolved salt that does not evaporate when water settles — creating a brine layer at the tank bottom that is more corrosive to injection components than fresh water contamination from land-based storage.' },
      { sector: 'MINING', detail: 'Bulk fuel deliveries to remote sites arrive after long-distance road transport. Vibration during transit re-emulsifies settled water back into suspension, delivering fine water droplets uniformly dispersed through the fuel — the condition least visible on inspection and most damaging to injection system tolerances.' },
      { sector: 'CONSTRUCTION', detail: 'Mobile refueling bowsers on active sites are exposed to rain and humidity during every fueling operation. Water enters through loose filler caps, outdoor drum transfers and bowser condensation. On sites where multiple bowsers and operators share refueling duties, there is no consistent quality control over the condition of the fuel reaching each machine.' },
    ],
    testimonial: {
      quote: 'Water intrusion was destroying our injection pumps on a predictable seasonal cycle. HYDROCORE™ hydrophobic separation eliminated that cycle entirely — our last two maintenance inspections showed dry sumps across every test unit.',
      role: 'Agricultural Equipment Director',
      sector: 'Harvest Operations — 45 combine harvesters',
    },
    ctaTag: '// IDENTIFY YOUR HYDROCORE™ ELEMENT',
    ctaHeading: 'FIND YOUR WATER PROTECTION',
    ctaBody: 'Cross-reference 500,000+ OEM part numbers. Identify the exact HYDROCORE™ water separation element for your fuel system.',
  },

  thermacore: {
    categoryTag: '// THERMAL SYSTEMS PROTECTION · THERMACORE™',
    heroTitle: 'THERMACORE™',
    heroSubtitle: 'SCA ADDITIVE',
    heroTagline: 'SCA additive release technology for thermal systems with cavitation prevention and extended cooling circuit protection. Controlled gradual dosing that maintains coolant chemistry within the protection corridor across the full service interval.',
    heroImage: '/images/coolant-hero.avif',
    heroStats: [
      { key: 'TECHNOLOGY', value: 'SCA RELEASE' },
      { key: 'FUNCTION', value: 'VAPOR PREVENTION' },
      { key: 'DOSING', value: 'GRADUAL' },
    ],
    logoSrc: '/assets/THERMACORE.avif',
    systemHeadline: 'CHEMICAL ASSET PROTECTION\nFOR THE COOLING CIRCUIT.',
    systemParagraphs: [
      'Diesel engine cooling systems face two simultaneous corrosion threats: electrochemical attack on aluminum, copper and steel surfaces, and cavitation erosion on cylinder liner external surfaces driven by pressure waves from piston firing events. Both failure modes are prevented by maintaining SCA (Supplemental Coolant Additive) chemistry within a tight concentration corridor.',
      'THERMACORE™ deploys a controlled gradual release mechanism that replenishes SCA chemistry as it is consumed through the service interval — maintaining protection concentration without peaks or valleys that conventional coolant change schedules cannot guarantee.',
      'The gradual dosing system prevents the inhibitor concentration spikes that occur when SCA is added as a single dose at service — high initial concentration that drops progressively to sub-protection levels before the next service interval, leaving the cooling circuit unprotected for a portion of every service cycle.',
    ],
    productImageSrc: '/images/coolant-mesa.avif',
    productImageCaption: 'THERMACORE™ · SCA ADDITIVE RELEASE PROTECTION ELEMENT',
    stagesHeading: 'THREE PROTECTION MECHANISMS FOR COOLING CIRCUIT INTEGRITY.',
    stages: [
      {
        number: '01',
        tag: 'MECHANISM 1',
        title: 'ADDITIVE RELEASE CONTROL',
        body: 'THERMACORE™ controlled additive release matrix delivers SCA chemistry into the coolant stream at a rate matched to consumption. As inhibitor concentration falls through use, the release rate increases to compensate — maintaining the target protection corridor without operator intervention between service intervals. This active concentration management eliminates the unprotected coolant condition that occurs at the end of conventional SCA dosing intervals.',
        stat: '100%',
        statLabel: 'SCA concentration corridor maintenance across service interval',
      },
      {
        number: '02',
        tag: 'MECHANISM 2',
        title: 'VAPOR PREVENTION LAYER',
        body: 'Cavitation erosion on cylinder liner surfaces begins with vapor bubble formation at the liner wall during pressure wave events from piston combustion. THERMACORE™ vapor prevention chemistry forms a protective molecular layer on ferrous surfaces that suppresses the nucleate boiling that initiates bubble formation. By preventing vapor bubble genesis at the metal surface, THERMACORE™ eliminates the cavitation collapse energy that erodes liner walls over time.',
        stat: '0',
        statLabel: 'Liner surface cavitation erosion events with THERMACORE™ active',
      },
      {
        number: '03',
        tag: 'MECHANISM 3',
        title: 'HEAT MANAGEMENT BARRIER',
        body: 'The SCA film maintained by THERMACORE™ on all cooling circuit metal surfaces also functions as a thermal transfer optimization barrier. The molecular protection layer is calibrated to maintain metal surface contact without creating thermal insulation effects — protecting against corrosion while preserving the heat transfer efficiency between the engine block and the coolant stream that cooling system design depends on.',
        stat: '99%',
        statLabel: 'Corrosion protection efficiency across metal surface types',
      },
    ],
    specs: [
      { label: 'SCA TECHNOLOGY', value: 'GRADUAL', sub: 'Controlled release across service interval' },
      { label: 'VAPOR PREVENTION', value: 'ACTIVE', sub: 'Cylinder liner cavitation protection' },
      { label: 'METALS PROTECTED', value: '5', sub: 'Aluminum · Copper · Iron · Steel · Brass' },
      { label: 'DOSING METHOD', value: 'PASSIVE', sub: 'No operator intervention between services' },
      { label: 'COOLANT COMPATIBILITY', value: 'ALL', sub: 'Ethylene glycol · Propylene glycol · OAT' },
      { label: 'SERVICE INTERVAL', value: 'EXTENDED', sub: 'Maintains protection to full OEM interval' },
    ],
    applicationsHeading: 'WHERE THERMACORE™ PROTECTS',
    applicationsSubtext: 'THERMACORE™ SCA protection is the thermal system defense choice for diesel engines with aluminum and cast iron cooling circuits.',
    applications: [
      { sector: 'HEAVY TRANSPORT', detail: 'Modern heavy diesel cooling circuits combine aluminum charge air coolers, copper heater cores, cast iron engine blocks and steel coolant lines in a single circuit. Each metal has a different corrosion chemistry requiring simultaneous inhibitor protection. A conventional single-dose SCA event provides peak concentration immediately after service, then falls progressively through the interval — leaving multi-metal circuits partially unprotected before the next service is due.' },
      { sector: 'POWER GENERATION', detail: 'Standby generator cooling systems sit at ambient temperature with no coolant circulation for weeks between test cycles. SCA inhibitor films that depend on continuous contact with metal surfaces dissipate during long static periods. The cooling circuit is unprotected during the restart sequence — which is the highest thermal stress event in the genset operating profile.' },
      { sector: 'AGRICULTURE', detail: 'Agricultural equipment in storage through off-seasons experiences freeze-thaw cycles and static corrosion exposure across multiple months. Liner pitting and head gasket corrosion that develops during off-season storage is not visible until engine inspection — typically the season after the corrosion occurred, when the engine is already damaged.' },
      { sector: 'MINING', detail: 'Cylinder liner cavitation erosion in heavy diesel engines under full mining load cycles at 3,000–4,000 RPM generates pitting at a rate five to ten times higher than highway truck operation. A liner in a mining machine may reach replacement threshold in 4,000–6,000 hours versus 20,000+ hours in highway service — the difference is determined by SCA concentration consistency.' },
      { sector: 'CONSTRUCTION', detail: 'Construction sites use high-pressure alkaline washdown to clean equipment as part of pre-inspection preparation. Detergent water that enters coolant reservoirs through overflow and splash during washdown dilutes inhibitor concentration below protection threshold — an event that goes unnoticed because the coolant level appears normal and the color remains unchanged.' },
      { sector: 'INDUSTRIAL', detail: 'Stationary industrial engines in process facilities are scheduled for maintenance around production shutdowns, not engine operating hours. A cooling circuit that passes its SCA threshold between two scheduled shutdowns provides no visible warning — corrosion progresses silently until the next inspection reveals damage that has been accumulating for months.' },
    ],
    testimonial: {
      quote: 'Cylinder liner pitting from cavitation was costing us an average of $12,000 per engine rebuild. THERMACORE™ SCA technology has maintained coolant chemistry within specification continuously for 18 months — zero pitting events recorded across our generator fleet.',
      role: 'Power Generation Asset Manager',
      sector: 'Data Center Backup Fleet — 32 generators',
    },
    ctaTag: '// IDENTIFY YOUR THERMACORE™ ELEMENT',
    ctaHeading: 'FIND YOUR COOLING PROTECTION',
    ctaBody: 'Cross-reference 500,000+ OEM part numbers. Identify the exact THERMACORE™ SCA element for your engine cooling specification.',
  },

  drycore: {
    categoryTag: '// PNEUMATIC DRYING TECHNOLOGY · DRYCORE™',
    heroTitle: 'DRYCORE™',
    heroSubtitle: 'DESICCANT DRYER',
    heroTagline: 'Molecular sieve desiccant technology removing moisture from pneumatic systems with precision efficiency. Corrosion prevention and extended service life for air brake, suspension and control circuit asset protection.',
    heroImage: '/images/airdryer-hero.avif',
    heroStats: [
      { key: 'TECHNOLOGY', value: 'MOLECULAR SIEVE' },
      { key: 'FUNCTION', value: 'WATER ABSORPTION' },
      { key: 'PROTECTION', value: 'CORROSION PREVENTION' },
    ],
    logoSrc: '/images/drycore(fn).avif',
    systemHeadline: 'MOLECULAR-LEVEL\nMOISTURE CUSTODY.',
    systemParagraphs: [
      'Compressed air systems for braking, suspension and pneumatic control contain moisture drawn in during compression from ambient air. At system operating temperature, this moisture remains vapor-phase. When air cools in downstream circuits, valves and actuators, vapor transitions to liquid — causing valve corrosion, seal swelling and control system failures.',
      'DRYCORE™ molecular sieve desiccant captures water vapor at the molecular level before phase transition occurs — preventing liquid water formation in pneumatic circuits entirely rather than managing the consequences after it forms.',
      'When moisture breaks through a saturated desiccant bed, liquid water enters the downstream pneumatic circuit immediately. In air brake systems, this means water in brake chambers, relay valves and spring brake assemblies. The corrosion begins immediately — and every component that liquid water reached must be inspected and potentially replaced before the vehicle returns to service.',
    ],
    productImageSrc: '/images/airdryer.avif',
    productImageCaption: 'DRYCORE™ · DESICCANT DRYER PROTECTION ELEMENT',
    stagesHeading: 'THREE STAGES OF PNEUMATIC MOISTURE CONTROL.',
    stages: [
      {
        number: '01',
        tag: 'STAGE 1',
        title: 'WATER ABSORPTION MATRIX',
        body: 'Compressed air entering the DRYCORE™ element passes through the primary molecular sieve desiccant matrix where water vapor is adsorbed at molecular contact sites on the desiccant crystal surface. Molecular sieve adsorption is thermodynamically preferred over silica gel at typical compressed air system operating temperatures — delivering higher moisture removal efficiency per unit volume across the full humidity range from arid to tropical ambient conditions.',
        stat: '100%',
        statLabel: 'Water vapor capture at primary desiccant matrix',
      },
      {
        number: '02',
        tag: 'STAGE 2',
        title: 'MOISTURE CUSTODY ZONE',
        body: 'Adsorbed moisture is retained within the molecular sieve matrix crystal structure under the mechanical and thermal stresses of normal dryer operation. The custody zone capacity is sized to accommodate the moisture load from specified air flow rates and ambient humidity conditions without saturation breakthrough between purge cycles. Breakthrough prevention is the critical performance specification — any moisture that exits the desiccant bed reaches downstream pneumatic components.',
        stat: '0',
        statLabel: 'Moisture breakthrough events at rated operating conditions',
      },
      {
        number: '03',
        tag: 'STAGE 3',
        title: 'CORROSION PREVENTION SYSTEM',
        body: 'The downstream protection delivered by DRYCORE™ moisture custody extends across all pneumatic circuit components — brake chambers, relay valves, spring brakes, air suspension valves and electronic control modules with pneumatic interfaces. By maintaining dry air throughout the circuit, DRYCORE™ eliminates the electrochemical corrosion that water promotes on metal valve seats, piston rods and spring surfaces, and the swelling degradation that moisture causes in rubber seals and diaphragms.',
        stat: '99%',
        statLabel: 'Corrosion event prevention in protected pneumatic circuits',
      },
    ],
    specs: [
      { label: 'DESICCANT TYPE', value: 'MOLECULAR', sub: 'Sieve adsorption technology' },
      { label: 'MOISTURE REMOVAL', value: '100%', sub: 'Water vapor capture at rated conditions' },
      { label: 'BREAKTHROUGH', value: 'ZERO', sub: 'No moisture to downstream circuit' },
      { label: 'PURGE COMPATIBLE', value: 'YES', sub: 'Designed for cyclic adsorption/regeneration' },
      { label: 'TEMP RANGE', value: '-40°C', sub: 'Cold-rated dew point suppression' },
      { label: 'OEM FITMENT', value: '100%', sub: 'Drop-in replacement for OEM air dryer' },
    ],
    applicationsHeading: 'WHERE DRYCORE™ PROTECTS',
    applicationsSubtext: 'DRYCORE™ desiccant protection covers every pneumatic asset protection application where moisture in compressed air causes component degradation.',
    applications: [
      { sector: 'HEAVY TRANSPORT', detail: 'In sub-zero ambient temperatures, liquid water in air brake distribution lines and chambers freezes into ice plugs that prevent valve actuation. A vehicle with frozen brake components cannot be driven to a heated workshop — it requires roadside intervention in the exact conditions that created the failure. The repair event takes the vehicle out of service at the worst-case time and location.' },
      { sector: 'BUS & COACH', detail: 'Urban transit bus air suspension maintains ride height through bellows constantly adjusted by height control valves. Moisture-corroded height control valves develop stiction — they stop responding to small adjustment inputs, leaving the bus at incorrect height. On low-floor accessible buses, this creates a boarding ramp gap that violates accessibility compliance standards and forces the vehicle out of service.' },
      { sector: 'RAIL', detail: 'The triple valve on a railway freight wagon is the primary brake control device. Moisture-induced internal corrosion causes valve response delay — an extended stopping distance — before it produces a complete valve failure. Extended stopping distance on a loaded freight consist is a train handling safety issue that must be investigated before the wagon returns to service.' },
      { sector: 'MANUFACTURING', detail: 'Pneumatic actuators in automated assembly systems depend on sub-millimeter positioning repeatability. Moisture contamination causes valve stiction that introduces positioning uncertainty into the actuator cycle. This shows first in dimensional variance in finished parts — after an entire batch has already been assembled and may need to be scrapped.' },
      { sector: 'MINING', detail: 'Underground mine environments maintain near-100% relative humidity at face depth. Air compressors processing saturated air continuously can saturate a degraded desiccant bed in hours. Moisture breakthrough in this environment sends liquid water directly into pneumatic drill equipment designed exclusively for dry compressed air service.' },
      { sector: 'CONSTRUCTION', detail: 'Construction site pneumatic tools — jackhammers, nail guns, air-powered tools — operate outdoors across the full ambient humidity range. Without effective moisture protection, internal tool components rust between shifts, reducing tool service life by 50–70% compared to protected service. The replacement cost accumulates as a routine budget line without identification of the root cause.' },
    ],
    testimonial: {
      quote: 'Our pneumatic braking system required brake valve replacements every 18 months on average due to moisture corrosion. After installing DRYCORE™ desiccant elements, we are at 36 months with zero brake valve failures. The ROI was immediate.',
      role: 'Fleet Safety Director',
      sector: 'Municipal Bus Operator — 90 units',
    },
    ctaTag: '// IDENTIFY YOUR DRYCORE™ ELEMENT',
    ctaHeading: 'FIND YOUR DESICCANT PROTECTION',
    ctaBody: 'Cross-reference 500,000+ OEM part numbers. Identify the exact DRYCORE™ desiccant element for your pneumatic system specification.',
  },

  duratech: {
    categoryTag: '// FLEET MAINTENANCE SYSTEMS · DURATECH™',
    heroTitle: 'DURATECH™',
    heroSubtitle: 'MASTER KIT',
    heroTagline: 'Master kit consolidation with OEM interchangeability delivering fleet-ready solutions for standardized maintenance operations. Single-source protection for multi-system service events across mixed-model fleets.',
    heroImage: '/images/almacen-4_converted.avif',
    heroStats: [
      { key: 'SYSTEM', value: 'MASTER KIT' },
      { key: 'FITMENT', value: 'OEM INTERCHANGE' },
      { key: 'COVERAGE', value: 'MULTI-SYSTEM' },
    ],
    logoSrc: '/images/duratech(fn).avif',
    systemHeadline: 'ONE SOURCE.\nEVERY SYSTEM. EVERY VEHICLE.',
    systemParagraphs: [
      'Fleet maintenance operations managing mixed-model vehicle populations face a consistent challenge: sourcing compatible filter elements from multiple suppliers for each vehicle variant, managing separate inventory lines, and coordinating service timing across different replacement intervals.',
      'DURATECH™ master kit architecture consolidates all service-interval filter elements for a defined vehicle platform into a single sourcing event. Oil, fuel, air and cabin filters — all OEM-interchangeable, all coordinated to a unified service interval — in one kit.',
      'A wrong-element installation on a single vehicle does not cause an immediate failure — it creates a silent protection gap. The sourcing error is no longer traceable when the failure event eventually occurs, often thousands of kilometers later. In mixed-model fleets, wrong-element installations are a consistent outcome of high-part-number sourcing environments, not technician errors.',
    ],
    productImageSrc: '/images/npr-01_converted.avif',
    productImageCaption: 'DURATECH™ · MASTER KIT FLEET MAINTENANCE SYSTEM',
    stagesHeading: 'THREE CONSOLIDATION PRINCIPLES FOR FLEET EFFICIENCY.',
    stages: [
      {
        number: '01',
        tag: 'PRINCIPLE 1',
        title: 'MULTI-SYSTEM CONSOLIDATION',
        body: 'Each DURATECH™ master kit consolidates all filtration elements required for a complete vehicle service event into a single package. The kit composition is vehicle-specific — matched to the exact oil, fuel, air and cabin specifications of the target vehicle platform — eliminating the possibility of incorrect element selection that occurs when sourcing components individually from a general catalogue. One kit, one vehicle, one complete service.',
        stat: '1',
        statLabel: 'Source required per complete multi-system service',
      },
      {
        number: '02',
        tag: 'PRINCIPLE 2',
        title: 'OEM INTERCHANGEABILITY',
        body: 'Every element in the DURATECH™ master kit is designed to direct OEM specification — same dimensions, same bypass valve settings, same sealing surfaces, same thread specifications. OEM interchangeability means no modification to vehicle systems, no adapter plates, no calibration adjustments. Technicians can service any platform in the fleet with DURATECH™ kits with the same confidence as OEM-supplied elements, at fleet purchasing economics.',
        stat: '100%',
        statLabel: 'OEM dimensional and specification interchangeability',
      },
      {
        number: '03',
        tag: 'PRINCIPLE 3',
        title: 'STANDARDIZED INVENTORY',
        body: 'The DURATECH™ kit system converts fleet filter inventory from an unmanaged collection of individual part numbers to a structured kit-based inventory with predictable consumption rates. For fleet managers, this means reorder quantities based on vehicle count and service cycle frequency — not variable individual part consumption rates. Inventory holding costs fall, stockout risk falls, and administrative overhead for purchasing and parts management falls with them.',
        stat: '↓',
        statLabel: 'Inventory complexity per vehicle vs. individual part sourcing',
      },
    ],
    specs: [
      { label: 'KIT CONTENTS', value: '4+', sub: 'Oil · Fuel · Air · Cabin elements per kit' },
      { label: 'OEM INTERCHANGE', value: '100%', sub: 'Spec-matched to OEM requirements' },
      { label: 'VEHICLE COVERAGE', value: 'BROAD', sub: 'Kits for passenger, LCV and HDV platforms' },
      { label: 'INTERVAL SYNC', value: 'YES', sub: 'Elements coordinated to unified service schedule' },
      { label: 'IDENTIFICATION', value: 'CLEAR', sub: 'Platform-specific marking prevents mis-install' },
      { label: 'SOURCING', value: 'SINGLE', sub: 'One supplier, one order, one delivery' },
    ],
    applicationsHeading: 'WHERE DURATECH™ DELIVERS',
    applicationsSubtext: 'DURATECH™ master kit system is designed for operations managing multiple vehicles where sourcing efficiency and inventory simplification deliver measurable cost benefits.',
    applications: [
      { sector: 'FLEET OPERATORS', detail: 'A 50-vehicle fleet with 3 truck models requires 12–18 different filter part numbers per service cycle when sourcing elements individually. Each service event creates purchasing, warehouse and picking work proportional to part number count. Wrong-element installations — correct type, wrong specification for that model — are a consistent outcome of high-part-number picking environments, even with experienced technicians.' },
      { sector: 'WORKSHOPS', detail: 'An independent workshop servicing 8 vehicle brands needs to stock filter elements for every make-model-year combination in its customer base. Individual-part sourcing creates inventory holdings measured in hundreds of active part numbers, most moving at low frequency. Dead inventory, stockouts and emergency sourcing charges erode workshop margin continuously without appearing as a single identifiable cost line.' },
      { sector: 'RENTAL OPERATIONS', detail: 'Vehicle rental fleets schedule maintenance by calendar interval across mixed-model populations. When a vehicle comes in for service, the correct elements for that specific model must be in stock. A stockout on a specific model variant forces a maintenance deferral — the vehicle returns to rental without completing a full service because one element was missing from an individual-part order.' },
      { sector: 'MINING OPERATIONS', detail: 'Remote mine site supply logistics run on delivery cycles measured in days or weeks. A missing element specification on a single service order means either waiting for the next delivery cycle with an unserviced machine, or emergency airfreighting a single filter element at a cost that exceeds its value by an order of magnitude.' },
      { sector: 'MUNICIPAL FLEETS', detail: 'Public sector fleet maintenance budgets are set annually based on projected per-vehicle costs. Individual-part sourcing creates variable per-vehicle filter costs that fluctuate with model mix, supplier pricing changes and emergency sourcing events. Predictable per-vehicle maintenance cost is a budget management requirement that variable individual-part sourcing cannot consistently deliver.' },
      { sector: 'CONSTRUCTION', detail: 'A construction contractor operating excavators, graders and trucks from three manufacturers needs separate sourcing relationships and stocking strategies for each platform. On an active project site, a missing element delays a scheduled service — and the machine that cannot be serviced on time is the one that needs to work tomorrow.' },
    ],
    testimonial: {
      quote: 'The synchronized kit program eliminated parts sourcing errors entirely. Previously, wrong-interval filter changes were causing 15% of our maintenance writebacks. DURATECH™ model-specific kits brought that to zero in the first month.',
      role: 'Fleet Operations Manager',
      sector: 'Regional Distribution Network — 175 units',
    },
    ctaTag: '// IDENTIFY YOUR DURATECH™ KIT',
    ctaHeading: 'FIND YOUR FLEET KIT',
    ctaBody: 'Cross-reference 500,000+ OEM part numbers. Identify the exact DURATECH™ master kit for your vehicle or equipment platform.',
  },

  marineclean: {
    categoryTag: '// MARINE FILTRATION SYSTEMS · MARINECLEAN™',
    heroTitle: 'MARINECLEAN™',
    heroSubtitle: 'SALT-RESISTANT',
    heroTagline: 'Salt-resistant epoxy coating with brine rejection technology meeting IMO certification for commercial marine filtration. Corrosion shield defense for diesel fuel and hydraulic systems operating in saltwater environments.',
    heroImage: '/images/marino-taller.avif',
    heroStats: [
      { key: 'CERTIFICATION', value: 'IMO' },
      { key: 'PROTECTION', value: 'SALT-RESISTANT' },
      { key: 'SYSTEM', value: 'CORROSION SHIELD' },
    ],
    logoSrc: '/images/marineclean(fn).avif',
    systemHeadline: 'MARINE-GRADE DEFENSE\nAGAINST SALT CORROSION.',
    systemParagraphs: [
      'Marine diesel systems operate in the most corrosive environment accessible to filtration technology. Salt spray, salt aerosol and seawater ingress attack filter housings, sealing interfaces and bypass valve components continuously — not just in rough conditions, but as a constant ambient environment.',
      'MARINECLEAN™ salt-resistant architecture addresses this environment through a defense-in-depth approach: protective epoxy coating on all external surfaces, brine rejection geometry at critical water ingress points, and corrosion-resistant internal components throughout the protection circuit.',
      'A filtration failure at sea does not get repaired in a workshop. Housing corrosion that creates bypass in a port workshop becomes a fuel contamination event mid-passage — when the vessel is days from the nearest service facility and cannot stop for emergency maintenance without charter penalties, scheduling consequences and insurance notifications that far exceed any equipment replacement cost.',
    ],
    productImageSrc: '/images/marino-taller.avif',
    productImageCaption: 'MARINECLEAN™ · SALT-RESISTANT MARINE FILTRATION SYSTEM',
    stagesHeading: 'THREE LAYERS OF MARINE CORROSION DEFENSE.',
    stages: [
      {
        number: '01',
        tag: 'LAYER 1',
        title: 'SALT RESISTANCE COATING',
        body: 'The exterior epoxy coating system applied to all MARINECLEAN™ components is formulated specifically for continuous saltwater aerosol exposure. Salt spray does not penetrate the coating system to reach underlying metal surfaces — the protection mechanism is barrier isolation, not chemical inhibition. The coating maintains integrity through the thermal cycling that marine installations experience between cold seawater ambient and diesel engine heat rejection.',
        stat: '100%',
        statLabel: 'Salt spray barrier coverage on external surfaces',
      },
      {
        number: '02',
        tag: 'LAYER 2',
        title: 'BRINE REJECTION BARRIER',
        body: 'At any point where salt water could enter the filtration circuit — tank breathers, housing seals, drain valve interfaces — MARINECLEAN™ brine rejection geometry physically prevents ingress. The brine rejection architecture operates as a one-way protection barrier: filtered fluid can drain, but seawater cannot enter against the flow path. This is particularly critical for fuel systems where seawater contamination causes microbial growth and emulsification that permanently degrades fuel quality.',
        stat: '0',
        statLabel: 'Seawater ingress events through brine rejection interfaces',
      },
      {
        number: '03',
        tag: 'LAYER 3',
        title: 'CORROSION SHIELD INTERNALS',
        body: 'Internal bypass valve components, spring elements and sealing surfaces are manufactured from corrosion-resistant materials that maintain dimensional and mechanical integrity in the event of brief salt water contact during service events or filter change intervals. The corrosion shield specification ensures that even after exposure to a marine service environment, MARINECLEAN™ bypass valve function remains within calibrated specification.',
        stat: '99%',
        statLabel: 'Internal component corrosion resistance at saltwater contact',
      },
    ],
    specs: [
      { label: 'CERTIFICATION', value: 'IMO', sub: 'International maritime organization standard' },
      { label: 'SALT RESISTANCE', value: 'FULL', sub: 'Continuous saltwater aerosol exposure rated' },
      { label: 'BRINE REJECTION', value: 'ACTIVE', sub: 'Seawater ingress prevention at all interfaces' },
      { label: 'COATING SYSTEM', value: 'EPOXY', sub: 'Marine-grade barrier protection' },
      { label: 'CORROSION SHIELD', value: '99%', sub: 'Internal component corrosion resistance' },
      { label: 'FLUID SYSTEMS', value: '2', sub: 'Fuel filtration · Hydraulic filtration' },
    ],
    applicationsHeading: 'WHERE MARINECLEAN™ PROTECTS',
    applicationsSubtext: 'MARINECLEAN™ salt-resistant protection covers all diesel fuel and hydraulic filtration applications in marine and coastal environments.',
    applications: [
      { sector: 'COMMERCIAL SHIPPING', detail: 'A bulk carrier or container vessel on a deep-sea route spends 14–30 days at sea between port calls. Any filtration failure during this period must be managed with onboard tools and spares. Commercial maritime schedules do not accommodate unplanned maintenance stops — route deviation for an emergency port call carries charter penalties and insurance notifications that begin immediately.' },
      { sector: 'HARBOR OPERATIONS', detail: 'Tugs and pilot boats dock multiple times per day. Each docking cycle exposes fuel and hydraulic components to direct saltwater splash at the waterline. Repeated wet-dry cycling is more corrosive to standard filtration materials than continuous immersion — each drying cycle leaves a concentrated salt residue that attacks surfaces until the next wetting event.' },
      { sector: 'OFFSHORE PLATFORMS', detail: 'Platform support vessels and fixed offshore installation diesel systems operate in environments where salt aerosol from wave action combines with drilling mud, process chemicals and combustion byproducts simultaneously. The chemical exposure spectrum on an offshore installation is more aggressive than coastal marine service and requires a corrosion resistance specification that addresses multiple attack vectors.' },
      { sector: 'FISHING INDUSTRY', detail: 'Commercial fishing vessels operate in remote offshore environments where the nearest port with diesel injection repair capability may be a multi-day voyage. Propulsion loss at sea is not a cost event — it is a safety event requiring emergency response. Preventive filtration integrity is measured against the consequence of its failure, not against its own cost.' },
      { sector: 'MARINE HYDRAULICS', detail: 'Shipboard hydraulic systems for crane, hatch cover and steering gear are installed in exposed deck positions where direct seawater contact during heavy sea states is routine. Filtration components in these locations are not protected from the marine environment — they are a permanent part of it, and must be specified accordingly.' },
      { sector: 'COASTAL INFRASTRUCTURE', detail: 'Shore-based power and water treatment facilities at coastal locations receive constant salt aerosol deposition from prevailing onshore winds regardless of weather conditions. Filter housings on outdoor-installed diesel backup generators at these facilities experience continuous marine-grade corrosion exposure without the inspection frequency of a crewed vessel.' },
    ],
    testimonial: {
      quote: 'Operating in the Gulf with salt spray at every sea state, our previous filters required replacement every 250 engine hours. MARINECLEAN™ salt-resistant construction extended that to 750 hours while maintaining zero contamination events in the injection system.',
      role: 'Chief Engineer',
      sector: 'Offshore Supply Vessel Fleet — 12 vessels',
    },
    ctaTag: '// IDENTIFY YOUR MARINECLEAN™ ELEMENT',
    ctaHeading: 'FIND YOUR MARINE PROTECTION',
    ctaBody: 'Cross-reference 500,000+ OEM part numbers. Identify the exact MARINECLEAN™ element for your marine or coastal application.',
  },

  microkappa: {
    categoryTag: '// CABIN AIR PROTECTION · MICROKAPPA™',
    heroTitle: 'MICROKAPPA™',
    heroSubtitle: 'ELECTROSTATIC HEPA',
    heroTagline: 'Electrostatic plus activated carbon with HEPA filtration capturing allergens, odors and particulate contamination in vehicle cabin air systems. Three-mechanism defense for occupant health protection in heavy-duty and passenger vehicle cabins.',
    heroImage: '/images/cabin-hero.avif',
    heroStats: [
      { key: 'TECHNOLOGY', value: 'ELECTROSTATIC' },
      { key: 'ODOR CONTROL', value: 'ACTIVATED CARBON' },
      { key: 'STANDARD', value: 'HEPA CLASS' },
    ],
    logoSrc: '/images/microkappa(fn).avif',
    systemHeadline: 'THREE MECHANISMS.\nZERO CONTAMINATION REACHES THE OCCUPANT.',
    systemParagraphs: [
      'Vehicle cabin air filtration is not an engine protection system — it is an occupant health protection system. The contamination targets are different: PM2.5 and PM10 particles, pollen, bacteria, diesel exhaust gases, NOx compounds, and volatile organic compounds from road and industrial sources.',
      'MICROKAPPA™ electrostatic HEPA architecture combines three capture mechanisms in a single element because no single mechanism addresses the full contamination spectrum. Electrostatic attraction targets aerosol-range particles, mechanical HEPA filtration captures larger particles, and activated carbon adsorption removes molecular contamination that particulate filtration cannot intercept.',
      'This three-mechanism approach is particularly important in heavy-duty vehicle cabins — trucks, buses, construction equipment — where operators spend full working days in the cabin and where ambient contamination levels from diesel exhaust, dust and industrial sources are significantly higher than passenger vehicle environments.',
    ],
    productImageSrc: '/images/filtro-de-cabina.avif',
    productImageCaption: 'MICROKAPPA™ · ELECTROSTATIC HEPA CABIN PROTECTION',
    stagesHeading: 'THREE PROTECTION MECHANISMS FOR OCCUPANT HEALTH.',
    stages: [
      {
        number: '01',
        tag: 'MECHANISM 1',
        title: 'ELECTROSTATIC PARTICLE ATTRACTION',
        body: 'MICROKAPPA™ electrostatic layer carries a permanent electrostatic charge that attracts aerosol-range particles — including diesel particulate matter, fine road dust and bacterial aerosols — through electrostatic attraction force rather than physical interception. Particles that would pass through a mechanical filter of the same fiber density are captured through the electrostatic mechanism, allowing MICROKAPPA™ to achieve HEPA-class particle capture without the airflow restriction that purely mechanical HEPA filtration creates in cabin HVAC systems.',
        stat: '99%',
        statLabel: 'PM2.5 particle capture efficiency at electrostatic layer',
      },
      {
        number: '02',
        tag: 'MECHANISM 2',
        title: 'ACTIVATED CARBON ODOR CONTROL',
        body: 'The activated carbon layer addresses molecular contamination — diesel exhaust gases, NOx compounds, benzene, toluene, and volatile organic compounds from adhesives, road surface treatments and industrial emissions. Carbon adsorption captures molecules at the carbon surface through van der Waals forces, removing them from the air stream before they reach the cabin interior. The activated carbon capacity is sized to maintain effective adsorption through the full recommended service interval in typical urban and industrial driving environments.',
        stat: '95%',
        statLabel: 'Molecular contaminant removal efficiency at activated carbon layer',
      },
      {
        number: '03',
        tag: 'MECHANISM 3',
        title: 'HEPA PRECISION BARRIER',
        body: 'The HEPA-class precision barrier captures larger particles — pollen, mold spores, dust mite allergens and bacteria — through mechanical interception and inertial impaction. This layer is the defense against the biological allergen fraction that causes occupant respiratory response. In agricultural vehicle cabins where pollen concentration can exceed urban ambient by orders of magnitude during harvest seasons, HEPA-class barrier protection is the difference between safe occupant conditions and occupational health exposure events.',
        stat: '99.97%',
        statLabel: 'HEPA barrier efficiency at 0.3µm particle size',
      },
    ],
    specs: [
      { label: 'ELECTROSTATIC', value: 'PERMANENT', sub: 'Charged fiber layer for aerosol capture' },
      { label: 'ACTIVATED CARBON', value: 'HIGH LOAD', sub: 'Molecular contamination adsorption' },
      { label: 'HEPA CLASS', value: '99.97%', sub: 'Particle capture at 0.3µm threshold' },
      { label: 'PM2.5 CAPTURE', value: '99%', sub: 'Fine particulate protection efficiency' },
      { label: 'ODOR REMOVAL', value: '95%', sub: 'VOC and exhaust gas molecular removal' },
      { label: 'SERVICE INTERVAL', value: 'EXTENDED', sub: 'Engineered for annual or OEM schedule' },
    ],
    applicationsHeading: 'WHERE MICROKAPPA™ PROTECTS',
    applicationsSubtext: 'MICROKAPPA™ three-mechanism protection covers every vehicle cabin type where occupant air quality is a health or operational priority.',
    applications: [
      { sector: 'HEAVY TRANSPORT', detail: 'A long-haul truck driver spends 2,000–2,500 hours per year inside a closed cab environment. At PM2.5 concentrations measured at 25–80 µg/m³ in unprotected heavy vehicle cabins, annual occupational exposure exceeds WHO safe limits within the first working month of the year. European occupational health regulations require demonstrable air quality control in commercial vehicle cabins.' },
      { sector: 'BUS & COACH', detail: 'An urban bus driver follows routes through its own exhaust recirculated from the vehicle ahead, collecting NOx and PM at every stop in heavy traffic for 8–10 hours per shift. The driver cabin is simultaneously the most exposed and the most enclosed position in the urban air quality problem the bus itself contributes to.' },
      { sector: 'AGRICULTURE', detail: 'Airborne pollen concentrations immediately around a harvesting combine can reach 500–1,000 µg/m³ — twenty to forty times the level that triggers severe allergic response in sensitized individuals. An operator forced out of the cab by allergic response during a short harvest window creates a yield loss that cannot be recovered — the harvest window does not wait for crew changes.' },
      { sector: 'CONSTRUCTION', detail: 'Respirable crystalline silica from earthworks, concrete cutting and demolition creates particles below 4 µm that deposit in deep lung tissue. Silicosis from cumulative occupational exposure is irreversible and fully attributable to work conditions. Construction equipment operators are among the highest-risk silicosis exposure groups in any industrial workforce.' },
      { sector: 'MINING', detail: 'Underground mining combines diesel exhaust, explosive detonation residue and mineral dust in a confined ventilated environment. Fine mineral dust composition varies with ore type — some ore bodies produce carcinogenic mineral fiber during drilling and blasting. The complete airborne hazard spectrum in underground operations is not addressable by mechanical filtration alone.' },
      { sector: 'PASSENGER VEHICLES', detail: 'Urban residents in cities with PM2.5 above 20 µg/m³ spend significant commute time in a vehicle where interior air quality is entirely determined by the cabin filter specification. Children and elderly passengers are disproportionately affected by PM2.5 exposure. A degraded cabin filter concentrates urban air pollution for every occupant on every trip rather than reducing it.' },
    ],
    testimonial: {
      quote: 'Driver fatigue reports dropped by 35% across our long-haul fleet after switching to MICROKAPPA™ cabin air systems. Particulate and VOC levels inside the cab are now measurably lower than outside ambient air. That is occupational health you can prove.',
      role: 'Occupational Health Director',
      sector: 'Long-Haul Logistics Operator — 200 cabs',
    },
    ctaTag: '// IDENTIFY YOUR MICROKAPPA™ ELEMENT',
    ctaHeading: 'FIND YOUR CABIN PROTECTION',
    ctaBody: 'Cross-reference 500,000+ OEM part numbers. Identify the exact MICROKAPPA™ element for your vehicle cabin specification.',
  },

};
