import { TechDetailData } from '@/components/TechDetailPage';

export const TECH_PAGES: Record<string, TechDetailData> = {

  'aquaguard-series': {
    categoryTag: '// FUEL ASSET PROTECTION · SERIES FH',
    heroTitle: 'HYDROCORE',
    heroSubtitle: '/SERIES™',
    heroTagline: 'Three-stage graduated asset protection for high-pressure fuel injection systems. Water, sediment and sub-micron contamination intercepted before they reach the injection circuit.',
    heroImage: '/images/turbine-plant.avif',
    heroStats: [
      { key: '900FH', value: '90 GPH' },
      { key: '1000FH', value: '180 GPH' },
      { key: 'ISO 16332', value: 'CERTIFIED' },
    ],
    logoSrc: '/images/Hihdrocore.avif',
    systemHeadline: 'THREE-STAGE DEFENSE.\nFULL CONTAMINATION SPECTRUM.',
    systemParagraphs: [
      'Conventional fuel filters intercept particles. HYDROCORE/SERIES™ intercepts the full contamination spectrum — particulate, free water, emulsified water and dissolved water — through a sequenced three-stage protection architecture that operates independently of fuel flow rate and back-pressure conditions.',
      'The 900FH and 1000FH models deploy HYDROCORE™ turbine rotation as the first line of defense — a passive inertial system that requires no electronic control, no actuators and no maintenance intervention. Protection begins the moment fuel enters the housing.',
      'The result: a fuel injection circuit that receives verified, clean fuel — every cycle, every hour, regardless of source fuel quality or operating conditions.',
    ],
    productImageSrc: '/images/turbine-plant.avif',
    productImageCaption: 'HYDROCORE/SERIES™ · 900FH / 1000FH',
    stagesHeading: 'EACH STAGE ELIMINATES WHAT THE PREVIOUS ONE CANNOT.',
    stages: [
      {
        number: '01',
        tag: 'STAGE 1',
        title: 'INERTIAL INTERCEPTION',
        body: 'HYDROCORE™ turbine rotation induces centrifugal momentum on incoming fuel, driving macro-particles and free water outward against the chamber wall by inertial force alone. No moving parts. Zero mechanical dependency. The intercepted mass accumulates in the sealed base chamber — permanently separated from the fuel path before the protection sequence even begins.',
        stat: '100%',
        statLabel: 'Macro-particle removal at entry',
      },
      {
        number: '02',
        tag: 'STAGE 2',
        title: 'GRADUATED COALESCENCE',
        body: 'Fuel transitions through a staggered graduated contact zone where microscopic water droplets — too small to separate by inertia alone — are forced into repeated surface contact. Each contact cycle causes droplets to merge, grow, and fall by gravity into the sealed collection chamber below. The graduated layer architecture ensures no water molecule bypasses this stage regardless of fuel pressure or flow rate.',
        stat: '99%',
        statLabel: 'Emulsified water eliminated',
      },
      {
        number: '03',
        tag: 'STAGE 3',
        title: 'HYDROCORE™ PRECISION BARRIER',
        body: 'The final HYDROCORE™ hydrophobic protection barrier intercepts sub-micron contamination and dissolved water before the fuel enters the high-pressure injection circuit. The barrier architecture repels water molecules at contact — they cannot pass through regardless of differential pressure. Available in 2, 10 and 30 micron defense ratings to match your injection system\'s exact protection requirement.',
        stat: '2µm',
        statLabel: 'Minimum precision barrier rating',
      },
    ],
    specs: [
      { label: 'MODEL 900FH', value: '90 GPH', sub: '340 LPH — Light to medium duty' },
      { label: 'MODEL 1000FH', value: '180 GPH', sub: '681 LPH — Heavy duty operations' },
      { label: 'PROTECTION RATING', value: '99%', sub: 'Water separation efficiency' },
      { label: 'BARRIER OPTIONS', value: '3', sub: '2µm · 10µm · 30µm' },
      { label: 'CERTIFICATION', value: 'ISO', sub: '16332 — Fuel/water separation standard' },
      { label: 'DRAIN SYSTEM', value: 'AUTO', sub: 'Integrated visual monitoring port' },
    ],
    applicationsHeading: 'WHERE HYDROCORE/SERIES™ PROTECTS',
    applicationsSubtext: 'FH-series turbine protection systems are validated for land-based combustion asset protection. Marine applications are served by the FM series.',
    applications: [
      { sector: 'HEAVY TRANSPORT', detail: 'Long-haul diesel fleets and common rail injection systems operating at high continuous duty cycles. The 1000FH is the designated asset protection solution for premium-class trucks with HPCR fuel systems.' },
      { sector: 'POWER GENERATION', detail: 'Stationary diesel gensets and backup power units where fuel quality directly determines operational continuity. A single contamination event can force extended maintenance shutdowns during peak demand.' },
      { sector: 'AGRICULTURE', detail: 'Tractors, combines and harvesting equipment operating in dusty, humid conditions where fuel storage tanks are exposed to condensation cycles. The 900FH extends injection system service life through each critical season.' },
      { sector: 'MINING', detail: 'Off-highway extraction equipment running 24/7 in environments where water ingress from condensation, rain and contaminated bulk fuel deliveries is a constant operational threat.' },
      { sector: 'CONSTRUCTION', detail: 'Excavators, graders and heavy machinery on demanding site cycles where fuel systems absorb contamination from multiple sources simultaneously.' },
      { sector: 'RAILWAY', detail: 'Diesel locomotives and rolling stock requiring absolute fuel circuit integrity across extreme temperature and humidity ranges over extended service intervals.' },
    ],
    testimonial: {
      quote: 'After installing 1000FH units on our port machinery fleet, diesel consumption stabilized and we eliminated three injector replacement events in a single quarter. The turbine pre-stage makes a measurable difference in hostile fuel environments.',
      role: 'Refinery Equipment Manager',
      sector: 'Port Operations — 85 units',
    },
    ctaTag: '// IDENTIFY YOUR HYDROCORE/SERIES™ SKU',
    ctaHeading: 'FIND YOUR PROTECTION SYSTEM',
    ctaBody: 'Cross-reference 500,000+ OEM part numbers. Identify the exact 900FH or 1000FH model for your asset.',
  },

  syntrax: {
    categoryTag: '// LUBRICATION ASSET PROTECTION · SYNTRAX™',
    heroTitle: 'SYNTRAX™',
    heroSubtitle: 'AI-ENGINEERED PROTECTION',
    heroTagline: 'Multi-layer lubrication protection system calibrated by AI algorithms to intercept sub-micron contamination before it reaches turbocharger bearings, crankshaft journals and precision valve train components.',
    heroImage: '/images/oil-hero.avif',
    heroStats: [
      { key: 'PROTECTION LAYERS', value: '4 ACTIVE' },
      { key: 'TECHNOLOGY', value: 'AI-CALIBRATED' },
      { key: 'TARGET', value: 'TURBO CUSTODY' },
    ],
    logoSrc: '/images/sintrax(fn).avif',
    systemHeadline: 'NOT JUST A FILTER.\nAN OIL CIRCUIT GUARDIAN.',
    systemParagraphs: [
      'Conventional oil filters rely on a single-density barrier to intercept contaminants. SYNTRAX™ deploys a four-layer protection matrix where each layer is calibrated to a specific contamination size class — from coarse metallic debris at the outer zone to sub-micron carbonaceous particles at the core barrier.',
      'The AI-engineered gradient was developed by analyzing contamination profiles across 48 engine types under heavy-duty field conditions. The result is a protection matrix that matches real-world contamination distribution, not laboratory averages.',
      'Every SYNTRAX™ element is bonded through a proprietary thermal process that eliminates layer migration under thermal cycling and high oil-flow pulsation — zero barrier displacement, zero protection gap.',
    ],
    productImageSrc: '/images/syntrax.avif',
    productImageCaption: 'SYNTRAX™ · AI-ENGINEERED LUBRICATION PROTECTION',
    stagesHeading: 'FOUR LAYERS. ZERO BYPASS.',
    stages: [
      {
        number: '01',
        tag: 'LAYER 1',
        title: 'MACRO-PARTICLE INTERCEPTION',
        body: 'The outermost protection zone targets coarse metallic debris, carbon agglomerates and particulate clusters above 40 microns. These large contaminants are intercepted at the entry surface before they can migrate inward and consume capacity from the precision inner layers. Load distribution ensures the outer layer handles the highest volume contamination fraction without restriction to oil flow.',
        stat: '40µm',
        statLabel: 'Outer zone intercept threshold',
      },
      {
        number: '02',
        tag: 'LAYER 2',
        title: 'INTERMEDIATE DENSITY GRADIENT',
        body: 'As oil penetrates the second protection zone, the gradient density progressively increases, capturing mid-range contamination between 10 and 40 microns. This layer is responsible for metallic wear particles shed by piston rings, camshaft lobes and timing components — the contamination class most correlated with bearing surface degradation. Graduated fiber architecture prevents premature blind-loading.',
        stat: '10µm',
        statLabel: 'Intermediate intercept threshold',
      },
      {
        number: '03',
        tag: 'LAYER 3',
        title: 'TURBO CUSTODY BARRIER',
        body: 'The third layer is engineered specifically for turbocharger shaft bearing protection. At 3–5 microns, contaminants that pass through layers 1 and 2 are captured in the turbo custody zone — a high-density protection band where fiber compaction and path length combine to achieve near-absolute retention. Turbocharger bearings operate on oil films measured in microns; this layer is the last defense before the oil enters the forced induction circuit.',
        stat: '3µm',
        statLabel: 'Turbo custody barrier rating',
      },
      {
        number: '04',
        tag: 'LAYER 4',
        title: 'THERMAL BONDING ANCHOR',
        body: 'A multi-layer element has a structural problem that no filter manufacturer talks about: under sustained high oil temperature and flow pulsation from combustion cycles, the layers compress and shift relative to each other. When that happens, gaps form between layers — bypass paths that didn\'t exist in the new element. By 5,000 km you no longer have 4 discrete protection layers working as designed. You have a compressed mass with voids. SYNTRAX™ thermal bonding anchors every layer to fixed position at manufacture. The protection geometry on day 1 is identical on the day of change. No progressive degradation. No gap formation. The filter you install is the filter that comes out.',
        stat: '100%',
        statLabel: 'Layer position integrity across full service interval',
      },
    ],
    specs: [
      { label: 'PROTECTION LAYERS', value: '4', sub: 'AI-calibrated density gradient matrix' },
      { label: 'OUTER INTERCEPT', value: '40µm', sub: 'Macro-particle entry zone' },
      { label: 'TURBO CUSTODY', value: '3µm', sub: 'Precision turbocharger barrier' },
      { label: 'BONDING PROCESS', value: 'THERMAL', sub: 'Zero-migration layer lock' },
      { label: 'OIL COMPATIBILITY', value: '100%', sub: 'Mineral · Synthetic · Semi-synthetic' },
      { label: 'BYPASS VALVE', value: 'ZERO', sub: 'No unfiltered oil bypass under rated pressure' },
    ],
    applicationsHeading: 'WHERE SYNTRAX™ PROTECTS',
    applicationsSubtext: 'SYNTRAX™ protection matrix is validated for turbocharged and naturally aspirated engines across all duty cycles and oil grades.',
    applications: [
      { sector: 'HEAVY TRANSPORT', detail: 'Long-haul diesel engines operating at sustained high RPM and thermal load cycles. SYNTRAX™ turbo custody layer is the critical barrier between field contamination and a high-cost turbocharger replacement event.' },
      { sector: 'POWER GENERATION', detail: 'Stationary genset engines running continuous base-load duty where oil contamination builds progressively between extended service intervals. The four-layer matrix maintains consistent protection throughout the full change period.' },
      { sector: 'AGRICULTURE', detail: 'Seasonal-use engines subject to extended shutdown periods and moisture ingress. The SYNTRAX™ outer layer captures the high-particle-load first-start contamination spike common in agricultural equipment after dormancy.' },
      { sector: 'MINING', detail: 'Off-highway equipment operating in extreme particulate environments where engine oil contamination rates far exceed on-road duty cycles. Extended capacity outer layers delay restriction onset in high-dust operation.' },
      { sector: 'CONSTRUCTION', detail: 'Excavators and graders running continuous multi-shift operations where oil sampling between intervals is impractical. The progressive density gradient builds contamination capacity gradually, extending the safe service interval.' },
      { sector: 'INDUSTRIAL', detail: 'Compressors and industrial prime movers where bearing clearances are tightly toleranced and any contamination migration to the lubrication circuit causes measurable performance degradation.' },
    ],
    labResults: [
      { test: 'Multi-Pass Filtration Efficiency', standard: 'ISO 4548-12', result: '99.7', unit: '%' },
      { test: 'Dirt Holding Capacity', standard: 'ISO 4548-12', result: '42.8', unit: 'g' },
      { test: 'Collapse Pressure Rating', standard: 'ISO 4548-7', result: '≥ 20', unit: 'bar' },
      { test: 'Layer Migration Resistance', standard: 'ELIMFILTERS®-LT-01', result: '0', unit: 'events / 500h' },
      { test: 'Turbo Bearing Contamination', standard: 'SAE J1858', result: '< 3', unit: 'µm pass-through' },
    ],
    testimonial: {
      quote: 'After switching to SYNTRAX™ across our 140-unit fleet, turbocharger replacements dropped by 67% in 18 months. The four-layer architecture is the only explanation — our duty cycles and fuel quality didn\'t change.',
      role: 'Fleet Maintenance Director',
      sector: 'Long-Haul Transport Operator — 140 units',
    },
    ctaTag: '// IDENTIFY YOUR SYNTRAX™ ELEMENT',
    ctaHeading: 'FIND YOUR ENGINE PROTECTION',
    ctaBody: 'Cross-reference 500,000+ OEM part numbers. Identify the exact SYNTRAX™ element for your engine specification.',
  },

  nanoforce: {
    categoryTag: '// HYDRAULIC ASSET PROTECTION · NANOFORCE™',
    heroTitle: 'NANOFORCE™',
    heroSubtitle: 'HYDRAULIC PRECISION GUARD',
    heroTagline: 'Multi-layer protection architecture engineered for high-pressure hydraulic asset defense. Vapor control and structural integrity systems that maintain protection performance under sustained high-pressure pulsation cycles.',
    heroImage: '/images/syntrapore-hero.avif',
    heroStats: [
      { key: 'ARCHITECTURE', value: 'MULTI-LAYER' },
      { key: 'VAPOR CONTROL', value: 'ACTIVE' },
      { key: 'STRUCTURAL', value: 'HIGH-PRESSURE' },
    ],
    logoSrc: '/images/nanoforce(fn).avif',
    systemHeadline: 'HIGH-PRESSURE HYDRAULIC\nCIRCUIT PROTECTION.',
    systemParagraphs: [
      'Hydraulic systems are the most contamination-sensitive circuits in any mobile or stationary machine. Hydraulic control valves, pumps and actuators operate on tolerances measured in single-digit microns — any contamination that bypasses filtration accelerates wear exponentially, not linearly.',
      'NANOFORCE™ multi-layer protection architecture is engineered specifically for the hydraulic circuit operating environment: high and variable pressure, temperature cycling from ambient to 85°C operating, and continuous flow pulsation from pump cycles that mechanically stress filter elements in ways that static test conditions do not capture.',
      'Vapor control technology embedded in the NANOFORCE™ protection matrix addresses the hydraulic contamination source that conventional filters ignore — the vapor phase water and dissolved gas that forms free-phase contamination when hydraulic fluid temperature changes under load.',
    ],
    productImageSrc: '/images/hidraulic.avif',
    productImageCaption: 'NANOFORCE™ · HYDRAULIC PRECISION GUARD ELEMENT',
    stagesHeading: 'THREE LAYERS FOR HIGH-PRESSURE HYDRAULIC INTEGRITY.',
    stages: [
      {
        number: '01',
        tag: 'LAYER 1',
        title: 'MULTI-LAYER GUARD',
        body: 'The outer protection layer intercepts large metallic particles, rubber degradation products from hydraulic seals, and polymer contamination from hose liner breakdown. These contamination types are characteristic of hydraulic circuit aging and are the primary cause of valve spool scoring and pump gear wear. The guard layer capacity is sized for extended operation between hydraulic fluid service intervals.',
        stat: '100%',
        statLabel: 'Macro-contamination interception at entry zone',
      },
      {
        number: '02',
        tag: 'LAYER 2',
        title: 'VAPOR CONTROL BARRIER',
        body: 'The vapor control layer addresses dissolved water and entrained vapor contamination in hydraulic fluid — the invisible contamination that conventional hydraulic filters do not address. When hydraulic systems cycle between ambient and operating temperature, dissolved water in the fluid transitions to free-phase micro-droplets that cause control valve stiction and pump cavitation. The vapor control layer coalesces and captures this phase-transition water before it accumulates in critical actuator circuits.',
        stat: '99%',
        statLabel: 'Dissolved water capture at vapor control layer',
      },
      {
        number: '03',
        tag: 'LAYER 3',
        title: 'STRUCTURAL INTEGRITY CORE',
        body: 'The innermost structural integrity layer is the NANOFORCE™ precision barrier and element backbone simultaneously. It achieves sub-micron particle interception while providing the anti-collapse structural support that prevents protection layer compression under high-flow pulsation events. The structural core maintains full element geometry under cold-start high-viscosity flow surges that can collapse conventional hydraulic filter elements and bypass filtration entirely.',
        stat: '3µm',
        statLabel: 'Structural core precision barrier rating',
      },
    ],
    specs: [
      { label: 'PROTECTION LAYERS', value: '3', sub: 'Guard · Vapor control · Structural core' },
      { label: 'PRECISION BARRIER', value: '3µm', sub: 'Structural core intercept rating' },
      { label: 'VAPOR CONTROL', value: 'ACTIVE', sub: 'Dissolved water phase-transition capture' },
      { label: 'OPERATING PRESSURE', value: 'HIGH', sub: 'Rated for continuous pulsation cycles' },
      { label: 'FLUID COMPATIBILITY', value: 'ALL', sub: 'Mineral · Synthetic · Bio-hydraulic fluids' },
      { label: 'ANTI-COLLAPSE', value: '100%', sub: 'Cold-start viscosity surge rated structure' },
    ],
    applicationsHeading: 'WHERE NANOFORCE™ PROTECTS',
    applicationsSubtext: 'NANOFORCE™ hydraulic asset defense covers every hydraulic circuit type from mobile equipment to industrial fixed installations.',
    applications: [
      { sector: 'CONSTRUCTION', detail: 'Excavators, hydraulic hammers and heavy lifting equipment where hydraulic contamination is the primary driver of control valve replacement costs. NANOFORCE™ vapor control layer addresses the water ingress issue that accelerates degradation in equipment operating in high-humidity environments.' },
      { sector: 'AGRICULTURE', detail: 'Combine harvesters and tractors with hydraulic implement control circuits that must maintain precise flow control for variable rate applications. Sub-3-micron protection at the structural core maintains valve spool clearance integrity throughout the service season.' },
      { sector: 'MINING', detail: 'Hydraulic excavators and rock drills operating at sustained high cycle rates where pump and valve contamination wear is the dominant maintenance cost driver. NANOFORCE™ multi-layer protection extends hydraulic pump life and reduces unplanned maintenance events.' },
      { sector: 'MANUFACTURING', detail: 'Industrial hydraulic presses and CNC machining center hydraulic systems where positioning accuracy depends on valve spool cleanliness. Sub-3-micron filtration at the structural core is the industry standard for precision manufacturing hydraulic circuits.' },
      { sector: 'MARINE', detail: 'Shipboard hydraulic systems for steering gear, crane and hatch cover control where saltwater vapor ingress through reservoir breathers creates the dissolved water contamination that the NANOFORCE™ vapor control layer specifically addresses.' },
      { sector: 'POWER GENERATION', detail: 'Turbine governor and control hydraulic systems where contamination-induced control valve stiction can cause load rejection events with significant operational and grid stability consequences.' },
    ],
    testimonial: {
      quote: 'Our excavators were experiencing control valve wear every 2,000 hours. After switching to NANOFORCE™ hydraulic protection, the last fleet inspection showed zero scoring at 4,500 hours. The vapor control layer is what our previous filters were missing.',
      role: 'Equipment Superintendent',
      sector: 'Open-Pit Mining Operation — 48 machines',
    },
    ctaTag: '// IDENTIFY YOUR NANOFORCE™ ELEMENT',
    ctaHeading: 'FIND YOUR HYDRAULIC PROTECTION',
    ctaBody: 'Cross-reference 500,000+ OEM part numbers. Identify the exact NANOFORCE™ element for your hydraulic system specification.',
  },

  macrocore: {
    categoryTag: '// AIR ASSET PROTECTION · MACROCORE™',
    heroTitle: 'MACROCORE™',
    heroSubtitle: 'PDG ARCHITECTURE',
    heroTagline: 'Every contaminant that bypasses air intake reaches cylinder bores and turbocharger bearings without further interception. MACROCORE™ PDG distributes contamination load across three calibrated density zones — eliminating the surface-loading failure mode that leaves conventional elements 40–60% unused at service change.',
    heroImage: '/images/mecanica-air.avif',
    heroStats: [
      { key: 'CAPTURE EFF.', value: '99.98%' },
      { key: 'ANTI-COLLAPSE', value: '427 kPa' },
      { key: 'DUST CAPACITY', value: '480 g/m²' },
    ],
    logoSrc: '/images/macrocore(fn).avif',
    systemHeadline: 'NOT A SURFACE BARRIER.\nA FULL-DEPTH PROTECTION MATRIX.',
    systemParagraphs: [
      'Conventional single-density air filter elements share a common failure mode: they load from the surface inward. As the upstream face accumulates dust and particles, restriction builds exponentially — but the interior capacity of the element remains largely unused. The element reaches its service restriction threshold while retaining 40–60% of its theoretical contamination capacity unused. The result is premature replacement events, increased service frequency and turbocharged engine restriction starvation during extended field operations.',
      'MACROCORE™ Progressive Density Gradient (PDG) reverses this failure mode through a three-zone fiber architecture that precisely matches fiber density to particle size distribution in real-world air contamination profiles. The open-architecture outer zone captures the bulk mass fraction of macro-particles without restriction. The gradient transition matrix captures mid-range contamination across five progressive density steps. The precision diffusion core addresses sub-micron particles through Brownian motion contact — the capture mechanism that inertial-only designs cannot reach. Contamination load distributes through the full protection depth, not at the entry surface alone.',
      'Air intake protection also carries a structural requirement absent from oil or fuel filtration: the element must resist vacuum collapse during boost-cycle pressure transients. MACROCORE™ anti-collapse construction and equidistant pleat geometry maintain full protection geometry under the highest differential pressures any turbocharged engine can generate — ensuring no bypass channel opens as restriction builds across the service interval.',
    ],
    productImageSrc: '/images/mecanico-jd.avif',
    productImageCaption: 'MACROCORE™ · PROGRESSIVE DENSITY GRADIENT AIR PROTECTION',
    stagesHeading: 'THREE DENSITY ZONES. ZERO SURFACE-LOADING FAILURE.',
    stages: [
      {
        number: '01',
        tag: 'OUTER ZONE',
        title: 'BULK-LOAD INTERCEPTION',
        body: 'The outer protection zone is engineered with a high void-volume open fiber architecture that intercepts macro-particles — coarse dust, soil aggregates, crop residue and large carbon particles above 20 microns — without creating measurable restriction to airflow. By capturing the high-mass contamination fraction at the entry zone, the outer layer prevents premature surface loading of the gradient and core layers. This is the capacity amplifier: stripping out 80–90% of the contamination mass volume at entry and distributing usable service life across the full protection depth rather than concentrating load at the element face.',
        stat: '>20µm',
        statLabel: 'Bulk-load interception threshold',
      },
      {
        number: '02',
        tag: 'MID-ZONE',
        title: 'GRADIENT TRANSITION MATRIX',
        body: 'The gradient transition matrix is where MACROCORE™ PDG engineering is most technically precise. Five sequential density steps within a single zone create a continuously increasing capture efficiency band from 5 to 20 micron particle sizes — without the bypass channels that form at abrupt step-change density boundaries in conventional layered designs. Fine silica dust, road surface particulate, agricultural fine particles and combustion byproducts in this size range are the primary contributors to piston ring wear and cylinder bore abrasion. The gradient matrix captures them progressively without restriction accumulation at any single density boundary — the mechanism that makes premature restriction failure physically impossible in this zone.',
        stat: '5–20µm',
        statLabel: 'Gradient matrix capture range',
      },
      {
        number: '03',
        tag: 'CORE BARRIER',
        title: 'DUAL-MECHANISM DIFFUSION CORE',
        body: 'The precision core barrier deploys two capture mechanisms that address different particle physics simultaneously. Inertial impaction captures particles above 1 micron with sufficient mass to deviate from air streamlines and contact fiber surfaces. Diffusion capture — Brownian motion contact — addresses sub-micron particles too light for inertial deviation, forcing random-walk contact with the high-density core fiber matrix. This dual-mechanism architecture closes the sub-micron capture gap that single-mechanism barriers leave open — the gap that allows the smallest, sharpest abrasive particles to pass directly into turbocharger compressor stages and combustion chambers. Anti-collapse construction rated for 427 kPa ensures core geometry remains intact under the highest vacuum conditions any turbocharged engine can generate at rated boost.',
        stat: '99.98%',
        statLabel: 'Dual-mechanism capture efficiency at rated airflow',
      },
    ],
    specs: [
      { label: 'PDG EFFICIENCY', value: '99.98%', sub: 'ISO 5011 single-pass — rated airflow conditions' },
      { label: 'ANTI-COLLAPSE', value: '427 kPa', sub: '62 PSI differential pressure structural rating' },
      { label: 'DUST CAPACITY', value: '480 g/m²', sub: 'ISO 5011 — total dirt holding capacity' },
      { label: 'CLEAN RESTRICTION', value: '<1.5 kPa', sub: 'New element airflow resistance at rated flow' },
      { label: 'THERMAL RATING', value: '120°C', sub: 'Continuous — turbo inlet temperature rated' },
      { label: 'CERTIFICATION', value: 'ISO 5011', sub: 'SAE J726 · ASTM D202 compliant' },
    ],
    labResults: [
      { test: 'Single-Pass Filtration Efficiency', standard: 'ISO 5011', result: '99.98', unit: '%' },
      { test: 'Dust Holding Capacity', standard: 'ISO 5011', result: '480', unit: 'g/m²' },
      { test: 'Anti-Collapse Differential Pressure', standard: 'ISO 5011', result: '≥ 427', unit: 'kPa' },
      { test: 'Clean Element Airflow Restriction', standard: 'ISO 5011', result: '< 1.5', unit: 'kPa' },
      { test: 'Thermal Stability (Continuous)', standard: 'ELIMFILTERS®-AT-02', result: '120', unit: '°C' },
    ],
    applicationsHeading: 'WHERE MACROCORE™ PROTECTS',
    applications: [
      { sector: 'HEAVY TRANSPORT', detail: 'Turbocharged diesel engines operating at continuous high airflow demand. The MACROCORE™ anti-collapse structure protects against vacuum events during turbo boost transition cycles — the pressure differential condition that collapses conventional filter elements and opens unfiltered air bypass paths directly to turbocharger compressor blades and intercooler circuits.' },
      { sector: 'MINING', detail: '24/7 off-highway extraction equipment in silica-heavy dust environments where intake contamination rates can exceed 10× on-road benchmarks. PDG full-depth loading distributes the sustained high contamination mass flux that would surface-load and restrict conventional single-density elements within hours of service start.' },
      { sector: 'AGRICULTURE', detail: 'Combines and tractors operating in simultaneous fine soil dust and coarse crop residue — a dual contamination challenge that single-density elements cannot handle efficiently. MACROCORE™ bulk-load outer zone captures the coarse crop residue fraction without restriction; the gradient core captures the fine silica soil fraction that survives pre-cleaning and reaches the engine.' },
      { sector: 'POWER GENERATION', detail: 'Stationary industrial prime movers and gas compressors where any air intake bypass event causes direct abrasive cylinder wear. PDG full-depth loading extends service intervals and reduces planned maintenance shutdowns — critical for base-load power units where offline time carries direct operational cost consequences.' },
      { sector: 'CONSTRUCTION', detail: 'Excavators, bulldozers and motor graders on earthwork sites where respirable silica dust is the dominant contamination challenge. The diffusion-capture core intercepts sub-5-micron silica fractions that pass through inertial pre-cleaners — preventing the progressive bore wear that is the leading cause of early overhaul in construction equipment engines.' },
      { sector: 'INDUSTRIAL', detail: 'Compressors and high-flow industrial blowers where inlet air cleanliness determines service life of precision rotary components. MACROCORE™ equidistant pleat geometry provides uniform airflow across the full element face — eliminating restriction variance and media channeling that develops in variable-pleat-spacing designs under progressive contamination load.' },
    ],
    testimonial: {
      quote: 'We run 220 units in coal dust — the most abrasive air intake environment we operate in. MACROCORE™ extended air filter service intervals by 40% compared to our previous OEM elements. Zero bypass events recorded across two full service cycles. Cylinder bore wear measurements at major overhaul confirmed measurable improvement. This is real engineering, not specification sheet claims.',
      role: 'Fleet Maintenance Manager',
      sector: 'Coal Handling Terminal — 220 units',
    },
    ctaTag: '// IDENTIFY YOUR MACROCORE™ ELEMENT',
    ctaHeading: 'FIND YOUR AIR PROTECTION',
    ctaBody: 'Cross-reference 500,000+ OEM part numbers. Identify the exact MACROCORE™ element for your engine or compressor specification.',
  },

  intekcore: {
    categoryTag: '// HEAVY-DUTY HOUSING SYSTEMS · INTEKCORE™',
    heroTitle: 'INTEKCORE™',
    heroSubtitle: 'FILTER HOUSING SYSTEMS',
    heroTagline: 'Engineered filter housing systems for heavy-duty trucks and industrial machinery. High-pressure rated, OEM-compatible housings that protect critical engine circuits across the most demanding operational environments.',
    heroImage: '/images/mecanica-air.avif',
    heroStats: [
      { key: 'RATED PRESSURE', value: 'HIGH-PSI' },
      { key: 'COMPATIBILITY', value: 'OEM-FIT' },
      { key: 'ENVIRONMENT', value: 'HEAVY-DUTY' },
    ],
    logoSrc: '/images/intekcore(fn).avif',
    systemHeadline: 'THE HOUSING IS NOT\nA PASSIVE COMPONENT.',
    systemParagraphs: [
      'In heavy-duty truck and machinery applications, the filter housing defines the reliability boundary of the entire filtration system. A compromised housing — through corrosion, thread wear, bypass valve failure or seal degradation — neutralizes the protection value of the filter element it contains. INTEKCORE™ housing systems are engineered so the housing never becomes the failure point.',
      'Constructed from high-grade materials rated for continuous high-pressure operation, INTEKCORE™ housings maintain structural integrity across the full thermal cycling range of heavy commercial and industrial engines — from cold starts in extreme climates to sustained high-load thermal conditions in mining and construction operations.',
      'Universal mounting geometry and OEM-compatible thread standards make INTEKCORE™ housings direct-fit replacements across major truck and machinery platforms. No fabrication. No adapter plates. No serviceability compromise.',
    ],
    productImageSrc: '/images/mecanica-air.avif',
    productImageCaption: 'INTEKCORE™ · HEAVY-DUTY FILTER HOUSING SYSTEMS',
    stagesHeading: 'THREE ENGINEERING PRINCIPLES FOR HOUSING RELIABILITY.',
    stages: [
      {
        number: '01',
        tag: 'PRINCIPLE 1',
        title: 'HIGH-PRESSURE STRUCTURAL INTEGRITY',
        body: 'INTEKCORE™ housing bodies are rated for the peak pressure spikes that occur during cold-start conditions in heavy diesel applications — when oil viscosity creates instantaneous pressure surges that can stress inferior housing materials beyond their elastic limit. The housing wall geometry distributes burst load across the full structure rather than concentrating stress at the thread interface or bypass valve seat, eliminating the fracture failure mode that makes low-cost housings a liability in high-value asset operations.',
        stat: 'HIGH',
        statLabel: 'Burst pressure rating above standard housing specifications',
      },
      {
        number: '02',
        tag: 'PRINCIPLE 2',
        title: 'CORROSION-RESISTANT CONSTRUCTION',
        body: 'Trucks and machinery operating in agriculture, mining, construction and marine-adjacent environments expose filter housings to chemical contamination, humidity cycling, fertilizer residue, salt and abrasive particulate that accelerates corrosion on conventional steel housings. INTEKCORE™ material selection and surface treatment maintains housing integrity across multi-year service cycles — preventing the external degradation that leads to thread seizure, bypass valve sticking and catastrophic seal failure during element replacement.',
        stat: '100%',
        statLabel: 'Seal integrity maintained across full service cycle',
      },
      {
        number: '03',
        tag: 'PRINCIPLE 3',
        title: 'PRECISION SEAL ARCHITECTURE',
        body: 'The INTEKCORE™ sealing system is engineered for heavy commercial torque cycles — the repeated high-torque installation and removal that characterizes fleet workshop maintenance. Seal groove geometry maintains O-ring compression within specification across the full range of technician-applied torque variation, preventing the under-seal bypass events that occur when housings are installed to different torque standards across a mixed crew maintenance environment.',
        stat: '0',
        statLabel: 'Bypass events within rated torque installation range',
      },
    ],
    specs: [
      { label: 'CONSTRUCTION', value: 'HD-GRADE', sub: 'High-pressure rated housing material' },
      { label: 'SEAL SYSTEM', value: 'PRECISION', sub: 'Torque-tolerant O-ring groove geometry' },
      { label: 'BYPASS VALVE', value: 'INTEGRATED', sub: 'Rated bypass valve, factory calibrated' },
      { label: 'THREAD STANDARD', value: 'OEM-FIT', sub: 'Compatible with major truck & machinery platforms' },
      { label: 'SURFACE TREATMENT', value: 'ANTI-CORR', sub: 'Corrosion-resistant for harsh environments' },
      { label: 'SERVICE ACCESS', value: 'TOOL-FIT', sub: 'Standard service tooling, no special equipment' },
    ],
    applicationsHeading: 'WHERE INTEKCORE™ HOUSING SYSTEMS OPERATE',
    applicationsSubtext: 'INTEKCORE™ housing systems are the structural foundation for filter protection on heavy trucks, off-highway machinery and industrial power units.',
    applications: [
      { sector: 'HEAVY TRUCKS', detail: 'Long-haul and regional heavy commercial trucks operating on demanding freight cycles. INTEKCORE™ housings withstand the vibration, pressure cycling and temperature variation of continuous highway operation without developing the micro-leaks that degrade filter performance between service intervals.' },
      { sector: 'CONSTRUCTION MACHINERY', detail: 'Excavators, bulldozers, graders and crane systems operating in dusty, chemically aggressive environments. Housing corrosion resistance is critical when equipment is washed down with chemical cleaners or operates adjacent to concrete, lime or fertilizer contamination sources.' },
      { sector: 'MINING EQUIPMENT', detail: 'Off-highway extraction equipment running 24/7 in remote sites where housing failure forces extended downtime. INTEKCORE™ structural ratings ensure housing integrity across the extreme pressure and thermal cycles of continuous mining operation.' },
      { sector: 'AGRICULTURE', detail: 'Tractors, combines and harvesters exposed to fertilizer, pesticide and agricultural chemical contamination that corrodes standard housings. INTEKCORE™ corrosion-resistant construction extends housing service life across multi-season agricultural operation.' },
      { sector: 'BUS & COACH FLEETS', detail: 'Urban transit and long-distance coach fleets requiring high service frequency without housing degradation. INTEKCORE™ thread integrity ensures reliable element replacement across high-cycle workshop maintenance operations.' },
      { sector: 'INDUSTRIAL POWER UNITS', detail: 'Stationary and mobile industrial power generation and hydraulic systems where housing reliability directly determines operational continuity. INTEKCORE™ precision seal architecture prevents the bypass leakage that contaminates hydraulic circuits and engine oil systems.' },
    ],
    testimonial: {
      quote: 'Housing failures were our number one unplanned maintenance item. Since standardizing on INTEKCORE™ housings across our truck fleet, we have had zero seal failures and zero contamination bypass events in 14 months of full fleet operation.',
      role: 'Regional Fleet Director',
      sector: 'Heavy Transport Operator — 310 units',
    },
    ctaTag: '// IDENTIFY YOUR INTEKCORE™ HOUSING',
    ctaHeading: 'FIND YOUR HOUSING SYSTEM',
    ctaBody: 'Cross-reference 500,000+ OEM part numbers. Identify the exact INTEKCORE™ housing for your truck or machinery platform.',
  },

  syntepore: {
    categoryTag: '// FUEL ASSET PROTECTION · SYNTEPORE™',
    heroTitle: 'SYNTEPORE™',
    heroSubtitle: 'PRECISION INJECTOR GUARD',
    heroTagline: 'Progressive multi-layer protection architecture intercepting sub-micron contamination before it reaches Common Rail injectors. The last line of defense for high-pressure fuel injection systems operating above 2,000 bar.',
    heroImage: '/images/nanoforce.avif',
    heroStats: [
      { key: 'BARRIER RATING', value: '4 MICRON' },
      { key: 'PROTECTION', value: 'ZERO MIGRATION' },
      { key: 'TARGET', value: 'INJECTOR DEFENSE' },
    ],
    logoSrc: '/images/syntapore(fn).avif',
    systemHeadline: 'THE INJECTOR\'S\nFINAL GUARDIAN.',
    systemParagraphs: [
      'Common Rail injection systems operate at pressures exceeding 2,000 bar. At this pressure, a contamination particle as small as 4 microns can score injector needle seats and destroy the precision tolerances that control injection timing and fuel atomization quality.',
      'SYNTEPORE™ is engineered as the terminal protection layer between the fuel supply system and the injection circuit. Where pre-filters handle bulk contamination, SYNTEPORE™ eliminates the residual sub-micron fraction — the particles that conventional filtration misses and that HPCR systems cannot tolerate.',
      'Progressive layer architecture ensures that contamination load is distributed across the protection matrix — preventing premature single-point restriction and extending the service interval beyond standard fuel filter benchmarks.',
    ],
    productImageSrc: '/images/nanoforce (2).avif',
    productImageCaption: 'SYNTEPORE™ · PRECISION INJECTOR GUARD ELEMENT',
    stagesHeading: 'THREE PROGRESSIVE LAYERS. ABSOLUTE INJECTOR DEFENSE.',
    stages: [
      {
        number: '01',
        tag: 'LAYER 1',
        title: 'PROGRESSIVE CAPTURE ZONE',
        body: 'The outer protection layer intercepts particles from 40 microns down to 10 microns in a graduated capture architecture that distributes contamination load evenly across the filter surface. This zone prevents premature restriction at entry points and ensures full utilization of the protection matrix capacity across the service interval. Water droplets and gel contaminants are also intercepted at this stage before reaching the precision barrier.',
        stat: '40µm',
        statLabel: 'Progressive capture zone entry threshold',
      },
      {
        number: '02',
        tag: 'LAYER 2',
        title: 'INTERMEDIATE PROTECTION BAND',
        body: 'The intermediate layer targets contamination between 10 and 4 microns — the particle size range most directly correlated with injector needle wear and spool valve erosion in HPCR systems. Fiber architecture in this zone is calibrated for maximum surface contact time, ensuring even fine particles in suspension do not migrate through to the precision barrier with sufficient velocity to cause impact damage.',
        stat: '4µm',
        statLabel: 'Intermediate band capture threshold',
      },
      {
        number: '03',
        tag: 'LAYER 3',
        title: 'ZERO MIGRATION BARRIER',
        body: 'The innermost layer is the SYNTEPORE™ zero migration barrier — a high-compaction protection surface designed to achieve absolute retention of any particle that reaches it from layers 1 and 2. Zero migration means no particle above 4 microns exits the element and enters the injection rail under any operating pressure or flow condition. The barrier is structurally reinforced to withstand cold-start fuel viscosity spikes without bypass.',
        stat: '0',
        statLabel: 'Particles above 4µm passing the zero migration barrier',
      },
    ],
    specs: [
      { label: 'PRECISION BARRIER', value: '4µm', sub: 'Absolute retention at terminal layer' },
      { label: 'PROGRESSIVE LAYERS', value: '3', sub: 'Load-distributed protection matrix' },
      { label: 'INJECTION RATED', value: 'HPCR', sub: '2,000+ bar system compatibility' },
      { label: 'WATER INTERCEPT', value: 'STAGE 1', sub: 'Free and emulsified water capture' },
      { label: 'BYPASS', value: 'ZERO', sub: 'No bypass under rated operating pressure' },
      { label: 'SERVICE INTERVAL', value: 'EXTENDED', sub: 'Progressive loading extends service life' },
    ],
    applicationsHeading: 'WHERE SYNTEPORE™ PROTECTS',
    applicationsSubtext: 'SYNTEPORE™ is the designated precision protection element for any diesel system where fuel injection tolerances demand sub-4-micron cleanliness.',
    applications: [
      { sector: 'HEAVY TRANSPORT', detail: 'Euro IV–VI compliant long-haul diesel engines with Common Rail systems where injection pressure exceeds 1,800 bar. SYNTEPORE™ is the terminal protection element preventing contamination-induced injector replacement events on high-value power units.' },
      { sector: 'POWER GENERATION', detail: 'Critical standby gensets and base-load generators where fuel quality cannot be guaranteed from bulk delivery sources. SYNTEPORE™ terminal filtration ensures injection system integrity regardless of supply fuel contamination.' },
      { sector: 'AGRICULTURE', detail: 'Modern precision agricultural machinery with electronically controlled injection systems. A single contamination event can disable variable rate injection functionality mid-season — SYNTEPORE™ prevents the scenario.' },
      { sector: 'MINING', detail: 'Off-highway diesel equipment in remote extraction sites where service parts availability is limited and injection system failures create extended production stoppages. SYNTEPORE™ extends the viable service interval beyond conventional fuel filter specifications.' },
      { sector: 'CONSTRUCTION', detail: 'High-value construction equipment with Tier 4 Final emissions-compliant engines that require absolute fuel system cleanliness to maintain SCR and DPF integrity alongside injection performance.' },
      { sector: 'RAILWAY', detail: 'Diesel-electric locomotive fuel systems where long service intervals and diverse bulk fuel sources demand terminal protection that conventional fuel filtration cannot guarantee.' },
    ],
    testimonial: {
      quote: 'Our HPCR injection system was generating one injector failure per 60,000 kilometers on average. With SYNTEPORE™ inline protection, we passed 180,000 kilometers on the test fleet with zero injection events. The sub-micron barrier is the difference.',
      role: 'Technical Director',
      sector: 'Commercial Fleet — Long-Haul Division',
    },
    ctaTag: '// IDENTIFY YOUR SYNTEPORE™ ELEMENT',
    ctaHeading: 'FIND YOUR INJECTOR PROTECTION',
    ctaBody: 'Cross-reference 500,000+ OEM part numbers. Identify the exact SYNTEPORE™ element for your fuel injection system specification.',
  },

  aquaguard: {
    categoryTag: '// WATER SEPARATION TECHNOLOGY · HYDROCORE™',
    heroTitle: 'HYDROCORE™',
    heroSubtitle: 'WATER SEPARATOR',
    heroTagline: 'Hydrophobic protection technology achieving 99.8% water separation efficiency from fuel systems. Three-phase water interception — free, emulsified and dissolved — before contamination reaches the injection circuit.',

    heroImage: '/images/turbine-1.avif',
    heroStats: [
      { key: 'EFFICIENCY', value: '99.8%' },
      { key: 'BARRIER TYPE', value: 'HYDROPHOBIC' },
      { key: 'PROTECTION', value: 'WATER REPULSION' },
    ],
    logoSrc: '/images/Hihdrocore.avif',
    systemHeadline: 'HYDROPHOBIC DEFENSE.\nWATER CANNOT PASS.',
    systemParagraphs: [
      'Water contamination in fuel systems operates across three phases: free water that settles and can be drained, emulsified water suspended in micro-droplets that conventional filters cannot intercept, and dissolved water that forms free phase when temperature changes. Each phase causes a different failure mode — microbial growth, injector corrosion, and cavitation erosion respectively.',
      'HYDROCORE™ hydrophobic technology addresses all three phases through a sequenced interception architecture where each protection layer is engineered for a specific water contamination state. The result is 99.8% water separation efficiency — validated across the full operating temperature and fuel flow range.',
      'The HYDROCORE™ collection chamber operates as a sealed reservoir that permanently removes intercepted water from the fuel circuit. Integrated visual monitoring port allows service technicians to assess water accumulation without element removal.',
    ],
    productImageSrc: '/images/fuelseparator.avif',
    productImageCaption: 'HYDROCORE™ · WATER SEPARATION PROTECTION TECHNOLOGY',
    stagesHeading: 'THREE PHASES OF WATER. ONE PROTECTION SYSTEM.',
    stages: [
      {
        number: '01',
        tag: 'PHASE 1',
        title: 'FREE WATER COLLECTION',
        body: 'Free water — the bulk water phase that separates from fuel by gravity — is intercepted at the entry stage by the HYDROCORE™ collection geometry. Incoming fuel flow is directed past the collection chamber where free water masses are diverted by density differential and captured in the sealed reservoir below. This stage removes the contamination fraction most likely to cause immediate microbial growth and corrosion in the fuel system.',
        stat: '100%',
        statLabel: 'Free water phase interception at entry stage',
      },
      {
        number: '02',
        tag: 'PHASE 2',
        title: 'EMULSIFIED WATER COALESCENCE',
        body: 'Emulsified water — suspended as micro-droplets too small for gravity separation — is captured through the HYDROCORE™ coalescence architecture. The hydrophilic contact surface causes micro-droplets to coalesce on contact, growing until they achieve sufficient mass to fall by gravity into the sealed collection chamber. The graduated contact geometry ensures repeated droplet surface contact regardless of fuel flow velocity or emulsification degree.',
        stat: '99.8%',
        statLabel: 'Combined water separation efficiency rating',
      },
      {
        number: '03',
        tag: 'PHASE 3',
        title: 'HYDROCORE™ HYDROPHOBIC BARRIER',
        body: 'The precision hydrophobic barrier is the terminal protection layer against dissolved water and residual micro-droplet contamination. The hydrophobic surface architecture physically repels water molecules at contact — fuel molecules pass through, water molecules cannot. This barrier operates on a molecular interaction principle: water contact angle on the barrier surface exceeds 90°, making penetration thermodynamically impossible regardless of differential pressure.',
        stat: '2µm',
        statLabel: 'Precision barrier minimum rating',
      },
    ],
    specs: [
      { label: 'SEPARATION EFFICIENCY', value: '99.8%', sub: 'Combined free + emulsified + dissolved water' },
      { label: 'COLLECTION CHAMBER', value: 'SEALED', sub: 'Permanent water removal from fuel circuit' },
      { label: 'HYDROPHOBIC BARRIER', value: '2µm', sub: 'Terminal water repulsion layer minimum rating' },
      { label: 'MONITORING', value: 'VISUAL', sub: 'Integrated water level monitoring port' },
      { label: 'FUEL COMPATIBILITY', value: '100%', sub: 'Diesel · Biodiesel · Heating oil · Kerosene' },
      { label: 'DRAIN SYSTEM', value: 'MANUAL/AUTO', sub: 'Drain valve or automatic drain options' },
    ],
    applicationsHeading: 'WHERE HYDROCORE™ PROTECTS',
    applicationsSubtext: 'HYDROCORE™ water separation technology protects any fuel system where water ingress threatens injection system integrity.',
    applications: [
      { sector: 'HEAVY TRANSPORT', detail: 'Diesel fuel systems where bulk fuel from storage tanks arrives with water contamination from condensation cycles. HYDROCORE™ removes this contamination before it reaches sensitive Common Rail injectors.' },
      { sector: 'POWER GENERATION', detail: 'Stationary gensets with extended fuel storage periods where condensation accumulation in fuel tanks creates a chronic water contamination source. HYDROCORE™ continuous protection prevents the microbial growth that water accumulation promotes in stored fuel.' },
      { sector: 'AGRICULTURE', detail: 'Farm equipment fuel systems where outdoor fuel storage in diurnal temperature cycling environments creates regular water ingress through tank breathers. The collection chamber visual port allows field service personnel to assess water accumulation without equipment shutdown.' },
      { sector: 'MARINE', detail: 'Diesel marine engines where salt spray and humidity create elevated water contamination rates in fuel systems. HYDROCORE™ hydrophobic barrier prevents salt-water contamination of injection systems in marine service.' },
      { sector: 'MINING', detail: 'Remote site equipment fueled from bulk storage tanks subject to high humidity and temperature variation. HYDROCORE™ terminal protection ensures injection system integrity when fuel source quality cannot be guaranteed.' },
      { sector: 'CONSTRUCTION', detail: 'Construction site equipment fueled from mobile refueling units where water contamination risk is elevated by outdoor fuel handling and storage conditions.' },
    ],
    testimonial: {
      quote: 'Water intrusion was destroying our injection pumps on a predictable seasonal cycle. HYDROCORE™ hydrophobic separation eliminated that cycle entirely — our last two maintenance inspections showed dry sumps across every test unit.',
      role: 'Agricultural Equipment Director',
      sector: 'Harvest Operations — 45 combine harvesters',
    },
    ctaTag: '// IDENTIFY YOUR HYDROCORE™ ELEMENT',
    ctaHeading: 'FIND YOUR WATER PROTECTION',
    ctaBody: 'Cross-reference 500,000+ OEM part numbers. Identify the exact HYDROCORE™ water separation element for your fuel system.',
  },

  cooltech: {
    categoryTag: '// THERMAL SYSTEMS PROTECTION · THERMOCORE™',
    heroTitle: 'THERMOCORE™',
    heroSubtitle: 'SCA ADDITIVE',
    heroTagline: 'SCA additive release technology for thermal systems with cavitation prevention and extended cooling circuit protection. Controlled gradual dosing that maintains coolant chemistry within the protection corridor across the full service interval.',
    heroImage: '/images/coolant-hero.avif',
    heroStats: [
      { key: 'TECHNOLOGY', value: 'SCA RELEASE' },
      { key: 'FUNCTION', value: 'VAPOR PREVENTION' },
      { key: 'DOSING', value: 'GRADUAL' },
    ],
    logoSrc: '/images/Thermacore.avif',
    systemHeadline: 'CHEMICAL ASSET PROTECTION\nFOR THE COOLING CIRCUIT.',
    systemParagraphs: [
      'Diesel engine cooling systems face two simultaneous corrosion threats: electrochemical attack on aluminum, copper and steel surfaces, and cavitation erosion on cylinder liner external surfaces driven by pressure waves from piston firing events. Both failure modes are prevented by maintaining SCA (Supplemental Coolant Additive) chemistry within a tight concentration corridor.',
      'THERMOCORE™ deploys a controlled gradual release mechanism that replenishes SCA chemistry as it is consumed through the service interval — maintaining protection concentration without peaks or valleys that conventional coolant change schedules cannot guarantee.',
      'The gradual dosing system prevents the inhibitor concentration spikes that occur when SCA is added as a single dose at service — high initial concentration that drops progressively to sub-protection levels before the next service interval, leaving the cooling circuit unprotected for a portion of every service cycle.',
    ],
    productImageSrc: '/images/coolant-mesa.avif',
    productImageCaption: 'THERMOCORE™ · SCA ADDITIVE RELEASE PROTECTION ELEMENT',
    stagesHeading: 'THREE PROTECTION MECHANISMS FOR COOLING CIRCUIT INTEGRITY.',
    stages: [
      {
        number: '01',
        tag: 'MECHANISM 1',
        title: 'ADDITIVE RELEASE CONTROL',
        body: 'THERMOCORE™ controlled additive release matrix delivers SCA chemistry into the coolant stream at a rate matched to consumption. As inhibitor concentration falls through use, the release rate increases to compensate — maintaining the target protection corridor without operator intervention between service intervals. This active concentration management eliminates the unprotected coolant condition that occurs at the end of conventional SCA dosing intervals.',
        stat: '100%',
        statLabel: 'SCA concentration corridor maintenance across service interval',
      },
      {
        number: '02',
        tag: 'MECHANISM 2',
        title: 'VAPOR PREVENTION LAYER',
        body: 'Cavitation erosion on cylinder liner surfaces begins with vapor bubble formation at the liner wall during pressure wave events from piston combustion. THERMOCORE™ vapor prevention chemistry forms a protective molecular layer on ferrous surfaces that suppresses the nucleate boiling that initiates bubble formation. By preventing vapor bubble genesis at the metal surface, THERMOCORE™ eliminates the cavitation collapse energy that erodes liner walls over time.',
        stat: '0',
        statLabel: 'Liner surface cavitation erosion events with THERMOCORE™ active',
      },
      {
        number: '03',
        tag: 'MECHANISM 3',
        title: 'HEAT MANAGEMENT BARRIER',
        body: 'The SCA film maintained by THERMOCORE™ on all cooling circuit metal surfaces also functions as a thermal transfer optimization barrier. The molecular protection layer is calibrated to maintain metal surface contact without creating thermal insulation effects — protecting against corrosion while preserving the heat transfer efficiency between the engine block and the coolant stream that cooling system design depends on.',
        stat: '99%',
        statLabel: 'Corrosion protection efficiency across metal surface types',
      },
    ],
    specs: [
      { label: 'SCA TECHNOLOGY', value: 'GRADUAL', sub: 'Controlled release across service interval' },
      { label: 'VAPOR PREVENTION', value: 'ACTIVE', sub: 'Cylinder liner cavitation protection' },
      { label: 'METALS PROTECTED', value: '5', sub: 'Aluminum · Copper · Iron · Steel · Brass' },
      { label: 'DOSING METHOD', value: 'PASSIVE', sub: 'No operator intervention between services' },
      { label: 'COOLANT COMPATIBILITY', value: 'ALL', sub: 'Ethylene glycol · Propylene glycol · OAT' },
      { label: 'SERVICE INTERVAL', value: 'EXTENDED', sub: 'Maintains protection to full OEM interval' },
    ],
    applicationsHeading: 'WHERE THERMOCORE™ PROTECTS',
    applicationsSubtext: 'THERMOCORE™ SCA protection is the thermal system defense choice for diesel engines with aluminum and cast iron cooling circuits.',
    applications: [
      { sector: 'HEAVY TRANSPORT', detail: 'Long-haul diesel engines with complex cooling circuits combining aluminum heat exchangers, copper heater cores and cast iron engine blocks — all requiring simultaneous SCA protection from a single dosing system.' },
      { sector: 'POWER GENERATION', detail: 'Stationary diesel gensets operating on extended service intervals where SCA depletion between service events is a known failure risk. THERMOCORE™ gradual release maintains protection through the full interval without mid-cycle coolant chemistry intervention.' },
      { sector: 'AGRICULTURE', detail: 'Seasonal-use agricultural equipment where cooling system corrosion can advance undetected during off-season storage if SCA concentration falls to sub-protection levels. THERMOCORE™ maintains active protection chemistry regardless of duty cycle.' },
      { sector: 'MINING', detail: 'Off-highway diesel equipment with large displacement engines subject to high thermal cycling rates. Cavitation erosion on cylinder liners is an accelerated failure risk in heavy-load mining applications — THERMOCORE™ vapor prevention layer is the direct countermeasure.' },
      { sector: 'CONSTRUCTION', detail: 'Construction equipment operating in environments where coolant quality degradation through ingress of environmental contaminants is a constant risk. THERMOCORE™ SCA maintenance compensates for dilution events that reduce inhibitor concentration below protection threshold.' },
      { sector: 'INDUSTRIAL', detail: 'Stationary industrial engines and generating sets in process industry applications where unplanned cooling system failures cause production disruption with significant downstream cost consequences.' },
    ],
    testimonial: {
      quote: 'Cylinder liner pitting from cavitation was costing us an average of $12,000 per engine rebuild. THERMOCORE™ SCA technology has maintained coolant chemistry within specification continuously for 18 months — zero pitting events recorded across our generator fleet.',
      role: 'Power Generation Asset Manager',
      sector: 'Data Center Backup Fleet — 32 generators',
    },
    ctaTag: '// IDENTIFY YOUR THERMOCORE™ ELEMENT',
    ctaHeading: 'FIND YOUR COOLING PROTECTION',
    ctaBody: 'Cross-reference 500,000+ OEM part numbers. Identify the exact THERMOCORE™ SCA element for your engine cooling specification.',
  },

  drycore: {
    categoryTag: '// PNEUMATIC DRYING TECHNOLOGY · DRYCORE™',
    heroTitle: 'DRYCORE™',
    heroSubtitle: 'DESICCANT DRYER',
    heroTagline: 'Molecular sieve desiccant technology removing moisture from pneumatic systems with precision efficiency. Corrosion prevention and extended service life for air brake, suspension and control circuit asset protection.',
    heroImage: '/images/airdryer-hero.avif',
    heroStats: [
      { key: 'TECHNOLOGY', value: 'MOLECULAR SIEVE' },
      { key: 'FUNCTION', value: 'WATER ABSORPTION' },
      { key: 'PROTECTION', value: 'CORROSION PREVENTION' },
    ],
    logoSrc: '/images/drycore(fn).avif',
    systemHeadline: 'MOLECULAR-LEVEL\nMOISTURE CUSTODY.',
    systemParagraphs: [
      'Compressed air systems for braking, suspension and pneumatic control contain moisture drawn in during compression from ambient air. At system operating temperature, this moisture remains vapor-phase. When air cools in downstream circuits, valves and actuators, vapor transitions to liquid — causing valve corrosion, seal swelling and control system failures.',
      'DRYCORE™ molecular sieve desiccant captures water vapor at the molecular level before phase transition occurs — preventing liquid water formation in pneumatic circuits entirely rather than managing the consequences after it forms.',
      'Extended service life desiccant matrix is formulated for the cyclic loading pattern of air dryer systems — high moisture intake during compressor cycles, purge regeneration during unloaded cycles — maintaining adsorption capacity across multiple thousand operating hours.',
    ],
    productImageSrc: '/images/airdryer.avif',
    productImageCaption: 'DRYCORE™ · DESICCANT DRYER PROTECTION ELEMENT',
    stagesHeading: 'THREE STAGES OF PNEUMATIC MOISTURE CONTROL.',
    stages: [
      {
        number: '01',
        tag: 'STAGE 1',
        title: 'WATER ABSORPTION MATRIX',
        body: 'Compressed air entering the DRYCORE™ element passes through the primary molecular sieve desiccant matrix where water vapor is adsorbed at molecular contact sites on the desiccant crystal surface. Molecular sieve adsorption is thermodynamically preferred over silica gel at typical compressed air system operating temperatures — delivering higher moisture removal efficiency per unit volume across the full humidity range from arid to tropical ambient conditions.',
        stat: '100%',
        statLabel: 'Water vapor capture at primary desiccant matrix',
      },
      {
        number: '02',
        tag: 'STAGE 2',
        title: 'MOISTURE CUSTODY ZONE',
        body: 'Adsorbed moisture is retained within the molecular sieve matrix crystal structure under the mechanical and thermal stresses of normal dryer operation. The custody zone capacity is sized to accommodate the moisture load from specified air flow rates and ambient humidity conditions without saturation breakthrough between purge cycles. Breakthrough prevention is the critical performance specification — any moisture that exits the desiccant bed reaches downstream pneumatic components.',
        stat: '0',
        statLabel: 'Moisture breakthrough events at rated operating conditions',
      },
      {
        number: '03',
        tag: 'STAGE 3',
        title: 'CORROSION PREVENTION SYSTEM',
        body: 'The downstream protection delivered by DRYCORE™ moisture custody extends across all pneumatic circuit components — brake chambers, relay valves, spring brakes, air suspension valves and electronic control modules with pneumatic interfaces. By maintaining dry air throughout the circuit, DRYCORE™ eliminates the electrochemical corrosion that water promotes on metal valve seats, piston rods and spring surfaces, and the swelling degradation that moisture causes in rubber seals and diaphragms.',
        stat: '99%',
        statLabel: 'Corrosion event prevention in protected pneumatic circuits',
      },
    ],
    specs: [
      { label: 'DESICCANT TYPE', value: 'MOLECULAR', sub: 'Sieve adsorption technology' },
      { label: 'MOISTURE REMOVAL', value: '100%', sub: 'Water vapor capture at rated conditions' },
      { label: 'BREAKTHROUGH', value: 'ZERO', sub: 'No moisture to downstream circuit' },
      { label: 'PURGE COMPATIBLE', value: 'YES', sub: 'Designed for cyclic adsorption/regeneration' },
      { label: 'TEMP RANGE', value: '-40°C', sub: 'Cold-rated dew point suppression' },
      { label: 'OEM FITMENT', value: '100%', sub: 'Drop-in replacement for OEM air dryer' },
    ],
    applicationsHeading: 'WHERE DRYCORE™ PROTECTS',
    applicationsSubtext: 'DRYCORE™ desiccant protection covers every pneumatic asset protection application where moisture in compressed air causes component degradation.',
    applications: [
      { sector: 'HEAVY TRANSPORT', detail: 'Air brake systems on heavy trucks and trailers where moisture in the brake circuit causes valve corrosion and spring brake corrosion seizure. In cold climates, liquid water in brake circuits freezes and causes complete brake system failure.' },
      { sector: 'BUS & COACH', detail: 'Passenger transit vehicle air suspension and brake systems in urban environments with high ambient humidity. DRYCORE™ molecular protection ensures air suspension ride height control valves maintain calibrated function throughout service intervals.' },
      { sector: 'RAIL', detail: 'Locomotive and wagon air brake systems where moisture in the main reservoir and distribution system is the primary cause of triple valve corrosion and brake performance degradation on long-haul rail operations.' },
      { sector: 'MANUFACTURING', detail: 'Compressed air systems for pneumatic tools, actuators and process control instrumentation where moisture causes valve stiction, calibration drift and tool corrosion in production environments.' },
      { sector: 'MINING', detail: 'Pneumatic drill and rock breaking equipment air supply systems in underground mining where ambient humidity is extreme and moisture in compressed air rapidly degrades equipment designed for dry service.' },
      { sector: 'CONSTRUCTION', detail: 'Air brake systems on construction site vehicles and pneumatic equipment supply lines where outdoor operation exposes air systems to the full ambient humidity range without climate control protection.' },
    ],
    testimonial: {
      quote: 'Our pneumatic braking system required brake valve replacements every 18 months on average due to moisture corrosion. After installing DRYCORE™ desiccant elements, we are at 36 months with zero brake valve failures. The ROI was immediate.',
      role: 'Fleet Safety Director',
      sector: 'Municipal Bus Operator — 90 units',
    },
    ctaTag: '// IDENTIFY YOUR DRYCORE™ ELEMENT',
    ctaHeading: 'FIND YOUR DESICCANT PROTECTION',
    ctaBody: 'Cross-reference 500,000+ OEM part numbers. Identify the exact DRYCORE™ desiccant element for your pneumatic system specification.',
  },

  duratech: {
    categoryTag: '// FLEET MAINTENANCE SYSTEMS · DURATECH™',
    heroTitle: 'DURATECH™',
    heroSubtitle: 'MASTER KIT',
    heroTagline: 'Master kit consolidation with OEM interchangeability delivering fleet-ready solutions for standardized maintenance operations. Single-source protection for multi-system service events across mixed-model fleets.',
    heroImage: '/images/almacen-4_converted.avif',
    heroStats: [
      { key: 'SYSTEM', value: 'MASTER KIT' },
      { key: 'FITMENT', value: 'OEM INTERCHANGE' },
      { key: 'COVERAGE', value: 'MULTI-SYSTEM' },
    ],
    logoSrc: '/images/duratech(fn).avif',
    systemHeadline: 'ONE SOURCE.\nEVERY SYSTEM. EVERY VEHICLE.',
    systemParagraphs: [
      'Fleet maintenance operations managing mixed-model vehicle populations face a consistent challenge: sourcing compatible filter elements from multiple suppliers for each vehicle variant, managing separate inventory lines, and coordinating service timing across different replacement intervals.',
      'DURATECH™ master kit architecture consolidates all service-interval filter elements for a defined vehicle platform into a single sourcing event. Oil, fuel, air and cabin filters — all OEM-interchangeable, all coordinated to a unified service interval — in one kit.',
      'Inventory standardization across a mixed-model fleet is the long-term operational benefit. DURATECH™ kit design philosophy reduces per-vehicle part number count, eliminates cross-contamination errors between similar-looking elements, and simplifies technician training for multi-make service operations.',
    ],
    productImageSrc: '/images/npr-01_converted.avif',
    productImageCaption: 'DURATECH™ · MASTER KIT FLEET MAINTENANCE SYSTEM',
    stagesHeading: 'THREE CONSOLIDATION PRINCIPLES FOR FLEET EFFICIENCY.',
    stages: [
      {
        number: '01',
        tag: 'PRINCIPLE 1',
        title: 'MULTI-SYSTEM CONSOLIDATION',
        body: 'Each DURATECH™ master kit consolidates all filtration elements required for a complete vehicle service event into a single package. The kit composition is vehicle-specific — matched to the exact oil, fuel, air and cabin specifications of the target vehicle platform — eliminating the possibility of incorrect element selection that occurs when sourcing components individually from a general catalogue. One kit, one vehicle, one complete service.',
        stat: '1',
        statLabel: 'Source required per complete multi-system service',
      },
      {
        number: '02',
        tag: 'PRINCIPLE 2',
        title: 'OEM INTERCHANGEABILITY',
        body: 'Every element in the DURATECH™ master kit is designed to direct OEM specification — same dimensions, same bypass valve settings, same sealing surfaces, same thread specifications. OEM interchangeability means no modification to vehicle systems, no adapter plates, no calibration adjustments. Technicians can service any platform in the fleet with DURATECH™ kits with the same confidence as OEM-supplied elements, at fleet purchasing economics.',
        stat: '100%',
        statLabel: 'OEM dimensional and specification interchangeability',
      },
      {
        number: '03',
        tag: 'PRINCIPLE 3',
        title: 'STANDARDIZED INVENTORY',
        body: 'The DURATECH™ kit system converts fleet filter inventory from an unmanaged collection of individual part numbers to a structured kit-based inventory with predictable consumption rates. For fleet managers, this means reorder quantities based on vehicle count and service cycle frequency — not variable individual part consumption rates. Inventory holding costs fall, stockout risk falls, and administrative overhead for purchasing and parts management falls with them.',
        stat: '↓',
        statLabel: 'Inventory complexity per vehicle vs. individual part sourcing',
      },
    ],
    specs: [
      { label: 'KIT CONTENTS', value: '4+', sub: 'Oil · Fuel · Air · Cabin elements per kit' },
      { label: 'OEM INTERCHANGE', value: '100%', sub: 'Spec-matched to OEM requirements' },
      { label: 'VEHICLE COVERAGE', value: 'BROAD', sub: 'Kits for passenger, LCV and HDV platforms' },
      { label: 'INTERVAL SYNC', value: 'YES', sub: 'Elements coordinated to unified service schedule' },
      { label: 'IDENTIFICATION', value: 'CLEAR', sub: 'Platform-specific marking prevents mis-install' },
      { label: 'SOURCING', value: 'SINGLE', sub: 'One supplier, one order, one delivery' },
    ],
    applicationsHeading: 'WHERE DURATECH™ DELIVERS',
    applicationsSubtext: 'DURATECH™ master kit system is designed for operations managing multiple vehicles where sourcing efficiency and inventory simplification deliver measurable cost benefits.',
    applications: [
      { sector: 'FLEET OPERATORS', detail: 'Transport operators managing 20+ vehicle fleets where maintenance scheduling, parts ordering and technician efficiency are direct operating cost drivers. DURATECH™ kit standardization reduces maintenance event duration and parts procurement overhead per vehicle.' },
      { sector: 'WORKSHOPS', detail: 'Independent service workshops managing multi-brand vehicle maintenance where stocking individual filter elements across every make and model creates unsustainable inventory complexity. Kit-based sourcing simplifies stock management and customer service delivery.' },
      { sector: 'RENTAL OPERATIONS', detail: 'Vehicle rental fleets with mixed-model populations requiring routine scheduled maintenance at defined intervals. DURATECH™ kit structure matches rental fleet service scheduling requirements and simplifies technician training for multi-model maintenance.' },
      { sector: 'MINING OPERATIONS', detail: 'Remote mining site maintenance operations where supply chain efficiency is critical and inventory holding costs are elevated by geographic isolation. DURATECH™ kit-based sourcing reduces part number count and simplifies remote site inventory management.' },
      { sector: 'MUNICIPAL FLEETS', detail: 'Public sector vehicle fleets for municipal services, transit operations and emergency services where maintenance budgets are defined annually and predictable per-vehicle maintenance costs are essential for budget planning.' },
      { sector: 'CONSTRUCTION', detail: 'Construction contractor equipment fleets where machines from multiple manufacturers require coordinated maintenance scheduling. DURATECH™ kits for each equipment platform simplify on-site maintenance operations and reduce dependency on multi-supplier logistics.' },
    ],
    testimonial: {
      quote: 'The synchronized kit program eliminated parts sourcing errors entirely. Previously, wrong-interval filter changes were causing 15% of our maintenance writebacks. DURATECH™ model-specific kits brought that to zero in the first month.',
      role: 'Fleet Operations Manager',
      sector: 'Regional Distribution Network — 175 units',
    },
    ctaTag: '// IDENTIFY YOUR DURATECH™ KIT',
    ctaHeading: 'FIND YOUR FLEET KIT',
    ctaBody: 'Cross-reference 500,000+ OEM part numbers. Identify the exact DURATECH™ master kit for your vehicle or equipment platform.',
  },

  marineclean: {
    categoryTag: '// MARINE FILTRATION SYSTEMS · MARINECLEAN™',
    heroTitle: 'MARINECLEAN™',
    heroSubtitle: 'SALT-RESISTANT',
    heroTagline: 'Salt-resistant epoxy coating with brine rejection technology meeting IMO certification for commercial marine filtration. Corrosion shield defense for diesel fuel and hydraulic systems operating in saltwater environments.',
    heroImage: '/images/marino-taller.avif',
    heroStats: [
      { key: 'CERTIFICATION', value: 'IMO' },
      { key: 'PROTECTION', value: 'SALT-RESISTANT' },
      { key: 'SYSTEM', value: 'CORROSION SHIELD' },
    ],
    logoSrc: '/images/marineclean(fn).avif',
    systemHeadline: 'MARINE-GRADE DEFENSE\nAGAINST SALT CORROSION.',
    systemParagraphs: [
      'Marine diesel systems operate in the most corrosive environment accessible to filtration technology. Salt spray, salt aerosol and seawater ingress attack filter housings, sealing interfaces and bypass valve components continuously — not just in rough conditions, but as a constant ambient environment.',
      'MARINECLEAN™ salt-resistant architecture addresses this environment through a defense-in-depth approach: protective epoxy coating on all external surfaces, brine rejection geometry at critical water ingress points, and corrosion-resistant internal components throughout the protection circuit.',
      'IMO certification for commercial marine application confirms MARINECLEAN™ compliance with international maritime standards for fuel and hydraulic filtration in commercial shipping, offshore platform and harbor operations.',
    ],
    productImageSrc: '/images/marino-taller.avif',
    productImageCaption: 'MARINECLEAN™ · SALT-RESISTANT MARINE FILTRATION SYSTEM',
    stagesHeading: 'THREE LAYERS OF MARINE CORROSION DEFENSE.',
    stages: [
      {
        number: '01',
        tag: 'LAYER 1',
        title: 'SALT RESISTANCE COATING',
        body: 'The exterior epoxy coating system applied to all MARINECLEAN™ components is formulated specifically for continuous saltwater aerosol exposure. Salt spray does not penetrate the coating system to reach underlying metal surfaces — the protection mechanism is barrier isolation, not chemical inhibition. The coating maintains integrity through the thermal cycling that marine installations experience between cold seawater ambient and diesel engine heat rejection.',
        stat: '100%',
        statLabel: 'Salt spray barrier coverage on external surfaces',
      },
      {
        number: '02',
        tag: 'LAYER 2',
        title: 'BRINE REJECTION BARRIER',
        body: 'At any point where salt water could enter the filtration circuit — tank breathers, housing seals, drain valve interfaces — MARINECLEAN™ brine rejection geometry physically prevents ingress. The brine rejection architecture operates as a one-way protection barrier: filtered fluid can drain, but seawater cannot enter against the flow path. This is particularly critical for fuel systems where seawater contamination causes microbial growth and emulsification that permanently degrades fuel quality.',
        stat: '0',
        statLabel: 'Seawater ingress events through brine rejection interfaces',
      },
      {
        number: '03',
        tag: 'LAYER 3',
        title: 'CORROSION SHIELD INTERNALS',
        body: 'Internal bypass valve components, spring elements and sealing surfaces are manufactured from corrosion-resistant materials that maintain dimensional and mechanical integrity in the event of brief salt water contact during service events or filter change intervals. The corrosion shield specification ensures that even after exposure to a marine service environment, MARINECLEAN™ bypass valve function remains within calibrated specification.',
        stat: '99%',
        statLabel: 'Internal component corrosion resistance at saltwater contact',
      },
    ],
    specs: [
      { label: 'CERTIFICATION', value: 'IMO', sub: 'International maritime organization standard' },
      { label: 'SALT RESISTANCE', value: 'FULL', sub: 'Continuous saltwater aerosol exposure rated' },
      { label: 'BRINE REJECTION', value: 'ACTIVE', sub: 'Seawater ingress prevention at all interfaces' },
      { label: 'COATING SYSTEM', value: 'EPOXY', sub: 'Marine-grade barrier protection' },
      { label: 'CORROSION SHIELD', value: '99%', sub: 'Internal component corrosion resistance' },
      { label: 'FLUID SYSTEMS', value: '2', sub: 'Fuel filtration · Hydraulic filtration' },
    ],
    applicationsHeading: 'WHERE MARINECLEAN™ PROTECTS',
    applicationsSubtext: 'MARINECLEAN™ salt-resistant protection covers all diesel fuel and hydraulic filtration applications in marine and coastal environments.',
    applications: [
      { sector: 'COMMERCIAL SHIPPING', detail: 'Deep sea cargo vessels and tankers where diesel engine fuel filtration must meet IMO certification requirements and withstand continuous saltwater aerosol exposure throughout multi-month voyages.' },
      { sector: 'HARBOR OPERATIONS', detail: 'Tugs, pilot vessels and harbor service craft operating in salt water environments with frequent docking cycles that expose fuel system components to direct seawater splash.' },
      { sector: 'OFFSHORE PLATFORMS', detail: 'Oil and gas platform diesel generating sets and utility systems where the ambient environment combines salt aerosol with process chemical exposure that demands the highest corrosion resistance specification.' },
      { sector: 'FISHING INDUSTRY', detail: 'Commercial fishing vessels operating in coastal and deep-sea environments where fuel system reliability is critical for vessel safety and where maintenance capability is limited to vessel service ports.' },
      { sector: 'MARINE HYDRAULICS', detail: 'Shipboard crane, hatch cover and steering gear hydraulic systems that require corrosion-resistant filtration meeting commercial marine standards in permanently saltwater-exposed installations.' },
      { sector: 'COASTAL INFRASTRUCTURE', detail: 'Coastal power generation and water treatment facilities with diesel backup generation where fuel filtration components are permanently exposed to salt aerosol from prevailing wind patterns.' },
    ],
    testimonial: {
      quote: 'Operating in the Gulf with salt spray at every sea state, our previous filters required replacement every 250 engine hours. MARINECLEAN™ salt-resistant construction extended that to 750 hours while maintaining zero contamination events in the injection system.',
      role: 'Chief Engineer',
      sector: 'Offshore Supply Vessel Fleet — 12 vessels',
    },
    ctaTag: '// IDENTIFY YOUR MARINECLEAN™ ELEMENT',
    ctaHeading: 'FIND YOUR MARINE PROTECTION',
    ctaBody: 'Cross-reference 500,000+ OEM part numbers. Identify the exact MARINECLEAN™ element for your marine or coastal application.',
  },

  microkappa: {
    categoryTag: '// CABIN AIR PROTECTION · MICROKAPPA™',
    heroTitle: 'MICROKAPPA™',
    heroSubtitle: 'ELECTROSTATIC HEPA',
    heroTagline: 'Electrostatic plus activated carbon with HEPA filtration capturing allergens, odors and particulate contamination in vehicle cabin air systems. Three-mechanism defense for occupant health protection in heavy-duty and passenger vehicle cabins.',
    heroImage: '/images/cabin-hero.avif',
    heroStats: [
      { key: 'TECHNOLOGY', value: 'ELECTROSTATIC' },
      { key: 'ODOR CONTROL', value: 'ACTIVATED CARBON' },
      { key: 'STANDARD', value: 'HEPA CLASS' },
    ],
    logoSrc: '/images/microkappa(fn).avif',
    systemHeadline: 'THREE MECHANISMS.\nZERO CONTAMINATION REACHES THE OCCUPANT.',
    systemParagraphs: [
      'Vehicle cabin air filtration is not an engine protection system — it is an occupant health protection system. The contamination targets are different: PM2.5 and PM10 particles, pollen, bacteria, diesel exhaust gases, NOx compounds, and volatile organic compounds from road and industrial sources.',
      'MICROKAPPA™ electrostatic HEPA architecture combines three capture mechanisms in a single element because no single mechanism addresses the full contamination spectrum. Electrostatic attraction targets aerosol-range particles, mechanical HEPA filtration captures larger particles, and activated carbon adsorption removes molecular contamination that particulate filtration cannot intercept.',
      'This three-mechanism approach is particularly important in heavy-duty vehicle cabins — trucks, buses, construction equipment — where operators spend full working days in the cabin and where ambient contamination levels from diesel exhaust, dust and industrial sources are significantly higher than passenger vehicle environments.',
    ],
    productImageSrc: '/images/filtro-de-cabina.avif',
    productImageCaption: 'MICROKAPPA™ · ELECTROSTATIC HEPA CABIN PROTECTION',
    stagesHeading: 'THREE PROTECTION MECHANISMS FOR OCCUPANT HEALTH.',
    stages: [
      {
        number: '01',
        tag: 'MECHANISM 1',
        title: 'ELECTROSTATIC PARTICLE ATTRACTION',
        body: 'MICROKAPPA™ electrostatic layer carries a permanent electrostatic charge that attracts aerosol-range particles — including diesel particulate matter, fine road dust and bacterial aerosols — through electrostatic attraction force rather than physical interception. Particles that would pass through a mechanical filter of the same fiber density are captured through the electrostatic mechanism, allowing MICROKAPPA™ to achieve HEPA-class particle capture without the airflow restriction that purely mechanical HEPA filtration creates in cabin HVAC systems.',
        stat: '99%',
        statLabel: 'PM2.5 particle capture efficiency at electrostatic layer',
      },
      {
        number: '02',
        tag: 'MECHANISM 2',
        title: 'ACTIVATED CARBON ODOR CONTROL',
        body: 'The activated carbon layer addresses molecular contamination — diesel exhaust gases, NOx compounds, benzene, toluene, and volatile organic compounds from adhesives, road surface treatments and industrial emissions. Carbon adsorption captures molecules at the carbon surface through van der Waals forces, removing them from the air stream before they reach the cabin interior. The activated carbon capacity is sized to maintain effective adsorption through the full recommended service interval in typical urban and industrial driving environments.',
        stat: '95%',
        statLabel: 'Molecular contaminant removal efficiency at activated carbon layer',
      },
      {
        number: '03',
        tag: 'MECHANISM 3',
        title: 'HEPA PRECISION BARRIER',
        body: 'The HEPA-class precision barrier captures larger particles — pollen, mold spores, dust mite allergens and bacteria — through mechanical interception and inertial impaction. This layer is the defense against the biological allergen fraction that causes occupant respiratory response. In agricultural vehicle cabins where pollen concentration can exceed urban ambient by orders of magnitude during harvest seasons, HEPA-class barrier protection is the difference between safe occupant conditions and occupational health exposure events.',
        stat: '99.97%',
        statLabel: 'HEPA barrier efficiency at 0.3µm particle size',
      },
    ],
    specs: [
      { label: 'ELECTROSTATIC', value: 'PERMANENT', sub: 'Charged fiber layer for aerosol capture' },
      { label: 'ACTIVATED CARBON', value: 'HIGH LOAD', sub: 'Molecular contamination adsorption' },
      { label: 'HEPA CLASS', value: '99.97%', sub: 'Particle capture at 0.3µm threshold' },
      { label: 'PM2.5 CAPTURE', value: '99%', sub: 'Fine particulate protection efficiency' },
      { label: 'ODOR REMOVAL', value: '95%', sub: 'VOC and exhaust gas molecular removal' },
      { label: 'SERVICE INTERVAL', value: 'EXTENDED', sub: 'Engineered for annual or OEM schedule' },
    ],
    applicationsHeading: 'WHERE MICROKAPPA™ PROTECTS',
    applicationsSubtext: 'MICROKAPPA™ three-mechanism protection covers every vehicle cabin type where occupant air quality is a health or operational priority.',
    applications: [
      { sector: 'HEAVY TRANSPORT', detail: 'Long-haul truck driver cabins where occupants spend 8–12 hours per day in a closed environment. Diesel exhaust exposure from engine and surrounding traffic, combined with road dust, makes MICROKAPPA™ molecular and particle protection critical for occupational health compliance.' },
      { sector: 'BUS & COACH', detail: 'Urban transit bus cabins where operator and passenger exposure to NOx and PM2.5 from urban diesel traffic in enclosed bus lane environments creates measurable air quality challenges that MICROKAPPA™ electrostatic and HEPA mechanisms address.' },
      { sector: 'AGRICULTURE', detail: 'Combine harvester and tractor cabins during harvest operations where airborne pollen concentration can cause severe allergic response in operators. HEPA-class barrier protection prevents occupational health events that force operators out of service during critical harvest windows.' },
      { sector: 'CONSTRUCTION', detail: 'Excavator and crane operator cabins on earthwork and demolition sites where airborne silica dust, cement dust and demolition particulate create occupational lung disease risk. MICROKAPPA™ HEPA barrier captures silica particles at all size fractions.' },
      { sector: 'MINING', detail: 'Underground mining vehicle cabins where ambient contamination combines diesel particulate with mineral dust fractions specific to the ore type being extracted. Electrostatic capture addresses the fine fraction that overcomes purely mechanical cabin filter designs.' },
      { sector: 'PASSENGER VEHICLES', detail: 'Family and executive passenger vehicles in urban environments where PM2.5 from traffic, pollen seasonal loads and interior VOC sources make three-mechanism protection the preferred specification for occupant health-conscious buyers.' },
    ],
    testimonial: {
      quote: 'Driver fatigue reports dropped by 35% across our long-haul fleet after switching to MICROKAPPA™ cabin air systems. Particulate and VOC levels inside the cab are now measurably lower than outside ambient air. That is occupational health you can prove.',
      role: 'Occupational Health Director',
      sector: 'Long-Haul Logistics Operator — 200 cabs',
    },
    ctaTag: '// IDENTIFY YOUR MICROKAPPA™ ELEMENT',
    ctaHeading: 'FIND YOUR CABIN PROTECTION',
    ctaBody: 'Cross-reference 500,000+ OEM part numbers. Identify the exact MICROKAPPA™ element for your vehicle cabin specification.',
  },

  // Slug aliases — new canonical routes after renaming deprecated entries
  // Old URLs (/technologies/aquaguard, /technologies/cooltech) remain functional via these keys
  'hydrocore-series': undefined as unknown as TechDetailData,
  'hydrocore':        undefined as unknown as TechDetailData,
  'thermocore':       undefined as unknown as TechDetailData,
};

// Resolve aliases at runtime (avoids duplicating large data objects)
TECH_PAGES['hydrocore-series'] = TECH_PAGES['aquaguard-series'];
TECH_PAGES['hydrocore']        = TECH_PAGES['aquaguard'];
TECH_PAGES['thermocore']       = TECH_PAGES['cooltech'];
