import { CANONICAL_PUBLIC_SYSTEMS, CANONICAL_PUBLIC_SYSTEM_DETAILS } from '../public-systems';

export const KC_SYSTEMS = CANONICAL_PUBLIC_SYSTEMS;
export const KC_SYSTEM_DETAILS = CANONICAL_PUBLIC_SYSTEM_DETAILS;
