/**
 * ELIMFILTERS Knowledge Center — Canonical Technology Registry
 * Source of truth: docs/brand/TECHNOLOGY_REGISTRY.md
 */

import type { KCTechnology } from './types';

export const KC_TECHNOLOGIES: KCTechnology[] = [
  {
    slug: 'macrocore',
    name: 'MACROCORE™',
    domain: 'Air Intake & Airflow Protection',
    tagline: 'Engine air-intake protection architecture integrating media, capacity, restriction and sealing.',
    engineeringPrinciple: 'MACROCORE™ is the ELIMFILTERS architecture for engine air-intake protection. It integrates media configuration, contaminant-holding capacity, restriction control, and sealing integrity according to airflow demand and operating conditions.',
    selectionGuidance: 'Select the intake architecture from the engine airflow requirement, housing geometry, dust concentration, duty cycle and acceptable restriction progression. The review must cover the complete clean-air boundary: inlet routing, pre-cleaning where applicable, primary element, safety element, seals, clamps and service indicator. A high-capacity element cannot compensate for a damaged housing or an unsealed joint, and a low initial restriction is not sufficient if dust capacity is inadequate for the operating environment. Service decisions should follow measured restriction and inspection of the intake path rather than appearance alone.',
    evidenceBoundary: 'MACROCORE™ defines an application architecture, not one universal efficiency, dust capacity or service interval. ISO 5011 provides the relevant laboratory framework for product-level air-cleaner evaluation, but published values must remain tied to the tested element and housing configuration. Final validation requires the engine maker's airflow and restriction limits, the installed housing, the contaminant environment and approved ELIMFILTERS product evidence.',
    contamination: ['Airborne particulate contamination'],
    performanceSpecs: [],
    standards: ['ISO 5011'],
    relatedSystems: ['air-intake-protection'],
    relatedIndustries: [],
    worksWith: ['INTEKCORE™'],
    image: '/images/technologies/macrocore-media.png',
  },
  {
    slug: 'microkappa',
    name: 'MICROKAPPA™',
    domain: 'Air Intake & Airflow Protection',
    tagline: 'Cabin air filtration technology for operator-environment protection.',
    engineeringPrinciple: 'MICROKAPPA™ applies cabin filtration media according to the operator environment, airflow requirement and HVAC system constraints.',
    selectionGuidance: 'Cabin filtration selection begins with the vehicle HVAC layout, filter dimensions, seal geometry, blower airflow and the operator environment. Dust, pollen and fine particulate exposure must be balanced against pressure drop because excessive resistance can reduce ventilation, demisting and thermal performance. The review should also consider recirculation behavior, door-open exposure, loading rate and whether the filter frame maintains a continuous seal inside the housing. Recurring airflow complaints require inspection of the complete HVAC path, including evaporator contamination and installation damage, rather than automatically shortening the filter interval.',
    evidenceBoundary: 'MICROKAPPA™ does not assign one particle-efficiency rating, odor-control capability or replacement interval to every cabin filter. Those claims depend on the individual media configuration, test method, airflow and application. Product selection must be supported by verified fit and performance data; the technology page explains the engineering role and cannot replace vehicle-specific service information or occupational exposure controls.',
    contamination: ['Cabin airborne particulate contamination'],
    performanceSpecs: [],
    standards: [],
    relatedSystems: ['air-intake-protection'],
    relatedIndustries: [],
    worksWith: [],
  },
  {
    slug: 'drycore',
    name: 'DRYCORE™',
    domain: 'Air Intake & Airflow Protection',
    tagline: 'Air-dryer filtration technology for pneumatic brake-system protection.',
    engineeringPrinciple: 'DRYCORE™ controls moisture in compressed-air circuits to support pneumatic brake-system reliability.',
    selectionGuidance: 'Air-dryer protection must be matched to compressor duty, purge behavior, reservoir layout, ambient temperature, humidity and the pneumatic system's actual moisture load. Diagnosis should distinguish normal condensate management from a failed purge valve, saturated desiccant, oil carryover, air leakage or excessive compressor cycling. The filter and desiccant assembly must also be compatible with the installed cartridge interface and service procedure. In brake applications, recurring water downstream of the dryer is a system symptom that warrants inspection of the compressor, governor, heater, purge cycle and reservoirs before another cartridge is fitted.',
    evidenceBoundary: 'DRYCORE™ describes moisture-control architecture for approved compressed-air and pneumatic applications; it does not promise one dew point, oil-removal efficiency or service interval across all vehicles and climates. Any quantitative performance claim belongs to a validated cartridge and test condition. Final service decisions must follow the equipment manufacturer's safety requirements, the installed dryer design and verified application data.',
    contamination: ['Moisture in compressed air'],
    performanceSpecs: [],
    standards: [],
    relatedSystems: ['air-intake-protection'],
    relatedIndustries: [],
    worksWith: [],
  },
  {
    slug: 'intekcore',
    name: 'INTEKCORE™',
    domain: 'Air Intake & Airflow Protection',
    tagline: 'Air intake housing technology for controlled airflow and sealing integrity.',
    engineeringPrinciple: 'INTEKCORE™ integrates housing geometry, element retention and sealing to preserve the protected intake boundary.',
    selectionGuidance: 'Housing selection and inspection must resolve airflow demand, inlet orientation, mounting loads, element retention and the integrity of every seal between the dirty-air and clean-air sides. Deformed covers, damaged threads, missing latches, cracked ducts or incorrect elements can create an unfiltered bypass even when the media itself is intact. The review should include the clean-air tube, restriction indicator connection and downstream clamps because contamination can enter anywhere after the filter. Element replacement must preserve the designed compression and seating geometry instead of relying only on matching external dimensions.',
    evidenceBoundary: 'INTEKCORE™ is a housing and sealing architecture, not a universal airflow or efficiency specification. ISO 5011 testing is meaningful only for the evaluated air-cleaner configuration. Product claims must remain tied to the approved housing, element and operating condition, while installation acceptance requires verified fit, secure retention and an intact clean-air boundary.',
    contamination: ['Unfiltered-air bypass risk'],
    performanceSpecs: [],
    standards: ['ISO 5011'],
    relatedSystems: ['air-intake-protection'],
    relatedIndustries: [],
    worksWith: ['MACROCORE™'],
  },
  {
    slug: 'syntapore',
    name: 'SYNTAPORE™',
    domain: 'Fuel Cleanliness Protection',
    tagline: 'Diesel-fuel filtration architecture for primary, secondary and cartridge filter applications.',
    engineeringPrinciple: 'SYNTAPORE™ is the ELIMFILTERS diesel-fuel filtration architecture developed for primary, secondary and cartridge filter applications. It supports staged particulate control before fuel reaches high-pressure pumps, injectors and other precision components. The architecture allows each filtration position to be matched to the required efficiency, contaminant capacity, fuel flow and pressure-drop conditions. This application-specific approach supports reliable fuel-system protection across different engines, operating environments and service strategies. Product-level performance and service intervals are validated individually according to the filter, application and applicable test requirements.',
    selectionGuidance: 'Selection starts by identifying whether the element serves a primary, secondary or cartridge position, then matching fuel flow, injection-system sensitivity, contaminant load, cold-flow behavior and allowable restriction. The complete fuel path should be reviewed for storage contamination, transfer practices and upstream water management because a final filter cannot correct every source condition by itself. Seal materials, connections and bypass behavior must match the approved housing. When restriction rises prematurely, diagnosis should distinguish abnormal contamination, fuel quality, low-temperature waxing and an incorrect element before changing the maintenance interval.',
    evidenceBoundary: 'SYNTAPORE™ does not create a universal micron rating, efficiency, capacity or service life for every diesel filter. Quantitative claims require product-level evidence under the applicable test method and the approved application. HYDROCORE™ remains the architecture for standard non-turbine water separators, while TURBOCORE™ is reserved for approved FH and FG turbine-style systems; those scopes must not be merged.',
    contamination: ['Fuel particulate contamination'],
    performanceSpecs: [],
    standards: [],
    relatedSystems: ['fuel-cleanliness-protection'],
    relatedIndustries: [],
    worksWith: ['HYDROCORE™', 'TURBOCORE™'],
    image: '/images/technologies/syntapore-media.png',
  },
  {
    slug: 'hydrocore',
    name: 'HYDROCORE™',
    domain: 'Fuel Cleanliness Protection',
    tagline: 'Fuel/water separation architecture for approved standard non-turbine separators with drain or transparent-bowl configurations.',
    engineeringPrinciple: 'HYDROCORE™ is the ELIMFILTERS fuel/water separation architecture for approved standard non-turbine separator filters. It coordinates the separation media and approved separator construction around fuel flow, water management, drainage, bowl configuration and service conditions. FH and FG turbine-style systems are excluded and are governed exclusively by TURBOCORE™. Product-level water-separation performance must be supported by the validated configuration and applicable test requirements.',
    selectionGuidance: 'A separator application must be evaluated from the incoming water condition, fuel flow, housing design, drainage method, bowl configuration and maintenance access. Effective operation depends on removing collected water before it reaches the element's working volume, maintaining intact seals and preventing contaminated transfer or storage practices from overwhelming the system. Inspection should differentiate free water, dispersed water, microbial debris and ordinary particulate loading because each condition changes the corrective action. Selection also has to preserve fuel supply under peak engine demand and remain compatible with the approved non-turbine separator housing.',
    evidenceBoundary: 'HYDROCORE™ applies only to approved standard non-turbine separator configurations. It does not establish one water-removal percentage, particle efficiency, capacity or drain interval for all products. Those values require validation for the individual element and assembly. FH and FG turbine-style architectures are explicitly outside this scope and are governed by TURBOCORE™.',
    contamination: ['Free water in diesel fuel', 'Dispersed or emulsified water where supported by the validated product configuration'],
    performanceSpecs: [],
    standards: [],
    relatedSystems: ['fuel-cleanliness-protection'],
    relatedIndustries: [],
    worksWith: ['SYNTAPORE™', 'TURBOCORE™'],
  },
  {
    slug: 'turbocore',
    name: 'TURBOCORE™',
    domain: 'Fuel Cleanliness Protection',
    tagline: 'Turbine-style fuel/water separation architecture reserved for approved FH and FG series systems.',
    engineeringPrinciple: 'TURBOCORE™ is the ELIMFILTERS turbine-style fuel/water separation architecture reserved exclusively for approved FH and FG series systems. It addresses fuel cleanliness and water management within the approved turbine separator configuration while remaining distinct from HYDROCORE™, which governs standard non-turbine separators. Product-level efficiency, water-separation performance, capacity and service intervals require validated application-specific evidence.',
    selectionGuidance: 'Turbine-style separation must be selected as a complete approved FH or FG system, including the housing size, dedicated element series, bowl and drain arrangement, fuel-flow requirement and available service space. Review the contamination source and water-management practice as well as the separator itself; repeated water accumulation can indicate storage, transfer or tank problems that require upstream correction. During service, the correct internal seals, element orientation and drain condition are essential to preserve the intended flow path. Standard spin-on or cartridge separator logic should not be substituted merely because external dimensions appear compatible.',
    evidenceBoundary: 'TURBOCORE™ is restricted to approved FH and FG turbine-style systems and their dedicated replacement architecture. It does not provide a universal water-separation efficiency, particle rating, capacity or service interval. Every performance statement must be supported by the validated housing-and-element configuration and applicable test evidence. Standard non-turbine separators remain within HYDROCORE™ scope.',
    contamination: ['Fuel particulate contamination', 'Water contamination in approved FH and FG turbine-style separator systems'],
    performanceSpecs: [],
    standards: [],
    relatedSystems: ['fuel-cleanliness-protection'],
    relatedIndustries: [],
    worksWith: ['SYNTAPORE™', 'HYDROCORE™'],
  },
  {
    slug: 'syntrax',
    name: 'SYNTRAX™',
    domain: 'Lubrication Protection',
    tagline: 'Lubrication-filtration architecture for wear debris, soot agglomerates and oil contaminant control.',
    engineeringPrinciple: 'SYNTRAX™ is the ELIMFILTERS lubrication-filtration architecture designed to control wear debris, soot agglomerates and other contaminants circulating within engine oil. Its engineering approach balances filtration performance, contaminant capacity, oil flow, pressure drop and valve integrity throughout changing temperatures and operating conditions. This enables the filter configuration to be selected according to engine duty, lubricant condition and the established maintenance program. Performance and service capacity are determined for each product and application rather than assigned as universal values to the complete technology.',
    selectionGuidance: 'Lubrication filtration selection must account for oil viscosity across startup and operating temperature, engine flow demand, bypass-valve behavior, contaminant generation and the established oil-drain strategy. The element must control wear debris and soot agglomerates without starving lubricated components during cold starts or high-flow operation. Recurring short intervals should trigger review of combustion condition, coolant or fuel dilution, air-intake sealing and sampling history rather than an automatic move to a different nominal rating. Fit, gasket compression, anti-drainback function and housing condition remain part of the protected lubrication circuit.',
    evidenceBoundary: 'SYNTRAX™ defines lubrication-filtration architecture, not one micron rating, capacity, bypass setting or oil-drain interval for all engines. Product performance belongs to the individual filter and approved application. Oil analysis can support condition assessment, but interpretation must use consistent sampling and engine-specific limits; it does not replace verified fit, pressure-flow requirements or manufacturer service guidance.',
    contamination: ['Lubricant particulate contamination'],
    performanceSpecs: [],
    standards: [],
    relatedSystems: ['lubrication-protection'],
    relatedIndustries: [],
    worksWith: [],
    image: '/images/technologies/syntrax-media.png',
  },
  {
    slug: 'nanoforce',
    name: 'NANOFORCE™',
    domain: 'Hydraulic Protection',
    tagline: 'Hydraulic-filtration architecture for fluid cleanliness around pump, valve and actuator tolerances.',
    engineeringPrinciple: 'NANOFORCE™ is the ELIMFILTERS hydraulic-filtration architecture developed to maintain fluid cleanliness around the tolerance requirements of pumps, valves, actuators and precision hydraulic components. Media and element construction are selected according to the required cleanliness target, critical particle size, system flow, pressure, fluid viscosity and operating duty. This engineering flexibility allows filtration to be configured for pressure-line, return-line and approved offline applications. Product-level efficiency, Beta performance, contaminant capacity and pressure ratings must be supported by validated data under the applicable test standards.',
    selectionGuidance: 'Hydraulic filtration must be placed and sized around the most contamination-sensitive component, the target cleanliness code, circuit flow, operating pressure, fluid viscosity and expected ingression rate. Pressure-line, return-line and offline positions impose different structural and differential-pressure duties, so elements should not be interchanged by dimensions alone. The review should include reservoir breathers, fill practices, cylinder exposure and maintenance cleanliness because filters cannot offset uncontrolled ingression indefinitely. Trending particle counts and differential pressure is more informative than replacing elements on appearance or a generic hour interval.',
    evidenceBoundary: 'NANOFORCE™ does not assign one Beta ratio, micron rating, collapse strength, pressure limit or service life to every hydraulic element. ISO 16889 and ISO 4406 provide performance and cleanliness frameworks, but claims must remain tied to validated product data and the actual circuit. Final selection requires the approved housing, flow direction, bypass arrangement, fluid compatibility and equipment cleanliness target.',
    contamination: ['Hydraulic-fluid particulate contamination'],
    performanceSpecs: [],
    standards: ['ISO 16889', 'ISO 4406'],
    relatedSystems: ['hydraulic-protection'],
    relatedIndustries: [],
    worksWith: [],
    image: '/images/technologies/nanoforce-media.png',
  },
  {
    slug: 'thermacore',
    name: 'THERMACORE™',
    domain: 'Cooling System Protection',
    tagline: 'Coolant filtration technology for cooling-system cleanliness and component protection.',
    engineeringPrinciple: 'THERMACORE™ supports cooling-system protection through coolant filtration selected for the approved engine and maintenance requirements.',
    selectionGuidance: 'Cooling-system filtration must be evaluated together with coolant specification, chemical condition, water quality, corrosion products, scale, system volume and the engine maker's maintenance practice. The filter cannot correct incompatible coolant mixtures, active combustion-gas leakage, depleted inhibitors or untreated make-up water. Diagnosis should therefore distinguish suspended debris from chemical precipitation, corrosion and external contamination before changing the filtration strategy. Where a coolant filter or additive-bearing element is approved, its chemistry, thread, seal and release characteristics must match the installed system and the current coolant formulation.',
    evidenceBoundary: 'THERMACORE™ describes approved cooling-system protection architecture; it does not establish one filtration efficiency, additive charge or replacement interval for every engine. Quantitative claims and chemical compatibility must be supported by the individual product, coolant and application evidence. Equipment-manufacturer requirements and coolant analysis take precedence over generalized schedules, especially after overheating, component replacement or coolant mixing.',
    contamination: ['Cooling-system particulate contamination'],
    performanceSpecs: [],
    standards: [],
    relatedSystems: ['cooling-system-protection'],
    relatedIndustries: [],
    worksWith: [],
  },
];