/**
 * ELIMFILTERS Knowledge Center — Canonical Technology Registry
 * Source of truth: docs/brand/TECHNOLOGY_REGISTRY.md
 */

import type { KCTechnology } from './types';

export const KC_TECHNOLOGIES: KCTechnology[] = [
  {
    slug: 'macrocore',
    name: 'MACROCORE™',
    domain: 'Air Intake & Airflow Protection',
    tagline: 'Engine air filtration technology for primary and secondary intake protection.',
    engineeringPrinciple: 'MACROCORE™ supports contamination control at the engine air-intake boundary through the coordinated selection of filtration media, sealing integrity, airflow and service conditions.',
    contamination: ['Airborne particulate contamination'],
    performanceSpecs: [],
    standards: ['ISO 5011'],
    relatedSystems: ['air-intake-protection'],
    relatedIndustries: [],
    worksWith: ['INTEKCORE™'],
  },
  {
    slug: 'microkappa',
    name: 'MICROKAPPA™',
    domain: 'Air Intake & Airflow Protection',
    tagline: 'Cabin air filtration technology for operator-environment protection.',
    engineeringPrinciple: 'MICROKAPPA™ applies cabin filtration media according to the operator environment, airflow requirement and HVAC system constraints.',
    contamination: ['Cabin airborne particulate contamination'],
    performanceSpecs: [],
    standards: [],
    relatedSystems: ['air-intake-protection'],
    relatedIndustries: [],
    worksWith: [],
  },
  {
    slug: 'drycore',
    name: 'DRYCORE™',
    domain: 'Air Intake & Airflow Protection',
    tagline: 'Air-dryer filtration technology for pneumatic brake-system protection.',
    engineeringPrinciple: 'DRYCORE™ controls moisture in compressed-air circuits to support pneumatic brake-system reliability.',
    contamination: ['Moisture in compressed air'],
    performanceSpecs: [],
    standards: [],
    relatedSystems: ['air-intake-protection'],
    relatedIndustries: [],
    worksWith: [],
  },
  {
    slug: 'intekcore',
    name: 'INTEKCORE™',
    domain: 'Air Intake & Airflow Protection',
    tagline: 'Air intake housing technology for controlled airflow and sealing integrity.',
    engineeringPrinciple: 'INTEKCORE™ integrates housing geometry, element retention and sealing to preserve the protected intake boundary.',
    contamination: ['Unfiltered-air bypass risk'],
    performanceSpecs: [],
    standards: ['ISO 5011'],
    relatedSystems: ['air-intake-protection'],
    relatedIndustries: [],
    worksWith: ['MACROCORE™'],
  },
  {
    slug: 'syntapore',
    name: 'SYNTAPORE™',
    domain: 'Fuel Cleanliness Protection',
    tagline: 'Fuel filtration technology for primary, secondary and cartridge applications.',
    engineeringPrinciple: 'SYNTAPORE™ supports staged particulate contamination control within approved diesel fuel filtration applications.',
    contamination: ['Fuel particulate contamination'],
    performanceSpecs: [],
    standards: [],
    relatedSystems: ['fuel-cleanliness-protection'],
    relatedIndustries: [],
    worksWith: ['HYDROCORE™'],
  },
  {
    slug: 'hydrocore',
    name: 'HYDROCORE™',
    domain: 'Fuel Cleanliness Protection',
    tagline: 'Fuel/water separation technology across standard spin-on/cartridge separators and approved Turbine Series FH/FG applications.',
    engineeringPrinciple: 'HYDROCORE™ controls water carryover in diesel fuel through separation media selected around flow, contamination load, service condition and the approved separator architecture, standard or turbine-style.',
    contamination: ['Free water in diesel fuel', 'Emulsified water where supported by the validated product configuration', 'Water contamination in approved turbine applications'],
    performanceSpecs: [],
    standards: [],
    relatedSystems: ['fuel-cleanliness-protection'],
    relatedIndustries: [],
    worksWith: ['SYNTAPORE™'],
  },
  {
    slug: 'syntrax',
    name: 'SYNTRAX™',
    domain: 'Lubrication Protection',
    tagline: 'Lubrication filtration technology for component protection.',
    engineeringPrinciple: 'SYNTRAX™ controls lubricant contamination through filtration selected for the engine duty cycle and service conditions.',
    contamination: ['Lubricant particulate contamination'],
    performanceSpecs: [],
    standards: [],
    relatedSystems: ['lubrication-protection'],
    relatedIndustries: [],
    worksWith: [],
  },
  {
    slug: 'nanoforce',
    name: 'NANOFORCE™',
    domain: 'Hydraulic Protection',
    tagline: 'Hydraulic filtration technology for fluid cleanliness and component protection.',
    engineeringPrinciple: 'NANOFORCE™ supports hydraulic contamination control by matching filtration performance to the cleanliness requirement and system duty.',
    contamination: ['Hydraulic-fluid particulate contamination'],
    performanceSpecs: [],
    standards: ['ISO 16889', 'ISO 4406'],
    relatedSystems: ['hydraulic-protection'],
    relatedIndustries: [],
    worksWith: [],
  },
  {
    slug: 'thermacore',
    name: 'THERMACORE™',
    domain: 'Cooling System Protection',
    tagline: 'Coolant filtration technology for cooling-system cleanliness and component protection.',
    engineeringPrinciple: 'THERMACORE™ supports cooling-system protection through coolant filtration selected for the approved engine and maintenance requirements.',
    contamination: ['Cooling-system particulate contamination'],
    performanceSpecs: [],
    standards: [],
    relatedSystems: ['cooling-system-protection'],
    relatedIndustries: [],
    worksWith: [],
  },
];