/**
 * ELIMFILTERS Knowledge Center — canonical technology registry.
 * This file is the public source of truth for active technology names.
 */

import type { KCTechnology } from './types';

export const KC_TECHNOLOGIES: KCTechnology[] = [
  {
    slug: 'macrocore',
    name: 'MACROCORE™',
    domain: 'Air Intake & Airflow Protection Systems',
    tagline: 'Engine air-filtration technology for severe-duty contamination control.',
    engineeringPrinciple: 'MACROCORE™ is the ELIMFILTERS air-filtration technology for primary and secondary engine air-cleaning applications. Media construction, efficiency, restriction, dust-holding capacity and service limits are product-specific and must be verified against the applicable product data and test method.',
    contamination: ['Airborne mineral dust', 'Silica-bearing particulate', 'Soot and environmental debris'],
    performanceSpecs: [{ label: 'Performance basis', value: 'Product-specific; verify applicable ISO 5011 test data' }],
    standards: ['ISO 5011'],
    relatedSystems: ['air-intake-protection'],
    relatedIndustries: ['mining', 'construction', 'agriculture', 'oil-gas', 'power-generation', 'truck-fleets'],
    worksWith: ['INTEKCORE™'],
  },
  {
    slug: 'microkappa',
    name: 'MICROKAPPA™',
    domain: 'Air Intake & Airflow Protection Systems',
    tagline: 'Cabin-air filtration technology for operator-environment contamination control.',
    engineeringPrinciple: 'MICROKAPPA™ is the ELIMFILTERS cabin-air filtration technology. Particle, odor and gas-removal capability depends on the specific media configuration and application; product-level claims require corresponding validated data.',
    contamination: ['Cabin particulate', 'Fine airborne dust', 'Application-dependent odor and vapor contaminants'],
    performanceSpecs: [{ label: 'Performance basis', value: 'Product-specific; verify applicable cabin-air test data' }],
    standards: ['ISO 11155'],
    relatedSystems: ['air-intake-protection'],
    relatedIndustries: ['mining', 'construction', 'agriculture', 'automotive', 'bus-coach'],
    worksWith: [],
  },
  {
    slug: 'drycore',
    name: 'DRYCORE™',
    domain: 'Air Intake & Airflow Protection Systems',
    tagline: 'Air-dryer protection technology for compressed-air systems.',
    engineeringPrinciple: 'DRYCORE™ is the ELIMFILTERS technology family for air-dryer and compressed-air contamination-control applications. Moisture-management and particulate performance depend on the specific dryer, cartridge and operating conditions.',
    contamination: ['Moisture', 'Compressor carryover', 'Particulate contamination'],
    performanceSpecs: [{ label: 'Performance basis', value: 'Application-specific; verify cartridge and system specifications' }],
    standards: ['ISO 8573-1'],
    relatedSystems: ['air-intake-protection'],
    relatedIndustries: ['truck-fleets', 'bus-coach', 'construction'],
    worksWith: [],
  },
  {
    slug: 'intekcore',
    name: 'INTEKCORE™',
    domain: 'Air Intake & Airflow Protection Systems',
    tagline: 'Air-intake housing and airflow-management technology.',
    engineeringPrinciple: 'INTEKCORE™ covers ELIMFILTERS air-intake housings and related airflow-management components. Housing sealing, restriction control, pre-cleaning and service configuration must be evaluated as a complete intake system.',
    contamination: ['Coarse airborne debris', 'Dust ingress through intake systems', 'Seal-bypass risk'],
    performanceSpecs: [{ label: 'Performance basis', value: 'Housing- and application-specific' }],
    standards: ['ISO 5011'],
    relatedSystems: ['air-intake-protection'],
    relatedIndustries: ['mining', 'construction', 'agriculture', 'oil-gas'],
    worksWith: ['MACROCORE™'],
  },
  {
    slug: 'syntapore',
    name: 'SYNTAPORE™',
    domain: 'Fuel Cleanliness Protection Systems',
    tagline: 'Fuel-filtration technology for primary and secondary spin-on and cartridge filters.',
    engineeringPrinciple: 'SYNTAPORE™ is the canonical ELIMFILTERS technology for diesel fuel filters used as primary or secondary stages in spin-on and cartridge configurations. Product-specific particle efficiency, water-management capability, pressure loss, flow capacity and service interval must be supported by the applicable validated product data.',
    contamination: ['Diesel-fuel particulate', 'Storage and handling debris', 'Application-dependent water contamination'],
    performanceSpecs: [{ label: 'Application scope', value: 'Primary and secondary fuel filtration; spin-on and cartridge formats' }],
    standards: ['ISO 4020', 'ISO 16332'],
    relatedSystems: ['fuel-cleanliness-protection'],
    relatedIndustries: ['mining', 'construction', 'agriculture', 'truck-fleets', 'marine', 'oil-gas', 'power-generation', 'railway'],
    worksWith: ['TURBOCORE™'],
  },
  {
    slug: 'turbocore',
    name: 'TURBOCORE™',
    domain: 'Fuel Cleanliness Protection Systems',
    tagline: 'FH/FG turbine fuel-filtration and fuel/water-separation technology.',
    engineeringPrinciple: 'TURBOCORE™ is the canonical ELIMFILTERS technology for FH and FG turbine-style fuel filtration and water-separation assemblies. Its scope includes 1000FH, 900FH and 500FG assemblies and the corresponding 2010, 2040 and 2020 element families in 30, 10 and 2 micron grades where applicable. Flow, separation efficiency, restriction and service limits are model- and element-specific and must be verified against validated product data.',
    contamination: ['Diesel-fuel particulate', 'Free water', 'Entrained water'],
    performanceSpecs: [
      { label: 'Assembly families', value: '1000FH · 900FH · 500FG' },
      { label: 'Element families', value: '2010 · 2040 · 2020' },
      { label: 'Available micron grades', value: '30 · 10 · 2 µm, as applicable' },
    ],
    standards: ['ISO 16332'],
    relatedSystems: ['fuel-cleanliness-protection'],
    relatedIndustries: ['power-generation', 'mining', 'agriculture', 'truck-fleets', 'construction', 'marine', 'oil-gas'],
    worksWith: ['SYNTAPORE™'],
  },
  {
    slug: 'thermacore',
    name: 'THERMACORE™',
    domain: 'Cooling System Protection',
    tagline: 'Cooling-system filtration and coolant-protection technology.',
    engineeringPrinciple: 'THERMACORE™ is the ELIMFILTERS technology for coolant-filtration and cooling-system protection. Filtration, additive-management and compatibility characteristics depend on the specific product and coolant chemistry and must be supported by application-specific data.',
    contamination: ['Corrosion products', 'Scale and suspended solids', 'Cooling-system debris'],
    performanceSpecs: [{ label: 'Performance basis', value: 'Product- and coolant-chemistry-specific' }],
    standards: ['ASTM D6210', 'ASTM D3306'],
    relatedSystems: ['cooling-system-protection'],
    relatedIndustries: ['mining', 'construction', 'truck-fleets', 'agriculture', 'power-generation'],
    worksWith: [],
  },
  {
    slug: 'syntrax',
    name: 'SYNTRAX™',
    domain: 'Lube/Oil Protection Systems',
    tagline: 'Lubrication-filtration technology for engine and equipment oil circuits.',
    engineeringPrinciple: 'SYNTRAX™ is the ELIMFILTERS lubrication-filtration technology. Efficiency, capacity, bypass characteristics and service interval are product-specific and must be evaluated against the applicable lubricant, duty cycle and validated test data.',
    contamination: ['Wear particles', 'Combustion-derived solids', 'External particulate ingress'],
    performanceSpecs: [{ label: 'Performance basis', value: 'Product-specific; verify applicable test data' }],
    standards: ['ISO 16889', 'SAE J1858'],
    relatedSystems: ['lubrication-protection'],
    relatedIndustries: ['mining', 'construction', 'agriculture', 'truck-fleets', 'marine', 'oil-gas', 'railway', 'power-generation'],
    worksWith: [],
  },
  {
    slug: 'nanoforce',
    name: 'NANOFORCE™',
    domain: 'Hydraulic Protection Systems',
    tagline: 'Hydraulic-filtration technology for contamination-sensitive fluid-power systems.',
    engineeringPrinciple: 'NANOFORCE™ is the ELIMFILTERS hydraulic-filtration technology. Required efficiency, collapse resistance, pressure rating and target cleanliness must be selected for the specific hydraulic circuit and supported by the applicable product and test data.',
    contamination: ['Hard particulate', 'Wear debris', 'External ingress'],
    performanceSpecs: [{ label: 'Performance basis', value: 'Circuit- and product-specific; verify ISO 16889 data where applicable' }],
    standards: ['ISO 16889', 'ISO 4406'],
    relatedSystems: ['hydraulic-protection'],
    relatedIndustries: ['mining', 'construction', 'agriculture', 'manufacturing', 'oil-gas', 'marine'],
    worksWith: [],
  },
  {
    slug: 'marineclean',
    name: 'MARINECLEAN™',
    domain: 'Marine Filtration Ecosystem',
    tagline: 'Marine application architecture for coordinated filtration protection.',
    engineeringPrinciple: 'MARINECLEAN™ identifies ELIMFILTERS marine application architecture across relevant filtration domains. Product selection remains governed by the underlying protection system, equipment requirements and validated application data.',
    contamination: ['Marine-environment particulate', 'Fuel and fluid contamination', 'Salt-laden environmental exposure'],
    performanceSpecs: [{ label: 'Performance basis', value: 'Application-specific; governed by underlying product technologies' }],
    standards: [],
    relatedSystems: ['air-intake-protection', 'fuel-cleanliness-protection', 'lubrication-protection', 'hydraulic-protection', 'cooling-system-protection'],
    relatedIndustries: ['marine'],
    worksWith: ['MACROCORE™', 'SYNTAPORE™', 'TURBOCORE™', 'SYNTRAX™', 'NANOFORCE™', 'THERMACORE™'],
  },
  {
    slug: 'duractech',
    name: 'DURACTECH™',
    domain: 'Severe-Duty Filtration Architecture',
    tagline: 'Coordinated severe-duty filtration architecture for demanding service environments.',
    engineeringPrinciple: 'DURACTECH™ identifies coordinated severe-duty filtration architecture across multiple ELIMFILTERS protection systems. It does not replace the underlying technology-specific performance requirements.',
    contamination: ['High contaminant loading', 'Severe-duty service exposure', 'Multi-system contamination risk'],
    performanceSpecs: [{ label: 'Performance basis', value: 'Defined by the underlying product technologies and application' }],
    standards: [],
    relatedSystems: ['air-intake-protection', 'fuel-cleanliness-protection', 'lubrication-protection', 'hydraulic-protection', 'cooling-system-protection'],
    relatedIndustries: ['mining', 'construction', 'agriculture', 'truck-fleets', 'waste-municipal'],
    worksWith: ['MACROCORE™', 'SYNTAPORE™', 'TURBOCORE™', 'SYNTRAX™', 'NANOFORCE™', 'THERMACORE™'],
  },
];
