'use client';

import '@/i18n';
import Link from 'next/link';
import { motion } from 'motion/react';
import { Navigation } from '@/components/Navigation';
import { Footer } from '@/components/Footer';

const SECTIONS = [
  { title: '1. Scope and Controller', body: `Kleo Technology LLC, a Texas limited liability company operating the ELIMFILTERS brand and digital platforms, is the controller responsible for the processing described in this Privacy Policy. This Policy explains how ELIMFILTERS collects, uses, discloses, retains, and protects information across elimfilters.com, Part Search, the Knowledge System, distributor tools, APIs, web chat, email, WhatsApp, Instagram, Facebook, LinkedIn, and other ELIMFILTERS-operated digital services.` },
  { title: '2. Information We Collect', body: `Depending on your interaction, we may collect contact and identity information; company, role, country, and distributor information; account and authentication data; equipment, vehicle, engine, OEM-reference, operating-condition, maintenance, warranty, quotation, order, and support information; search queries and navigation activity; AI and bot conversations; files, photographs, and technical documents you submit; device, browser, IP address, approximate location, logs, identifiers, cookie choices, and diagnostic information; and records required for security, fraud prevention, legal compliance, and dispute resolution.` },
  { title: '3. Sources of Information', body: `Information may come directly from you, your employer or distributor organization, authorized partners, platform activity, connected communication channels, service providers, public business sources, and lawful third-party product or equipment data. Do not submit personal or confidential information that is unnecessary for the requested service.` },
  { title: '4. Purposes of Processing', body: `We use information to operate and secure the services; authenticate users; answer technical, sales, warranty, support, and distributor inquiries; provide search, cross-reference, quotation, and product recommendations; process communications and commercial requests; personalize and improve content; detect abuse and attacks; maintain audit records; comply with law and contracts; enforce policies; protect rights and safety; and develop, test, evaluate, and improve ELIMFILTERS systems.` },
  { title: '5. AI and Automated Systems', body: `AI-assisted features may process prompts, conversation history, equipment details, search results, and supporting documents. Outputs may be generated automatically and may not be reviewed by a person. Interactions may be logged for service delivery, quality evaluation, safety, security, audit, troubleshooting, and improvement. ELIMFILTERS does not intend for users to submit regulated data, unnecessary sensitive personal information, or third-party trade secrets. Automated recommendations do not replace application-specific human validation.` },
  { title: '6. Service Providers and Other Disclosures', body: `We may disclose information to providers supporting hosting, databases, content delivery, security, monitoring, analytics, artificial intelligence, communications, email, customer relationship management, payments, logistics, and professional services. Current analytics may include Google Analytics 4, PostHog, and Microsoft Clarity when consent is provided. Communications may be processed through Microsoft 365 and Meta-operated channels such as WhatsApp, Instagram, or Facebook. Regional inquiry information may be shared with an authorized ELIMFILTERS distributor where necessary to provide requested local support. We may also disclose information for legal compliance, corporate transactions, protection of rights, or with your direction or consent. We do not sell personal information for monetary consideration.` },
  { title: '7. Advertising and Profiling', body: `ELIMFILTERS does not currently disclose personal information to data brokers or use personal information for cross-context behavioral advertising. If these practices change, we will update this Policy and provide legally required notices and opt-out mechanisms before applying the change to covered information.` },
  { title: '8. Legal Bases for International Users', body: `Where a legal basis is required, processing may rely on performance of a contract or requested pre-contract steps, compliance with legal obligations, legitimate interests in operating and protecting industrial services, consent for optional analytics or marketing, and establishment or defense of legal claims. Consent may be withdrawn without affecting processing already lawfully performed.` },
  { title: '9. Cookies and Analytics', body: `Strictly necessary technologies support security, sessions, language, and consent storage. Optional analytics should load only after consent. Analytics providers may receive technical identifiers and usage information. Details are provided in the Cookie Policy. Browser controls may also block or delete cookies, although doing so can impair functionality.` },
  { title: '10. Retention', body: `We retain information only as long as reasonably necessary for the purpose collected, contractual obligations, account administration, support history, security, audit, fraud prevention, warranty or transaction records, legal claims, and applicable law. Retention varies by category. Information may be deleted, aggregated, or de-identified when no longer required. Distributor and commercial records may be retained after termination where required by contract, tax, accounting, warranty, or limitation periods.` },
  { title: '11. Security', body: `ELIMFILTERS uses reasonable administrative, technical, and organizational safeguards appropriate to the nature of the information, including encrypted transmission, access controls, credential protection, logging, least-privilege practices, backups, and security review. No system is completely secure. Users must protect credentials and promptly report suspected compromise.` },
  { title: '12. International Transfers', body: `ELIMFILTERS and its providers may process information in the United States and other countries where infrastructure or personnel are located. Where required, transfers are supported by contractual, organizational, or other legally recognized safeguards. Privacy protections and government-access rules may differ between countries.` },
  { title: '13. Your Privacy Rights', body: `Depending on applicable law, you may request access, correction, deletion, portability, restriction, or information about processing; object to certain processing; withdraw consent; and opt out of covered sale, targeted advertising, or profiling practices if introduced. We may verify identity and authority before acting. Authorized agents may be required to provide proof of authorization. Some requests may be limited by legal, security, contractual, evidentiary, or operational exceptions.` },
  { title: '14. Requests and Appeals', body: `Submit a privacy request to info@elimfilters.com and identify the account, communication channel, or interaction involved. We will respond within the period required by applicable law. If a covered request is denied, you may appeal by replying with “Privacy Appeal” and explaining the basis for reconsideration. We will provide the result and any further complaint options required by law.` },
  { title: '15. Children', body: `The services are intended for business and industrial users and are not directed to children. ELIMFILTERS does not knowingly collect personal information from children under 13. If you believe a child submitted information, contact us so it can be reviewed and deleted where appropriate.` },
  { title: '16. Third-Party Services', body: `Links, embedded tools, social platforms, and communication channels operated by third parties are governed by their own privacy practices. ELIMFILTERS is not responsible for independent third-party processing outside its control.` },
  { title: '17. Changes and Contact', body: `Kleo Technology LLC may update this Policy when ELIMFILTERS services, providers, laws, or practices change. Material revisions will be identified by the effective date and, where appropriate, additional notice or renewed consent. Privacy questions and requests may be sent to info@elimfilters.com.` },
];

const RELATED = [
  { label:'Terms of Service', href:'/legal/terms' },
  { label:'Cookie Policy', href:'/legal/cookies' },
  { label:'Acceptable Use Policy', href:'/legal/acceptable-use' },
  { label:'AI Use Policy', href:'/legal/ai-policy' },
  { label:'Copyright & DMCA Policy', href:'/legal/copyright' },
];

export default function PrivacyPolicyPage() {
  return <><Navigation /><main style={{ background:'#000', color:'#fff', minHeight:'100vh' }}>
    <div style={{ padding:'1.5rem 8%', borderBottom:'1px solid rgba(255,255,255,0.04)' }}><Link href="/" style={{ fontFamily:'JetBrains Mono, monospace', fontSize:'0.72rem', letterSpacing:'0.14em', color:'rgba(255,255,255,0.4)', textDecoration:'none' }}>← ELIMFILTERS</Link></div>
    <section style={{ padding:'4rem 8% 3rem', borderBottom:'1px solid rgba(255,241,45,0.08)' }}><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:0.5}}><p style={{ fontFamily:'JetBrains Mono, monospace', fontSize:'0.7rem', letterSpacing:'0.18em', color:'#FFF12D', opacity:0.8, marginBottom:'1rem', textTransform:'uppercase' }}>{'// Legal · Privacy'}</p><h1 style={{ fontFamily:'var(--font-body)', fontWeight:700, fontSize:'clamp(2rem, 4vw, 3rem)', margin:'0 0 1rem' }}>Privacy Policy</h1><p style={{ color:'rgba(255,255,255,0.45)', margin:0 }}>Last updated: August 2026</p></motion.div></section>
    <div style={{ maxWidth:'820px', margin:'0 auto', padding:'4rem 8%' }}>{SECTIONS.map((s,i)=><section key={i} style={{ marginBottom:'2.5rem', paddingBottom:'2.5rem', borderBottom:'1px solid rgba(255,255,255,0.05)' }}><h2 style={{ fontSize:'1.05rem', color:'#FFF12D', marginBottom:'0.9rem' }}>{s.title}</h2><p style={{ fontSize:'0.92rem', color:'rgba(255,255,255,0.7)', lineHeight:1.8 }}>{s.body}</p></section>)}<div style={{ display:'flex', flexWrap:'wrap', gap:'0.75rem' }}>{RELATED.map(r=><Link key={r.href} href={r.href} style={{ fontSize:'0.82rem', color:'rgba(255,255,255,0.6)', textDecoration:'none', padding:'0.4rem 0.85rem', border:'1px solid rgba(255,255,255,0.1)', borderRadius:'4px' }}>{r.label}</Link>)}</div></div>
  </main><Footer /></>;
}
