-- =============================================================================
-- KG PHASE 4 — SEED SYSTEM AND CONTAMINATION MODE CANONICAL BLOCKS
-- File: 003_seed_system_blocks.sql
-- Purpose: Insert canonical definitions for 6 filtration systems + 5 contamination modes
-- Safe to run: YES (ON CONFLICT DO UPDATE — idempotent, increments version)
-- Depends on: 001_schema.sql, 002_seed_technology_blocks.sql
-- Affects elimfilters_catalog: NO
--
-- Section A: 6 filtration system canonical blocks
-- Section B: 5 contamination mode canonical blocks
--
-- Standards per system (from SEMANTIC_RULES_REPORT.md §8):
--   lube-oil:       ISO 16889, ISO 4406, SAE J1211
--   air-intake:     SAE J1539, ISO 5011, SAE J726
--   cabin:          ISO 11155, DIN 71220
--   fuel:           ASTM D6304, ISO 12937
--   hydraulic:      ISO 16889, NFPA T2.14, DIN 51524, ISO 4406
--   compressed-air: ISO 8573-1, ISO 8573-2, ISO 8573-3
-- =============================================================================


-- =============================================================================
-- SECTION A — FILTRATION SYSTEM CANONICAL BLOCKS (6 rows)
-- =============================================================================

-- ─── A1. LUBE / OIL FILTRATION SYSTEM ────────────────────────────────────────

INSERT INTO kg_canonical_blocks (
  concept_slug, concept_type, display_name,
  definition,
  system_context,
  failure_mechanism,
  industrial_impact,
  related_standards,
  related_technologies,
  industrial_role,
  citation_url
) VALUES (
  'lube-oil', 'system', 'Lube / Oil Filtration Systems',

  'Lube oil filtration systems maintain ISO 4406 particle cleanliness codes in diesel
engine crankcase oil, transmission fluid, and bearing lubrication circuits by removing
particulate contamination generated by combustion, component wear, and ingested
atmospheric dust through full-flow and bypass filtration stages.',

  'Applies to all internal combustion engines, automatic and manual transmissions,
final drive assemblies, and bearing lubrication circuits in off-highway and on-highway
equipment. Critical systems: diesel engine crankcase (SAE 15W-40, SAE 5W-40 oils),
transmission fluid circuits (Allison TES-295, ZF TE-ML), gear oil circuits (SAE 85W-140,
SAE 80W-90), and bearing forced-lubrication systems. Operating temperature range: 80–120°C
continuous for engine oil, 80–130°C for transmission fluid.',

  'Particle contamination in lube oil above ISO 4406 code 18/16/13 (vs. target 16/14/11)
introduces hard abrasive particles (silica 1–20µm, metallic oxides 1–50µm) into oil
film between bearing journal and shell → micro-cutting wear on bearing surface →
bearing clearance increase → oil film breakdown under load → metal-to-metal contact
→ bearing seizure. Combustion-generated soot (0.01–0.1µm) in diesel engine oil
increases oil viscosity → reduced oil circulation → cold-start lubrication delay.
Acidic combustion products in oil exceed base number (BN) reserve → corrosive attack
on bearing alloys (lead, copper) → corrosive wear.',

  'Optimal ISO 16/14/11 cleanliness targets extend engine bearing life 3–5× versus
uncontrolled ISO 19/17/14 operation: 15,000–25,000 hours vs. 2,000–3,000 hours. Oil
consumption increase from particle wear: +15–40%. Engine blow-by from ring wear:
+5–10%. Fuel economy degradation from increased friction: -5–12%. Compression ratio
drop from cylinder bore wear: -10–25%. Equipment availability without lube contamination
control: -15–25%. Engine overhaul frequency at ISO 16/14/11: 1 per 15,000–25,000 hours
vs. 1 per 3,000–5,000 hours at ISO 19/17/14.',

  '[
    {"code": "ISO 16889", "scope": "Multi-pass filter performance test for lube oil — Beta ratio at 10µm, 12µm absolute"},
    {"code": "ISO 4406", "scope": "Particle cleanliness code classification — 3-number code for 4µm, 6µm, 14µm particle channels"},
    {"code": "SAE J1211", "scope": "Crankcase ventilation — oil carryover and blow-by measurement standards for diesel engines"}
  ]'::jsonb,

  '[
    {"slug": "syntrax", "mechanism": "Synthetic lube oil media — extended drain interval capability, ISO 16/14/11 maintenance"},
    {"slug": "duratech", "mechanism": "Extended lifecycle media — maintains Beta ratio performance over 1,000-hour drain intervals"},
    {"slug": "THERMACORE", "mechanism": "Coolant filtration on same engine platform — prevents coolant-oil cross-contamination"},
    {"slug": "marineclean", "mechanism": "Marine lube oil filtration — accounts for salt-air and humidity contamination profile"}
  ]'::jsonb,

  'Lube oil contamination control is the single largest controllable factor in engine
bearing and transmission component lifespan; ISO 4406 code selection determines
whether equipment operates 15,000+ hours (system approach) or 2,000–3,000 hours
(commodity approach) between major overhauls.',

  '/knowledge-system/standards/lube-oil-systems'
)
ON CONFLICT (concept_slug, concept_type) DO UPDATE SET
  definition           = EXCLUDED.definition,
  system_context       = EXCLUDED.system_context,
  failure_mechanism    = EXCLUDED.failure_mechanism,
  industrial_impact    = EXCLUDED.industrial_impact,
  related_standards    = EXCLUDED.related_standards,
  related_technologies = EXCLUDED.related_technologies,
  industrial_role      = EXCLUDED.industrial_role,
  citation_url         = EXCLUDED.citation_url,
  version              = kg_canonical_blocks.version + 1,
  last_updated         = CURRENT_DATE,
  updated_at           = NOW();


-- ─── A2. AIR INTAKE FILTRATION SYSTEM ────────────────────────────────────────

INSERT INTO kg_canonical_blocks (
  concept_slug, concept_type, display_name,
  definition,
  system_context,
  failure_mechanism,
  industrial_impact,
  related_standards,
  related_technologies,
  industrial_role,
  citation_url
) VALUES (
  'air-intake', 'system', 'Air Intake Filtration Systems',

  'Air intake filtration systems remove atmospheric particulate contamination from
combustion air supplied to diesel and gasoline engines, maintaining intake air cleanliness
to SAE J1539 and ISO 5011 efficiency standards to prevent abrasive particle ingestion
that causes accelerated cylinder bore and piston ring wear.',

  'Applies to all internal combustion engines requiring filtered combustion air. Critical
systems: primary air filter (cellulose or synthetic media, 15–25µm nominal efficiency),
safety/secondary element (HEPA-class backup), pre-cleaner stage (centrifugal separation,
50–80% bulk removal). Equipment categories: agricultural tractors (1,000–400 hp),
mining haul trucks (1,000–4,000 hp), construction excavators (100–700 hp), diesel
generators (50–5,000 kW), marine propulsion diesels. Ambient particulate conditions:
0.001 g/m³ (clean air) to 5+ g/m³ (active construction, mining blast areas).',

  'Insufficient air intake filtration allows atmospheric silica particles (quartz, 0.5–80µm,
Mohs hardness 7) to enter combustion chamber → particle impingement on piston crown
and cylinder bore surface → two-body abrasive wear on cast iron or chrome bore coating
→ bore ovality → ring-to-bore seal loss → compression pressure drop → blow-by increase
→ oil contamination with combustion gases → oil degradation acceleration. Filter bypass
from collapsed element or improper sealing introduces bulk dust → catastrophic wear in
50–200 hours. Air restriction above engine manufacturer limit (typically 625–750 mm H₂O)
reduces volumetric efficiency → power loss → fuel consumption increase.',

  'Air intake filtration failure causing accelerated bore wear reduces engine compression
by -10–25%. Oil consumption increase from bore wear: +15–40%. Fuel economy degradation
from reduced compression and increased friction: -5–12%. Engine blow-by increase:
+5–10%. Equipment availability without effective air intake filtration in dusty
environments: -15–25%. Engine rebuild interval: 3,000–5,000 hours (uncontrolled) vs.
10,000–15,000+ hours (controlled). Air filter restriction monitoring is standard on
all modern diesel engines; service at 500–750 mm H₂O restriction limit.',

  '[
    {"code": "SAE J1539", "scope": "Air cleaner element test procedure for highway vehicle engines — particulate efficiency, restriction, dust capacity"},
    {"code": "ISO 5011", "scope": "Inlet air cleaning equipment for internal combustion engines — test methods for efficiency and dust capacity"},
    {"code": "SAE J726", "scope": "Air cleaner test code for off-highway engines — applicable to agricultural, construction, mining equipment"}
  ]'::jsonb,

  '[
    {"slug": "macrocore", "mechanism": "Primary air filtration media — 18µm absolute efficiency, high dust capacity for heavy-duty applications"},
    {"slug": "intekcore", "mechanism": "Pre-cleaner stage — 60–80% bulk particulate removal before primary filter, extends service intervals 2–3×"}
  ]'::jsonb,

  'Air intake filtration is the primary defense against atmospheric silica ingestion, which
is the leading cause of premature cylinder bore wear in off-highway diesel engines;
filtration system design (pre-cleaner + primary element) determines whether engine
service life meets or falls short of 10,000-hour design targets.',

  '/knowledge-system/standards/air-intake-systems'
)
ON CONFLICT (concept_slug, concept_type) DO UPDATE SET
  definition           = EXCLUDED.definition,
  system_context       = EXCLUDED.system_context,
  failure_mechanism    = EXCLUDED.failure_mechanism,
  industrial_impact    = EXCLUDED.industrial_impact,
  related_standards    = EXCLUDED.related_standards,
  related_technologies = EXCLUDED.related_technologies,
  industrial_role      = EXCLUDED.industrial_role,
  citation_url         = EXCLUDED.citation_url,
  version              = kg_canonical_blocks.version + 1,
  last_updated         = CURRENT_DATE,
  updated_at           = NOW();


-- ─── A3. CABIN / OPERATOR SAFETY FILTRATION SYSTEM ───────────────────────────

INSERT INTO kg_canonical_blocks (
  concept_slug, concept_type, display_name,
  definition,
  system_context,
  failure_mechanism,
  industrial_impact,
  related_standards,
  related_technologies,
  industrial_role,
  citation_url
) VALUES (
  'cabin', 'system', 'Cabin / Operator Safety Filtration Systems',

  'Cabin air filtration systems maintain operator cab air quality within ISO 11155 and
DIN 71220 specifications by removing particulate matter (PM10, PM2.5), gaseous
contaminants (NOx, CO, VOCs, pesticides), and biological contaminants from
pressurized cab recirculation and fresh-air intake airstreams.',

  'Applies to enclosed operator cabs on heavy construction equipment, agricultural
machinery, mining vehicles, and forestry equipment operating in environments with
elevated particulate, chemical, or biological air contamination. Cab ventilation
systems: positive-pressure (cab maintained at +50–100 Pa above ambient to prevent
infiltration), HVAC-integrated filtration, recirculation + fresh-air combination.
Typical cab air volume: 3–8 m³. Air changes: 2–6 per hour for fresh-air mode.
Critical exposure environments: silica dust (construction, mining), pesticide
(agriculture), diesel exhaust (tunneling, underground mining).',

  'Cab air filtration failure or service interval exceedance → filter media blinding
→ cab pressure drop below +50 Pa → ambient air infiltration → PM10 and PM2.5
ingestion by operator → cumulative respirable silica exposure above OSHA PEL
50 µg/m³ (8h TWA) → silicosis risk (latency 5–10 years). Absence of activated
carbon stage in pesticide-exposure environments → organophosphate vapor ingestion
→ acute and chronic cholinergic effects. CO infiltration from engine exhaust above
35 ppm → cognitive impairment, safety risk. Chemical exposure at or above TLV
thresholds triggers occupational health liability and regulatory enforcement.',

  'Respirable silica occupational exposure limit (OSHA 29 CFR 1910.1053): 50 µg/m³
8h TWA. Silicosis medical surveillance program cost: $500–$2,000 per worker annually
for exposed workers. ISO 11155-1 requires ≥95% filtration efficiency at particles
above 1µm for cab certification compliance. DIN 71220 requires activated carbon test
compliance for chemical contaminant filtration. Cab air filter replacement interval:
500–1,000 hours in normal environments, 250–500 hours in high-dust environments.
Failure to maintain ISO 11155 compliance exposes equipment operators to long-term
respiratory disease risk and employers to occupational disease liability.',

  '[
    {"code": "ISO 11155", "scope": "Road vehicles — air filters for passenger compartments — Part 1: particulate test, Part 2: gaseous contaminant test"},
    {"code": "DIN 71220", "scope": "Cab air filtration for off-highway equipment — efficiency requirements for particle and gaseous contaminant removal"}
  ]'::jsonb,

  '[
    {"slug": "microkappa", "mechanism": "HEPA-class + activated carbon cab filtration — removes PM10, PM2.5, NOx, VOCs, pesticides per ISO 11155 and DIN 71220"}
  ]'::jsonb,

  'Cabin air filtration is a mandatory occupational health control; ISO 11155 and DIN
71220 compliance protects operators from respirable silica, diesel exhaust particulate,
and chemical exposure that causes chronic occupational disease with long latency
periods that make preventive filtration the only effective intervention.',

  '/knowledge-system/standards/cabin-safety-systems'
)
ON CONFLICT (concept_slug, concept_type) DO UPDATE SET
  definition           = EXCLUDED.definition,
  system_context       = EXCLUDED.system_context,
  failure_mechanism    = EXCLUDED.failure_mechanism,
  industrial_impact    = EXCLUDED.industrial_impact,
  related_standards    = EXCLUDED.related_standards,
  related_technologies = EXCLUDED.related_technologies,
  industrial_role      = EXCLUDED.industrial_role,
  citation_url         = EXCLUDED.citation_url,
  version              = kg_canonical_blocks.version + 1,
  last_updated         = CURRENT_DATE,
  updated_at           = NOW();


-- ─── A4. FUEL FILTRATION SYSTEM ───────────────────────────────────────────────

INSERT INTO kg_canonical_blocks (
  concept_slug, concept_type, display_name,
  definition,
  system_context,
  failure_mechanism,
  industrial_impact,
  related_standards,
  related_technologies,
  industrial_role,
  citation_url
) VALUES (
  'fuel', 'system', 'Fuel Filtration Systems',

  'Fuel filtration systems remove water, particulate contamination, and microbial
contamination from diesel fuel before delivery to high-pressure injection systems,
maintaining fuel cleanliness at ISO 12/9/6 or tighter (per common-rail injection
manufacturer specifications) and water content below 200 ppm per ASTM D6304.',

  'Applies to diesel fuel circuits from bulk storage through transfer pumps, fuel tanks,
pre-filters (water separation + coarse particle removal), secondary filters (fine
particle removal, 4–10µm), and high-pressure fuel pumps. Critical for common-rail
systems operating at 1,600–2,200 bar injection pressure with pump and injector
component clearances of 1–3µm. Equipment: agricultural combines, construction
excavators, mining haul trucks, marine propulsion, stationary power generation.
Fuel types: EN 590 diesel, biodiesel blends (B5–B20), synthetic diesel (HVO).',

  'Particle contamination at ISO code above 14/12/9 in fuel → abrasive wear on
high-pressure fuel pump plunger/barrel assembly (1–3µm clearance) → volumetric
efficiency loss → injection pressure shortfall → incomplete fuel atomization → increased
carbon deposits → injector spray tip erosion → long-term nozzle orifice enlargement
→ spray cone angle degradation → reduced combustion efficiency. Water above 200 ppm
→ accelerated corrosion of injection system steel components (chromium-molybdenum
alloys, carbon steel pump housings) → corrosive wear → contamination with corrosion
products → filter plugging cascade.',

  'Common-rail high-pressure fuel pump replacement cost: $600–$2,500. Injector set
replacement (6-cylinder engine): $1,200–$5,000. Fuel system contamination causes
30–40% of unplanned engine maintenance events in fleets without systematic fuel
filtration. Hard-start frequency increase from fuel contamination: +5–15 seconds
cold-start delay. Fuel consumption increase from degraded injection pattern: +3–8%.
Injector cleaning interval reduction from 5,000–8,000 hours (controlled) to
2,000–3,000 hours (contaminated). Equipment availability reduction: -8–15% from
fuel system failures.',

  '[
    {"code": "ASTM D6304", "scope": "Standard test method for determination of water in petroleum products by coulometric Karl Fischer titration — range 10–25,000 ppm"},
    {"code": "ISO 12937", "scope": "Petroleum products — determination of water by coulometric Karl Fischer titration — applicable to fuel water content verification"},
    {"code": "ISO 16889", "scope": "Filter element performance testing — Beta ratio at 4µm, 6µm, 10µm for fuel filtration applications"}
  ]'::jsonb,

  '[
    {"slug": "aquaguard", "mechanism": "Water separation — removes free and emulsified water before fine filtration stage"},
    {"slug": "SYNTAPORE", "mechanism": "Fuel particle filtration at 4–10µm absolute — protects common-rail injection system components"}
  ]'::jsonb,

  'Fuel filtration is the primary protection system for common-rail injection components
operating at 1,600–2,200 bar with 1–3µm clearances; fuel contamination damage to
high-pressure pumps and injectors is progressive and irreversible, making proactive
contamination control mandatory for the 10,000–15,000 hour service life of modern
diesel injection systems.',

  '/knowledge-system/standards/fuel-filtration-systems'
)
ON CONFLICT (concept_slug, concept_type) DO UPDATE SET
  definition           = EXCLUDED.definition,
  system_context       = EXCLUDED.system_context,
  failure_mechanism    = EXCLUDED.failure_mechanism,
  industrial_impact    = EXCLUDED.industrial_impact,
  related_standards    = EXCLUDED.related_standards,
  related_technologies = EXCLUDED.related_technologies,
  industrial_role      = EXCLUDED.industrial_role,
  citation_url         = EXCLUDED.citation_url,
  version              = kg_canonical_blocks.version + 1,
  last_updated         = CURRENT_DATE,
  updated_at           = NOW();


-- ─── A5. HYDRAULIC SYSTEM ─────────────────────────────────────────────────────

INSERT INTO kg_canonical_blocks (
  concept_slug, concept_type, display_name,
  definition,
  system_context,
  failure_mechanism,
  industrial_impact,
  related_standards,
  related_technologies,
  industrial_role,
  citation_url
) VALUES (
  'hydraulic', 'system', 'Hydraulic Systems',

  'Hydraulic systems transmit and control mechanical force via pressurized fluid, and
require ISO 4406 cleanliness codes of 16/14/11 to 17/15/12 to protect proportional
valve spools (2–8µm clearance), servo valve spools (1–3µm clearance), and variable-
displacement pump components from abrasive particle wear and fluid oxidation degradation.',

  'Applies to hydraulic circuits in mobile equipment (construction, agriculture, material
handling) and fixed plant installations. Circuit types: open-center (low-pressure return),
closed-center (constant pressure), load-sensing (variable pressure, proportional valves),
and servo-hydraulic (high-precision, servo valves). Operating pressures: 50–350 bar.
Fluid temperatures: 40–80°C continuous operation, up to 90°C transient peak.
Fluid types: ISO VG 32–68 mineral hydraulic oil, HFA-HFD fire-resistant fluids,
biodegradable esters (HEES). Component clearances: proportional valves 2–8µm,
servo valves 1–3µm, gear pumps 0.5–5µm, vane pumps 1–10µm.',

  'Particle contamination above ISO 4406 code 17/15/12 (vs. target 16/14/11 for
proportional valves) → particles entering valve spool-body clearance (2–8µm) →
surface abrasion of hardened valve spool → internal leakage increase (10–30%)
→ spool position accuracy loss → machine function inaccuracy → system pressure
variations → additional heat generation (+5–15 kW) → fluid temperature increase
(+20–30°C) → accelerated fluid oxidation → varnish precursor formation → varnish
deposition on servo valve spools → servo valve stiction. Fluid temperature above
80°C sustained accelerates oil oxidation 2–4× per 10°C.',

  'Hydraulic system contamination reduces equipment availability -15–30%. Unplanned
maintenance frequency: 1–2 events per 500 hours without cleanliness control.
System pressure increase from contamination: +10–30%. Heat generation increase:
+5–15 kW (additional cooling load). Fluid temperature increase: +20–30°C above
design. Proportional valve replacement cost: €800–€4,000 per valve. Servo valve
replacement: €2,000–€15,000. Hydraulic pump overhaul from contamination wear:
€500–€5,000. Maintaining ISO 16/14/11 extends proportional valve life 3–5× versus
operation at ISO 19/17/14.',

  '[
    {"code": "ISO 16889", "scope": "Multi-pass filter performance — Beta ratio determination at 3µm, 6µm, 12µm for hydraulic filtration"},
    {"code": "ISO 4406", "scope": "Fluid cleanliness code classification — 3-number code for hydraulic system contamination management"},
    {"code": "NFPA T2.14", "scope": "Hydraulic fluid power system cleanliness requirements for mobile and industrial equipment"},
    {"code": "DIN 51524", "scope": "Hydraulic fluid minimum requirements — HL, HLP, HVLP classifications for ISO VG 32–68 fluids"}
  ]'::jsonb,

  '[
    {"slug": "nanoforce", "mechanism": "Hydraulic filtration at Beta(x)[c]≥200 at 3µm — maintains ISO 16/14/11 cleanliness for proportional valve protection"},
    {"slug": "aquaguard", "mechanism": "Water separation from hydraulic fluid — water contamination reduces film strength and accelerates oxidation"}
  ]'::jsonb,

  'Hydraulic contamination control is the primary determinant of proportional and servo
valve service life; ISO 4406 cleanliness code selection and filtration system design
determine whether hydraulic components achieve their 10,000–20,000 hour design life
or require replacement every 2,000–3,000 hours.',

  '/knowledge-system/standards/hydraulic-systems'
)
ON CONFLICT (concept_slug, concept_type) DO UPDATE SET
  definition           = EXCLUDED.definition,
  system_context       = EXCLUDED.system_context,
  failure_mechanism    = EXCLUDED.failure_mechanism,
  industrial_impact    = EXCLUDED.industrial_impact,
  related_standards    = EXCLUDED.related_standards,
  related_technologies = EXCLUDED.related_technologies,
  industrial_role      = EXCLUDED.industrial_role,
  citation_url         = EXCLUDED.citation_url,
  version              = kg_canonical_blocks.version + 1,
  last_updated         = CURRENT_DATE,
  updated_at           = NOW();


-- ─── A6. COMPRESSED AIR SYSTEM ───────────────────────────────────────────────

INSERT INTO kg_canonical_blocks (
  concept_slug, concept_type, display_name,
  definition,
  system_context,
  failure_mechanism,
  industrial_impact,
  related_standards,
  related_technologies,
  industrial_role,
  citation_url
) VALUES (
  'compressed-air', 'system', 'Compressed Air Systems',

  'Compressed air systems deliver treated, contaminant-free air to pneumatic tools,
control instruments, and process applications at purity levels defined by ISO 8573-1
classes (particle, water, and oil content), requiring coalescing filtration, desiccant
drying, and/or activated carbon treatment to remove liquid water, oil aerosol, water
vapor, and particulate contamination from compressor discharge air.',

  'Applies to industrial compressed air distribution systems downstream of reciprocating,
rotary screw, or centrifugal compressors. Air treatment train components: aftercooler
(bulk water removal), pre-filter coalescer (liquid water and bulk oil removal), refrigerant
or desiccant dryer (moisture reduction to dew point specification), fine coalescer
(oil aerosol removal), activated carbon filter (oil vapor removal for Class 1 oil purity).
Applications: pneumatic control systems, air tools, spray painting, food/beverage
processing, pharmaceutical manufacturing, instrument air, vehicle air brakes.
Operating pressures: 4–16 bar. Flow rates: 1–10,000+ Nm³/h.',

  'Water vapor condensation in compressed air distribution pipework (dew point > ambient
temperature) → liquid water accumulates in low points → freezing in winter conditions
→ valve and actuator freeze-up → process stoppage. Oil carryover from compressor
(without filtration: 0.5–10 mg/m³) → oil film deposition on pneumatic valve seats
→ valve flow coefficient degradation → actuator response slowdown → process control
inaccuracy. Particulate contamination (rust, scale from steel pipework) → pneumatic
component abrasion → valve and cylinder wear → leakage increase.',

  'ISO 8573-1 purity class requirements by application:
Class 1 (≤0.01 mg/m³ oil, -70°C dew point): pharmaceutical, food contact surfaces.
Class 2 (≤0.1 mg/m³ oil, -40°C dew point): instrument air, precision assembly.
Class 4 (≤5 mg/m³ oil, +3°C dew point): general manufacturing, air tools.
Unfiltered compressor air oil carryover: 2–5 mg/m³. Required removal to Class 1:
99.8% efficiency. Compressed air dryer installation payback versus valve replacement
and downtime: 6–18 months in high-humidity environments. Food-grade air non-compliance
under EU Regulation 1935/2004: product recall liability.',

  '[
    {"code": "ISO 8573-1", "scope": "Compressed air purity classes — specifies maximum concentrations for particles, water (dew point and liquid), and oil (aerosol and vapor)"},
    {"code": "ISO 8573-2", "scope": "Test methods for aerosol oil content in compressed air — measurement of oil carryover from compressors"},
    {"code": "ISO 8573-3", "scope": "Test methods for measurement of humidity in compressed air — relevant to moisture control"}
  ]'::jsonb,

  '[
    {"slug": "drycore", "mechanism": "Desiccant air drying — achieves -20°C to -40°C pressure dew point per ISO 8573-1 Class 1–4"},
    {"slug": "gasultra", "mechanism": "Coalescing filtration — removes liquid water droplets and oil aerosol to ISO 8573-1 Class 1 oil purity"}
  ]'::jsonb,

  'Compressed air purity compliance to ISO 8573-1 is required for instrumentation
reliability, process quality assurance, and food/pharmaceutical regulatory compliance;
compressed air treatment system design determines whether pneumatic equipment meets
its 3–7 year design life or requires replacement every 6–18 months from contamination
damage.',

  '/knowledge-system/standards/compressed-air-systems'
)
ON CONFLICT (concept_slug, concept_type) DO UPDATE SET
  definition           = EXCLUDED.definition,
  system_context       = EXCLUDED.system_context,
  failure_mechanism    = EXCLUDED.failure_mechanism,
  industrial_impact    = EXCLUDED.industrial_impact,
  related_standards    = EXCLUDED.related_standards,
  related_technologies = EXCLUDED.related_technologies,
  industrial_role      = EXCLUDED.industrial_role,
  citation_url         = EXCLUDED.citation_url,
  version              = kg_canonical_blocks.version + 1,
  last_updated         = CURRENT_DATE,
  updated_at           = NOW();


-- =============================================================================
-- SECTION B — CONTAMINATION MODE CANONICAL BLOCKS (5 rows)
-- Quantified impact metrics from SEMANTIC_MODEL_REPORT.md §3
-- =============================================================================

-- ─── B1. PARTICLE WEAR ────────────────────────────────────────────────────────

INSERT INTO kg_canonical_blocks (
  concept_slug, concept_type, display_name,
  definition,
  system_context,
  failure_mechanism,
  industrial_impact,
  related_standards,
  related_technologies,
  industrial_role,
  citation_url
) VALUES (
  'particle-wear', 'contamination_mode', 'Particle Wear in Engines',

  'Particle wear occurs when hard abrasive particles (silica, metallic oxides, carbides)
suspended in engine oil or hydraulic fluid are entrained in oil film between moving
surfaces, causing progressive micro-cutting abrasion that increases bearing clearances,
degrades sealing surfaces, and accelerates the wear-debris-generation cycle.',

  'Applies to: engine lube oil circuits (crankshaft bearings, piston rings, cylinder bores),
hydraulic systems (pump internals, proportional valve spools, servo valve spools),
transmission fluid circuits (clutch plates, gear surfaces), and air intake systems
where particle ingestion generates initial abrasive contamination. Particle size range
most damaging: 2–15µm (similar scale to bearing film thickness of 3–10µm).
Contamination sources: air-borne atmospheric silica (air intake ingestion), fuel-borne
contamination (fuel injection system wear), internally generated wear debris (self-
reinforcing cycle), and ingested contamination during maintenance.',

  'Hard particles (silica Mohs 7, iron oxide Mohs 5–6) trapped between bearing journal
(steel, 60–65 HRC) and bearing shell (copper-lead alloy, 30–40 HRC) → micro-cutting
of softer bearing surface → surface asperity removal → bearing clearance opening
→ reduced oil film thickness under load → increased contact between journal and shell
→ adhesive wear onset → metallic wear particles generated → self-accelerating wear
cycle. Three-body wear (particles rolling between two surfaces) causes 2–3× greater
wear rate than two-body wear. Above bearing design clearance, journal-to-shell contact
under load → bearing seizure.',

  'Oil consumption increase from particle wear (piston ring and bore wear): +15–40%.
Engine blow-by increase from ring wear: +5–10%. Fuel economy degradation from
increased friction: -5–12%. Compression ratio drop from cylinder bore wear: -10–25%.
Equipment availability without particle wear control: -15–25%. Root cause: bearing
wear from particle contamination at ISO codes above 16/14/11 (engine) or 17/15/12
(hydraulic).',

  '[
    {"code": "ISO 16889", "scope": "Filter Beta ratio — primary measurement tool for particle capture efficiency controlling abrasive wear particles"},
    {"code": "ISO 4406", "scope": "Particle cleanliness codes — target codes define maximum allowable particle concentrations for bearing protection"},
    {"code": "SAE J1539", "scope": "Air cleaner element efficiency — air intake particle removal preventing combustion ingestion of abrasive particles"}
  ]'::jsonb,

  '[
    {"slug": "macrocore", "mechanism": "Air intake filtration — prevents atmospheric silica ingestion that initiates the wear cycle"},
    {"slug": "nanoforce", "mechanism": "Hydraulic sub-micron filtration — captures 3–6µm particles in the critical wear-particle size range"},
    {"slug": "syntrax", "mechanism": "Lube oil synthetic media — maintains ISO 16/14/11 cleanliness to interrupt wear cycle in engine bearings"},
    {"slug": "duratech", "mechanism": "Extended-drain lube filtration — maintains particle capture efficiency over 1,000-hour drain intervals"}
  ]'::jsonb,

  'Particle wear is the root cause of premature component failure across engine, hydraulic,
and transmission systems; controlling particle concentration at ISO 4406 target codes
through filtration is the only mechanism by which bearing and component life can be
extended 3–5× beyond uncontrolled baseline.',

  '/knowledge-system/contamination/particle-wear'
)
ON CONFLICT (concept_slug, concept_type) DO UPDATE SET
  definition           = EXCLUDED.definition,
  system_context       = EXCLUDED.system_context,
  failure_mechanism    = EXCLUDED.failure_mechanism,
  industrial_impact    = EXCLUDED.industrial_impact,
  related_standards    = EXCLUDED.related_standards,
  related_technologies = EXCLUDED.related_technologies,
  industrial_role      = EXCLUDED.industrial_role,
  citation_url         = EXCLUDED.citation_url,
  version              = kg_canonical_blocks.version + 1,
  last_updated         = CURRENT_DATE,
  updated_at           = NOW();


-- ─── B2. DIESEL WATER CONTAMINATION ──────────────────────────────────────────

INSERT INTO kg_canonical_blocks (
  concept_slug, concept_type, display_name,
  definition,
  system_context,
  failure_mechanism,
  industrial_impact,
  related_standards,
  related_technologies,
  industrial_role,
  citation_url
) VALUES (
  'diesel-water', 'contamination_mode', 'Diesel Water Contamination',

  'Diesel water contamination occurs when free or emulsified water enters diesel fuel
from atmospheric condensation in storage tanks, transfer contamination, or seal
leakage, and degrades fuel injection system performance by promoting injector nozzle
corrosion, microbial growth, and fuel gum formation when water concentration exceeds
200 ppm (measured per ASTM D6304).',

  'Applies to diesel fuel circuits from bulk storage tanks through transfer pumps, day
tanks, fuel filters, to high-pressure injection systems. High-risk scenarios: seasonal
temperature cycling causing condensation in partially filled tanks (50–200 ppm water
accumulation per week), marine environment fuel storage (continuous humidity exposure),
biodiesel blends (B5–B20 with higher water absorption), and long-term storage of
standby generator fuel (>6 months stagnation with microbial growth risk). Free water
settles in tank bottom; emulsified water (0.1–5µm droplets) passes through fuel system.',

  'Free water in diesel fuel (>200 ppm) pools at tank bottom → water enters fuel pump
inlet → water ingestion by common-rail high-pressure pump → localized corrosion of
chromium-molybdenum pump plunger → corrosion debris generation → plunger-barrel wear
→ injection pressure shortfall. Water emulsification by fuel turbulence → water
droplets pass 30µm pre-filter → reach injector nozzle → flash vaporization at nozzle
(injection pressure 1,600–2,200 bar, nozzle temperature 150–250°C) → nozzle surface
pitting → spray orifice erosion → spray cone degradation. Water above 1,000 ppm
supports microbial growth (Pseudomonas, Cladosporium fungal species) → biofilm formation
→ filter plugging → fuel flow restriction.',

  'Hard-start increase from water contamination: +5–15 seconds cold start delay. Fuel
consumption increase from degraded injection spray: +3–8%. Injector cleaning interval
reduction: 2,000–3,000 hours (contaminated) vs. 5,000–8,000 hours (controlled).
Equipment availability reduction: -12–18% for water-contaminated fuel systems.
Injector replacement cost per set (6-cylinder): $1,200–$4,800. Microbial contamination
remediation cost (tank cleaning, biocide treatment, filter replacement): $500–$3,000
per tank per incident.',

  '[
    {"code": "ASTM D6304", "scope": "Karl Fischer titration test for water in petroleum products — primary measurement for diesel fuel water content verification, range 10–25,000 ppm"},
    {"code": "ISO 12937", "scope": "Petroleum products water measurement by coulometric Karl Fischer titration — applicable to fuel system water content specification compliance"}
  ]'::jsonb,

  '[
    {"slug": "aquaguard", "mechanism": "Water coalescing and separation — removes free water to below 200 ppm before fuel injection system"},
    {"slug": "SYNTAPORE", "mechanism": "Fuel particle filtration downstream of water separator — removes corrosion products generated by water contamination"}
  ]'::jsonb,

  'Water contamination in diesel fuel is the primary initiating mechanism for injector
corrosion, microbial contamination, and fuel gum formation; maintaining fuel water
content below 200 ppm through coalescing separation is essential for common-rail
injection system service life and emergency/standby generator reliability.',

  '/knowledge-system/contamination/diesel-water-contamination'
)
ON CONFLICT (concept_slug, concept_type) DO UPDATE SET
  definition           = EXCLUDED.definition,
  system_context       = EXCLUDED.system_context,
  failure_mechanism    = EXCLUDED.failure_mechanism,
  industrial_impact    = EXCLUDED.industrial_impact,
  related_standards    = EXCLUDED.related_standards,
  related_technologies = EXCLUDED.related_technologies,
  industrial_role      = EXCLUDED.industrial_role,
  citation_url         = EXCLUDED.citation_url,
  version              = kg_canonical_blocks.version + 1,
  last_updated         = CURRENT_DATE,
  updated_at           = NOW();


-- ─── B3. HYDRAULIC SYSTEM CONTAMINATION ──────────────────────────────────────

INSERT INTO kg_canonical_blocks (
  concept_slug, concept_type, display_name,
  definition,
  system_context,
  failure_mechanism,
  industrial_impact,
  related_standards,
  related_technologies,
  industrial_role,
  citation_url
) VALUES (
  'hydraulic-contamination', 'contamination_mode', 'Hydraulic System Contamination',

  'Hydraulic system contamination encompasses particulate (metallic wear debris, silica,
seal degradation particles), chemical (fluid oxidation products, varnish precursors),
and water contamination in hydraulic circuits that exceeds ISO 4406 cleanliness
targets, causing progressive wear of valve spools, pump internals, and actuator
seals.',

  'Applies to all hydraulic circuits including open-center, closed-center, load-sensing,
and servo-hydraulic systems in mobile equipment and industrial machinery. Contamination
sources: built-in contamination from manufacturing (metal chips, welding slag in cylinders
and hoses), ingressed contamination from cylinder rod seal leakage, hose connection
contamination during maintenance, and internally generated wear particles from pump
and valve components. Particle size distribution in hydraulic fluid: 1–100µm range,
with 3–15µm particles most critical for proportional valve wear.',

  'Particle contamination above ISO 4406 code 18/16/13 (vs. target 16/14/11 for
proportional valves) → particles enter proportional valve spool-body clearance (2–8µm)
→ spool surface abrasion → internal leakage increase 10–30% → actuator positioning
accuracy loss → system pressure variations → additional heat generation +5–15 kW
→ fluid temperature increase +20–30°C → accelerated oil oxidation → varnish precursors
form (polymerized hydrocarbon deposits) → deposit on servo valve spools
→ spool stiction → valve failure. Seal degradation particles from aged elastomeric
seals accelerate the contamination cycle.',

  'Equipment availability reduction: -15–30%. Unplanned maintenance frequency: 1–2
events per 500 operating hours without cleanliness control. System pressure increase
from contamination: +10–30%. Heat generation increase: +5–15 kW. Fluid temperature
increase: +20–30°C above design range. Proportional valve replacement: €800–€4,000
per valve. Servo valve replacement: €2,000–€15,000. Hydraulic pump overhaul from
contamination wear: €500–€5,000. Maintaining ISO 16/14/11 extends proportional valve
life 3–5× versus uncontrolled ISO 19/17/14 operation.',

  '[
    {"code": "ISO 16889", "scope": "Multi-pass filter performance test — Beta ratio at 3µm, 6µm, 12µm for hydraulic filtration"},
    {"code": "ISO 4406", "scope": "Cleanliness code classification for hydraulic fluid — target codes 16/14/11 to 17/15/12 for proportional valve systems"},
    {"code": "NFPA T2.14", "scope": "Hydraulic fluid power cleanliness requirements for mobile equipment"},
    {"code": "DIN 51524", "scope": "Hydraulic fluid classification — HL, HLP, HVLP minimum requirements"}
  ]'::jsonb,

  '[
    {"slug": "nanoforce", "mechanism": "Hydraulic sub-micron filtration at Beta(x)[c]≥200 at 3µm — controls particle contamination at ISO 16/14/11 target"},
    {"slug": "aquaguard", "mechanism": "Water separation from hydraulic fluid — water contamination accelerates oxidation and reduces oil film strength"}
  ]'::jsonb,

  'Hydraulic contamination is the primary cause of proportional and servo valve failure
in precision hydraulic systems; particle contamination control at ISO 4406 cleanliness
targets is the single most impactful maintenance action for extending hydraulic
component service life from 2,000–3,000 hours to 10,000–20,000 hours.',

  '/knowledge-system/contamination/hydraulic-system-contamination'
)
ON CONFLICT (concept_slug, concept_type) DO UPDATE SET
  definition           = EXCLUDED.definition,
  system_context       = EXCLUDED.system_context,
  failure_mechanism    = EXCLUDED.failure_mechanism,
  industrial_impact    = EXCLUDED.industrial_impact,
  related_standards    = EXCLUDED.related_standards,
  related_technologies = EXCLUDED.related_technologies,
  industrial_role      = EXCLUDED.industrial_role,
  citation_url         = EXCLUDED.citation_url,
  version              = kg_canonical_blocks.version + 1,
  last_updated         = CURRENT_DATE,
  updated_at           = NOW();


-- ─── B4. VARNISH FORMATION ────────────────────────────────────────────────────

INSERT INTO kg_canonical_blocks (
  concept_slug, concept_type, display_name,
  definition,
  system_context,
  failure_mechanism,
  industrial_impact,
  related_standards,
  related_technologies,
  industrial_role,
  citation_url
) VALUES (
  'varnish-formation', 'contamination_mode', 'Varnish Formation in Hydraulic and Lube Oil',

  'Varnish formation is the deposition of polymerized hydrocarbon oxidation products
as insoluble lacquer-like coatings on metal surfaces in hydraulic and lube oil systems,
occurring when oil thermal oxidation products exceed fluid solubility limits and
precipitate onto servo valve spools, oil passages, and heat exchanger surfaces.',

  'Applies to hydraulic servo systems operating above 70°C sustained fluid temperature,
turbine lube systems with extended oil service periods, and industrial hydraulic systems
with inadequate cooling or heat exchanger fouling. High-risk scenarios: hydraulic systems
with restricted radiator cooling (blocked fins, high ambient temperature), continuous
high-load operation with inadequate oil cooler capacity, and turbine control systems
with extended oil fill periods (3–5 years). Varnish deposition rate increases
exponentially above 75°C (Arrhenius law: 2× oxidation rate per 10°C increase).',

  'Thermal oxidation of hydraulic/lube oil (above 70°C sustained) → peroxide formation
in oil → hydroperoxide decomposition → polymerized oxidation products accumulate →
exceed oil solubility limit → precipitation on metal surfaces (servo valve spool,
orifice passages, oil cooler tubes) → insoluble varnish deposit layer growth (0.1–2µm
thickness per 1,000 hours at 80°C) → servo valve spool clearance reduction → spool
stiction onset → valve response degradation → hydraulic system instability. Varnish
deposits on heat exchanger surfaces reduce heat transfer efficiency 10–30%.',

  'Hydraulic servo valve stiction from varnish deposits causes positioning errors of
0.5–5% of full stroke at 1–2µm varnish deposit thickness. Servo valve replacement
cost: €2,000–€15,000. Oil cooler efficiency reduction from varnish fouling: 10–30%
→ additional fluid temperature increase 5–15°C above design → accelerated varnish
formation feedback cycle. Turbine control hydraulic system varnish removal (chemical
flush): $5,000–$50,000 per system per incident. Varnish remediation requires complete
system flush, fluid replacement, and valve cleaning or replacement.',

  '[
    {"code": "ISO 4406", "scope": "Cleanliness codes — varnish precursor particles are sub-2µm, partially captured by fine filtration but primarily a fluid chemistry issue"},
    {"code": "DIN 51524", "scope": "Hydraulic fluid classification — HL and HLP fluids have defined oxidation stability requirements"}
  ]'::jsonb,

  '[
    {"slug": "nanoforce", "mechanism": "Fine hydraulic filtration — removes varnish precursor particles before they deposit on sensitive valve surfaces"},
    {"slug": "syntrax", "mechanism": "Lube oil filtration — captures oxidation product particles in engine oil before they accumulate in bearings and oil passages"}
  ]'::jsonb,

  'Varnish formation is an irreversible system degradation mode requiring expensive chemical
flush and component replacement; temperature control combined with fine filtration to
remove varnish precursor particles is the only effective preventive strategy, as varnish
deposits cannot be removed by normal filtration once they form.',

  '/knowledge-system/contamination/varnish-formation'
)
ON CONFLICT (concept_slug, concept_type) DO UPDATE SET
  definition           = EXCLUDED.definition,
  system_context       = EXCLUDED.system_context,
  failure_mechanism    = EXCLUDED.failure_mechanism,
  industrial_impact    = EXCLUDED.industrial_impact,
  related_standards    = EXCLUDED.related_standards,
  related_technologies = EXCLUDED.related_technologies,
  industrial_role      = EXCLUDED.industrial_role,
  citation_url         = EXCLUDED.citation_url,
  version              = kg_canonical_blocks.version + 1,
  last_updated         = CURRENT_DATE,
  updated_at           = NOW();


-- ─── B5. MICROBIAL GROWTH ─────────────────────────────────────────────────────

INSERT INTO kg_canonical_blocks (
  concept_slug, concept_type, display_name,
  definition,
  system_context,
  failure_mechanism,
  industrial_impact,
  related_standards,
  related_technologies,
  industrial_role,
  citation_url
) VALUES (
  'microbial-growth', 'contamination_mode', 'Microbial Growth in Diesel Fuel and Hydraulic Fluid',

  'Microbial growth in diesel fuel and water-based hydraulic fluids occurs when fungal
and bacterial species colonize the water-fuel interface above 1,000 ppm water
concentration, producing biofilm, acidic metabolites, and biomass that plugs filters,
corrodes tank surfaces, and degrades fuel/fluid quality.',

  'Applies to diesel fuel in storage tanks (bulk storage > 6 months stagnation), marine
fuel tanks (continuous high-humidity environment), standby generator fuel tanks, and
water-based hydraulic fluids (HFA, HFB type emulsions). Primary microbial species:
Pseudomonas aeruginosa (bacteria), Cladosporium resinae (fungus, diesel bug), Hormoconis
resinae (fungus). Growth conditions: water concentration >1,000 ppm at water-fuel
interface, temperature 10–40°C optimal (dormant at <5°C or >55°C), carbon source
from hydrocarbon fuel/fluid. High-risk: ULSD (ultra-low sulfur diesel) with reduced
natural biocide properties versus older high-sulfur diesel.',

  'Water accumulation above 1,000 ppm at tank bottom → fungal and bacterial colonization
at water-diesel interface → biofilm growth (microbial mat 0.5–5mm thick) → biofilm
fragments detach from tank wall → biomass particles (10–500µm) enter fuel circuit
→ filter media plugging → differential pressure increase → filter bypass → unfiltered
fuel reaches injection system → injector nozzle plugging. Metabolic acids (acetic,
formic acid) generated by microbial digestion → pH reduction in water phase → tank
corrosion → iron oxide particles → additional filter loading → accelerated pump and
injector wear from corrosion debris.',

  'Microbial filter plugging can occur within 2–4 weeks of microbial establishment at
>1,000 ppm water. Filter replacement frequency increase from 1 per 500 hours (normal)
to 1 per 50–100 hours (microbially contaminated). Biocide treatment cost per tank
incident: $200–$1,000. Tank cleaning required after severe contamination: $500–$5,000.
Fuel system decontamination including filter replacement and system flush: $1,000–$8,000
per vehicle. Standby generator fuel system microbial contamination: most common cause
of fuel system failure at emergency power demand, with reported event rates of
15–30% of poorly maintained standby systems.',

  '[
    {"code": "ASTM D6304", "scope": "Water content measurement by Karl Fischer — threshold 1,000 ppm water supports microbial growth"},
    {"code": "ISO 12937", "scope": "Diesel fuel water measurement — monitoring below 200 ppm prevents conditions for microbial growth initiation"}
  ]'::jsonb,

  '[
    {"slug": "aquaguard", "mechanism": "Water separation to below 200 ppm — removes the water phase required for microbial survival and growth"},
    {"slug": "SYNTAPORE", "mechanism": "Fuel particle filtration — removes biofilm fragments and biomass particles before they reach injection system"}
  ]'::jsonb,

  'Microbial growth in diesel fuel is a leading cause of unplanned fuel system maintenance
in standby power, marine, and long-term storage applications; maintaining water content
below 200 ppm through coalescing filtration is the only reliable prevention strategy,
as biocide treatment after establishment requires complete system decontamination.',

  '/knowledge-system/contamination/microbial-growth'
)
ON CONFLICT (concept_slug, concept_type) DO UPDATE SET
  definition           = EXCLUDED.definition,
  system_context       = EXCLUDED.system_context,
  failure_mechanism    = EXCLUDED.failure_mechanism,
  industrial_impact    = EXCLUDED.industrial_impact,
  related_standards    = EXCLUDED.related_standards,
  related_technologies = EXCLUDED.related_technologies,
  industrial_role      = EXCLUDED.industrial_role,
  citation_url         = EXCLUDED.citation_url,
  version              = kg_canonical_blocks.version + 1,
  last_updated         = CURRENT_DATE,
  updated_at           = NOW();


-- =============================================================================
-- Expected after successful run:
--   Section A: 6 system rows inserted (concept_type='system')
--   Section B: 5 contamination mode rows inserted (concept_type='contamination_mode')
--   Total new rows: 11
--
-- Verify with:
--   SELECT concept_type, COUNT(*) FROM kg_canonical_blocks
--   GROUP BY concept_type ORDER BY concept_type;
--   -- After 002 + 003: technology=13, system=6, contamination_mode=5
--   -- Total: 24 rows
--
--   SELECT concept_slug, version, last_updated
--   FROM kg_canonical_blocks WHERE concept_type = 'system'
--   ORDER BY concept_slug;
--   -- Expected: 6 rows: air-intake, cabin, compressed-air, fuel, hydraulic, lube-oil
-- =============================================================================
