'use client';

import Link from 'next/link';
import { motion } from 'motion/react';
import RetrievalBlock from '@/components/RetrievalBlock';

const CORE_CONCEPTS = [
  {
    code: 'PCM',
    title: 'Particle Capture Mechanics',
    href: '/knowledge-system/contamination/particle-wear',
    description: 'Inertial impaction, interception, and diffusion — three physical mechanisms by which filter media arrests particles. Efficiency is particle-size dependent: inertial impaction dominates at >10µm, diffusion dominates at <0.3µm.',
  },
  {
    code: 'BEF',
    title: 'Beta Ratio & Filter Efficiency',
    href: '/knowledge-system/standards/iso-16889',
    description: 'ISO 16889 defines Beta ratio (βx) as the ratio of upstream to downstream particle count at a given micron threshold. β10 = 200 means 99.5% capture efficiency at 10µm. The test methodology uses multi-pass procedures with ISO 12103-1 contaminant.',
  },
  {
    code: 'CCM',
    title: 'Cleanliness Code Measurement',
    href: '/knowledge-system/standards/iso-4406',
    description: 'ISO 4406 translates particle counts per milliliter into a three-number cleanliness code (e.g., 16/14/11). Each step increase in code number doubles the particle population. Hydraulic systems targeting 17/15/12 allow 640–1300 particles ≥4µm per mL.',
  },
  {
    code: 'WSP',
    title: 'Water Separation Physics',
    href: '/knowledge-system/contamination/diesel-water',
    description: 'Free water coalesces on hydrophilic media surfaces, forming droplets that grow until gravity separation occurs. Emulsified water requires demulsification before coalescing. ASTM D6304 quantifies total water content via Karl Fischer titration.',
  },
  {
    code: 'AFL',
    title: 'Air Filtration & Flow Dynamics',
    href: '/knowledge-system/standards/air-intake-systems',
    description: 'Air filter restriction increases with dust loading. ISO 5011 defines the standardized test dust, test chamber geometry, and flow rate parameters for measuring filter efficiency and pressure drop across the element lifecycle.',
  },
  {
    code: 'HCM',
    title: 'Hydraulic Contamination Dynamics',
    href: '/knowledge-system/contamination/hydraulic-system',
    description: 'Proportional control valves tolerate clearances of 1–3µm. Contamination particles at or above this threshold cause spool wear, stiction, and control signal deviation. Kidney-loop offline filtration removes contaminants independent of system flow cycles.',
  },
];

const PRINCIPLES = [
  {
    number: '01',
    title: 'Media Efficiency Is Particle-Size Specific',
    body: 'No filter element captures all particles at all sizes with equal efficiency. Beta ratio (βx) must be specified at the relevant particle size for the protected component. A hydraulic proportional valve requires β3 ≥200; an engine oil system may specify β10 ≥200. Selecting media without specifying the critical micron threshold produces unmeasurable and unreliable protection.',
  },
  {
    number: '02',
    title: 'Dirt Capacity Determines Service Life',
    body: 'Filter element service life is governed by dirt holding capacity — the total mass of contaminant a filter can hold before reaching terminal restriction. ISO 16889 test procedure measures this via gravimetric analysis. High dirt capacity delays bypass valve opening, extending the protection window before the next service interval.',
  },
  {
    number: '03',
    title: 'Bypass Valves Define the Protection Floor',
    body: 'Bypass valves open when differential pressure across the element exceeds the design cracking pressure (typically 1.5–6 bar depending on system). During bypass, unfiltered fluid bypasses the media entirely. Systems with frequent bypass events — caused by cold starts, overloading, or extended service intervals — lose filtration protection at the highest-risk operating moments.',
  },
  {
    number: '04',
    title: 'Contamination Is Additive and Self-Reinforcing',
    body: 'Wear particles generated by contamination become additional contaminants. A 20µm particle abrades bearing surfaces, generating 5µm wear debris, which passes through filters designed for 10µm targets and accelerates damage in downstream components. This cascade mechanism is why cleanliness targets must be maintained continuously, not recovered after a contamination event.',
  },
];

const FAQS = [
  {
    q: 'What is the difference between nominal and absolute filter ratings?',
    a: 'Nominal ratings indicate the particle size at which a filter removes some unspecified percentage of particles — typically 50–98% — making them non-reproducible and unsuitable for engineering specifications. Absolute ratings, expressed as Beta ratio under ISO 16889 test conditions, define capture efficiency at a specific particle size with reproducible multi-pass test methodology. For any system with contamination-sensitive components, only absolute Beta ratio ratings provide defensible filtration specifications.',
  },
  {
    q: 'How does temperature affect filter media performance?',
    a: 'Elevated temperatures reduce fluid viscosity, increasing flow velocity through media pores and reducing contact time for particle interception. Cold temperatures increase viscosity, raising differential pressure and risk of bypass valve activation. Synthetic media (polyester, glass fiber) maintains dimensional stability across wider temperature ranges than cellulose media, which swells in water-contaminated fluids. Temperature derating factors must be applied to filter element specifications when operating outside the ISO 16889 test temperature of 60°C ±2°C.',
  },
  {
    q: 'Why does ISO 4406 use three cleanliness code numbers instead of one?',
    a: 'Three particle size thresholds (≥4µm, ≥6µm, ≥14µm) are reported because different failure mechanisms are driven by different particle populations. Servo valve spool wear is driven by the ≥4µm population. Bearing surface fatigue is driven by ≥6µm particles. Gear tooth scoring is more closely associated with ≥14µm particles. A single code number cannot simultaneously characterize all three failure risk populations. Hydraulic systems targeting 17/15/12 are allowing approximately 640–1300, 160–320, and 20–40 particles per mL respectively at these thresholds.',
  },
  {
    q: 'What determines when a filter element should be replaced?',
    a: 'Condition-based replacement is driven by differential pressure across the element. When differential pressure reaches the filter indicator setpoint (typically 70–80% of bypass cracking pressure), the element has reached its working dirt capacity. Time-based replacement on fixed intervals assumes consistent contamination loading — an assumption that fails in variable-duty equipment. Combined approaches using differential pressure monitoring with maximum time-interval backstop provide optimal protection without unnecessary element changes.',
  },
];

export default function SciencePage() {
  return (
    <main style={{ background: '#000', color: '#fff', minHeight: '100vh' }}>
      {/* Back */}
      <Link href="/knowledge-system" style={{
        position: 'fixed', top: '1rem', right: '1.5rem', zIndex: 9999,
        display: 'flex', alignItems: 'center', gap: '0.4rem',
        background: 'rgba(0,0,0,0.85)', border: '1px solid rgba(255,241,45,0.35)',
        borderRadius: '4px', padding: '0.45rem 1rem',
        fontFamily: 'Outfit, sans-serif', fontWeight: 700, fontSize: '0.72rem',
        letterSpacing: '0.12em', color: '#FFF12D', textDecoration: 'none',
        backdropFilter: 'blur(8px)',
      }}>← KNOWLEDGE</Link>

      {/* Hero */}
      <section style={{
        paddingTop: 'clamp(5rem, 10vw, 8rem)',
        paddingBottom: '4rem',
        background: 'linear-gradient(180deg, rgba(255,241,45,0.05) 0%, transparent 100%)',
        borderBottom: '1px solid rgba(255,255,255,0.06)',
        textAlign: 'center',
      }}>
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          style={{ maxWidth: '700px', margin: '0 auto', padding: '0 2rem' }}
        >
          <p style={{
            fontFamily: 'JetBrains Mono, monospace',
            fontSize: '0.7rem',
            letterSpacing: '0.18em',
            color: '#FFF12D',
            marginBottom: '1rem',
            opacity: 0.85,
          }}>
            // KNOWLEDGE SYSTEM · FILTRATION SCIENCE
          </p>
          <h1 style={{
            fontFamily: 'Outfit, sans-serif',
            fontSize: 'clamp(2rem, 5vw, 3.2rem)',
            fontWeight: 700,
            letterSpacing: '-0.01em',
            lineHeight: 1.15,
            marginBottom: '1rem',
          }}>
            Filtration Science
          </h1>
          <p style={{
            fontFamily: 'Inter, sans-serif',
            fontSize: '1rem',
            color: 'rgba(255,255,255,0.5)',
            maxWidth: '500px',
            margin: '0 auto',
            lineHeight: 1.65,
          }}>
            Physical principles governing particle capture, fluid dynamics, media efficiency, and contamination measurement in industrial filtration systems.
          </p>
        </motion.div>
      </section>

      {/* Domain Introduction */}
      <section style={{
        padding: '4rem 2rem',
        background: 'linear-gradient(180deg, rgba(255,241,45,0.02) 0%, transparent 100%)',
        borderBottom: '1px solid rgba(255,255,255,0.06)',
      }}>
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.2 }}
          style={{ maxWidth: '860px', margin: '0 auto' }}
        >
          <p style={{
            fontFamily: 'Inter, sans-serif',
            fontSize: '1rem',
            color: 'rgba(255,255,255,0.7)',
            lineHeight: 1.8,
            marginBottom: '1.5rem',
          }}>
            Industrial filtration operates at the intersection of fluid mechanics, surface chemistry, and particle physics. The effectiveness of a filtration system is not determined by the product selected — it is determined by whether the physical capture mechanisms in the media match the contamination characteristics of the fluid, the particle size distribution of the threat, and the cleanliness sensitivity of the protected component. Understanding these mechanisms is the prerequisite for any defensible filtration specification.
          </p>
          <p style={{
            fontFamily: 'Inter, sans-serif',
            fontSize: '1rem',
            color: 'rgba(255,255,255,0.7)',
            lineHeight: 1.8,
          }}>
            The core relationship is: contamination source → particle size distribution → cleanliness target (ISO 4406) → Beta ratio requirement (ISO 16889) → media selection → service interval design. Every filtration decision that skips a step in this chain introduces an uncontrolled variable into equipment reliability. The standards and contamination domains in this knowledge system document each step with engineering precision.
          </p>
        </motion.div>
      </section>

      {/* Core Concepts Grid */}
      <section style={{ maxWidth: '1200px', margin: '0 auto', padding: '4rem 2rem' }}>
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.1 }}
          style={{ marginBottom: '2.5rem' }}
        >
          <p style={{
            fontFamily: 'JetBrains Mono, monospace',
            fontSize: '0.65rem',
            letterSpacing: '0.15em',
            color: 'rgba(255,241,45,0.6)',
            marginBottom: '0.5rem',
          }}>
            // CORE CONCEPTS
          </p>
          <h2 style={{
            fontFamily: 'Outfit, sans-serif',
            fontSize: 'clamp(1.3rem, 3vw, 1.8rem)',
            fontWeight: 600,
            letterSpacing: '-0.01em',
          }}>
            Filtration Physics Domains
          </h2>
        </motion.div>

        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(min(300px, 100%), 1fr))',
          gap: '1.5rem',
        }}>
          {CORE_CONCEPTS.map((concept, i) => (
            <motion.div
              key={concept.code}
              initial={{ opacity: 0, y: 24 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.4, delay: 0.1 + i * 0.07 }}
            >
              <Link href={concept.href} style={{ textDecoration: 'none', display: 'block' }}>
                <motion.div
                  whileHover={{ borderColor: 'rgba(255,241,45,0.35)', y: -2 }}
                  transition={{ duration: 0.2 }}
                  style={{
                    background: 'rgba(255,255,255,0.02)',
                    border: '1px solid rgba(255,255,255,0.07)',
                    padding: '1.75rem',
                    height: '100%',
                    display: 'flex',
                    flexDirection: 'column',
                    gap: '1rem',
                  }}
                >
                  <span style={{
                    fontFamily: 'JetBrains Mono, monospace',
                    fontSize: '0.6rem',
                    color: 'rgba(255,241,45,0.55)',
                    letterSpacing: '0.12em',
                  }}>
                    {concept.code}
                  </span>
                  <h3 style={{
                    fontFamily: 'Outfit, sans-serif',
                    fontSize: '1rem',
                    fontWeight: 600,
                    color: '#fff',
                    lineHeight: 1.4,
                  }}>
                    {concept.title}
                  </h3>
                  <p style={{
                    fontFamily: 'Inter, sans-serif',
                    fontSize: '0.85rem',
                    color: 'rgba(255,255,255,0.45)',
                    lineHeight: 1.65,
                    marginTop: 'auto',
                  }}>
                    {concept.description}
                  </p>
                  <span style={{
                    fontFamily: 'JetBrains Mono, monospace',
                    fontSize: '0.65rem',
                    color: 'rgba(255,241,45,0.4)',
                    letterSpacing: '0.08em',
                  }}>
                    READ →
                  </span>
                </motion.div>
              </Link>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Engineering Principles */}
      <section style={{
        borderTop: '1px solid rgba(255,255,255,0.06)',
        padding: '4rem 2rem',
      }}>
        <div style={{ maxWidth: '860px', margin: '0 auto' }}>
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            style={{ marginBottom: '3rem' }}
          >
            <p style={{
              fontFamily: 'JetBrains Mono, monospace',
              fontSize: '0.65rem',
              letterSpacing: '0.15em',
              color: 'rgba(255,241,45,0.6)',
              marginBottom: '0.5rem',
            }}>
              // ENGINEERING PRINCIPLES
            </p>
            <h2 style={{
              fontFamily: 'Outfit, sans-serif',
              fontSize: 'clamp(1.3rem, 3vw, 1.8rem)',
              fontWeight: 600,
              letterSpacing: '-0.01em',
            }}>
              Fundamental Design Constraints
            </h2>
          </motion.div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '2rem' }}>
            {PRINCIPLES.map((p, i) => (
              <motion.div
                key={p.number}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.4, delay: 0.1 + i * 0.08 }}
                style={{
                  display: 'grid',
                  gridTemplateColumns: '3rem 1fr',
                  gap: '1.5rem',
                  paddingBottom: '2rem',
                  borderBottom: i < PRINCIPLES.length - 1 ? '1px solid rgba(255,255,255,0.05)' : 'none',
                }}
              >
                <span style={{
                  fontFamily: 'JetBrains Mono, monospace',
                  fontSize: '0.7rem',
                  color: 'rgba(255,241,45,0.35)',
                  paddingTop: '0.3rem',
                }}>
                  {p.number}
                </span>
                <div>
                  <h3 style={{
                    fontFamily: 'Outfit, sans-serif',
                    fontSize: '1rem',
                    fontWeight: 600,
                    color: '#fff',
                    marginBottom: '0.75rem',
                  }}>
                    {p.title}
                  </h3>
                  <p style={{
                    fontFamily: 'Inter, sans-serif',
                    fontSize: '0.9rem',
                    color: 'rgba(255,255,255,0.55)',
                    lineHeight: 1.75,
                  }}>
                    {p.body}
                  </p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section style={{
        borderTop: '1px solid rgba(255,255,255,0.06)',
        padding: '4rem 2rem',
      }}>
        <div style={{ maxWidth: '860px', margin: '0 auto' }}>
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            style={{ marginBottom: '3rem' }}
          >
            <p style={{
              fontFamily: 'JetBrains Mono, monospace',
              fontSize: '0.65rem',
              letterSpacing: '0.15em',
              color: 'rgba(255,241,45,0.6)',
              marginBottom: '0.5rem',
            }}>
              // TECHNICAL QUESTIONS
            </p>
            <h2 style={{
              fontFamily: 'Outfit, sans-serif',
              fontSize: 'clamp(1.3rem, 3vw, 1.8rem)',
              fontWeight: 600,
              letterSpacing: '-0.01em',
            }}>
              Engineering Q&A
            </h2>
          </motion.div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
            {FAQS.map((faq, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 16 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.4, delay: 0.1 + i * 0.07 }}
                style={{
                  background: 'rgba(255,255,255,0.02)',
                  border: '1px solid rgba(255,255,255,0.07)',
                  padding: '1.75rem',
                }}
              >
                <p style={{
                  fontFamily: 'Outfit, sans-serif',
                  fontSize: '0.95rem',
                  fontWeight: 600,
                  color: '#fff',
                  marginBottom: '0.75rem',
                  lineHeight: 1.5,
                }}>
                  {faq.q}
                </p>
                <p style={{
                  fontFamily: 'Inter, sans-serif',
                  fontSize: '0.875rem',
                  color: 'rgba(255,255,255,0.55)',
                  lineHeight: 1.75,
                }}>
                  {faq.a}
                </p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Related Domains */}
      <section style={{
        borderTop: '1px solid rgba(255,255,255,0.06)',
        padding: '4rem 2rem',
      }}>
        <div style={{ maxWidth: '860px', margin: '0 auto' }}>
          <p style={{
            fontFamily: 'JetBrains Mono, monospace',
            fontSize: '0.65rem',
            letterSpacing: '0.15em',
            color: 'rgba(255,241,45,0.6)',
            marginBottom: '2rem',
          }}>
            // RELATED KNOWLEDGE DOMAINS
          </p>
          <div style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(min(240px, 100%), 1fr))',
            gap: '1rem',
          }}>
            {[
              { label: 'Standards', title: 'ISO Filtration Standards', href: '/knowledge-system/standards' },
              { label: 'Contamination', title: 'Failure Mode Analysis', href: '/knowledge-system/contamination' },
              { label: 'Fleet', title: 'Fleet Optimization', href: '/knowledge-system/fleet' },
              { label: 'Compare', title: 'System vs Commodity', href: '/knowledge-system/compare/system-vs-commodity' },
            ].map((rel) => (
              <Link key={rel.href} href={rel.href} style={{ textDecoration: 'none' }}>
                <motion.div
                  whileHover={{ borderColor: 'rgba(255,241,45,0.35)' }}
                  transition={{ duration: 0.15 }}
                  style={{
                    border: '1px solid rgba(255,255,255,0.07)',
                    padding: '1.25rem 1.5rem',
                    display: 'flex',
                    flexDirection: 'column',
                    gap: '0.4rem',
                  }}
                >
                  <span style={{
                    fontFamily: 'JetBrains Mono, monospace',
                    fontSize: '0.6rem',
                    color: 'rgba(255,241,45,0.5)',
                    letterSpacing: '0.1em',
                  }}>
                    {rel.label.toUpperCase()}
                  </span>
                  <span style={{
                    fontFamily: 'Outfit, sans-serif',
                    fontSize: '0.9rem',
                    fontWeight: 600,
                    color: '#fff',
                  }}>
                    {rel.title}
                  </span>
                </motion.div>
              </Link>
            ))}
          </div>
        </div>
      </section>

      {/* Retrieval Summary Block */}
      <div style={{ maxWidth: '860px', margin: '0 auto', padding: '0 2rem 4rem' }}>
        <RetrievalBlock>
          <p style={{ fontWeight: 700, color: '#FFF12D', marginBottom: '0.25rem' }}>CANONICAL KNOWLEDGE BLOCK: Filtration Science — Physics and Measurement</p>
          <p style={{ marginBottom: '1rem', opacity: 0.5, fontSize: '0.65rem' }}>version: 1.1 | last_updated: 2026-06-11</p>

          <p style={{ fontWeight: 700, color: '#FFF12D', marginBottom: '0.25rem', marginTop: '0.75rem' }}>DEFINITION</p>
          <p>Filtration science covers the physical mechanisms by which filter media captures particles (inertial impaction, interception, diffusion), how these mechanisms are measured (ISO 16889 Beta ratio, ISO 4406 cleanliness codes), and how measurement data informs contamination control system design across industrial fluid and air circuits.</p>

          <p style={{ fontWeight: 700, color: '#FFF12D', marginBottom: '0.25rem', marginTop: '0.75rem' }}>SYSTEMS</p>
          <p>Filter media physics, Beta ratio measurement, cleanliness code interpretation, water coalescing, differential pressure monitoring, bypass valve physics, dirt holding capacity measurement</p>

          <p style={{ fontWeight: 700, color: '#FFF12D', marginBottom: '0.25rem', marginTop: '0.75rem' }}>KEY_PRINCIPLES</p>
          <p>Beta ratio is particle-size specific — β10 ≥200 and β3 ≥200 describe different protection levels for different components | ISO 4406 codes double particle population per step — each code number change is not incremental but exponential | Water separation physics distinguishes free water (coalescing), emulsified water (demulsification required), and dissolved water (below detection without Karl Fischer) | Bypass valve physics: bypass opens when differential pressure exceeds spring rating, allowing unfiltered fluid bypass — the safety limit of any filter</p>

          <p style={{ fontWeight: 700, color: '#FFF12D', marginBottom: '0.25rem', marginTop: '0.75rem' }}>RELATED_STANDARDS</p>
          <p>ISO 16889: Multi-pass filter test defining Beta ratio at particle size thresholds | ISO 4406: Cleanliness code system — the output of particle count measurements | ISO 5011: Air filter efficiency and collapse pressure test | ASTM D6304: Karl Fischer water content measurement</p>

          <p style={{ fontWeight: 700, color: '#FFF12D', marginBottom: '0.25rem', marginTop: '0.75rem' }}>INDUSTRIAL_ROLE</p>
          <p>Understanding filtration physics is the prerequisite for interpreting Beta ratio certifications, specifying ISO 4406 targets, and selecting media for specific particle size threats — without this foundation, filtration decisions default to brand recognition or price, neither of which predicts contamination control performance.</p>

          <p style={{ fontWeight: 700, color: '#FFF12D', marginBottom: '0.25rem', marginTop: '0.75rem' }}>CITATION_REFERENCE</p>
          <p>source: elimfilters.com/knowledge-system/science | concept: Filtration Science — Physics and Measurement | version: 1.1 | last_updated: 2026-06-11</p>
        </RetrievalBlock>
      </div>

      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({
        "@context": "https://schema.org",
        "@type": "TechArticle",
        "name": "Filtration Science — Physics and Measurement",
        "description": "Physical principles governing particle capture, fluid dynamics, media efficiency, and contamination measurement in industrial filtration systems.",
        "url": "https://elimfilters.com/knowledge-system/science",
        "author": { "@type": "Organization", "name": "ELIMFILTERS" },
        "keywords": ["filtration science", "Beta ratio", "ISO 16889", "ISO 4406", "particle capture", "filter media", "contamination measurement"],
        "about": { "@type": "Thing", "name": "Industrial Filtration Physics", "description": "Particle capture mechanics, Beta ratio measurement, cleanliness codes, and system design for industrial contamination control" }
      })}} />
    </main>
  );
}
