"""
enrich_db_equipment.py
Inherits equipment data for DB* codes (DBL/DBF) from their P* alternatives.

Logic:
  - DB* codes with zero equipment look up their alternatives[]
  - Collect all equipment entries from those P* codes (deduplicated)
  - Generate SQL UPDATE statements for elimfilters_catalog

Usage:
  python3 scripts/enrich_db_equipment.py

Output:
  scripts/enrich_db_equipment.sql  — run this against the production DB
"""

import json
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

FILES = [
    (os.path.join(SCRIPT_DIR, "donaldson_lube_results.json"),  "lube"),
    (os.path.join(SCRIPT_DIR, "donaldson_fuel_results.json"),  "fuel"),
]

def load_index(path):
    """Return dict: part_number → product record."""
    with open(path, encoding="utf-8") as f:
        products = json.load(f)
    return {p["part_number"]: p for p in products if p.get("part_number")}


def collect_inherited_equipment(db_code, index):
    """
    For a DB* code with zero equipment, walk its alternatives and collect
    all unique equipment entries from P* codes in the same index.
    Deduplication key: (equipment, type, engine).
    """
    record = index.get(db_code, {})
    alternatives = record.get("alternatives", [])
    seen = set()
    inherited = []

    for alt_code in alternatives:
        alt_record = index.get(alt_code)
        if not alt_record:
            continue
        for entry in alt_record.get("equipment", []):
            key = (
                entry.get("equipment", ""),
                entry.get("type", ""),
                entry.get("engine", ""),
            )
            if key not in seen:
                seen.add(key)
                inherited.append(entry)

    return inherited


def generate_sql(db_code, equipment_list):
    """
    Generate UPDATE statement for elimfilters_catalog.
    Matches on codigo_base = db_code.
    Sets equipment_applications to the inherited list.
    """
    equipment_json = json.dumps(equipment_list, ensure_ascii=False)
    escaped = equipment_json.replace("'", "''")
    return (
        f"UPDATE elimfilters_catalog\n"
        f"SET equipment_applications = '{escaped}'::jsonb\n"
        f"WHERE codigo_base = '{db_code}';"
    )


def main():
    sql_blocks = []
    summary = []

    for file_path, category in FILES:
        index = load_index(file_path)

        db_codes = [
            code for code, rec in index.items()
            if code.startswith("DB") and not rec.get("equipment")
        ]

        print(f"\n[{category.upper()}] {len(db_codes)} DB* codes with 0 equipment:")

        for db_code in sorted(db_codes):
            inherited = collect_inherited_equipment(db_code, index)
            print(f"  {db_code}: {len(inherited)} entries inherited from alternatives")

            if inherited:
                sql_blocks.append(f"-- {db_code} ({category}) — {len(inherited)} entries inherited")
                sql_blocks.append(generate_sql(db_code, inherited))
                sql_blocks.append("")
                summary.append((db_code, category, len(inherited), "WILL UPDATE"))
            else:
                sql_blocks.append(f"-- {db_code} ({category}) — 0 alternatives with equipment — SKIPPED")
                sql_blocks.append("")
                summary.append((db_code, category, 0, "SKIPPED"))

    # Write SQL file
    out_path = os.path.join(SCRIPT_DIR, "enrich_db_equipment.sql")
    header = (
        "-- enrich_db_equipment.sql\n"
        "-- Auto-generated by enrich_db_equipment.py\n"
        "-- Purpose: Inherit equipment data for DB* codes from P* alternatives\n"
        "-- Safe to re-run: YES (idempotent UPDATE — overwrites with same data)\n"
        "-- Affects: elimfilters_catalog.equipment_applications only\n"
        "-- Does NOT modify: technology, filter_type, sku, or any other field\n"
        "--\n"
        "-- Run with:\n"
        "--   psql $DATABASE_URL -f scripts/enrich_db_equipment.sql\n"
        "--\n"
    )
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(header)
        f.write("\n".join(sql_blocks))

    print(f"\n{'='*60}")
    print(f"SQL written to: {out_path}")
    print(f"\nSUMMARY:")
    print(f"{'Code':<12} {'Category':<8} {'Entries':<10} {'Action'}")
    print("-" * 45)
    total_updated = 0
    for code, cat, count, action in summary:
        print(f"{code:<12} {cat:<8} {count:<10} {action}")
        if action == "WILL UPDATE":
            total_updated += 1
    print(f"\nTotal DB* codes to update: {total_updated}")
    print(f"Total DB* codes skipped:   {len(summary) - total_updated}")


if __name__ == "__main__":
    os.chdir(SCRIPT_DIR)
    main()
