'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');const ROOT=__dirname;
const target=JSON.parse(fs.readFileSync(path.join(ROOT,'donaldson_coolant_filters_target_20260917.json'),'utf8'));
const comp=JSON.parse(fs.readFileSync(path.join(ROOT,'donaldson_coolant_competitors_direct_20260917.json'),'utf8'));
const files=fs.readdirSync(ROOT).filter(n=>/^donaldson_coolant_deep.*_results_20260917\.jsonl$/.test(n));
const sections=['attributes','cross_reference','equipment','alternate_parts','related_parts','resources'];const byCode=new Map();
const score=x=>(x?.status==='OK'?10000:0)+(x?.official?.description?1000:0)+(x?.audit?.expansion_complete?500:0)+Object.keys(x?.official?.attributes||{}).length;
for(const file of files)for(const line of fs.readFileSync(path.join(ROOT,file),'utf8').split(/\r?\n/).filter(Boolean)){let r;try{r=JSON.parse(line)}catch{continue}const old=byCode.get(r.codigo_base);if(!old||score(r)>score(old.row))byCode.set(r.codigo_base,{row:r,file});}
const collisions=new Map();for(const t of target){const base='EW7'+String(t.code).replace(/\D/g,'').slice(-4);const a=collisions.get(base)||[];a.push(t);collisions.set(base,a)}
function skuFor(t){const digits=String(t.code).replace(/\D/g,'');const base='EW7'+digits.slice(-4);const g=collisions.get(base)||[];return g.length<=1?base:'EW7'+digits.slice(-6)}
const final=[],failures=[];let deep=0,missing=0,error=0,partial=0;
for(const t of target){const a=byCode.get(t.code),r=a?.row,se=r?.audit?.sections||{};const pass=!!r&&r.status==='OK'&&r.official?.part_number===t.code&&!!r.official?.description&&Object.keys(r.official?.attributes||{}).length>0&&r.audit?.expansion_complete===true&&sections.every(k=>se[k]?.complete===true);if(pass)deep++;else{missing++;failures.push(t.code+':'+(r?.status||'MISSING'));if(r?.status==='ERROR')error++;if(r?.status==='PARTIAL')partial++;}const c=comp[t.code]||{};final.push({...r, codigo_base:t.code, sku:skuFor(t),family:'EW7',technology:'THERMACORE™',category:'coolant',competitor_codes:c.refs||[],competitor_source:{url:c.source_url||null,http_status:c.http_status??null,status:c.status||'MISSING'},evidence_source_file:a?.file||null});}
const codes=new Set(final.map(x=>x.codigo_base)),skus=new Set(final.map(x=>x.sku));const compRows=target.filter(t=>comp[t.code]).length,compErr=target.filter(t=>comp[t.code]?.status==='ERROR').length,withRefs=target.filter(t=>(comp[t.code]?.refs||[]).length>0).length,notFound=target.filter(t=>comp[t.code]?.status==='NOT_FOUND').length,totalRefs=target.reduce((n,t)=>n+(comp[t.code]?.refs||[]).length,0);
if(target.length!==29)failures.push('TARGET_COUNT');if(codes.size!==29)failures.push('CODE_UNIQUENESS');if(skus.size!==29)failures.push('SKU_UNIQUENESS');if(compRows!==29||compErr)failures.push('COMPETITOR_COVERAGE');
const complete=deep===29&&failures.length===0;const audit={family:'COOLANT',standard:'STRICT_DEEP_PARITY',universe_filters:33,active_filters:29,discontinued_filters:4,pagination_omission:['P551309'],target:29,EW7:29,technology:'THERMACORE™',unique_results:codes.size,unique_skus:skus.size,pass:deep,fail:29-deep,missing,error,partial,deep_product_pages:deep,competitor_rows:compRows,competitor_with_refs:withRefs,competitor_not_found:notFound,competitor_errors:compErr,total_competitor_refs:totalRefs,complete,failures:[...new Set(failures)],evidence_policy:'No fabricated values. All active EW7 products require complete official Donaldson product-page evidence; competitor NOT_FOUND is recorded as verified absence.',sha256:crypto.createHash('sha256').update(JSON.stringify(final)).digest('hex'),verified_at:new Date().toISOString()};
fs.writeFileSync(path.join(ROOT,'donaldson_coolant_final_results_20260917.json'),JSON.stringify(final,null,2));fs.writeFileSync(path.join(ROOT,'donaldson_coolant_final_strict_audit_20260917.json'),JSON.stringify(audit,null,2));console.log(JSON.stringify(audit,null,2));process.exitCode=complete?0:2;