$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
Set-Location $repoRoot

Write-Host "[KG-V2] Repository: $repoRoot"

if (-not (Get-Command graphify -ErrorAction SilentlyContinue)) {
    throw "graphify is not available in PATH"
}

if (-not (Get-Command claude -ErrorAction SilentlyContinue)) {
    throw "Claude Code is not available in PATH"
}

$graphPath = Join-Path $repoRoot 'graphify-out\graph.json'
if (-not (Test-Path $graphPath)) {
    throw "graphify-out\graph.json was not found. Run: graphify . --update --backend claude-cli"
}

$reportDir = Join-Path $repoRoot 'graphify-out\v2-audit'
New-Item -ItemType Directory -Path $reportDir -Force | Out-Null

if (-not $env:GRAPHIFY_MAX_WORKERS) {
    $env:GRAPHIFY_MAX_WORKERS = '2'
}
if (-not $env:GRAPHIFY_API_TIMEOUT) {
    $env:GRAPHIFY_API_TIMEOUT = '1200'
}
if (-not $env:GRAPHIFY_QUERY_LOG_DISABLE) {
    $env:GRAPHIFY_QUERY_LOG_DISABLE = '1'
}

Write-Host "[KG-V2] Generating communities and GRAPH_REPORT.md..."
graphify cluster-only .
if ($LASTEXITCODE -ne 0) {
    throw "graphify cluster-only failed with exit code $LASTEXITCODE"
}

Write-Host "[KG-V2] Labeling communities with Claude Code..."
graphify label --backend claude-cli
if ($LASTEXITCODE -ne 0) {
    throw "graphify label failed with exit code $LASTEXITCODE"
}

$queries = @(
    @{
        Name = '01-core-architecture.txt'
        Question = 'What are the central ELIMFILTERS technologies, protection systems, standards, industries, database entities, website pages and source files? Distinguish current authoritative sources from historical reports.'
    },
    @{
        Name = '02-collisions-and-conflicts.txt'
        Question = 'Which historical reports, generated files or duplicate names collide with current source-code or canonical knowledge entities? List the affected entities and authoritative source that should win.'
    },
    @{
        Name = '03-knowledge-coverage.txt'
        Question = 'What approved or technical knowledge appears in Markdown or Obsidian-style documentation but is not implemented in current website pages, APIs or canonical data files?'
    },
    @{
        Name = '04-evidence-gaps.txt'
        Question = 'Which engineering claims, performance claims, standards references or field-validation statements lack a clearly connected authoritative source or evidence record?'
    }
)

foreach ($query in $queries) {
    $outputPath = Join-Path $reportDir $query.Name
    Write-Host "[KG-V2] Query -> $($query.Name)"
    $result = graphify query $query.Question 2>&1
    $result | Set-Content -Path $outputPath -Encoding utf8
    if ($LASTEXITCODE -ne 0) {
        Write-Warning "Query failed: $($query.Question)"
    }
}

$summaryPath = Join-Path $reportDir 'README.md'
@"
# ELIMFILTERS Knowledge Graph v2 — Initial Audit

Generated by `scripts/graphify-v2-bootstrap.ps1`.

## Files

- `01-core-architecture.txt` — central technologies, systems, standards, industries and implementation nodes.
- `02-collisions-and-conflicts.txt` — historical/current-source collisions and authority recommendations.
- `03-knowledge-coverage.txt` — documented knowledge not implemented in pages, APIs or canonical data.
- `04-evidence-gaps.txt` — engineering and marketing claims without clear evidence paths.

## Governing documents

- `docs/knowledge-graph/KNOWLEDGE_GRAPH_ARCHITECTURE_V2.md`
- `docs/knowledge-graph/ELIMFILTERS_ONTOLOGY_V2.yaml`
- `docs/knowledge-graph/KNOWLEDGE_GRAPH_V2_IMPLEMENTATION_ROADMAP.md`

The files in this directory are generated audit outputs. They are not authoritative sources.
"@ | Set-Content -Path $summaryPath -Encoding utf8

Write-Host "[KG-V2] Completed. Review: $reportDir"