// AUTO-GENERATED — do not edit manually
// Regenerate with: node scripts/sync-jsonld-constants.js
// Source: elimfilters-vault/00-meta/CITATION_INDEX.json
// Generated: 2026-06-29T04:51:27.898Z
//
// Each constant is a pre-serialized JSON-LD string for use with:
//   <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: CONSTANT }} />

// DataCatalog, 0 entities
export const JSONLD_KNOWLEDGE_SYSTEM_HUB = "{\"@context\":\"https://schema.org\",\"@type\":\"DataCatalog\",\"name\":\"ELIMFILTERS Knowledge Vault\",\"description\":\"Machine-readable industrial filtration knowledge graph covering contamination modes, technologies, standards, and product families.\",\"url\":\"https://elimfilters.com/knowledge-system\",\"publisher\":{\"@type\":\"Organization\",\"name\":\"ELIMFILTERS\",\"url\":\"https://elimfilters.com\"},\"dataset\":[]}";

// CollectionPage, 0 standards
export const JSONLD_STANDARDS_INDEX = "{\"@context\":\"https://schema.org\",\"@type\":\"CollectionPage\",\"name\":\"Industrial Filtration Standards — ELIMFILTERS Knowledge System\",\"description\":\"Index of international standards governing industrial filtration: ISO 16889, ISO 4406, ISO 5011, ISO 11155, ISO 12937, ASTM D6304, SAE J1539, DIN 71220, NFPA T2.14.\",\"url\":\"https://elimfilters.com/knowledge-system/standards\",\"publisher\":{\"@type\":\"Organization\",\"name\":\"ELIMFILTERS\",\"url\":\"https://elimfilters.com\"},\"hasPart\":[]}";

// TechArticle + DefinedTermSet, 5 entities
export const JSONLD_AIR_INTAKE_SYSTEMS = "{\"@context\":\"https://schema.org\",\"@type\":[\"TechArticle\",\"DefinedTermSet\"],\"headline\":\"Air Intake Filtration Systems — ISO 5011 and SAE J1539 Standards\",\"description\":\"Air intake filtration system standards — ISO 5011, SAE J1539 — defining efficiency measurement, flow restriction, and dust holding capacity for diesel engine air intake filters.\",\"url\":\"https://elimfilters.com/knowledge-system/standards/air-intake-systems\",\"author\":{\"@type\":\"Organization\",\"name\":\"ELIMFILTERS\"},\"publisher\":{\"@type\":\"Organization\",\"name\":\"ELIMFILTERS\",\"url\":\"https://elimfilters.com\"},\"dateModified\":\"2026-06-03\",\"keywords\":\"air intake filtration, ISO 5011, SAE J1539, MACROCORE, SYNTEPORE, INTEKCORE, engine air filter, diesel air intake\",\"about\":[],\"mentions\":[],\"inLanguage\":\"en\",\"hasDefinedTerm\":[]}";

// TechArticle + DefinedTermSet, 4 entities
export const JSONLD_LUBE_OIL_SYSTEMS = "{\"@context\":\"https://schema.org\",\"@type\":[\"TechArticle\",\"DefinedTermSet\"],\"headline\":\"Lube Oil Filtration Systems — ISO 16889 and ISO 4406 Standards\",\"description\":\"Lube oil filtration system standards — ISO 16889 (Beta ratio), ISO 4406 (cleanliness codes) — defining particle contamination control in engine and hydraulic lube circuits.\",\"url\":\"https://elimfilters.com/knowledge-system/standards/lube-oil-systems\",\"author\":{\"@type\":\"Organization\",\"name\":\"ELIMFILTERS\"},\"publisher\":{\"@type\":\"Organization\",\"name\":\"ELIMFILTERS\",\"url\":\"https://elimfilters.com\"},\"dateModified\":\"2026-06-03\",\"keywords\":\"lube oil filtration, ISO 16889, ISO 4406, SYNTRAX, NANOFORCE, Beta ratio, cleanliness code, engine oil filter\",\"about\":[],\"mentions\":[],\"inLanguage\":\"en\",\"hasDefinedTerm\":[]}";

// TechArticle + DefinedTermSet, 3 entities
export const JSONLD_CABIN_SAFETY_SYSTEMS = "{\"@context\":\"https://schema.org\",\"@type\":[\"TechArticle\",\"DefinedTermSet\"],\"headline\":\"Cabin Safety Filtration Systems — ISO 11155 and DIN 71220 Standards\",\"description\":\"Cabin air filtration standards — ISO 11155 (particulate and gaseous), DIN 71220 — protecting equipment operators from PM10, PM2.5 and chemical exposure inside enclosed cabs.\",\"url\":\"https://elimfilters.com/knowledge-system/standards/cabin-safety-systems\",\"author\":{\"@type\":\"Organization\",\"name\":\"ELIMFILTERS\"},\"publisher\":{\"@type\":\"Organization\",\"name\":\"ELIMFILTERS\",\"url\":\"https://elimfilters.com\"},\"dateModified\":\"2026-06-03\",\"keywords\":\"cabin air filtration, ISO 11155, DIN 71220, MICROKAPPA, operator safety, PM10, cabin filter, respiratory protection\",\"about\":[],\"mentions\":[],\"inLanguage\":\"en\",\"hasDefinedTerm\":[]}";

// TechArticle + DefinedTermSet, 3 entities
export const JSONLD_FUEL_SYSTEMS = "{\"@context\":\"https://schema.org\",\"@type\":[\"TechArticle\",\"DefinedTermSet\"],\"headline\":\"Fuel Filtration Systems — ASTM D6304 and ISO 12937 Standards\",\"description\":\"Diesel fuel filtration standards — ASTM D6304, ISO 12937 — measuring water content in petroleum products and preventing injector damage from water contamination.\",\"url\":\"https://elimfilters.com/knowledge-system/standards/fuel-systems\",\"author\":{\"@type\":\"Organization\",\"name\":\"ELIMFILTERS\"},\"publisher\":{\"@type\":\"Organization\",\"name\":\"ELIMFILTERS\",\"url\":\"https://elimfilters.com\"},\"dateModified\":\"2026-06-03\",\"keywords\":\"fuel filtration, ASTM D6304, ISO 12937, HYDROCORE, diesel water contamination, Karl Fischer titration, fuel filter\",\"about\":[],\"mentions\":[],\"inLanguage\":\"en\",\"hasDefinedTerm\":[]}";

// TechArticle + DefinedTermSet, 5 entities
export const JSONLD_HYDRAULIC_SYSTEMS = "{\"@context\":\"https://schema.org\",\"@type\":[\"TechArticle\",\"DefinedTermSet\"],\"headline\":\"Hydraulic Filtration Systems — ISO 16889, ISO 4406, and NFPA T2.14 Standards\",\"description\":\"Hydraulic system filtration standards — ISO 16889 (Beta ratio), ISO 4406 (cleanliness codes), NFPA T2.14 (collapse resistance) — for proportional valve and pump protection.\",\"url\":\"https://elimfilters.com/knowledge-system/standards/hydraulic-systems\",\"author\":{\"@type\":\"Organization\",\"name\":\"ELIMFILTERS\"},\"publisher\":{\"@type\":\"Organization\",\"name\":\"ELIMFILTERS\",\"url\":\"https://elimfilters.com\"},\"dateModified\":\"2026-06-03\",\"keywords\":\"hydraulic filtration, ISO 16889, ISO 4406, NFPA T2.14, NANOFORCE, SYNTRAX, proportional valve, hydraulic filter\",\"about\":[],\"mentions\":[],\"inLanguage\":\"en\",\"hasDefinedTerm\":[]}";

// CollectionPage, 0 contamination modes
export const JSONLD_CONTAMINATION_INDEX = "{\"@context\":\"https://schema.org\",\"@type\":\"CollectionPage\",\"name\":\"Industrial Filtration Failure Analysis — ELIMFILTERS Knowledge System\",\"description\":\"Index of contamination failure modes: diesel water contamination, particle wear in engines, hydraulic system contamination, and cabin air contamination.\",\"url\":\"https://elimfilters.com/knowledge-system/contamination\",\"publisher\":{\"@type\":\"Organization\",\"name\":\"ELIMFILTERS\",\"url\":\"https://elimfilters.com\"},\"hasPart\":[]}";

// TechArticle, particle wear failure analysis
export const JSONLD_PARTICLE_WEAR = "{\"@context\":\"https://schema.org\",\"@type\":\"TechArticle\",\"headline\":\"Particle Wear in Engines — Abrasive Contamination Failure Analysis\",\"description\":\"Particle wear is the abrasive degradation of precision engine surfaces — piston rings, cylinder walls, crankshaft journals — caused by hard particle contamination in lube oil.\",\"url\":\"https://elimfilters.com/knowledge-system/contamination/particle-wear\",\"author\":{\"@type\":\"Organization\",\"name\":\"ELIMFILTERS\"},\"publisher\":{\"@type\":\"Organization\",\"name\":\"ELIMFILTERS\",\"url\":\"https://elimfilters.com\"},\"dateModified\":\"2026-06-03\",\"keywords\":\"particle wear, abrasive wear, engine contamination, ISO 16889, ISO 4406, MACROCORE, NANOFORCE, lube oil filtration, bearing wear\",\"about\":[],\"mentions\":[],\"inLanguage\":\"en\"}";

// TechArticle, diesel water contamination
export const JSONLD_DIESEL_WATER = "{\"@context\":\"https://schema.org\",\"@type\":\"TechArticle\",\"headline\":\"Diesel Water Contamination — Fuel System Failure Analysis\",\"description\":\"Diesel water contamination is the presence of dissolved, free, or emulsified water in diesel fuel systems causing injector damage, microbial growth, and corrosion.\",\"url\":\"https://elimfilters.com/knowledge-system/contamination/diesel-water\",\"author\":{\"@type\":\"Organization\",\"name\":\"ELIMFILTERS\"},\"publisher\":{\"@type\":\"Organization\",\"name\":\"ELIMFILTERS\",\"url\":\"https://elimfilters.com\"},\"dateModified\":\"2026-06-03\",\"keywords\":\"diesel water contamination, fuel contamination, ASTM D6304, ISO 12937, HYDROCORE, Karl Fischer titration, injector damage, fuel filter\",\"about\":[],\"mentions\":[],\"inLanguage\":\"en\"}";

// TechArticle, hydraulic system contamination
export const JSONLD_HYDRAULIC_CONTAMINATION = "{\"@context\":\"https://schema.org\",\"@type\":\"TechArticle\",\"headline\":\"Hydraulic System Contamination — Particle and Water Failure Analysis\",\"description\":\"Hydraulic system contamination is the presence of particles, water, and fluid degradation products in hydraulic fluid threatening proportional valve and pump reliability.\",\"url\":\"https://elimfilters.com/knowledge-system/contamination/hydraulic-system\",\"author\":{\"@type\":\"Organization\",\"name\":\"ELIMFILTERS\"},\"publisher\":{\"@type\":\"Organization\",\"name\":\"ELIMFILTERS\",\"url\":\"https://elimfilters.com\"},\"dateModified\":\"2026-06-03\",\"keywords\":\"hydraulic contamination, ISO 16889, ISO 4406, NFPA T2.14, NANOFORCE, SYNTRAX, proportional valve, hydraulic pump, fluid cleanliness\",\"about\":[],\"mentions\":[],\"inLanguage\":\"en\"}";
